### ISSUE TITLE
Automatically add newly created/added addresses to node's staking keys, if connected

### ISSUE THREAD

**Issue by AureliaDolo** [massalabs/massa#1796]
When creating or adding an address to the wallet, if the node is connected sent it given addresses to use as staking keys.

Or maybe just add an option to do that 

That raises the question: should we check if addresses in the wallet are the same as staking addresses and if not add them where they are missing

**Comment by AureliaDolo** [comment]
@damip @qdrn @sebastien-forestier what do you think ?

**Comment by qdrn** [comment]
I agree that it's painful right now to type multiple commands. I'm not sure you'd want to that automatically though. Maybe as an option.

**Comment by damip** [comment]
I agree it is dangerous to do it automatically. But it can be suggested in text by the client in interactive mode.

**Comment by AureliaDolo** [comment]
Maybe something like "type `node_add_staking_private_keys xxx` to start staking with this private_key after the "added Addresss xxx to the wallet" ?

**Comment by damip** [comment]
yes sounds good
