### ISSUE TITLE
Have a `CHANGELOG` file

### ISSUE THREAD

**Issue by yvan-sraka** [massalabs/massa#1811]
https://keepachangelog.com/

**Comment by yvan-sraka** [comment]
I rename the issue for disambiguation, GitHub have indeed the same mechanism https://github.com/massalabs/massa/releases ;)

**Comment by AureliaDolo** [comment]
@yvan-sraka is this resolved ? https://github.com/massalabs/massa/releases/tag/TEST.5.0
