### ISSUE TITLE
Add block receptions to higher lvl log

### ISSUE THREAD

**Issue by qdrn** [massalabs/massa#1817]
I think it's important to log when blocks (and maybe headers) are received in order to make statistics about block reception timings. Currently it's only available in log lvl 4 but lvl 4 log is way too heavy to run a node.

It could be only the hash and timing. No need to log the whole block as is currently done in lvl 4.

It could be in lvl 2 or 3. To be discussed.

**Comment by AureliaDolo** [comment]
At what point in the reception process do you want that kind of log ?
- immediately when it's received without any check ?
- at network level ?
- at protocol level ?
- at consensus level ?
- when integrated to the block graph ?

**Comment by qdrn** [comment]
I think it would make sense to log it when they are received, before any check.

**Comment by AureliaDolo** [comment]
Just the first time we receive a block or each time ?

**Comment by qdrn** [comment]
Only the first time, if possible. The idea is to monitor the health of the network (i.e. how much time it takes for one block to propagate to everyone).

**Comment by AureliaDolo** [comment]
Having the log only the first time we receive a block means checking that at protocol level.
