### ISSUE TITLE
Store more final blocks

### ISSUE THREAD

**Issue by qdrn** [massalabs/massa#1820]
Currently, as we removed storage, only very little final blocks are kept in memory (only what is needed to check incompatibilities etc...). Other blocks are pruned every `block_db_prune_interval`. As a result when someone disconnects for more than ~1-2 mins he has to bootstrap again as people have dropped all the final blocks. It would make sense to keep more final blocks in memory so that people don't have to bootstrap again for small disconnections. For example ~1h of blocks (around 2Go of RAM with full blocks). Could be settable through a parameter in config.

**Comment by AureliaDolo** [comment]
As a quick patch you can set block_db_prune_interval at ~1h given that every hour unused final blocks will be flushed all together, so that would be a bad timing for a deconnection.

One the other hand we can think about a better way to manage final blocks now that we don't have storage anymore.

**Comment by qdrn** [comment]
It would mean that everyone need to set block_db_prune_interval at 1h otherwise it's unlikely they will ask blocks to our servers. I think it's better to wait for a better way to manage final blocks than a quick and dirty patch.

**Comment by AureliaDolo** [comment]
I'm not sure what you mean by a better way to manage final blocks 
- currently they are kept in the RAM and almost all of them are flushed every  block_db_prune_interval
- when we had a storage, they would then be stored on the disk

I don't understand what kind of solution do you expect. The cache mechanism can indeed be updated to keep more final blocks, but it core will remain.

**Comment by qdrn** [comment]
I completely agree. I'm just saying we should not settle for the quick patch. Just do it a bit more clean, but the overall mechanism will stay similar.
Instead of keeping the blocks necessary to compute the graph rules we should keep for example `max(one cycle of block, blocks necessary to compute graph rules)`.

**Comment by AureliaDolo** [comment]
Yes :)

And I guess with the new consensus rule that is on it's way that part will evolve anyway.

And I'm wondering how much RAM would occupy 10 000 tx/sec ?

**Comment by qdrn** [comment]
> And I guess with the new consensus rule that is on it's way that part will evolve anyway.

Probably a bit :)

> And I'm wondering how much RAM would occupy 10 000 tx/sec ?

For one cycle it would be around ~2Go I think (500ko per block and ~4k blocks).
