### ISSUE TITLE
 `wallet_info` display nothing when passing `--json` CLI option

### ISSUE THREAD

**Issue by yvan-sraka** [massalabs/massa#1825]
Maybe something like that [{"addressxxxxxxxxxxxxxxxx": {private_key: "xxxxxxxxxxx", public_key: "xxxxxxxxxxx"}]

_Originally posted by @AureliaDolo in https://github.com/massalabs/massa/pull/1789#r751005303_

**Comment by AureliaDolo** [comment]
Are there other commands that display nothing ?

**Comment by yvan-sraka** [comment]
Every command that return an `Ok(Box::new(()))` in https://github.com/massalabs/massa/blob/main/massa-client/src/cmds.rs

**Comment by AureliaDolo** [comment]
> Every command that return an `Ok(Box::new(()))` in https://github.com/massalabs/massa/blob/main/massa-client/src/cmds.rs

Ok so it would be usefull if node_testnet_rewards_program_ownership_proof wallet_generate_private_key wallet_add_private_keys also returned something

* [ ] node_testnet_rewards_program_ownership_proof -> [String] // just the string that should be pasted in discord
* [ ]  wallet_generate_private_key -> [String] // created address
* [ ] wallet_add_private_keys -> [String] // derived address

**Comment by damip** [comment]
do we have wallet_remove_address ? if not, it should be added

**Comment by AureliaDolo** [comment]
> do we have wallet_remove_address ? if not, it should be added

#1124 was closed because that command was already implemented but without the confirmation check.

I did not include it in the previous list as anyway it returns nothing
