### ISSUE TITLE
`cargo test` fail on `macOS` in CI with a timeout error

### ISSUE THREAD

**Issue by yvan-sraka** [massalabs/massa#1826]

**Comment by AureliaDolo** [comment]
@gterzian @qdrn You both use macOs, are the tests failing locally for you ?

**Comment by qdrn** [comment]
Everything is running on my side (M1 Mac but I think it's the same on my laptop).

**Comment by yvan-sraka** [comment]
So, I will make further investigations!

**Comment by qdrn** [comment]
Works also on the `main` branch!

**Comment by yvan-sraka** [comment]
https://github.com/massalabs/massa/runs/4263360913?check_suite_focus=true

**Comment by adrien-zinger** [comment]
the branch #1831 temporary hide the problem. Maybe the CI environment is slower?

**Comment by AureliaDolo** [comment]
Maybe it's that same kind of issue we had with cargo tarpaulin

**Comment by yvan-sraka** [comment]
Do we give a higher priority badge to this issue?

**Comment by damip** [comment]
Someone who has a Mac can take over ?

**Comment by damip** [comment]
I don't get it, what does Mac OS have to do with the CI ?

**Comment by adrien-zinger** [comment]
> I don't get it, what does Mac OS have to do with the CI ?

The CI run unit test on Ubuntu, Windows but not on MacOS anymore because of some unexpected timeout errors. We could investigate on these errors

**Comment by yvan-sraka** [comment]
> I don't get it, what does Mac OS have to do with the CI?

Per-commit CI is just launched against ubuntu, but CI has a "full"-mode launched by BORS before merging that (I think is neat that why I did it this way) ensure that the project still builds/pass tests on the 3 major platforms we aim to target!

**Comment by qdrn** [comment]
Let me know if you need help/access to a Mac to investigate.

**Comment by gterzian** [comment]
Which tests were failing?

**Comment by AureliaDolo** [comment]
see https://github.com/massalabs/massa/pull/1831

**Comment by damip** [comment]
tests corrected except one with its own issue. Closing

**Comment by damip** [comment]
https://github.com/massalabs/massa/issues/2164
