### ISSUE TITLE
Study alternative crypto schemes

### ISSUE THREAD

**Issue by damip** [massalabs/massa#1841]
## Rationale

We are still using the now-quite-old and feature-lacking sha256 hash and secp256k1 signature.
The goal of this issue is to study modern alternatives.

### requirements

* security
* speed
* small hash size <= 256bits

### candidates

* BLAKE3: 
  * apparently 10x faster than sha256: https://nextjournal.com/mk/BLAKE3
  * has an official rust implementation: https://docs.rs/blake3/1.2.0/blake3/ with various SIMD optimizations

### requirements

* small public key (or with efficient compression/decompression)
* small signature
* signature verification speed
* bonus: m-of-n / multisig capabilities

### candidates

* Schnorr
  * https://medium.com/bitbees/what-the-heck-is-schnorr-52ef5dba289f
  * faster verif than ECDSA (3x) and BLS

* BLS
  * https://medium.com/cryptoadvance/bls-signatures-better-than-schnorr-5a7fe30ea716 
  * good: small signature size
  * bad: larger public key size
  * good: signature aggregation (all the signatures in the block can be compacted into a single one !)
  * good: m-of-n signature capabilities
  * bad: slower but optimizable: https://www.dash.org/blog/bls-is-it-really-that-slow/

**Comment by damip** [comment]
I vote for Blake3 + Schnorr !

**Comment by yvan-sraka** [comment]
Do you want to make a pool to ask the community?

**Comment by qdrn** [comment]
Might be of interest https://github.com/garyyu/rust-secp256k1-zkp/wiki/Schnorr-Signatures-(Aggregate-Signatures)

**Comment by damip** [comment]
We need a performance benchmark of the Rust implementations of Blake3 vs Sha256 as well as Schnorr vs Secp256k1. This is a nice task for an intern.

**Comment by adrien-zinger** [comment]
moved in discussions #1916

**Comment by Eitu33** [comment]
## Benchmark

After yesterday's presentation (available [here](https://docs.google.com/presentation/d/135d19IuIN_suKvYQl5M7c6tR_BUKYLF2hJQ6JvH6JmY/edit?usp=sharing)), here are the results of the new benchmark:

<img width="945" alt="Screenshot 2022-03-03 at 10 57 19" src="https://user-images.githubusercontent.com/89928840/156541372-af0fca9d-5a18-4a16-9f73-bd5ff6fc4844.png">

<img width="946" alt="Screenshot 2022-03-03 at 10 57 47" src="https://user-images.githubusercontent.com/89928840/156541389-64ad8fd2-b014-441b-b154-ee7681c77722.png">

The two `schnorr + blake3` slopes are superposed and have ratios that vary between 1.5 (for the shortest input data, 32b) and 4.73 time faster (for 10mb) when compared with `secp256k1 + sha256`.

I also included a BLS benchmark but it is significantly slower as expected.

## Additional information

### Standards origin countries

- sha256: United States
- blake3: Not standardized yet (blake1 was stanardized by Japan, Europe and US)
- secp256k1: United States
- schnorr: Japan, Europe and United States
- BLS: Japan, Europe and United States
