### ISSUE TITLE
[Feature] The client should never panic!

### ISSUE THREAD

**Issue by adrien-zinger** [massalabs/massa#1850]
It's a saint commandments spotted [here](https://github.com/massalabs/massa/pull/1827#discussion_r755375796) that's simply said:

> Client should never panic. 

We have to remove all bail! and panic! macros and write errors/warnings in standard err/warn output of the user instead.

**Comment by adrien-zinger** [comment]
@yvan-sraka @AureliaDolo any comments? :studio_microphone:

**Comment by yvan-sraka** [comment]
`bail!` is safe it's just an `return Err(_)`!

The only one `unwrap` lefts are the ones that should by construct never `panic!` and if a crash occurs in it's because of a bug and it is a good behaviour to not hide it!
