### ISSUE TITLE
[client] Highligth most used commands

### ISSUE THREAD

**Issue by AureliaDolo** [massalabs/massa#1854]
In GitLab by @Noxha

Yea, reordering is enough, ideally with some clear split "-----------" and maybe title.
No space maybe between the paragraph though, as a long list of commands is not handy to read on a terminal if it's bigger than the screen (better to see all of them without having to scroll)

_Originally posted by @massa-bot in https://github.com/massalabs/massa/issues/1307#issuecomment-966947421_

**Comment by AureliaDolo** [comment]
@yvan-sraka do you have any ideas on how to tackle that ?

**Comment by yvan-sraka** [comment]
Yup!

**Comment by AureliaDolo** [comment]
And what's your idea ? :)

**Comment by damip** [comment]
closing for now. Will reopen if usability complaints arise
