### ISSUE TITLE
Maybe reduce max_advertise_length before the next release

### ISSUE THREAD

**Issue by AureliaDolo** [massalabs/massa#1858]
To avoid sharing a 10 000 long peer list with most of them down after the end of the last episode, with @sebastien-forestier we considered reducing that parameter.

But that may increase the risk of having multiple independent networks.

@damip @qdrn what do you think ?

**Comment by qdrn** [comment]
In the end, will it change anything if we reduce that parameter ? People will still end up with thousands of peers that are not running anyway as the peers are advertised regularly, no ?

**Comment by AureliaDolo** [comment]
> In the end, will it change anything if we reduce that parameter ? People will still end up with thousands of peers that are not running anyway as the peers are advertised regularly, no ?

When we advertise peers we sort them from more recently active to less recently active. So if at round 1 I did not advertised a peer, it may be advertised in round 2 only if we were connected to it, or if enough previously "better" peers were banned.

**Comment by damip** [comment]
Basically all the untested peers are sorted randomly by every node (and at every announcement per node). So at every announcement you send, you will advertise different untested peers, and at every announcement you receive, you will receive different batches of untested peers and eventually you will end up with all peers anyways.

I vote for keeping this number high

**Comment by qdrn** [comment]
Isn't it a problem that it's a deterministic order ? Is it the same for every node ?

**Comment by damip** [comment]
among untested peers, the order will change from node to node AND between different uses for the same node

**Comment by qdrn** [comment]
It would be a problem if it was the same order for every node.
