### ISSUE TITLE
Rename hhasher related structs

### ISSUE THREAD

**Issue by AureliaDolo** [massalabs/massa#1899]
* [x] HHasher
* [x] EndorsementHashMap/Set
* [x] AddressHashMap/Set
* [x] BlockHashMap/Set
* [x] OperationHashMap/Set

**Comment by AureliaDolo** [comment]
@yvan-sraka you seemed to have a name idea ?

**Comment by yvan-sraka** [comment]
Since it's an `HashMap` without `hash` computation, I would name it `Map` :)
