### ISSUE TITLE
remove no share private key warning in JSON command line

### ISSUE THREAD

**Issue by damip** [massalabs/massa#1911]
![unknown](https://user-images.githubusercontent.com/10211103/144602715-73df914d-44ae-4ac6-8dae-12f622aed08e.png)

This breaks JSON parsers.

TODO: Remove all kinds of warnings (including not enough rolls/coins) from the command line output and only leave clean JSON

**Comment by yvan-sraka** [comment]
@AureliaDolo there is currently an `if json` we use in client to handle this case!

**Comment by AureliaDolo** [comment]
Indeed.

Maybe we should prioritize #1134, and test both json and regular output for each command

**Comment by damip** [comment]
Let's start by removing all non-json output in CLI mode
