### ISSUE TITLE
Move documentation to repository's wiki page

### ISSUE THREAD

**Issue by AureliaDolo** [massalabs/massa#1912]
### Discussed in https://github.com/massalabs/massa/discussions/1903

<div type='discussions-op-text'>

<sup>Originally posted by **YogaSakti** December  2, 2021</sup>
I think it will be easier to access if the documentation is moved to the repository's wiki page</div>

**Comment by AureliaDolo** [comment]
@yvan-sraka is there a way to link the .md files in the wiki, or it's better to just copy paste them out there ?

**Comment by qdrn** [comment]
I think it's a good idea to organise knowledge!

**Comment by yvan-sraka** [comment]
Solved by https://github.com/massalabs/massa/pull/1951
