### ISSUE TITLE
Consider Wasmtime

### ISSUE THREAD

**Issue by gterzian** [massalabs/massa#1921]
I propose we look a bit more into https://github.com/bytecodealliance/wasmtime

**Comment by gterzian** [comment]
@yvan-sraka @AureliaDolo @damip @adrien-zinger

**Comment by gterzian** [comment]
A few features that caught my attention: 

https://docs.rs/wasmtime/latest/wasmtime/struct.Store.html#method.interrupt_handle

https://docs.rs/wasmtime/latest/wasmtime/struct.Config.html#method.consume_fuel

**Comment by AureliaDolo** [comment]
#1955 is closed, so I close this
