### ISSUE TITLE
Document "node ID already used in MassaBot" error

### ISSUE THREAD

**Issue by qdrn** [massalabs/massa#1947]
See https://t.me/MassaLabs/2024

**Comment by AureliaDolo** [comment]
The code of the massa bot isn't in this repo ?

**Comment by qdrn** [comment]
No, but tutorials to stake and register are on this repo !

**Comment by AureliaDolo** [comment]
Oh so it's a section to add to the faq page. I understood "document 'node already in use' in massa bot" instead of "document ' node already in use in massa bot' " x)

**Comment by qdrn** [comment]
Sorry, my bad :)

**Comment by Noxhaa** [comment]
Done : https://github.com/massalabs/massa/wiki/faq
