### ISSUE TITLE
How timeout could be a correctness concept? Is the code could still be correct but fail tests with relaxed timeout?

### ISSUE THREAD

**Issue by AureliaDolo** [massalabs/massa#1950]
How timeout could be a correctness concept? Is the code could still be correct but fail tests with relaxed timeout?

Timeout are for performance measuring or fail early, if our timeout values just make fail the app when we enable coverage or build on macOS there is an underlying issue of failing too early and give a false negative...

_Originally posted by @yvan-sraka in https://github.com/massalabs/massa/issues/1831#issuecomment-982523836_

**Comment by AureliaDolo** [comment]
@damip

**Comment by damip** [comment]
Correctness and performance are tightly coupled in Massa. For example if a block takes more than t0/2 to propagate, it becomes a correctness issue (it goes out of the basic security assumptions of the architecture).

We mostly need to figure out why propagation takes so much time in the mac os CI

**Comment by yvan-sraka** [comment]
In your opinion is it linked to `cargo-tarpaulin` that make fail https://github.com/massalabs/massa/issues/914?!

**Comment by damip** [comment]
no idea :( it needs to be investigated...

**Comment by damip** [comment]
All tests have been corrected except one that has its own issue. Closing

**Comment by yvan-sraka** [comment]
> All tests have been corrected except one that has its own issue. Closing

Could you link the test here?

**Comment by yvan-sraka** [comment]
> Correctness and performance are tightly coupled in Massa. For example if a block takes more than t0/2 to propagate, it becomes a correctness issue (it goes out of the basic security assumptions of the architecture).
> 
> 
> 
> We mostly need to figure out why propagation takes so much time in the mac os CI

I could convert this reflection into a discussion about how to split correctness VS performance tests?
