### ISSUE TITLE
ASCIInema in Wiki/README

### ISSUE THREAD

**Issue by yvan-sraka** [massalabs/massa#1967]
I feel likes it's the best way to show off most of things https://asciinema.org

**Comment by AureliaDolo** [comment]
That looks shinny :sparkles: 

@Noxhaa

**Comment by damip** [comment]
very sexy, but keeping the official client simple and letting the community make shiny GUI versions makes a lot more sense strategically

**Comment by AureliaDolo** [comment]
From what I understood it is just a way of explaining how it works with a video, not actually changing it in any way.

**Comment by AureliaDolo** [comment]
And again from what I understand, it allows copy pasting directly from the video ?

**Comment by damip** [comment]
oh ok... for now Kesha is doing live sceen recordings, they work just as well

**Comment by AureliaDolo** [comment]
> oh ok... for now Kesha is doing live sceen recordings, they work just as well

But you can't copy paste from a screen recording :) 
(by the way Kesha is not in the github team ?)

**Comment by Noxhaa** [comment]
I'm closing the issue but I saved the link and kept the idea :)
