### ISSUE TITLE
Readonly Smart Contract Calls

### ISSUE THREAD

**Issue by gterzian** [massalabs/massa#1977]
### Discussed in https://github.com/massalabs/massa/discussions/1970

<div type='discussions-op-text'>

<sup>Originally posted by **damip** December  9, 2021</sup>
# Rationale

When using Massa in a Web3 context for example, one should be able to perform read-only Smart Contract calls.

See: https://ethereum.stackexchange.com/questions/765/what-is-the-difference-between-a-transaction-and-a-call/770

# Massa implementation

## API

Add a "sc_readonly_call" API endpoint 

Parameters:
* max_gas: u64  // max gas allowed for the readonly run
* bytecode: `Vec<u8>`  // bytecode to execute

Return value:
* executed_at: Slot  // slot at which the execution happened
* result:
  * (optional) error: Error 
  * (optional) return_value : Vec<u8>  // return value of the bytecode's main() function (TODO this needs to be discussed)
  * (optional) output_events: `Vec<SCOutputEvent>`  // output events generated during execution

 ## Operation

* when the sc_readonly_call is called, the bytecode's main() function will be called with the following execution context:
  * the execution will be done from the point of view of the current slot (even if there is currently no block there)
  * empty initial call stack (anonymous call)

* during the call, everything is allowed as with usual SC calls, except that any syscall attempting to WRITE anything to the SCE ledger will fail. Async message sending also fails when called from within a readonly context.

</div>

**Comment by damip** [comment]
@gterzian  any news or pain points on this ?

**Comment by gterzian** [comment]
> any news or pain points on this ?

Still in progress, is going to be for next week.

> the execution will be done from the point of view of the current slot

@damip What do you mean with the `current slot` here?

**Comment by gterzian** [comment]
Also, would it be good enough to run the code, and then undo the changes, like is currently done when there is an error?

**Comment by damip** [comment]
> @damip What do you mean with the `current slot` here?

the current slot is the latest slot at the current timestamp (see https://github.com/massalabs/massa/issues/1982 )

**Comment by damip** [comment]
> Also, would it be good enough to run the code, and then undo the changes, like is currently done when there is an error? See [628e4fb](https://github.com/massalabs/massa/commit/628e4fbe47ec68bf7805ff74bea9cd28c1c6db2e)

Hmmm maybe we can do that indeed... 

@adrien-zinger  @AureliaDolo @yvan-sraka  any opinions ?

**Comment by adrien-zinger** [comment]
> > Also, would it be good enough to run the code, and then undo the changes, like is currently done when there is an error? See [628e4fb](https://github.com/massalabs/massa/commit/628e4fbe47ec68bf7805ff74bea9cd28c1c6db2e)
> 
> Hmmm maybe we can do that indeed... 
> 
> @adrien-zinger  @AureliaDolo @yvan-sraka  any opinions ?

I totally agree with that !
