### ISSUE TITLE
What's the difference between best_parents and latest_final_blocks_periods

### ISSUE THREAD

**Issue by AureliaDolo** [massalabs/massa#1994]
What's the difference between these two ?

https://github.com/massalabs/massa/blob/46cdb7db16e7d15236f59fcf45d9f73d6ec4dc44/massa-consensus/src/block_graph.rs#L641-L644

**Comment by damip** [comment]
* best_parents are the current best parents that will be used as parents if we create a block. They are the latest blocks of the blockclique for each thread
* latest_final_blocks_periods are the latest final blocks of each thread

**Comment by AureliaDolo** [comment]
So the main difference is that blocks in latest_final_blocks_periods can be incompatible ? Whereas best_parents are always compatible ?

**Comment by damip** [comment]
all final blocks are always compatible, and all the block in a given clique are mutually compatible by definition, so latest_final_blocks_periods are mutually compatible and best_parents are mutually compatible

best_parents are almost never final, while latest_final_blocks_periods are always final

**Comment by AureliaDolo** [comment]
Ok so I guess it could be more clear in the doc

**Comment by damip** [comment]
documentation will come with the big refactoring spec
