### ISSUE TITLE
Bootstrap the ledger SC :computer: 

### ISSUE THREAD

**Issue by adrien-zinger** [massalabs/massa#1996]
With the same method that we bootstrap the nominal ledger we also need to bootstrap the ledger sc.

Look at the code here to know where is used the ledger SC.
https://github.com/massalabs/massa/blob/53d26b74c6d4a14c85ef6a8baadb5a74432522e3/massa-execution/src/vm.rs#L11-L16

The ledger sc is actually static because it was a fast solution to use the datas in both Interface and VM object. Look a the discussion #1984 to have more information. Keep in mind that all the question relative to the interface should be also referenced in this discussion.

With this information, feel free to modify the ledger sc management to success bootstrapping!

For more question about the current bootstrap you can ask @damip, @gterzian, @AureliaDolo.

**Comment by damip** [comment]
In the end, I decided to modify the ledger AFTER its static default initialization to achieve bootstrap
