### ISSUE TITLE
[Client] Create Execute SC operation

### ISSUE THREAD

**Issue by AureliaDolo** [massalabs/massa#1998]
I was thinking about adding a command like that 
```
send_smart_contract <sender_addresses> <path_to_byte_code> <max_gas> <gas_price> <available_coins> <fee>
```

Feel free to comment if you have any suggestions to make that more user friendly. (There will be no tooling around the massa app for now)

**Comment by damip** [comment]
let's have it to be able to interact with the SCE :)
