### ISSUE TITLE
MassaHash::from() is ambiguous

### ISSUE THREAD

**Issue by damip** [massalabs/massa#2002]
Hash::from in massa_hash does not create a MassaHash from bytes as one would expect (like from_bytes) but builds the MassaHash by computing the sha256 of the provided bytes.

This behavior is counter-intuitive, or at least ambiguous and can cause silent errors that are hard to detect .

We need to force a more explicit usage by forbidding "from" and adding a "hash_bytes" method for example

**Comment by yvan-sraka** [comment]
I see you add the `p1` priority flag! I could tackle this issue next sprint, it was my plan since the beginning to refactor and name everything in a less fuzzy non-obvious way!

**Comment by adrien-zinger** [comment]
Is it really 6.0 ?

**Comment by adrien-zinger** [comment]
> I see you add the `p1` priority flag! I could tackle this issue next sprint, it was my plan since the beginning to refactor and name everything in a less fuzzy non-obvious way!

this should be a discussion

**Comment by yvan-sraka** [comment]
we start discussing a bit about it here https://github.com/massalabs/massa/issues/1133

**Comment by damip** [comment]
yes we can rename ambiguous things. I added P1 to this one because the naming here is literally wrong and will cause silent errors in critical crypto sections of the code

**Comment by AureliaDolo** [comment]
Haven't we agree to change the priorities only on Monday mornings ?

**Comment by damip** [comment]
it's a quick fix, and it can be done anytime for V6

**Comment by yvan-sraka** [comment]
> it's a quick fix, and it can be done anytime for V6, no rush, but we must not forget it

Ok I take this issue I will tackle it next week :)

**Comment by AureliaDolo** [comment]
So what's a really better name ? @yvan-sraka @damip

**Comment by damip** [comment]
I vote for `Hash::compute_,from([u8])->Hash`
