### ISSUE TITLE
[FAQ] private keys sent over insecure connection

### ISSUE THREAD

**Issue by AureliaDolo** [massalabs/massa#2004]
We can at least add a section in the FAQ to warn users.

_Originally posted by @AureliaDolo in https://github.com/massalabs/massa/issues/1999#issuecomment-993707750_

**Comment by Noxhaa** [comment]
Added here:
https://github.com/massalabs/massa/wiki/FAQ#how-secure-are-the-private-keys

@AureliaDolo @damip

**Comment by AureliaDolo** [comment]
Regarding the communication between nodes, you can add that a handshake is performed at the connection with another peer. We sign random bytes that the peer sent us with our private key, and same on the other side. And data that is sent after that is signed by its creator, not the node that is sending it to us.

During the bootstrap, the handshake is asymmetric. We know the public key of the bootstrap node and we expect signed messages from it, but we do not communicate our public key, nor we sign the only message we send (just random bytes).

**Comment by Noxhaa** [comment]
Information added
