### ISSUE TITLE
Add and document monitoring scripts

### ISSUE THREAD

**Issue by qdrn** [massalabs/massa#2009]
It would be nice to add the various scripts that we use to log cpu/RAM/network/... activities and to document the usage so that we can share same with the community in order to help them identify why their nodes are failing.

**Comment by Noxhaa** [comment]
It would be nice indeed! I only have one from @sebastien-forestier so far and I haven't used python to visualize the data yet. I'll focus on the scripts first and share them on the wiki.

**Comment by AureliaDolo** [comment]
We can even make another public repo (or a submodule) to share some official scripts !

**Comment by Noxhaa** [comment]
I'm not very familiar with submodules but I checked and we could do that (and it seems to please people).

I will proceed today as follow:
- [ ] Adding a page to the wiki with the useful commands that I use (pidstat, vnstat) and how to run them
- [ ] Finish to adapt and share the py file "stats" from Seb
- [ ] Add others resources that helps monitor the node in general (The ones from the community)
- [ ] Review and create submodule/repo if necessary

**Comment by AureliaDolo** [comment]
@AurelienFT

**Comment by Noxhaa** [comment]
I created the page on the wiki and added some [commands](https://github.com/massalabs/massa/wiki/Monitoring-scripts-and-commands). Feel free to review it.

I worked on the python script but I have a small issue, I shall finish it this weekend.

**Comment by qdrn** [comment]
Closing as it's a very low priority and some of it is done by the inno team.
