### ISSUE TITLE
Man/Wiki/FAQ access in the client

### ISSUE THREAD

**Issue by AureliaDolo** [massalabs/massa#2010]
Add a wiki/faq/man/support (choose your preferred name) command in the client. 
At first we can just list common issues/questions and link the wiki or display the concerned section in the client.
That could be a special mode of the client, to not pollute the real commands.

And we could add a definition for each concept (maybe retrieved from a definitions page in the wiki)

In the future we may even add a little bit of NLP so people can just talk to the client (or this mode of the client) and maybe it may even redirect people to real people when it can't answer.

**Comment by damip** [comment]
This seems like a lot of work for little benefit. Why not just redirect to the online wiki ?

**Comment by AureliaDolo** [comment]
> This seems like a lot of work for little benefit. Why not just redirect to the online wiki ?

Maybe I went a little bit overkill with the NLP, but at first adding a few links at start up (or when displaying help) to the most important parts and the most frequently asked question could help the mods @Noxhaa

**Comment by Noxhaa** [comment]
If we use links and they lead to the WIki I think it's better. Having to update information in multiples places on a project that keeps on changing can be tricky, it's easy to overlook.

A link to the FAQ might be enough. People who installed the node are supposed to be coming from the wiki already.

**Comment by damip** [comment]
As per @Noxhaa 's feedback , closing the issue.
