### ISSUE TITLE
Maybe add a raspberry pi section in wiki/troubleshooting

### ISSUE THREAD

**Issue by AureliaDolo** [massalabs/massa#2012]
see https://discord.com/channels/828270821042159636/829703120409722930/921284381086199906 and https://github.com/massalabs/massa/issues/1249

**Comment by AureliaDolo** [comment]
@Noxhaa it seems a common issue

**Comment by Noxhaa** [comment]
I wrote a little something in the FAQ : https://github.com/massalabs/massa/wiki/FAQ#raspberry-pi-problem-thread-main-panicked

**Comment by damip** [comment]
Let's remind everyone that raspberry pis are NOT a supported architecture

**Comment by AureliaDolo** [comment]
> I wrote a little something in the FAQ : https://github.com/massalabs/massa/wiki/FAQ#raspberry-pi-problem-thread-main-panicked
> 
> @AureliaDolo @damip

You can always link #1249 so people that are interested can easily find how it is going on

**Comment by Noxhaa** [comment]
I didn't add it yet, as this issue doesn't seem to present a solution to the problem and we don't encourage the use of a Raspberry PI. But I noted the link to send in case of
