### ISSUE TITLE
Spec: from blocks to VM

### ISSUE THREAD

**Issue by damip** [massalabs/massa#2015]
Write a spec describing the journey from the consensus block graph to their execution in the smart contract VM

==> https://github.com/massalabs/massa/wiki/From-blocks-to-VM-execution

**Comment by yvan-sraka** [comment]
I would love to split wiki pages between:
- **User** documentation**: tutorials
- **Dev documentation**: internals (like, do we out the doc in an `hacking` subfolder?)

**Comment by damip** [comment]
@yvan-sraka  this is part of the dev doc. What should I do to split it away from the user doc ?

**Comment by yvan-sraka** [comment]
Create a `docs/hacking` subfolder and put dev dec in it?!

**Comment by damip** [comment]
@yvan-sraka  I tried... https://raw.githubusercontent.com/wiki/massalabs/massa/hacking/vm-block-feed

Looks like github's wiki system does not support subfolders (?)

**Comment by yvan-sraka** [comment]
@damip the right link is https://github.com/massalabs/massa/wiki/vm-block-feed :wink:!

**Comment by damip** [comment]
@yvan-sraka  how come the subfolder is not in the url ? What happens if we have a home in the root folder and another in a subfolder (with the same name) ?
