### ISSUE TITLE
network crash

### ISSUE THREAD

**Issue by damip** [massalabs/massa#2043]
![screen](https://user-images.githubusercontent.com/10211103/147373032-31cd84f5-465c-4ff5-a959-963caa017679.jpg)

**Comment by adrien-zinger** [comment]
It crashed during the stop? It's on the testnet branch?

**Comment by damip** [comment]
Testnet branch, crash during stop i think

**Comment by AureliaDolo** [comment]
It wasn't able to send a stop command to the node (as in node_worker.rs file, not the whole node) I guess it's related to that https://github.com/massalabs/massa/blob/ddefe92ddca6b0ab23698f81eeb489302be00ecc/massa-network/src/node_worker.rs#L386-L389

**Comment by AureliaDolo** [comment]
By the way @damip , do we really want that for 6.0 ?

**Comment by damip** [comment]
no, moved it to 7 :)

**Comment by AureliaDolo** [comment]
So I move it to 8.
