### ISSUE TITLE
error while bootstrapping

### ISSUE THREAD

**Issue by the-kote** [massalabs/massa#2044]
Hey! I have set up a new node on a dedicated server. After a few days, I updated the ssd on the server, so I reinstalled the node again. After that, the mass-node cannot bootstrap with messages such as (about 48h have passed):

WARN bootstrap: error while bootstrapping: io error: deadline has elapsed
WARN bootstrap: error while bootstrapping: io error: bootstrap handshake timed out

![massa](https://user-images.githubusercontent.com/95477800/147544278-88c9e2d1-7f20-4489-abd7-b6cab9e1afc9.png)

TCP 31244 and TCP 31245 are open on the router and allowed by the firewall. The first time I had install the node from source code, the second time I try and source code code and from the compiled binary - with the same result.

CPU 6C/12T, 32GB RAM, 1TB nvme
Ubuntu Server 20.04.3 LTS

What could be wrong?

**Comment by damip** [comment]
There seems to be a problem indeed, the nodes completely fails to bootstrap anyone when too many people (1000+) are trying to bootstrap at the same time.

**Comment by AureliaDolo** [comment]
It happened during the stress test at the end of the last testnet ?

**Comment by damip** [comment]
> 

Yes

**Comment by AureliaDolo** [comment]
Maybe it's because bootstrap nodes are banning peers for a few minutes and if the peer tries again, its ban time is increased. So maybe we could ensure that at least ban time has elapsed before trying again ?

**Comment by damip** [comment]
waitinf ban time makes sense only if the failure happened after establishing contact with the server. 
If the failure reason is for example lack of internet connectivity, it is better to keep a short retry time

**Comment by AureliaDolo** [comment]
And what if we have a short retry time and a longer restart time that after maybe half an hour either shut down the node completely or waits another half an hour before trying to bootstrap ?

**Comment by damip** [comment]
Most of the laod comes from people trying and failing to bootstrap, not from people whose node desyncs and restarts (the interval for this is very logn anyways, multiple cycles)

**Comment by AureliaDolo** [comment]
> Most of the laod comes from people trying and failing to bootstrap, not from people whose node desyncs and restarts (the interval for this is very logn anyways, multiple cycles)

I was thinking more about after half an hour of continuous bootstrap attempts we stop for a while, without the user needing to intervene.

**Comment by damip** [comment]
hmm that would reduce the load a bit, but it depends on the parameters (for how long do we try ? for how long do we wait ?)

**Comment by AureliaDolo** [comment]
> hmm that would reduce the load a bit, but it depends on the parameters (for how long do we try ? for how long do we wait ?)

We say people to stop trying to bootstrap for like half an hour or so and it seems to work

**Comment by damip** [comment]
strange

**Comment by AureliaDolo** [comment]
Maybe we have some kind of deadlock that is going on, as it seems a recurrent issue

**Comment by nodar395863** [comment]
I have same problem  , active roles are reset every day

**Comment by damip** [comment]
> I have same problem , active roles are reset every day

this is not the same problem. Here we are discussing a problem with bootstrapping (not roll sales)

**Comment by damip** [comment]
Solved (at least partially) by https://github.com/massalabs/massa/pull/2255

Let's reopen if it happens again
