### ISSUE TITLE
Transfer_coins ABI massa side

### ISSUE THREAD

**Issue by damip** [massalabs/massa#2055]
Add execution ABIs to transfer balance coins (spend from source, credit target):
* `transfer_coins(to_address: &str, raw_amount: u64)`
* `transfer_coins_for(from_address: &str, to_address: &str, raw_amount: u64)`

Note that raw_amount is the Amount AFTER multiplication by AMOUNT_DECIMAL_FACTOR

**Comment by gterzian** [comment]
@damip What is `AMOUNT_DECIMAL_FACTOR`? Can you please link to it in the code?

**Comment by damip** [comment]
@gterzian https://github.com/massalabs/massa/blob/feature/execution/add_cautious_bassoon/massa-models/src/settings.rs#L10

The internal representation of Amount is u64 but its string/user-facing interface is decimal. The decimal string representation is multiplied by AMOUNT_DECIMAL_FACTOR to obtain the internal u64 representation without loss of precision.

See https://github.com/massalabs/massa/blob/feature/execution/add_cautious_bassoon/massa-models/src/amount.rs
