### ISSUE TITLE
Bug: smart contract operation stuck in pool

### ISSUE THREAD

**Issue by AureliaDolo** [massalabs/massa#2073]

**Comment by damip** [comment]
I wasn't able to reproduce it with 1 node... it worked well in my tests

**Comment by sebastien-forestier** [comment]
Here is some log reproducing it:
[log.txt](https://github.com/massalabs/massa/files/7821139/log.txt)

I used 
`send_smart_contract ek1NWuumgfU2YkkAFkXkAsPFQvrCg5V2Zi15xmYy8434EU96v ./get_string.wat 1000000 0.001 0 1`

In the logs I see only things about propagating the operation.

**Comment by damip** [comment]
@sebastien-forestier 
The mqx gas per block was set to 10. So thisnbehavior is expected

**Comment by damip** [comment]
This should be fixed. Closing. If the problem re-appears, we should open a new one
