### ISSUE TITLE
Test: sc operation processing in block reception 

### ISSUE THREAD

**Issue by AureliaDolo** [massalabs/massa#2075]
Todo scenario

**Comment by gterzian** [comment]
@AureliaDolo Can you provide more info please? You could for example describe which part of the code this would relate to(and link to those parts with a permanent link by pressing `y`)

**Comment by AureliaDolo** [comment]
@gterzian I was thinking about adding an executeSc operation in here https://github.com/massalabs/massa/blob/main/massa-consensus/src/tests/scenarios_operations_check.rs

**Comment by gterzian** [comment]
Ok thanks, I'll take this one.
