### ISSUE TITLE
Finish output event system

### ISSUE THREAD

**Issue by AureliaDolo** [massalabs/massa#2080]

**Comment by damip** [comment]
here is a temporary alternative: https://github.com/massalabs/massa/pull/2083

**Comment by AureliaDolo** [comment]
> here is a temporary alternative: #2083

Should I remove that log ?

**Comment by AureliaDolo** [comment]
I'm quite stuck here: 
I want to have a struct like that
```rust
struct EventStore {
    map: HashMap<EventId, SCOutputEvent>,
    caller_to_event: HashMap<Address, EventId>,
    sc_to_event: HashMap<Address, EventId>,
    slot_to_event: HashMap<Slot, EventId>,
}
```
It would keep at most a configured number of output events.

I'm feeling quite confused with the following aspects
- How do I get an eventId ? What happens when the same event is produced twice during a block's execution ? I feel like it should not have the same id twice
- Do I keep that store at executionContext level ? Or somewhere else would be more appropriate ? 

Anyway, as I don't really know how exactly that will be used, if you have any suggestions :crab:  

@damip @z80dev @adrien-zinger @gterzian @yvan-sraka

**Comment by gterzian** [comment]
> Do I keep that store at executionContext level ? Or somewhere else would be more appropriate ?

I would say it should be kept in `execution`, and if necessary exposed via a command(if other components like the api need to access it). 

> What happens when the same event is produced twice during a block's execution. I feel like it should not have the same id twice

I think an event id should represent a single event, so if the "same" is fired multiple times they should have different ids(and not be the "same"). 

You probably need a `VecDeque` inside those maps(you could pop from the back/front once a limit has been reached).

**Comment by gterzian** [comment]
> How do I get an eventId 

I would say we need to do something similar as what has been done with other `_Id`, for example [`EndorsementId`](https://github.com/massalabs/massa/blob/992573de2b22d7f40d5502e59e946d922d33a57a/massa-models/src/endorsement.rs)

**Comment by AureliaDolo** [comment]
> > How do I get an eventId
> 
> I would say we need to do something similar as what has been done with other `_Id`, for example [`EndorsementId`]

The issue I have with just hashing, is that every thing else that we get an id from has a signature in it so if it has the same hash it's really the same object generated only once, but we don't have that guarantee here :/

**Comment by damip** [comment]
Indeed, this needs more specification.

* we need to make sure that events generated in a readonly context are not sent to the global execution event storage but only back to be displayed in the client
* event emission needs to behave just like the SCE ledger changes and be added to the execution step history system: if a slot execution is cancelled/rolled back, its events need to be discarded as well
* event IDs can be computed as such: Hash(concatenate(slot, idnex_of_the_event_generated_at_that_slot) ) the same way we did for generating the hash of new SCs

**Comment by AureliaDolo** [comment]
I'm not sure about how to manage the index with read only calls, I can't increment it otherwise it won't be read only for real and I must have one otherwise two read only events can have the same id. Maybe I can work with a read only event count, but that seems weird. Or we just send read only events right to the client without computing their ids ?

**Comment by damip** [comment]
Nothing prevents you from incrementing it within the execution context, it has no consequence on execution history nor on the ledger. That's what we ended up deciding (Greg's idea) for read-only: do everything as if it was not read-only except 2 things:
* read_only = True in the context
* do not write the result of the execution into the execution steps history, that way everything that happened during the read-only execution has no consequence

**Comment by AureliaDolo** [comment]
What happens if at one slot event 1 and event 2 are RW produced, but on your node there was a read only event in between ? From what I understand the id of event 2 will be impacted by the existence on the RO event.

**Comment by AureliaDolo** [comment]
My issue was the the id of event 2 will be different whether RO event was executed on your not or not
