### ISSUE TITLE
Give an other name to feature `test` since it's a bit confusing ...

### ISSUE THREAD

**Issue by AureliaDolo** [massalabs/massa#2084]
I would create a follow-up issue on giving an other name to feature `test` since it's a bit confusing ...

_Originally posted by @yvan-sraka in https://github.com/massalabs/massa/pull/2069#pullrequestreview-844920489_

And update at the end of this page accordingly https://github.com/massalabs/massa/wiki/Resources-for-community-builders

**Comment by yvan-sraka** [comment]
`free-coins` sounds good :) (maybe be a bit advertising :money_mouth_face: but good)

**Comment by damip** [comment]
The problem with `free-coins` is that if you're an actual user, it's not very self-explanatory :)

Basically it's only clear to the person that created it. Others will need to read documentation to figure out what it is (if there is any documentation)

I would vote for `local-sandbox` something similar.

There is a similar problem with `[cornetto(const, 200)]`  : It's like reading `bananas(1000, dyn)`  and requires readers of the code to digress into reading external documentation to have a vague idea of what is going on. Something like `[set_value(const, 200)]`  would make it clearer.

What do you think ? (try to think as an end-user discovering it for the first time)

**Comment by AureliaDolo** [comment]
> I would vote for local-sandbox something similar.

I feel like there could be a misunderstanding with connections to other nodes. Having local in the name seems like their won't be connections to other, but that's false.

**Comment by AureliaDolo** [comment]
So let it be sandbox. And I'll add a check of the version: something along the lines of if sandbox then version = SAND.0.0 else the current version. In order to avoid as many connections as possible
