### ISSUE TITLE
Re-enable blockclique execution in VM

### ISSUE THREAD

**Issue by damip** [massalabs/massa#2101]
In pull request TODO, we disabled the exection of non-SCE-final blocks for performance reasons until we figure out optimizations.

TODO: re-enable them

Note: disabled sections contain "TODO DISABLED TEMPORARILY https://github.com/massalabs/massa/issues/2101"

**Comment by AureliaDolo** [comment]
So that means right now we only execute stuff at sce finality right ?

**Comment by damip** [comment]
> So that means right now we only execute stuff at sce finality right ?

true, we need to discuss how to implement history reuse (to avoid recomputing everything since finality when a single block is added) a "time cursor" that tries to execute all slots speculatively until the current time, and automatically goes 'lags" in time if it cannot go fast enough to follow real time, up to the limit of SCE-final slots of course.
