### ISSUE TITLE
Make a shinny graph to explain how the execution component works

### ISSUE THREAD

**Issue by AureliaDolo** [massalabs/massa#2123]
I don't know if I'm alone, but I'm getting easily lost in this part of the code, so it would be nice to have a graph, especially withe the execution step stuff. Kinda like we did with the block graph.

**Comment by AureliaDolo** [comment]
@adrien-zinger @gterzian I guess you're the ones that worked the most on that part

**Comment by AureliaDolo** [comment]
@damip maybe you could help us on that

**Comment by damip** [comment]
I am currently working on updating the block feed system for speculative execution. I will update the spec. I don't have the time to make (and especially maintain) graphs tho. If something is unclear in the text, please signal it for improvement

**Comment by damip** [comment]
A lot of documentation was added. Closing this for now
