### ISSUE TITLE
Revert #2141 after bugfix (and update wiki)

### ISSUE THREAD

**Issue by AureliaDolo** [massalabs/massa#2142]
Revert #2141 after https://github.com/rust-lang/rust/pull/92781 is merged and the compiler bug fixed

And don't forget to update the default nightly locally too. 
And maybe we should add a line about that in the doc, as currently testnet users pinned a specific nightly as default.

**Comment by AureliaDolo** [comment]
I was thinking about adding a line to make sure everyone uses the latest nightly as default I order to avoid that people that were here during the bug keep using the pinned version @Noxhaa

**Comment by Noxhaa** [comment]
I will just need to add `rustup default nightly` on the update tutorial. I'll do so just before the release of 6.6. Please keep me posted when you know when this will be.
