### ISSUE TITLE
Error: Index out of range at ~lib/array.ts:114 col: 42

### ISSUE THREAD

**Issue by vladimirdotk** [massalabs/massa#2143]
**Describe the bug**
At 122 cycle several people detected  an error in logs: `Error: Index out of range at ~lib/array.ts:114 col: 42`.

It seems like some kind of bug. Thought it might be important.

**Screenshots**
<img width="1415" alt="Screenshot 2022-01-12 at 20 11 31" src="https://user-images.githubusercontent.com/8599007/149188587-2f50c8ce-39d0-4afd-a830-9305c4e9aefe.png">

**Comment by adrien-zinger** [comment]
Hi! It isn't a bug, @vladimirdotk don't worry :slightly_smiling_face: this warning was thrown by a smart contract that failed for some reason, it's not related to the nodes or the blockclique.

In the current version, we're printing the smart contract's events on every node, also warnings! :sweat_smile: For the next versions, we will add a kind of `listening system` for each execution of a contract, and you will specify if you want to log it or not.
