### ISSUE TITLE
bug for consensus

### ISSUE THREAD

**Issue by capknsedat** [massalabs/massa#2153]
warning: an associated function with this name may be added to the standard library in the future
   --> massa-consensus/src/pos.rs:523:37
    |
523 |         let bits_u8_len = n_entries.div_ceil(&u8::BITS) as usize;
    |                                     ^^^^^^^^
    |
    = note: `#[warn(unstable_name_collisions)]` on by default
    = warning: once this associated item is added to the standard library, the ambiguity may cause an error or change in behavior!
    = note: for more information, see issue #48919 <https://github.com/rust-lang/rust/issues/48919>
    = help: call with fully qualified syntax `num::Integer::div_ceil(...)` to keep using the current method
    = help: add `#![feature(int_roundings)]` to the crate attributes to enable `core::num::<impl u32>::div_ceil`

   Compiling massa_api v0.1.0 (/root/massa/massa-api)
   Compiling massa_bootstrap v0.1.0 (/root/massa/massa-bootstrap)
w

**Comment by capknsedat** [comment]
rust giving ever error

**Comment by AureliaDolo** [comment]
It's a warning, it should not prevent your node from working properly. It was fixed in main.
