### ISSUE TITLE
DiscardReason::Invalid:discarded because a parent was discarded for the following reason

### ISSUE THREAD

**Issue by r1k0** [massalabs/massa#2159]
**Describe the bug**

INFO log suddenly show many logs such as

```
Jan 16 21:33:45 massa massa-node[456714]: #033[2m2022-01-16T20:33:45.862439Z#033[0m #033[32m INFO#033[0m #033[2mmassa_consensus::block_graph#033[0m#033[2m:#033[0m consensus.block_graph.maybe_note_attack_attempt DiscardReason::Invalid:discarded because a parent was discarded for the following reason: discarded because a parent was discarded for the following reason: discarded because a parent was discarded for the following reason: discarded because a parent was discarded for the following reason: discarded because a parent was discarded for the following reason: block graph check_operations error, operation apply to state: there was an inconsistency between containers final PoS cycle not available: 298
```

then, CPU drops, network drops and eventually staking will stop missing cycles and rolls will be sold.
If I spot the issue fast enough and restart the node, staking resumes, blocks are created again until the issue rises again.

**To Reproduce**

I have no idea how to reproduce it.
Start the node and wait. This occurs only for the last 2 days and 3 times in the last few hours.

**Expected behavior**
Issue should not occur as it stops staking and eventually sell rolls.

**Screenshots**

![image](https://user-images.githubusercontent.com/238676/149677470-fc712c78-25c6-4f19-a18e-1fda616e982b.png)

**Desktop (please complete the following information):**

- OS: ubuntu 20.04 

**Smartphone (please complete the following information):**

no phone

**Additional context**

Attached syslog with all logs.
[syslog.log](https://github.com/massalabs/massa/files/7877913/syslog.log)

monitoring:
![image](https://user-images.githubusercontent.com/238676/149678325-9319446b-0186-484d-857c-f60744a4a459.png)
![image](https://user-images.githubusercontent.com/238676/149678329-f8c344e0-35e8-4381-ab53-b7360ea6e138.png)

specs:
Intel(R) Core(TM) i9-9980HK CPU @ 2.40GHz
16G ram
50G disk

**Comment by AureliaDolo** [comment]
It looks like you have two cliques that are close enough so you're node is not able to see which one is the real one, until you reach a point when the data used to generate the seed used to draw the stakers is not final in time. When you reach that point you discard the block you weren't able to check and all it's descendants. But in the meantime you weren't able to produce blocks because you weren't able to check their correctness, hence the misses.

@damip in my opinion this seems quite worrying what do you think ?

**Comment by damip** [comment]
The ultimate reason for discard is "PoS cycle not available". 
Looks to me like blocks being processed or received too slowly (?)

**Comment by r1k0** [comment]
Also, I would like to point out that in syslog.log it shows that the issue pops up every time right after the start of a new cycle.
The chances that a long disconnection occurs only when the node prints "Started cycle XXX" is very very low isn't it?
Look at "Started cycle 263" and "Started cycle 295" and "Started cycle 298" in syslog.log.
I think there is something occurring at the very start of a cycle that triggers the PoS loopback to not be available at the very start of a cycle.

**Comment by damip** [comment]
>  the issue pops up every time right after the start of a new cycle
> The chances that a long disconnection occurs only when the node prints "Started cycle XXX" is very very low isn't it?

Take the worst case: if you are disconnected permanently starting from cycle X, the error will appear only when your node starts asking for a block that belongs to a cycle X+3 or later.

That being said, we still need to look into it !

**Comment by r1k0** [comment]
OK I see.
Issue appeared again, 10min ago.
Note that at the start of cycle 333 staking seemed to work. And I have noticed no internet downtime as I'm working from home via vpn and have a constant SSH shell opened on the node.

`Jan 17 17:26:24 massa massa-node[584058]: #033[2m2022-01-17T16:26:24.001322Z#033[0m #033[32m INFO#033[0m #033[2mmassa_consensus::consensus_worker#033[0m#033[2m:#033[0m Started cycle 333
Jan 17 17:26:36 massa massa-node[584058]: #033[2m2022-01-17T16:26:36.505908Z#033[0m #033[32m INFO#033[0m #033[2mmassa_consensus::consensus_worker#033[0m#033[2m:#033[0m Staked block 2Sp7P7nDqwhZzRaugA7wM5vDD6Xz5mdaJUggKh2t32JJzap56Q with address 28kU4nfEnbsxDDvU6xgkA3hG6LpvcsHwH7B1mKY4jvJpWDzd6z, at cycle 333, period 42624, thread 25
Jan 17 17:26:36 massa massa-node[584058]: #033[2m2022-01-17T16:26:36.508896Z#033[0m #033[32m INFO#033[0m #033[2mmassa_consensus::consensus_worker#033[0m#033[2m:#033[0m Next block creation slot for address 28kU4nfEnbsxDDvU6xgkA3hG6LpvcsHwH7B1mKY4jvJpWDzd6z: cycle 333, period 42626, thread 30, at time 2022-01-17 16:27:11 UTC
Jan 17 17:27:11 massa massa-node[584058]: #033[2m2022-01-17T16:27:11.007494Z#033[0m #033[32m INFO#033[0m #033[2mmassa_consensus::consensus_worker#033[0m#033[2m:#033[0m Staked block 2JzVeezFmfErMfWtCLG7mtgZGoLcvhGfC5FgHmrjbxUZznVCrW with address 28kU4nfEnbsxDDvU6xgkA3hG6LpvcsHwH7B1mKY4jvJpWDzd6z, at cycle 333, period 42626, thread 30
Jan 17 17:27:11 massa massa-node[584058]: #033[2m2022-01-17T16:27:11.012016Z#033[0m #033[32m INFO#033[0m #033[2mmassa_consensus::consensus_worker#033[0m#033[2m:#033[0m Next block creation slot for address 28kU4nfEnbsxDDvU6xgkA3hG6LpvcsHwH7B1mKY4jvJpWDzd6z: cycle 333, period 42629, thread 8, at time 2022-01-17 16:27:48 UTC
Jan 17 17:27:43 massa massa-node[584058]: #033[2m2022-01-17T16:27:43.018912Z#033[0m #033[33m WARN#033[0m #033[2mmassa_consensus::block_graph#033[0m#033[2m:#033[0m block graph check_operations error, operation apply to state: there was an inconsistency between containers final PoS cycle not available: 333
Jan 17 17:27:43 massa massa-node[584058]: Discarding ops: Invalid("block graph check_operations error, operation apply to state: there was an inconsistency between containers final PoS cycle not available: 333")
Jan 17 17:27:43 massa massa-node[584058]: #033[2m2022-01-17T16:27:43.018933Z#033[0m #033[32m INFO#033[0m #033[2mmassa_consensus::block_graph#033[0m#033[2m:#033[0m consensus.block_graph.maybe_note_attack_attempt DiscardReason::Invalid:block graph check_operations error, operation apply to state: there was an inconsistency between containers final PoS cycle not available: 333
Jan 17 17:27:46 massa massa-node[584058]: #033[2m2022-01-17T16:27:46.432004Z#033[0m #033[32m INFO#033[0m #033[2mmassa_protocol_worker::protocol_worker#033[0m#033[2m:#033[0m Connected to node 6Sne9WHemzbsy5xnydr6BgyTqtxcb1D2gPE5ex5BywrrjcCX3f
Jan 17 17:27:46 massa massa-node[584058]: #033[2m2022-01-17T16:27:46.564235Z#033[0m #033[32m INFO#033[0m #033[2mmassa_protocol_worker::protocol_worker#033[0m#033[2m:#033[0m Connected to node 5gXGzG8aSHR9dsJbAiEPzcoBhfLV5Rj2wM2HiYusDAN6iyNPD3
Jan 17 17:27:46 massa massa-node[584058]: #033[2m2022-01-17T16:27:46.838185Z#033[0m #033[32m INFO#033[0m #033[2mmassa_consensus::block_graph#033[0m#033[2m:#033[0m consensus.block_graph.maybe_note_attack_attempt DiscardReason::Invalid:discarded because a parent was discarded for the following reason: discarded because depend on block:8sibXmnRQh77rLyMUcHGq7uknbbN52t7CF2ctSyYUdt2G6sfA that has discard reason:block graph check_operations error, operation apply to state: there was an inconsistency between containers final PoS cycle not available: 333
Jan 17 17:27:47 massa massa-node[584058]: #033[2m2022-01-17T16:27:47.308534Z#033[0m #033[32m INFO#033[0m #033[2mmassa_protocol_worker::protocol_worker#033[0m#033[2m:#033[0m Connected to node 7533H6vc9dE3i1wnRiByDAXmVNtwNWBZvFDWTmshYPxVGeRjPc
Jan 17 17:27:47 massa massa-node[584058]: #033[2m2022-01-17T16:27:47.333225Z#033[0m #033[32m INFO#033[0m #033[2mmassa_consensus::block_graph#033[0m#033[2m:#033[0m consensus.block_graph.maybe_note_attack_attempt DiscardReason::Invalid:discarded because a parent was discarded for the following reason: discarded because a parent was discarded for the following reason: discarded because depend on block:8sibXmnRQh77rLyMUcHGq7uknbbN52t7CF2ctSyYUdt2G6sfA that has discard reason:block graph check_operations error, operation apply to state: there was an inconsistency between containers final PoS cycle not available: 333
Jan 17 17:27:48 massa massa-node[584058]: #033[2m2022-01-17T16:27:48.006410Z#033[0m #033[32m INFO#033[0m #033[2mmassa_consensus::consensus_worker#033[0m#033[2m:#033[0m Staked block hPQjThVLeKYurzuhTYa5geRywu6Hfj9nC4fNDP8oPTPanwTQS with address 28kU4nfEnbsxDDvU6xgkA3hG6LpvcsHwH7B1mKY4jvJpWDzd6z, at cycle 333, period 42629, thread 8
Jan 17 17:27:48 massa massa-node[584058]: #033[2m2022-01-17T16:27:48.011077Z#033[0m #033[32m INFO#033[0m #033[2mmassa_consensus::consensus_worker#033[0m#033[2m:#033[0m Next block creation slot for address 28kU4nfEnbsxDDvU6xgkA3hG6LpvcsHwH7B1mKY4jvJpWDzd6z: cycle 333, period 42642, thread 9, at time 2022-01-17 16:31:16.500 UTC
Jan 17 17:27:49 massa massa-node[584058]: #033[2m2022-01-17T16:27:49.116515Z#033[0m #033[32m INFO#033[0m #033[2mmassa_protocol_worker::protocol_worker#033[0m#033[2m:#033[0m Connected to node 5cK9X3XfyFTWChrogBVd5mCoANmmdkkxarkSzBF5Z2VTPyucSx
Jan 17 17:27:52 massa massa-node[584058]: #033[2m2022-01-17T16:27:52.987100Z#033[0m #033[32m INFO#033[0m #033[2mmassa_protocol_worker::protocol_worker#033[0m#033[2m:#033[0m Connected to node 7mTMFf6qc5ZLNzWrA7PBushp9fygBuyLxaWfeU7nvDYzgWKgRX
Jan 17 17:27:54 massa massa-node[584058]: #033[2m2022-01-17T16:27:54.901953Z#033[0m #033[32m INFO#033[0m #033[2mmassa_protocol_worker::protocol_worker#033[0m#033[2m:#033[0m Connection closed with 7mTMFf6qc5ZLNzWrA7PBushp9fygBuyLxaWfeU7nvDYzgWKgRX
Jan 17 17:27:55 massa massa-node[584058]: #033[2m2022-01-17T16:27:55.936257Z#033[0m #033[32m INFO#033[0m #033[2mmassa_protocol_worker::protocol_worker#033[0m#033[2m:#033[0m Connected to node 7mTMFf6qc5ZLNzWrA7PBushp9fygBuyLxaWfeU7nvDYzgWKgRX
Jan 17 17:27:56 massa massa-node[584058]: #033[2m2022-01-17T16:27:56.639542Z#033[0m #033[32m INFO#033[0m #033[2mmassa_protocol_worker::protocol_worker#033[0m#033[2m:#033[0m Connection closed with 5cK9X3XfyFTWChrogBVd5mCoANmmdkkxarkSzBF5Z2VTPyucSx
Jan 17 17:27:56 massa massa-node[584058]: #033[2m2022-01-17T16:27:56.936348Z#033[0m #033[32m INFO#033[0m #033[2mmassa_protocol_worker::protocol_worker#033[0m#033[2m:#033[0m Connection closed with 7mTMFf6qc5ZLNzWrA7PBushp9fygBuyLxaWfeU7nvDYzgWKgRX
Jan 17 17:27:58 massa massa-node[584058]: #033[2m2022-01-17T16:27:58.450064Z#033[0m #033[32m INFO#033[0m #033[2mmassa_protocol_worker::protocol_worker#033[0m#033[2m:#033[0m Connected to node 7mTMFf6qc5ZLNzWrA7PBushp9fygBuyLxaWfeU7nvDYzgWKgRX
Jan 17 17:28:03 massa massa-node[584058]: #033[2m2022-01-17T16:28:03.303026Z#033[0m #033[32m INFO#033[0m #033[2mmassa_protocol_worker::protocol_worker#033[0m#033[2m:#033[0m Connected to node 8AmLa77KBh7G7yFR3SEs336bUopzW1oLak54CvmawKQHh3Eo3n
Jan 17 17:28:03 massa massa-node[584058]: #033[2m2022-01-17T16:28:03.500426Z#033[0m #033[32m INFO#033[0m #033[2mmassa_protocol_worker::protocol_worker#033[0m#033[2m:#033[0m Connected to node 6LcUPS7Dpu7Ci9hZhn1UTcWpFifEsY6pdttMBSHA492Xir5UTm
Jan 17 17:28:03 massa massa-node[584058]: #033[2m2022-01-17T16:28:03.581893Z#033[0m #033[32m INFO#033[0m #033[2mmassa_consensus::block_graph#033[0m#033[2m:#033[0m consensus.block_graph.maybe_note_attack_attempt DiscardReason::Invalid:discarded because a parent was discarded for the following reason: discarded because a parent was discarded for the following reason: discarded because depend on block:8sibXmnRQh77rLyMUcHGq7uknbbN52t7CF2ctSyYUdt2G6sfA that has discard reason:block graph check_operations error, operation apply to state: there was an inconsistency between containers final PoS cycle not available: 333
`

**Comment by r1k0** [comment]
same issue for cycle 336.
made a script that runs in bg and restarts the node each time the message shows up, dirty but works and doesn't get the time to sell rolls.

`root@massa:~# cat crash_restart.sh
#!/bin/bash

while true;
do
  out="$(systemctl status  massad.service | grep 'DiscardReason::Invalid:discarded because a parent was discarded')"
  echo $(date) testcrash=${out}
  if [ "$out"  != '' ]; then
    systemctl restart massad
    sleep 10
  fi
  sleep 15
done
root@massa:~#
`

Hopefully this will go away for next episode, fingers crossed.


`Jan 17 19:08:48 massa massa-node[658424]: #033[2m2022-01-17T18:08:48.000536Z#033[0m #033[32m INFO#033[0m #033[2mmassa_consensus::consensus_worker#033[0m#033[2m:#033[0m Started cycle 336
Jan 17 19:09:45 massa massa-node[658424]: #033[2m2022-01-17T18:09:45.863338Z#033[0m #033[33m WARN#033[0m #033[2mmassa_consensus::block_graph#033[0m#033[2m:#033[0m block graph check_operations error, operation apply to state: there was an inconsistency between containers final PoS cycle not available: 336
Jan 17 19:09:45 massa massa-node[658424]: Discarding ops: Invalid("block graph check_operations error, operation apply to state: there was an inconsistency between containers final PoS cycle not available: 336")
Jan 17 19:09:45 massa massa-node[658424]: #033[2m2022-01-17T18:09:45.863359Z#033[0m #033[32m INFO#033[0m #033[2mmassa_consensus::block_graph#033[0m#033[2m:#033[0m consensus.block_graph.maybe_note_attack_attempt DiscardReason::Invalid:block graph check_operations error, operation apply to state: there was an inconsistency between containers final PoS cycle not available: 336
Jan 17 19:09:45 massa massa-node[658424]: #033[2m2022-01-17T18:09:45.986525Z#033[0m #033[32m INFO#033[0m #033[2mmassa_protocol_worker::protocol_worker#033[0m#033[2m:#033[0m Connected to node 6oocgB6tH5yGPR9TZFRokCEPhVbSWznEyZ45qwJHRpaXd7ND95
Jan 17 19:09:46 massa massa-node[658424]: #033[2m2022-01-17T18:09:46.394835Z#033[0m #033[32m INFO#033[0m #033[2mmassa_consensus::block_graph#033[0m#033[2m:#033[0m consensus.block_graph.maybe_note_attack_attempt DiscardReason::Invalid:discarded because a parent was discarded for the following reason: block graph check_operations error, operation apply to state: there was an inconsistency between containers final PoS cycle not available: 336
Jan 17 19:09:46 massa massa-node[658424]: #033[2m2022-01-17T18:09:46.546868Z#033[0m #033[32m INFO#033[0m #033[2mmassa_protocol_worker::protocol_worker#033[0m#033[2m:#033[0m Connected to node 6vQ5xuohEWiR3K7YjMVnGKMzx5cBPDDm9g3fszNgjM7k1sgWkj
Jan 17 19:09:47 massa massa-node[658424]: #033[2m2022-01-17T18:09:47.341684Z#033[0m #033[32m INFO#033[0m #033[2mmassa_consensus::block_graph#033[0m#033[2m:#033[0m consensus.block_graph.maybe_note_attack_attempt DiscardReason::Invalid:discarded because a parent was discarded for the following reason: block graph check_operations error, operation apply to state: there was an inconsistency between containers final PoS cycle not available: 336
`

**Comment by damip** [comment]
This might actually improve after the upcoming refactoring

**Comment by qdrn** [comment]
Maybe you don't have a downtime but if the bandwidth is severely reduced for a long time this can be the cause. From your graphs it's hard to tell if the bandwidth is reduced because of the issue or if the reduced bandwidth is causing the issue.

**Comment by r1k0** [comment]
Thanks Adrien,
I understand.
What leads me to think my line is not going down is that I spend 14h/d via vpn for work and entertainment and connections never drop, I would notice. Also my router is still synced to the WAN link (200MB down/ 20MB up).
So maybe 20Mb up is way too low,  that could be the case, and this issue showed up 3 days ago, maybe because the network load started to rise only 3 days ago? but then I'll probably never be able to run a massa node from home, which is a bit sad :(

**Comment by gcmartin** [comment]
Hello!

The same error happened to me today.

> [2m2022-01-18T20:19:49.510817Z[0m [33m WARN[0m [2mmassa_consensus::block_graph[0m[2m:[0m block graph check_operations error, operation apply to state: there was an inconsistency between containers final PoS cycle not available: 382
> Discarding ops: Invalid("block graph check_operations error, operation apply to state: there was an inconsistency between containers final PoS cycle not available: 382")
> [2m2022-01-18T20:19:49.510886Z[0m [32m INFO[0m [2mmassa_consensus::block_graph[0m[2m:[0m consensus.block_graph.maybe_note_attack_attempt DiscardReason::Invalid:block graph check_operations error, operation apply to state: there was an inconsistency between containers final PoS cycle not available: 382

Then a lot of similar errors:

> [2m2022-01-18T20:24:51.309966Z[0m [32m INFO[0m [2mmassa_consensus::block_graph[0m[2m:[0m consensus.block_graph.maybe_note_attack_attempt DiscardReason::Invalid:discarded because a parent was discarded for the following reason: discarded because depend on block:2J5NS3BorcdVjD9ofTjvvm5Efc5wFNLHEpgb49wSDYYNtFoPm9 that has discard reason:discarded because depend on block:2XuUDy9i7n9kShCexz5sv2nWtyGFwRobMuwMPFx4ewF3rrxLwg that has discard reason:discarded because depend on block:2geyDXEFDGrzh3YWt4Q3QV9WAQYMY6dQF5mRRTUkYfUPQ6C17g that has discard reason:discarded because depend on block:2MLjsQa8MFJL12rKbzdKAH8m8if9MyJK1QrVnUiCMYkgbfEQYW that has discard reason:discarded because depend on block:2WhWk58UvHf1RXUyx6ZzkfGdwc6Yw3CWXRan3GGQbseJmM9VRy that has discard reason:discarded because depend on block:2GShVe1iap1STNDxPys4aLRGQfjf6EXx9oMbLAzrskCS8ds3Ca that has discard reason:discarded because depend on block:2bFmhHrbEgiLxxVEqBc9qioWrTMQpwVfJm851qw5fhVsheQokV that has discard reason:
>  discarded because depend on block:2CGUpRNR1uPVv2LMEj3e4jjSkWpqTozL7qMGJrnnarXeejfzaj that has discard reason:discarded because depend on block:GhusPi7RoYmPRk61qA5RfXxTa5dA2LvMg8Wqv6yUwzzxSLhQY that has discard reason:discarded because depend on block:3rByD6cmkSrHmJYRpCpGMoGzC4DWVvTpiPUacu65BGvzDBw4t that has discard reason:discarded because depend on block:2o5X3V9GkAbtXPyw83pWDDKYS6QViRF58R3ZSAwEU8cC5MGxPV that has discard reason:discarded because depend on block:2EWp5DY1nJbRPubdEmtrtZXvkvkWDhsUv6sJ645x4j1yqmMtDA that has discard reason:discarded because depend on block:8U25Y8GSetEY5cJ9kx3iAkajiBXj4ubL9qD2qNkhsaqj11MAh that has discard reason:discarded because depend on block:oFUZszaBQtMeLHXBaMvnifS2kKuNG89jvASbf9fy47hF7zA84 that has discard reason:discarded because a parent was discarded for the following reason: discarded because depend on block:2BCt4X7hFFxuEmbbfYJxihMPh8eiNA994USgz2ZupmYiemVw4n that has discard reason:discarded because depend on block:A8PQRtfvoYajg6Z8284nQkZgDnSx
>  TpUaiJc1bFba9jkG7RdTE that has discard reason:discarded because depend on block:2gqqWUGC85ewuh4GgVQKk3iHjFFNkiB3sJGwjct5kQFDHGmWF6 that has discard reason:block graph check_operations error, operation apply to state: there was an inconsistency between containers final PoS cycle not available: 382
> [2m2022-01-18T20:24:51.310063Z[0m [33m WARN[0m [2mmassa_protocol_worker::protocol_worker[0m[2m:[0m node 8jGVipmb3bBad6Qu69d3AJjfPwTpyh4Pe98phya9eVwpWL5UGY sent us critically incorrect header

My node is a Ryzen 7 4800U, with 32 Gb RAM and a 1 Tb M2 SSD on a 1 Gbps Internet connection (100% dedicated to the Massa node).

My Internet connection was running fine at the moment. My last Internet connection issue was around 4am GMT+1 (9 hours ago) when my IP changed. My node restarted at this hour to update it's routable IP address (I have a script monitoring my connection to detect this condition, update the config file and restart the node).

During this crash, I noticed a spike in my netfilter.conntrack_sockets going from 100 to 555. It's the only time during this episode I saw a conntrack_sockets spike.

No change on CPU usage (about 3% usage). CPU usage decreased to 1.5% after the crash.

**Comment by damip** [comment]
> During this crash, I noticed a spike in my netfilter.conntrack_sockets going from 100 to 555. It's the only time during this episode I saw a conntrack_sockets spike.

That's an interesting piece of info. Did the Massa process create those sockets (could happen if there was a disconnect and Massa tried to reconnect to multiple nodes) ? Or something else, for example in the OS, thus maybe causing a problem for the Massa node ?

**Comment by gcmartin** [comment]
Hi Damir!

Unfortunately I don't know who created those sockets.

The server Massa is running on is 100% dedicated to it, with an Ubuntu Server 21.10 distro. I'm only running Massa and a NetData instance one it to monitor its metrics.

With a closer looks, the conntrack_sockets spike was more probably caused by the Massa block graph check_operations error and not the other way around. 

The error got logged at 20:19:49. At 20:19:50, connection were still at 166 and started climbing up.

![massa_conntrack](https://user-images.githubusercontent.com/13121863/150088288-7104a895-4e52-42f3-b344-e499acafe404.png)

At 21:19:45, the server was still starting only 1.5 new processes per seconds (and usually from 1 to 8). At 21:19:50, it created 34 new ones.
I'm only polling metrics each 5 seconds, so unfortunately I don't know what happened between 20:19:46 and 20:19:49.
But here again, the spike may has been caused by the Massa error rather than the other way around.

![massa_processes](https://user-images.githubusercontent.com/13121863/150088450-27cd5a91-3021-479f-84ed-928d37c22e50.png)

I found no clear abnormal activity before the error.

![massa_cpu](https://user-images.githubusercontent.com/13121863/150088493-07b52343-03a1-4066-a69b-6d6b59ce657d.png)

![massa_cpu_2](https://user-images.githubusercontent.com/13121863/150088501-9bbab1ca-e5cc-4e22-8c1f-36ac4be6566f.png)

There has been a little CPU usage spike from an other process just after the error but I suppose it's linked to the new connections processing.
Nothing unusual with Massa (in pink). The spike a few minutes later is when I restarted massa-node.

![massa_files](https://user-images.githubusercontent.com/13121863/150088846-da9240e7-6d92-4626-b181-fe0b8dbb1cff.png)

There also have been some file activity just after the error happened.

**Comment by r1k0** [comment]
just wanted to let you know that there is a lot of people having this exact error message showing up in the discord this ep8. There is now a pattern, it cannot just be due to internet lines that suddenly decided to drop for the start of ep8, please re open and have a look further, there is something to improve here. Thanks
