### ISSUE TITLE
Prevent foreign logs in the first place, not post-filtering

### ISSUE THREAD

**Issue by damip** [massalabs/massa#2163]
https://github.com/massalabs/massa/pull/2095

**Comment by yvan-sraka** [comment]
So the hack was made here: https://github.com/massalabs/massa/blob/main/massa-node/src/main.rs#L299-L301 (it uses `mass_trace!` prefix to filter out our logs)!

And after searching a lot in https://tracing.rs/ documentation, I still not find out a simple way to do it ...

The main principle is rather we disable log at compile time, but it requires us to compile all of our dependencies against a different version of tokio tracing, the same way it was statically enabled here https://github.com/massalabs/massa/issues/2111

Or to filter at runtime log, using the hack previously linked ...

**Comment by yvan-sraka** [comment]
So, the only way I see to tackle this (with my understanding of [cargo feature](https://doc.rust-lang.org/cargo/reference/features.html) resolvers) is still to compile all of our dependencies against a different version of tokio built with [`STATIC_MAX_LEVEL`](https://docs.rs/tracing/latest/tracing/level_filters/constant.STATIC_MAX_LEVEL.html) defined to our wanted value. The best trick I have in mind right now is playing with [overriding of dependencies](https://doc.rust-lang.org/cargo/reference/overriding-dependencies.html), which could be done in maybe a less dirty way if we're allowed to [Nixify the project](https://nixos.org/manual/nixpkgs/stable/#rust) a bit!
