### ISSUE TITLE
Add the `RELEASE_VERSION` in the artifacts names

### ISSUE THREAD

**Issue by yvan-sraka** [massalabs/massa#2170]
I think at some point you wanted to add the `RELEASE_VERSION` in the artifacts names @yvan-sraka. I'm not familiar with Github actions and struggled a bit to do that so if you can do it feel free to do it.

_Originally posted by @qdrn in https://github.com/massalabs/massa/issues/2114#issuecomment-1014604868_

**Comment by qdrn** [comment]
I believe something like that should work:
```yml
if [[ "${{ matrix.os }}" == "windows-latest" ]]
then
  7z a massa_${GITHUB_REF/refs\/tags\//}_${{ matrix.name }} massa
else
  tar czvf massa_${GITHUB_REF/refs\/tags\//}_${{ matrix.name }} massa
fi
```
