### ISSUE TITLE
 Shared "storage" library to avoid block copies

### ISSUE THREAD

**Issue by gterzian** [massalabs/massa#2178]
Part of https://github.com/massalabs/massa/issues/2162

Can we start with getting an overview of current "block copies"?

Also, how much do we need to copy eventually anyway, for example due to outgoing network messages?

**Comment by damip** [comment]
Ideally we don't want them anymore at all... If Storage stores objects like blocks or operations to make them available to the whole program, as well as their serialized versions, we won't even have to re-serialize things before sending them

**Comment by gterzian** [comment]
So I propose the following:

1. Sending `_Id` of objects in events/commands. The actual object can then be retrieved from a shared object(see 2).
2. Sharing a structure like the below:

```rust
pub struct Storage {
    blocks: Arc<RwLock<Map<BlockId, Block>>,
    operations: ...
    endorsements: ...
}

/// Shared as 
storage: Arc<RwLock<Storage>>
```

Note that if there is a lot of contention on certain internal maps, we can go further and have one lock per object, like:

```rust
pub struct Storage {
    blocks: Arc<RwLock<Map<BlockId, Arc<RwLock<Block>>>>,
    operations: ...
    endorsements: ...
}
```

This is fine if we use a library like [`parking_lot`](https://docs.rs/parking_lot/0.11.2/parking_lot/), which are designed for a large amount of locks(see https://webkit.org/blog/6161/locking-in-webkit/).

I'd like to give this a try, please let me know what you think.

cc @massalabs/core-team

**Comment by adrien-zinger** [comment]
> So I propose the following:
> 
>     1. Sending `_Id` of objects in events/commands. The actual object can then be retrieved from a shared object(see 2). Another option, as @damip mentioned, is to send the actual object as a "move" of data from one component to another, for example from network to consensus.
> 
>     2. Sharing a structure like the below:
> 
> 
> ```rust
> pub struct Storage {
>     blocks: Arc<RwLock<Map<BlockId, Block>>,
>     operations: ...
>     endorsements: ...
> }
> ```
> 
> Note that if there is a lot of contention on certain internal maps, but not on individual objects contained within those, we can go further and have one lock per object, like:
> 
> ```rust
> pub struct Storage {
>     blocks: Arc<RwLock<Map<BlockId, Arc<RwLock<Block>>>>,
>     operations: ...
>     endorsements: ...
> }
> ```
> 
> This is fine if we use a library like [`parking_lot`](https://docs.rs/parking_lot/0.11.2/parking_lot/), which are designed for a large amount of locks(see https://webkit.org/blog/6161/locking-in-webkit/).
> 
> I'd like to give this a try, please let me know what you think.
> 
> cc @massalabs/core-team

I think I'm going to be a big fan of parking_lot. That said, the second version with a double lock is great too.

**Comment by AureliaDolo** [comment]
Should we keep SCOutput events to that storage ?

**Comment by gterzian** [comment]
> Should we keep SCOutput events to that storage ?

We could. Is it large and used by different components?

**Comment by AureliaDolo** [comment]
> > Should we keep SCOutput events to that storage ?
> 
> We could. Is it large and used by different components?

It may be arbitrarily large (only limited by the producer's gas). It's produced during the execution and can be queried by the api

**Comment by gterzian** [comment]
@massalabs/core-team I've broken-up the work into several PRs, and more can be opened for other components like `execution` and `pool`, which I think can be tackled separately...

The "main" branch would be `shared_storage`...

**Comment by damip** [comment]
Here is extra food for thought: https://github.com/massalabs/massa/issues/2344

But for now let's stay like you did @gterzian  : container-wide arc rwlock + per-element arc rwlock

**Comment by gterzian** [comment]
As a side-note, I propose focusing on using blocks within storage for now, and leaving other objects(operations and so on), for later? In that case I'll remove those from the linked to PR.

**Comment by gterzian** [comment]
Also, is there someone else interested in looking at using shared storage in other components than those for which a PR has already been opened(for example API)? If so, you could simply open a PR off of the branch at https://github.com/massalabs/massa/pull/2233

**Comment by AurelienFT** [comment]
I wanted to help you by implementing the storage on the API but there is something that I don't understand.

Sometimes you have the `ActiveBlock` and you retrieve the stored block but you use a field that is already on the `ActiveBlock`. Examples : 
- https://github.com/massalabs/massa/blob/12461d5f0370c6338aaccc82452209ea505ac0ba/massa-graph/src/block_graph.rs#L208
- https://github.com/massalabs/massa/blob/12461d5f0370c6338aaccc82452209ea505ac0ba/massa-graph/src/block_graph.rs#L1089

Maybe it's just a WIP or there is a specific reason. If you can give me some insight. Thank you !

**Comment by gterzian** [comment]
@AurelienFT If you mean the `Slot`, yes that is right, I think have actually addressed this in https://github.com/massalabs/massa/pull/2233/commits/cf8c591dce01ba32229e1a919bbc4c8c4c9caa4c
