### ISSUE TITLE
Reduce Async usage

### ISSUE THREAD

**Issue by gterzian** [massalabs/massa#2179]
Part of https://github.com/massalabs/massa/issues/2162

Good candidate for this is to only use `async` in relation to networking, or other components where lots of sub-tasks are spawned, and to keep the main components running on threads.

**Comment by damip** [comment]
Sounds like it makes sense :) let's see if there is any devil in the details

**Comment by gterzian** [comment]
@damip See my comment above, by the way I've addressed it for now via https://github.com/massalabs/massa/pull/2233/commits/f89df90e5a23025d6d7ca894969a3a6e4265e2db

**Comment by damip** [comment]
> @damip See my comment above, by the way I've addressed it for now via [f89df90](https://github.com/massalabs/massa/commit/f89df90e5a23025d6d7ca894969a3a6e4265e2db)

Very good !
I'm just a bit scared by the "unwrap()" like here for example: https://github.com/massalabs/massa/commit/f89df90e5a23025d6d7ca894969a3a6e4265e2db#diff-7fd127a5266f7201f782ea024113f453dcfe21a8f157848affd4781e16c6e8fbR1115  given that "storage" should have internal cleanup systems, we should always be robust to something appearing/changing/disappearing from storage

**Comment by gterzian** [comment]
> we should always be robust to something appearing/changing/disappearing from storage

Yes, the `unwrap` is there mostly because it's a work in progress.

**Comment by damip** [comment]
remaining async usages:
* network: can be optimized but makes sense there
* protocol: could maybe be removes
* consensus: should be removed, but after the ledger unification that will massively reduce the complexity of the consensus module
* pool: this module might go away with further storage unification
* api: to be reviewed
* bootstrap: to be reviewed

**Comment by gterzian** [comment]
> pool: this module might go away with further storage unification

Just for clarification, I don't think `pool` will go away, just like `consensus` didn't go away once we switched to using shared storage for blocks. 

The reason is that all the logic currently in `operations_pool` should not be transferred to storage, because we want the logic to remain isolated in a module like `pool`, where the shared storage remains only about storing/retrieving of objects. 

But pool does not need async, indeed.

**Comment by gterzian** [comment]
I think `protocol` is probably a good first candidate to remove async.

Also note that at the level of `network`, we could run the network worker on a thread, while keeping the individual node workers async(since that is where the "real" networking happens). 

Note that having both protocol and the top-level network worker run on threads would open up some opportunities to work with a condvar and shared queue, which could enable to us further address some of the issues encountered at https://github.com/massalabs/massa/issues/2522 (for example via a condvar based pull workflow, replacing the currently push-based workflow where the channels eventually fill-up).

**Comment by AurelienFT** [comment]
Closing as Async isn't here in most of the modules and this issue is too generic.
