### ISSUE TITLE
Reduce MPSC usage in favor of RwLocks to allow multiple simultaneous reads

### ISSUE THREAD

**Issue by gterzian** [massalabs/massa#2180]
Part of https://github.com/massalabs/massa/issues/2162

A first question here is how much simultaneous reads we can actually do. I note most methods on objects are `&mut`, which would imply write operations.

This may be most useful in relation to a shared "storage" object, which is done at https://github.com/massalabs/massa/issues/2178

**Comment by damip** [comment]
Typically, the API is read-only on blocks, PoS is read-only as well, block propagation is read-only, execution is read-only, information gathering before block emission is readonly etc... 

There are many parts of the code that would like to read blocks simultaneously

**Comment by yvan-sraka** [comment]
I would like to give a try to https://github.com/zesterer/flume :)

**Comment by damip** [comment]
> I would like to give a try to https://github.com/zesterer/flume :)

for places where we need channels, we can use crossbeam, flume or any other crate.
This issue deals with doing away with async where it's not needed, dropping the "channel" model where not needed, and embracing threads and RwLocks where it makes sense.
