### ISSUE TITLE
Next release check list (6.6 or 7.0)

### ISSUE THREAD

**Issue by AureliaDolo** [massalabs/massa#2195]
* [x] #2224
* [x]  #2126 
* [x] add `rustup default nightly` on the update tutorial.
* [ ] increase max block size
* [x] if #2189 is merged #2235

**Comment by damip** [comment]
everything that is targeted towards V7 should be done this monday

**Comment by AureliaDolo** [comment]
@Noxhaa I edited the update page to include `rustup default nightly{ It is already on the install page. Am I missing a place to edit ?

**Comment by damip** [comment]
will leave block size as is for now
