### ISSUE TITLE
Use thread count from the static config instead of passing it as arg

### ISSUE THREAD

**Issue by AureliaDolo** [massalabs/massa#2197]
Thread count is now in the static config, shouldn't it be available here, without the need to duplicate it here ? Or am I missing on something @yvan-sraka

_Originally posted by @AureliaDolo in https://github.com/massalabs/massa/pull/2194#discussion_r787508042_

I think these function could be updated ? (searching for thread_count: u8) (I could be worth having a look at other commonly passed as args config parameters)
* [ ] pub fn get_thread(&self, thread_count: u8) -> u8
* [ ]  pub fn get_next_slot(&self, thread_count: u8) -> Result<Slot, ModelsError>
* [ ] pub fn get_block_slot_timestamp(
    thread_count: u8,
    t0: MassaTime,
    genesis_timestamp: MassaTime,
    slot: Slot,
) -> Result<MassaTime, ModelsError> // should take only slot as a param
* [ ]  pub fn get_latest_block_slot_at_timestamp(
    thread_count: u8,
    t0: MassaTime,
    genesis_timestamp: MassaTime,
    timestamp: MassaTime,
) -> Result<Option<Slot>, ModelsError>
* [ ] pub fn get_current_latest_block_slot(
    thread_count: u8,
    t0: MassaTime,
    genesis_timestamp: MassaTime,
    clock_compensation: i64,
) -> Result<Option<Slot>, ModelsError>
* [ ] pub fn time_range_to_slot_range(
    thread_count: u8,
    t0: MassaTime,
    genesis_timestamp: MassaTime,
    start_time: Option<MassaTime>,
    end_time: Option<MassaTime>,
) -> Result<(Option<Slot>, Option<Slot>), ModelsError>
* [ ] pub fn new(pool_settings: &'static PoolSettings, thread_count: u8) -> EndorsementPool
* [ ] fn new(op: Operation, thread_count: u8) -> Result<Self, PoolError> 
* [ ] pub fn new(
        pool_settings: &'static PoolSettings,
        thread_count: u8,
        operation_validity_periods: u64,
    ) -> OperationPool 
* [ ] pub async fn start_pool_controller(
    pool_settings: &'static PoolSettings,
    thread_count: u8,
    operation_validity_periods: u64,
    protocol_command_sender: ProtocolCommandSender,
    protocol_pool_event_receiver: ProtocolPoolEventReceiver,
) -> Result<(PoolCommandSender, PoolManager), PoolError>
* [ ] pub fn new(
        pool_settings: &'static PoolSettings,
        thread_count: u8,
        operation_validity_periods: u64,
        protocol_command_sender: ProtocolCommandSender,
        protocol_pool_event_receiver: ProtocolPoolEventReceiver,
        controller_command_rx: mpsc::Receiver<PoolCommand>,
        controller_manager_rx: mpsc::Receiver<PoolManagementCommand>,
    ) -> Result<PoolWorker, PoolError>

**Comment by yvan-sraka** [comment]
That's a good occasion to use https://crates.io/crates/cornetto

**Comment by AureliaDolo** [comment]
I guess we would need to make the config (or at least some part of it (like the compact config stuff)) available from really everywhere

**Comment by adrien-zinger** [comment]
There was a work for the thread count here => #2221 it shows up that `thread_count` isn't really a constant but a value that need to be used as a dependency to inject into the different actors in the project.
