### ISSUE TITLE
Allow smart contracts to filter or refuse funds

### ISSUE THREAD

**Issue by damip** [massalabs/massa#2202]
Currently there is no way for an SC to refuse / filter receiving funds.

Z80: "In Ethereum a smart contract can define a receive/fallback function to be called on receipt of coins which can revert to refuse the transfer, would be good to have similar functionality here."

**Comment by damip** [comment]
let's study this all together. All comments are welcome

**Comment by AureliaDolo** [comment]
I don't see the difference with calling a transfer coin function. What's the difference between refusing the coins and sending them back in the same execution? Maybe it would be more a helper function to define in the massa standard library ? @z80dev

**Comment by damip** [comment]
@AureliaDolo example: when using a Transaction operation, we won't trigger any smart contract execution, just transfer coins. So no way for the target to refuse the coins

**Comment by AureliaDolo** [comment]
So in that context smart contract means an address that is not associated with a private key ?

And are we talking sequential or parallel coins ? Or coins after the unification?

Anyway, from what I understand, at some points smart contracts will be able to listen for some events so that would be taken care of at that point

**Comment by damip** [comment]
> So in that context smart contract means an address that is not associated with a private key ?
> 
> And are we talking sequential or parallel coins ? Or coins after the unification?
> 
> Anyway, from what I understand, at some points smart contracts will be able to listen for some events so that would be taken care of at that point

we are talking about all coins and all types of addresses.

Maybe events could help, but then who pays the fees ?

**Comment by damip** [comment]
> > Maybe events could help, but then who pays the fees ?
> 
> The sender ? They took the risk sending coins that may be refused

that's easier said than done :) 

If you have a precise idea on how it would work, I'm open to a small spec

**Comment by AurelienFT** [comment]
New version more precise : https://github.com/massalabs/massa/issues/3247
