### ISSUE TITLE
Improve computation of Best Parents with the topological sort

### ISSUE THREAD

**Issue by sebastien-forestier** [massalabs/massa#2206]
In the Python code we used a topological sort to find the best parents in (cliquesize) time, [here](https://gitlab.com/blockclique/blockclique/-/blob/master/blockclique_pos/block_graph.py#L490).

In the current Rust code there is something in (T*cliquesize^2) time, [here](https://github.com/massalabs/massa/blob/main/massa-consensus/src/block_graph.rs#L3355).

We should probably do the simplest way with a topological sort.

The topological sort is build incrementally with no cost ([here](https://gitlab.com/blockclique/blockclique/-/blob/master/blockclique_pos/block_graph.py#L258)).

Final and stale blocks are removed from the structure ([here](https://gitlab.com/blockclique/blockclique/-/blob/master/blockclique_pos/block_graph.py#L578)), which is linear in the worst case but it's fast because those blocks should be around the begining of the topological sort.

**Comment by damip** [comment]
Even simpler and more efficient:

```rust
            self.best_parents = self.latest_final_blocks_periods.clone();
            for block_h in blockclique.block_ids.iter() {
                let b_slot = BlockGraph::get_full_active_block(&self.block_statuses, *block_h)
                    .ok_or_else(|| ConsensusError::ContainerInconsistency(format!("inconsistency inside block statuses updating best parents while adding {} - missing {}", add_block_id, block_h)))?
                    .block.header.content.slot;
                if b_slot.period > self.best_parents[b_slot.thread as usize].1 {
                    self.best_parents[b_slot.thread as usize] = (*block_h, b_slot.period);
                }
            }
```

**Comment by sebastien-forestier** [comment]
I like it
