### ISSUE TITLE
Operations Exceeding Block Size are Silently Dropped

### ISSUE THREAD

**Issue by z80dev** [massalabs/massa#2212]
**Describe the bug**
When I use `send_smart_contract` in massa-client to send a smart contract transaction to be executed, massa-client reports `Sent Operation <id>`.

When I look in the node logs to look for the execution of my smart contract, nothing appears, not even an error message indicating my transaction exceeded a size. 

**To Reproduce**
I have included an example of a wasm file that is too big. I had to wrap it in a zip because github doesn't allow uploads of wasm files.

1. Launch massa-client
2. Have an account with coins
3. Use the command `send_smart_contract <addr> ./toobig.wasm 100000000 .01 0 1`

**Expected behavior**
Node logs containing the output of smart contract execution

**Additional context**
This happened under two scenarios

* Instantiating two contracts on-chain in one operation (i.e. two calls to `include_base64` and `create_sc`, each)
* Instantiating one contract with many many print statements

In the second case, I only had so many print statements because I was trying to debug some behavior. Removing the print statements solved the issue. However, I worry that a much larger and more complex contract defining 20+ functions might hit this size limit as well. This can be worked around by splitting functionality into multiple contracts, but this introduces complexity to the smart contract code in order to work around the platform, instead of improving the platform in order to eliminate the need for this complexity.

[toobig.wasm.zip](https://github.com/massalabs/massa/files/7935028/toobig.wasm.zip)

**Comment by AureliaDolo** [comment]
From what I see in the [whitepaper](https://arxiv.org/pdf/1803.09029.pdf) maximum block size should to be around a few Mb, whereas the current default is around 100kb. I assume this could be solved at least partially increasing max_block_size in the settings @damip

**Comment by damip** [comment]
We limited block size to limit max throughput and avoid flooding. We might increase it a bit for the next testnet.

We can already:
* launch a labnet with bigger blocks
* add a warning in the client when the operation to send is larger than say max_block_size/2

That being said, smart contracts shouldn't be so large in the first place. We should open a discussion on reducing their size

**Comment by AureliaDolo** [comment]
> add a warning in the client when the operation to send is larger than say max_block_size/2

see #2217

**Comment by AureliaDolo** [comment]
> launch a labnet with bigger blocks

@damip should this new settings be also in the testnet ?
(I add that to the checklist #2195

**Comment by qdrn** [comment]
> @damip should this new settings be also in the testnet ? (I add that to the checklist #2195 )

No. We don't want to increase the block size too much as the testnet can only handle a given number of tx/s. If we increase it too much someone might break the testnet by flooding it.

On the long term we should focus on how to reduce the size of SCs. Or find a workaround if that's not possible.

**Comment by qdrn** [comment]
> > No. We don't want to increase the block size too much as the testnet can only handle a given number of tx/s. If we increase it too much someone might break the testnet by flooding it.
> 
> Do you mean that the block will never be the size used to compute the max tx per sec until mainnet ?

We will slowly increase block size over time when we improve the performances. Right now it's a bit risky as we know that it's still unstable with more than 1k tx/s.

**Comment by AureliaDolo** [comment]
> We will slowly increase block size over time when we improve the performances. Right now it's a bit risky as we know that it's still unstable with more than 1k tx/s.

Do you have a schedule ? Or some some criteria to know when to increase it ?

**Comment by qdrn** [comment]
Not really. As I said, it will depends on performance improvements that we can make. We'll see how it goes after the big refacto. Of course it also depends on the quality of the nodes running on the testnet.
