### ISSUE TITLE
Improve performance of block creation when pool is filled with operations that cannot be executed

### ISSUE THREAD

**Issue by sebastien-forestier** [massalabs/massa#2215]
At a throughput of 700 tx/s processed in blocks, the average propagation time of headers+blocks is 500ms.
When those transactions cannot be included in a block for instance because they have not enough balance, the propagation time of blocks becomes 1500ms on average.

![proptime](https://user-images.githubusercontent.com/11048486/151036764-04d48c8d-e89a-4d5f-bf6a-ac8a273dd503.png)

This is due to the time the block producer takes to create the block.

See for instance this logs:
```
2022-01-24T06:57:03.208199 INFO massa_consensus::consensus_worker  Staked block 2h9BaANNcA5wRgKitqa3h4qACZcwkvxuo5JieSK6wRRu1XbbY5 with address 2jswkBQt9ssoo9ynzhx32dAQ84kv1nbC2XtY2SVW655KVmMtXd, at cycle 611, period 78288, thread 29
```
The slot was at time  January 24, 2022 6:57:02.500 AM but the block is created after 708 ms in this case.

**Comment by AureliaDolo** [comment]
As a quick fix you can reduce max_operations_fill_attempts and increase operation_batch_size

**Comment by sebastien-forestier** [comment]
Correct me if I'm wrong but I think with the current settings, we have up to 100k operations in the pool for a given thread, and at each attempt to get a batch of 100 operations (6 attempts here), we check if each of the 100k operations meet some criteria (e.g. not being included in the "exclude" Set that can have size ~500 here): https://github.com/massalabs/massa/blob/testnet/massa-pool/src/operation_pool.rs#L298.

A quick fix could be to stop checking the 100k operations if we already found 100 that fit.

**Comment by damip** [comment]
> Correct me if I'm wrong but I think with the current settings, we have up to 100k operations in the pool for a given thread, and at each attempt to get a batch of 100 operations (6 attempts here), we check if each of the 100k operations meet some criteria (e.g. not being included in the "exclude" Set that can have size ~500 here): https://github.com/massalabs/massa/blob/testnet/massa-pool/src/operation_pool.rs#L298.
> 
> A quick fix could be to stop checking the 100k operations if we already found 100 that fit.

The config system is quite confusing in the current version I agree, that's why you looked at the wrong place for the config value. If you check massa_node/base_config/config.toml:

```
    # max number of batches of pool operations to scan when generating a block
    max_operations_fill_attempts = 102400
    # size of a pool operation batch for block creation
    operation_batch_size = 1024
```

**Comment by sebastien-forestier** [comment]
Ok, so in practice when the pool is full of 100k operations, there will be ~100 attempts.
At each attempt, `get_operation_batch` will start from the begin of the sorted operations, and will go further at each attempt as the 1000 operations of the previous batch are now in the `exclude` set, and this until the end of the 100k operations.
The first operations will thus be checked against `exclude` about 100 times, while the last operations only 1 time, so on average 50 times.
That's 50*100k = 5 million checks with the current parameters, instead of the 100k that are really needed.

The fix can be to not use `exclude` for operations of previous attempts, and use a cursor of interest instead: if in the previous attempt we checked up to an interest of X, in the next attempt we start `ops_by_thread_and_interest[block_slot.thread as usize].iter()` from interest X.
This X could be cached in the Pool, or a new optional arg for `get_operation_batch`.

Another thing we should do is to remove from the pool all the operations that were not taken in the block, to prevent pool spam.
This could be a new arg `remove_ops_from_pool` for `get_operation_batch`.

With this I suggest these parameters:
```
    # max number of batches of pool operations to scan when generating a block
    max_operations_fill_attempts = 10
    # size of a pool operation batch for block creation
    operation_batch_size = 1024
```

**Comment by damip** [comment]
> Ok, so in practice when the pool is full of 100k operations, there will be ~100 attempts. At each attempt, `get_operation_batch` will start from the begin of the sorted operations, and will go further at each attempt as the 1000 operations of the previous batch are now in the `exclude` set, and this until the end of the 100k operations. The first operations will thus be checked against `exclude` about 100 times, while the last operations only 1 time, so on average 50 times. That's 50*100k = 5 million checks with the current parameters, instead of the 100k that are really needed.


true

> The fix can be to not use `exclude` for operations of previous attempts, and use a cursor of interest instead: if in the previous attempt we checked up to an interest of X, in the next attempt we start `ops_by_thread_and_interest[block_slot.thread as usize].iter()` from interest X. This X could be cached in the Pool, or a new optional arg for `get_operation_batch`.

For performance, the ops are stored sorted in the pool within a BTreeMap. So we cannot keep the iterator between batches because new ops are added/removed at the same time (the pool worker runs in parallel) and the BTree might get rebalanced in-between.

We could however keep the hash of the last loaded operation, and relocate the iterator at every batch begin in `O(log(pool_size))` time, which is better than the `O(pool_size)` we have currently for sure. The downside is that we will by definition miss all the "better" operations that arrived while we were pulling batches.

> Another thing we should do is to remove from the pool all the operations that were not taken in the block, to prevent pool spam. This could be a new arg `remove_ops_from_pool` for `get_operation_batch`.

Yes and no. Depends on the reason of the discard... we need to think more about that because it could be turned into an attack. I think we would be better off with a "robot" sorting the pool all the time in the background by querying the latest balance info.

> 
> With this I suggest these parameters:
> 
> ```
>     # max number of batches of pool operations to scan when generating a block
>     max_operations_fill_attempts = 10
>     # size of a pool operation batch for block creation
>     operation_batch_size = 1024
> ```

WIth those parameters, even the current method should be very lightweight !

**Comment by sebastien-forestier** [comment]
> We could however keep the hash of the last loaded operation, and relocate the iterator at every batch begin in `O(log(pool_size))` time

Yes keep the hash or the last interest as I described.

I think we should discard if block_state_try_apply fails, which in the future will only be when not enough coins are available or if we implement https://github.com/massalabs/massa/discussions/2267 and the address has not enough coins/storage.

Then we can remove the parameter `max_operations_fill_attempts`, and check the full pool.

**Comment by damip** [comment]
> > We could however keep the hash of the last loaded operation, and relocate the iterator at every batch begin in `O(log(pool_size))` time
> 
> Yes keep the hash or the last interest as I described.

Actually, sorry what I said makes no sense because it is sorted by ROI, not by hash ! So the "cursor" should be the ROI if we go that way.

> 
> I think we should discard if block_state_try_apply fails, which in the future will only be when not enough coins are available or if we implement #2267 and the address has not enough coins/storage.
> 
> Then we can remove the parameter `max_operations_fill_attempts`, and check the full pool.

Some reasons not to do that for now:

* this work will be discarded quickly because we will refactor operation execution and block creation: block creation will only look at fees and operations will be taken care of by the Execution/VM module.
* if in an operation, A sends coins to B (that initially has 0 coins) then in a second operation with better ROI it sends them from B to C, then we will lose the second operation for no good reason if we implement this 
* the pool sorting and pruning itself should already take this kind of things into account to prioritize based on total spending vs balance

**Comment by qdrn** [comment]
> We could however keep the hash of the last loaded operation, and relocate the iterator at every batch begin in `O(log(pool_size))` time, which is better than the `O(pool_size)` we have currently for sure. The downside is that we will by definition miss all the "better" operations that arrived while we were pulling batches.

If it greatly improves performance/simplicity I think it's a small downside as it will rarely happens in practice (AFAIK).
 
> Yes and no. Depends on the reason of the discard... we need to think more about that because it could be turned into an attack. I think we would be better off with a "robot" sorting the pool all the time in the background by querying the latest balance info.

Probably the best thing to do. That's what you had in mind already for the refactoring, right ?

**Comment by damip** [comment]
> > We could however keep the hash of the last loaded operation, and relocate the iterator at every batch begin in `O(log(pool_size))` time, which is better than the `O(pool_size)` we have currently for sure. The downside is that we will by definition miss all the "better" operations that arrived while we were pulling batches.
> 
> If it greatly improves performance/simplicity I think it's a small downside as it will rarely happens in practice (AFAIK).

It could help for sure. Let's open an issue

> 
> > Yes and no. Depends on the reason of the discard... we need to think more about that because it could be turned into an attack. I think we would be better off with a "robot" sorting the pool all the time in the background by querying the latest balance info.
> 
> Probably the best thing to do. That's what you had in mind already for the refactoring, right ?

yes, still needs to be specified tho

**Comment by adrien-zinger** [comment]
I just looked at the `get_operation_batch` method, is the compiler smart enough to stop filtering when `batch_size` reached. Because that's not literally written. Starting from this observation,I didn't check the correctness of the following lines, but if the filter doesn't stop by itself we can force it like:

```rust
    /// Get max_count operation for thread block_slot.thread
    /// if vec is not full that means that there is no more interesting transactions left
    pub fn get_operation_batch(
        &mut self,
        block_slot: Slot,
        exclude: Set<OperationId>,
        batch_size: usize,
        max_size: u64,
    ) -> Result<Vec<(OperationId, Operation, u64)>, PoolError> {
        let mut i = 0;
        self.ops_by_thread_and_interest[block_slot.thread as usize]
            .iter()
            .take_while(|| i <= batch_size) /* stop filtering when return value == batch_size */
            .filter_map(|(_rentability, id)| {
                if exclude.contains(id) {
                    return None;
                }
                if let Some(w_op) = self.ops.get(id) {
                    if !w_op.op.get_validity_range(self.operation_validity_periods)
                        .contains(&block_slot.period) || w_op.byte_count > max_size {
                            massa_trace!("pool get_operation_batch not added to batch w_op.op.get_validity_range incorrect not added", {
                                "range": w_op.op.get_validity_range(self.operation_validity_periods),
                                "block_slot.period": block_slot.period
                            });
                        return None;
                    }
                    i += 1;
                    Some(Ok((*id, w_op.op.clone(), w_op.byte_count)))
                } else {
                    i += 1; /* ¯\_(°ペ)_/¯ here also ? */
                    Some(Err(PoolError::ContainerInconsistency(
                        format!("operation pool get_ops inconsistency: op_id={} is in ops_by_thread_and_interest but not in ops", id)
                    )))
                }
            })
            .collect()
    }
```

**Comment by damip** [comment]
> I just looked at the `get_operation_batch` method, is the compiler smart enough to stop filtering when `batch_size` reached. Because that's not literally written. Starting from this observation,I didn't check the correctness of the following lines, but if the filter doesn't stop by itself we can force it like:
> 
> ```rust
>     /// Get max_count operation for thread block_slot.thread
>     /// if vec is not full that means that there is no more interesting transactions left
>     pub fn get_operation_batch(
>         &mut self,
>         block_slot: Slot,
>         exclude: Set<OperationId>,
>         batch_size: usize,
>         max_size: u64,
>     ) -> Result<Vec<(OperationId, Operation, u64)>, PoolError> {
>         let mut i = 0;
>         self.ops_by_thread_and_interest[block_slot.thread as usize]
>             .iter()
>             .take_while(|_| i <= batch_size) /* stop filtering when return value == batch_size */
>             .filter_map(|(_rentability, id)| {
>                 if exclude.contains(id) {
>                     return None;
>                 }
>                 if let Some(w_op) = self.ops.get(id) {
>                     if !w_op.op.get_validity_range(self.operation_validity_periods)
>                         .contains(&block_slot.period) || w_op.byte_count > max_size {
>                             massa_trace!("pool get_operation_batch not added to batch w_op.op.get_validity_range incorrect not added", {
>                                 "range": w_op.op.get_validity_range(self.operation_validity_periods),
>                                 "block_slot.period": block_slot.period
>                             });
>                         return None;
>                     }
>                     i += 1;
>                     Some(Ok((*id, w_op.op.clone(), w_op.byte_count)))
>                 } else {
>                     i += 1; /* ¯\_(°ペ)_/¯ here also ? */
>                     Some(Err(PoolError::ContainerInconsistency(
>                         format!("operation pool get_ops inconsistency: op_id={} is in ops_by_thread_and_interest but not in ops", id)
>                     )))
>                 }
>             })
>             .collect()
>     }
> ```

Here is the answer :
https://play.rust-lang.org/?version=stable&mode=debug&edition=2021&gist=bea676080a3ce18745cdc44da7404ffa

it's not the compiler but the iterators: they are lazy => https://doc.rust-lang.org/book/ch13-02-iterators.html
```
In Rust, iterators are lazy, meaning they have no effect until you call methods that consume the iterator to use it up. 
```

**Comment by qdrn** [comment]
Still relevant. Do not close bot!

**Comment by damip** [comment]
Testnet14 should improve performance on this point. Let's reopen if the problem reappears.
