### ISSUE TITLE
Return Callstack as Comma-Separated List

### ISSUE THREAD

**Issue by z80dev** [massalabs/massa#2230]
**Describe the bug**
Currently, the return value of `getCallStack()` in a smart contract returns a JSON string. This JSON string is decoded into a `string[]` as it simply wraps a list of strings. 

This requires JSON parsing on the smart contract side each time we want to examine the call stack which happens pretty regularly. While we could implement this JSON parsing at the library level (i.e. in `massa-sc-std`'s assemblyscript code, parse the JSON into a `string[]` and return that to the smart contract caller already parsed) but this would require introducing a dependency into `massa-sc-std`. This would be its first dependency. 

While this may be the right decision in the long-term, as its possible that there are other low-level functions we want to parse before returning to the smart contract caller, currently we do not have other use-cases for this. Rather than introducing a dependency, it may be easier to return a comma-separated-list from Rust and then parse it in our library by splitting on commas which does not require an additional dependency. 

This gives us the benefit we want (smart contract authors don't have to decode JSON each time they want to examine the call stack) without the cost we are looking to avoid (introducing a the first dependency to `massa-sc-std`). The trade-off we are making instead is that *the return value of this function may be inconsistent with the convention followed by the other functions*. I would like some input from someone with a better idea of this from having worked on a larger scope of the codebase

**To Reproduce**
Current behavior

 (in smart contract)

```ts
import { JSON } from "json-as";

export function transfer(_args: string): string {
    const args = JSON.parse<TransferArgs>(_args);
    const addresses = JSON.parse<string[]>(Context.get_call_stack());
    const sender = addresses[0];
    return _transfer(sender, args.to, args.amount).toString();
}

export function allow(_args: string): string {
    const args = JSON.parse<AllowArgs>(_args);
    const addresses = JSON.parse<string[]>(Context.get_call_stack());
    const owner = addresses[0];
    _setAllowance(owner, args.spender, args.amount);
    return args.amount.toString();
}

```

**Expected behavior**

```ts
export function transfer(_args: string): string {
    const args = JSON.parse<TransferArgs>(_args);
    const addresses = Context.get_call_stack();
    const sender = addresses[0];
    return _transfer(sender, args.to, args.amount).toString();
}

export function allow(_args: string): string {
    const args = JSON.parse<AllowArgs>(_args);
    const addresses = Context.get_call_stack();
    const owner = addresses[0];
    _setAllowance(owner, args.spender, args.amount);
    return args.amount.toString();
}
```

**Additional context**
I know this seems like a minor issue, and in the short-term it definitely is. However, these *small* inconveniences can add up to a big one in aggregate. Improvements in development ergonomics go a long way. Changes like these allow developers to focus more time on the real purpose of their contract and spend less time figuring out how to be effective.

**Comment by damip** [comment]
This didn't make it into V7, since it's breaking, we'll schedule it for V8.
Of course we can test it on the labnet before :)

**Comment by damip** [comment]
@yvan-sraka  let's do this

**Comment by yvan-sraka** [comment]
Did we try to tackle this issue together with https://github.com/massalabs/massa-sc-template/issues/5 (killing two birds with one stone), what do you think about it @z80dev?

My other idea on what could be improved is to embed into `massa-sc-reuntime` redundant WASM code rather than writing it on top of each SC, it's a trade between the size of generated byte code rather than the portability of it, and could be seen as a post-compilation step, but I'm not sure yet about the disability of it @adrien-zinger? (my concern that this should be tackle with versioning in mind)
