### ISSUE TITLE
Error when starting node

### ISSUE THREAD

**Issue by mapleart** [massalabs/massa#2232]
Node version : TEST.6.5
thread 'main' panicked at 'This episode has come to an end, please get the latest testnet node version to continue', massa-node/src/main.rs:53:13

**Comment by AureliaDolo** [comment]
During the testnet, nodes have a end_timestamp at which they'll just stop and won't start until the next release. For the 6.5 it was set for Monday, January 31, 2022 4:00:00 PM GMT.

Testnet 7.0 hasn't been released yet.
