### ISSUE TITLE
Path auto-completion in client

### ISSUE THREAD

**Issue by qdrn** [massalabs/massa#2236]
It would be handy to have path auto completion with tab in the client, especially for SC :)

Do you think it's a lot of work @yvan-sraka ?

**Comment by yvan-sraka** [comment]
> It would be handy to have path auto completion with tab in the client, especially for SC :)
> 
> 
> 
> Do you think it's a lot of work @yvan-sraka ?

It's not a lot of work :) it could be left to the community as a "good first issue" or I can make it myself if we want this to be part of the next release!

**Comment by qdrn** [comment]
Better leave some good first issues. We can do it later :)
