### ISSUE TITLE
Format datastore entry in get_addresses endpoint

### ISSUE THREAD

**Issue by qdrn** [massalabs/massa#2237]
Since the data is stored in a hashmap with string values at the SC level, it would make sense to access it through the API as a hashmap with strings and not just bytes (see key datastore here: https://github.com/massalabs/massa/wiki/api#get_addresses).

Or at least document how to recover the initial hashmap from the bytes.

**Comment by AureliaDolo** [comment]
I find it risky to convert bytes to string that you may not know where there from. We can add a bool to specify whether you want to try to convert the datastore to string, in the API and/or in the client.

**Comment by qdrn** [comment]
In the long term `data` should store bytes. It's a limitation for now. There's no point to work on this as it will be bytes in the future.

Closing.
