### ISSUE TITLE
Next release checklist (8.0 or 7.1)

### ISSUE THREAD

**Issue by AureliaDolo** [massalabs/massa#2273]
Todo just before the next release
* [x] #2272 
* [ ] update config : timestamps and version
* [ ] move wiki submodule head up to date
* [ ] maybe #2318 
* [x] merge #2271
* [x] merge #2285
* [x] merge #2290
* [x] merge #2292
* [x] merge #2293
* [x] merge #2294
* [ ] hopefully #2297
* [ ] merge #2324 
* [ ] merge #2323
* [x] merge #2311 
* [ ] merge #2296
* [ ] merge #2287

**Comment by AurelienFT** [comment]
@damip The PR that seems ended and already partially reviewed to be merge before the new testnet launch are : 
- https://github.com/massalabs/massa/pull/2251
- https://github.com/massalabs/massa/pull/2351
- https://github.com/massalabs/massa/pull/2359
- https://github.com/massalabs/massa/pull/2311

**Comment by AureliaDolo** [comment]
outdated
