### ISSUE TITLE
RPC Abstraction should be usable by external projects

### ISSUE THREAD

**Issue by AurelienFT** [massalabs/massa#2280]
**Is your feature request related to a problem? Please describe.**
The client use a great interface to communicate with the RPC API. If I want to develop a tool for massa and I want to use the RPC API I would like to use this interface but it's in a binary not a library. So I have to rewrite mine (or copy paste).

**Describe the solution you'd like**
The solution would be to split the interactions with the RPC API to make it a separate crate as a library and publish it so that everyone can use it as a base to code their own tool in Rust.

**Describe alternatives you've considered**
/

**Additional context**
/

**Comment by AureliaDolo** [comment]
Duplicate #1952

**Comment by AurelienFT** [comment]
I think we can reopen it because the issue you tagged for duplicate is related to splitting the repl part. My point is to split the interaction with RPC to have something like an SDK that can be publish to help to develop on massa.
