### ISSUE TITLE
Document from_raw vs from string for amount

### ISSUE THREAD

**Issue by AureliaDolo** [massalabs/massa#2289]
This is a confusion that occurred a lot ! 

Amount is a u64 and a MAS is worth AMOUNT_DECIMAL_FACTOR * that u64.

Amount has two conversion methods:
* from string that consider MAS values
* from raw that consider that u64 that we lack a name for

There are not the same and from string should be preferred, even when initializing a value (except for zero, in that case use AMOUNT_ZERO) , as AMOUNT_DECIMAL_FACTOR may change.

@massalabs/core-team  Where should I put that ?

**Comment by damip** [comment]
from_raw has quite an explicit name, and that's how it's done elsewhere: https://docs.rs/neon/latest/neon/handle/trait.Managed.html#required-methods

If you search the word "raw" here: https://doc.rust-lang.org/nightly/std/thread/struct.JoinHandle.html  you'll find that it allows extracting the raw underlying representation when necessary.

If you look here: https://docs.rs/num/latest/num/rational/struct.Ratio.html  it allows (de-)constructing the wrapper to/from its raw representation.

In our case, raw values on Amount are ONLY useful when communicating with the smart contract engine through a raw intermediate representation. Unless we find a better way of doing so, we can just add a doc comment to the raw methods. Another option is to rename them to something like from_mantissa_u64/to_mantissa_u64 ... I don't like it that much.

**Comment by AureliaDolo** [comment]
the point here is not about smart contract but (see linked example) when initializing a value in rust code.

It's not obvious that Amount is not the same as MAS

**Comment by damip** [comment]
Ok I guess we should simply document Amount::from_raw and Amount::from_str.

My point about the smart contracts was mostly responding to "Maybe we should study the possibility of keeping from raw private" : for now we can't because we use the raw representation to transfer Amounts to/from the smart contract engine because it is much more practical than the serialized value (and that should be the only place we actually need it)

**Comment by yvan-sraka** [comment]
> the point here is not about smart contract but (see linked example) when initializing a value in rust code.
> 
> It's not obvious that Amount is not the same as MAS

Yes that's true that this in particularly unobvious, I made the mistake more than a couple time before understanding the behavior behind these constructors...

**Comment by damip** [comment]
documented it in https://github.com/massalabs/massa/pull/2294
