### ISSUE TITLE
Create a test tools module

### ISSUE THREAD

**Issue by adrien-zinger** [massalabs/massa#2295]
My problem is that every time I touch the unit tests in a module, I can find a tools.rs near that compute a lot of things to simplify the creation of a new test, and that tools is in a private scope.

For example in the execution module, it would be great to have access to some function defined in _'massa-consensus-worker/src/tests/tools.rs'_ and furthermore, have a common module where to put mocks etc...

I'm thinking about a common module, but we need first to look at what can be common (to avoid circular dependencies)

For example, in the execution-module I'll duplicate or fork `create_block_with_operations`. I'm sure it's always easy to maintain while it's in the scope of a unit test. Nevertheless, in a future, it could be faster to add a test.

**Comment by AureliaDolo** [comment]
For the tests that create blocks operations and so on, I would maybe put the in a test-tools mod in models.

**Comment by damip** [comment]
My initial proposal on the "split crates" task was to split into:
* xxx_exports containing interfaces, exported structures 
* xxx_worker containing the worker
* xxx_test_exports containing shared testing tools like random tools, mocks, a default XxxConfig for testing, etc...

And the xxx_test_exports crate wold be used by xxx_worker for its internal tests but also by other crates that need this
