### ISSUE TITLE
Refactor Block/Header 

### ISSUE THREAD

**Issue by gterzian** [massalabs/massa#2298]
From the point of view of network propagation and multistake protection, a block comes in two parts:

    the header + denunciations : they are propagated as an announcement
    endorsements + operations : they should be downloaded after asking explicitly, no need to send the header again as the asker has it already. Also in case of multistake they could be dropped from existing blocks and/or not downloaded.

From the point of view of consensus/graph and execution, a block has two conceptually different parts:

    header + denunciations + endorsements => required to integrate the block in the graph and compute finesses
    operations => only taken care of by the Execution module, not by consensus

We should think about both those separations and see what could be the optimal split

(source: https://github.com/massalabs/massa/issues/2264#issuecomment-1040130774)

**Comment by gterzian** [comment]
> We should think about both those separations and see what could be the optimal split

Ok, how about we focus on moving the Vec<Endorsement> out of the current BlockHeaderContent, and replacing it with a Vec<Denunciation>? @damip

**Comment by damip** [comment]
After thinking more about it, I still don't have a definitive answer to this problem. So I would vote for keeping both denunciations and endorsements in the header for now, and postpone this split for later (after the optimization of network messages and integration).
