### ISSUE TITLE
Remove get_active_block

### ISSUE THREAD

**Issue by gterzian** [massalabs/massa#2299]
https://github.com/massalabs/massa/blob/441283585efa2760a1e0dd3426726a64639ae902/massa-consensus-exports/src/consensus_controller.rs#L118

Seems to only be used in tests, and those tests are likely to be rewritten by passing id instead of blocks.

**Comment by damip** [comment]
good point

**Comment by gterzian** [comment]
This was done in https://github.com/massalabs/massa/pull/2428/commits/ab47a7985e7aa93f8ecfcb92145b56d06a027953
