### ISSUE TITLE
Prune shared storage

### ISSUE THREAD

**Issue by gterzian** [massalabs/massa#2308]
Part of https://github.com/massalabs/massa/issues/2178

Currently it's mostly `graph` that is in charge of pruning the block it manages locally, for example at:

https://github.com/massalabs/massa/blob/ec8dd82a86b1d1602d342a0610d31f9dae67d89a/massa-graph/src/block_graph.rs#L3200

Presumably it could instead prune the shared storage.

**Comment by damip** [comment]
I think we might need both: storage needs a way of pruning but graph will probably also maintain a local list of "active" and "final-but-still-needed" blocks

**Comment by gterzian** [comment]
> also maintain a local list of "active" and "final-but-still-needed" blocks that also needs to be pruned

Yes `consensus` will keep various things that relate to its local logic, and as those are pruned I think storage can be pruned alongside, by `consensus`. 

Other than consensus, is there another component that would be involved in pruning?

**Comment by damip** [comment]
> > also maintain a local list of "active" and "final-but-still-needed" blocks that also needs to be pruned
> 
> Yes `consensus` will keep various things that relate to its local logic, and as those are pruned I think storage can be pruned alongside.
> 
> Other than consensus, is there another component that would be involved in pruning?

no, I think only graph management will be responsible for pruning final blocks
