### ISSUE TITLE
Reduce max_operations_fill_attempts

### ISSUE THREAD

**Issue by damip** [massalabs/massa#2309]
Reduce max_operations_fill_attempts to 10 instead of 102400 in massa_node/base_config/config.toml

See discussion: https://github.com/massalabs/massa/issues/2215#issuecomment-1042737531

**Comment by sebastien-forestier** [comment]
I think we should completely remove this parameter.

**Comment by damip** [comment]
> I think we should completely remove this parameter.

see my response in #2215

**Comment by damip** [comment]
closing (see closed PR)
