### ISSUE TITLE
make peer management by PeerType more generic

### ISSUE THREAD

**Issue by AureliaDolo** [massalabs/massa#2319]
see #2297

**Comment by AureliaDolo** [comment]
@yvan-sraka if you have any fancy ideas :)

**Comment by yvan-sraka** [comment]
> @yvan-sraka if you have any fancy ideas :)

Do you recall the spaceship launch 🚀 code example from "Rust for Rustaceans"?!

**Comment by AureliaDolo** [comment]
> > @yvan-sraka if you have any fancy ideas :)
> 
> Do you recall the spaceship launch rocket code example from "Rust for Rustaceans"?!

It's on my desk at home I still have to read it x)
