### ISSUE TITLE
Add a private API command and client command to dynamically change the public IP of the node

### ISSUE THREAD

**Issue by damip** [massalabs/massa#2326]
Format: `set_temporary_public_ip(Option<IPAddress>)`  with the option to put it back to None.

This command is not persistent across node reboots. This can be a followup.

Note that this has only an influence on the peer database. 
When a new IP is set/unset, the peer database needs to handle the change properly.

The goal of this is to allow people with dynamic IPs to have an external service updating the public IP they announce on a regular basis.

**Comment by AureliaDolo** [comment]
> This command is not persistent across VM reboots.

What do you mean ?

**Comment by damip** [comment]
> > This command is not persistent across VM reboots.
> 
> What do you mean ?

sorry typo, corrected:)

**Comment by AureliaDolo** [comment]
So it's about adding a our_ip field in peer info db that overrides the default our ip in the network config ?
