### ISSUE TITLE
About type naming (no need to prefix everything with module name in which things are defined)

### ISSUE THREAD

**Issue by AureliaDolo** [massalabs/massa#2327]
Not sure about the naming of this trait, but more generally my logic is "if we are already in module `FooBar`, no needs to name something `FooBarState`, just `State` is enough, since we could after use it externally as `FooBar::State`" but this could be for sure tackle in another issue!

_Originally posted by @yvan-sraka in https://github.com/massalabs/massa/pull/2324#discussion_r812682298_

**Comment by yvan-sraka** [comment]
Ok my point is not really about how to name `trait` but more about how to name everything, here is a code snippet:
```rust
// foobar.rs
pub struct State {
    pub y: u8,
}
```
```rust
// lib.rs
mod foobar;

pub struct State {
    pub x: foobar::State,
}

pub fn blob() -> State {
    State {
        // State & FooBar::State couldn't be mistaken
        x: foobar::State { y: 42 },
    }
}
```

**Comment by adrien-zinger** [comment]
That's a good point that can be added in our coding style. Making names lighter and take profits of the `mod` system of rust in cases we are in an ambiguous context.
