### ISSUE TITLE
Potential address creation collision 

### ISSUE THREAD

**Issue by damip** [massalabs/massa#2331]
What we currently use to generate SC addresses:

```rust
        // deterministically generate a new unique smart contract address

        // create a seed from the current slot
        let mut data: Vec<u8> = self.slot.to_bytes_key().to_vec();
        // add the index of the created address within this context to the seed
        data.append(&mut self.created_addr_index.to_be_bytes().to_vec());
        // add a flag on whether we are in read-only mode or not to the seed
        // this prevents read-only contexts from shadowing existing addresses
        if self.read_only {
            data.push(0u8);
        } else {
            data.push(1u8);
        }
        // hash the seed to get a unique address
        let address = Address(massa_hash::hash::Hash::compute_from(&data));
```

The problem is that someone could predict this address in advance and send coins to it before it is created in order to make it appear in the ledger before its actual creation. This is not a big security problem per se, but newly created SC addresses could see "unexpected" extra coins on their balance... 

Is it really a problem ?

Note that read-only calls can also be targetted

**Comment by AureliaDolo** [comment]
> We cannot send coins to an address that doesn't exist yet. Is that true?

It creates it
