### ISSUE TITLE
Make max_in_connections_per_ip PeerType specific

### ISSUE THREAD

**Issue by AureliaDolo** [massalabs/massa#2333]
> > Also maybe it's worth specifying the max number of open nodes per IP address for each type to give more granularity.
> 
> You mean the max_in_connections_per_ip in Network settings would become PeerType specific ?

maybe as a followup

_Originally posted by @damip in https://github.com/massalabs/massa/pull/2297#discussion_r813649154_

* [ ] add max_in_connections_per_ip to PeerTypeConnectionConfig
* [ ] remove max_in_connections_per_ip from NetworkSettings
* [ ] propagate the changes
* [ ] update the tests

**Comment by AurelienFT** [comment]
Done in network refactoring.
