### ISSUE TITLE
Put massa-ledger on disk and split crate

### ISSUE THREAD

**Issue by damip** [massalabs/massa#2342]
* choose and implement a mass storage approach to store the massa-ledger on disk + RAM cache
* never manipulate full ledger entries, only sub-data
* split the massa-ledger crate like it was done for execution to avoid importing the mass storage apparatus everywhere

**Comment by Eitu33** [comment]
https://github.com/massalabs/massa/issues/2579

**Comment by damip** [comment]
@Eitu33  is this done ?

**Comment by damip** [comment]
> > split the massa-ledger crate like it was done for execution to avoid importing the mass storage apparatus everywhere
> 
> Are you talking about having a `massa-ledger-exports` and a `massa-ledger-worker` here?
> 
> I don't think it is as necessary as for execution for example, but if you wish to do that still we can make it a followup.
> 
> That would be the only thing missing.

the idea is that only the massa-ledger-worker has a RocksDB dependency, and no other crate has it

**Comment by Eitu33** [comment]
> the idea is that only the massa-ledger-worker has a RocksDB dependency, and no other crate has it

Ok I see you added this for test 12, I propose we close this and I reopen an issue only treating the "split crate" part.

**Comment by Eitu33** [comment]
Closing this, see corresponding followup issue.
