### ISSUE TITLE
Per-peer throughput limitation

### ISSUE THREAD

**Issue by damip** [massalabs/massa#2345]
# Rationale 

To avoid a single peer flooding our node and taking over all the available bandwidth, we need to limit the up and down bandwidth per peer.

#  Implementation

## General

* have a config-defined max_peer_bytes_per_second_up and max_peer_bytes_per_second_down
* setup an async buffering system as a wrapper around the tcpstream senders that limits writing to a certain number of bytes in the last second
* setup an async buffering system as a wrapper around the tcpstream receiver that limits the readout to a certain number of bytes in the last second

## Available crates

Here is one: https://github.com/tikv/async-speed-limit

Please check it out and also study alternatives.

**Comment by qdrn** [comment]
Bump.

**Comment by damip** [comment]
Done
