### ISSUE TITLE
Config changes for testnet 8.0

### ISSUE THREAD

**Issue by sebastien-forestier** [massalabs/massa#2364]
* [x]  version number
* [x] genesis timestamp
* [x] end timestamp
* [x] double block size
* [x] bootstrap nodes bootstrap a given ip only once per 24h 
* [x] increase block history size
* [x] reduce 4x the size of the tx pool  (to mitigate the pb of https://github.com/massalabs/massa/issues/2215)
* [x] increase pool batch size

**Comment by damip** [comment]
https://github.com/massalabs/massa/pull/2368
