### ISSUE TITLE
Update tooling cryptographic functions

### ISSUE THREAD

**Issue by Eitu33** [massalabs/massa#2370]
## Context

We have been studying alternative crypto schemes in an effort to determine if they could improve the performances.

You can check the benchmarks results [here](https://github.com/massalabs/massa/issues/1841#issuecomment-1057923069).

It was concluded that using Schnorr (from [secp256k1](https://docs.rs/secp256k1/latest/secp256k1/)) as signature and [Blake3](https://docs.rs/blake3/latest/blake3/) as hash would result in an improvement when compared to what is currently used, Secp256k1 and Sha256.

### Schnorr vs Secp256k1
- no loss in performance
- gain in features

### Blake3 vs Sha256
- no loss in security
- gain in performance

Changing the signature and the hash functions of massa is a breaking change and it requires a prior update of the tooling functions.

## To Do

- [ ] Evaluate what must be changed and update the todo list

## Related Issues

- https://github.com/massalabs/massa/issues/1841
- https://github.com/massalabs/massa/issues/2373

**Comment by AureliaDolo** [comment]
For reference https://github.com/massalabs/massa/pull/1584

**Comment by Eitu33** [comment]
I benchmarked the exact implementation I used after `secp256k1` crate refactoring:

<img width="943" alt="Screenshot 2022-03-09 at 12 10 29" src="https://user-images.githubusercontent.com/89928840/157431632-3dfe49bd-ac9d-43bf-9163-e56a6dd7f92f.png">
<img width="954" alt="Screenshot 2022-03-09 at 12 10 59" src="https://user-images.githubusercontent.com/89928840/157431644-ab25e3f8-0c1c-4338-8aa4-d1199db3eceb.png">

@damip Given the performance loss for signatures when compared to ecdsa signing (1.5 times slower) are we keeping the schnorr choice?

**Comment by damip** [comment]
ping

**Comment by damip** [comment]
done
