### ISSUE TITLE
Change massa cryptographic functions

### ISSUE THREAD

**Issue by Eitu33** [massalabs/massa#2373]
## Context

We have been studying alternative crypto schemes in an effort to determine if they could improve the performances.

You can check the benchmarks results [here](https://github.com/massalabs/massa/issues/1841#issuecomment-1057923069).

It was concluded that using Schnorr (from [secp256k1](https://docs.rs/secp256k1/latest/secp256k1/)) as signature and [Blake3](https://docs.rs/blake3/latest/blake3/) as hash would result in an improvement when compared to what is currently used, Secp256k1 and Sha256.

### Schnorr vs Secp256k1
- no loss in performance
- gain in features

### Blake3 vs Sha256
- no loss in security
- gain in performance

## To Do

Update `massa-hash`

- [x] functions
- [x] tests
- [x] doctests

Update `massa-signature`

- [x] functions
- [x] tests
- [x] doctests

## Related Issues

- https://github.com/massalabs/massa/issues/1841
- https://github.com/massalabs/massa/issues/2370

**Comment by AureliaDolo** [comment]
for reference https://github.com/massalabs/massa/pull/1584

**Comment by qdrn** [comment]
bump
