### ISSUE TITLE
Node desynchronization.

### ISSUE THREAD

**Issue by synchroph** [massalabs/massa#2380]
**Describe the bug**
Often appear node desynchronization with no response from local RPC with future node bootstrap or crash.

**To Reproduce**
Run a node.

**Expected behavior**
Response from local RPC.

**Screenshots**
![screen1](https://user-images.githubusercontent.com/34461653/156933561-4d4ef429-76f0-4f91-9410-cc258973568a.png)
![screen2](https://user-images.githubusercontent.com/34461653/156933811-dcc6c5df-f0b3-479c-bde2-afc3558f6699.png)
![screen3](https://user-images.githubusercontent.com/34461653/156933595-a8c293b5-82c4-4b76-9785-60355bb09c66.png)
![screen4](https://user-images.githubusercontent.com/34461653/156933599-d535fa41-1e03-4dfb-8d9f-ad10e628a86a.png)
![screen5](https://user-images.githubusercontent.com/34461653/156933613-6d73564f-aa51-440f-80f5-00703c0b928f.png)

Ubuntu 20.04

**Comment by synchroph** [comment]
It looks like this issue is caused by different projects nodes on my server. I run them through docker on different ports. It is strange.

**Comment by AurelienFT** [comment]
> It looks like this issue is caused by different projects nodes on my server. I run them through docker on different ports. It is strange.

Can you send here the result of the command of docker ps on the server that have the dockers ? Maybe you haven't expose the ports from docker or made a mapping so that it run on the good port on your server.

**Comment by synchroph** [comment]
Simpler. I found that there was another node that I was running without docker on the same system with Massa, so I moved it into a container and that sorted out my issue.

**Comment by AurelienFT** [comment]
Ok nice ! Happy for you :)

**Comment by synchroph** [comment]
I have the same problem with the attack, desynchronization again. Local RPC stop responding and the node is going on restart after a while. There are many messages in Discord with the same errors which I had earlier.
Looks like the problem is only appearing when bootstrap port 31245 is open.

**Comment by synchroph** [comment]
> > I have the same problem with the attack, desynchronization again. Local RPC stop responding and the node is going on restart after a while. There are many messages in Discord with the same errors which I had earlier. Looks like the problem is only appearing when bootstrap port 31245 is open.
> 
> Do you have any evidence supporting this claim ? It would help us investigate.

I have only logs from my node, they are similar to logs from my screens, but this time without crashing. Current practice shows me that when a node is behind a firewall or only the p2p port is open I had 0 warnings, errors.

**Comment by AureliaDolo** [comment]
> I have only logs from my node, they are similar to logs from my screens, but this time without crashing. Current practice shows me that when a node is behind a firewall or only the p2p port is open I had 0 warnings, errors.

Have you been able to see if you have some connected peers ?

**Comment by synchroph** [comment]
> > I have only logs from my node, they are similar to logs from my screens, but this time without crashing. Current practice shows me that when a node is behind a firewall or only the p2p port is open I had 0 warnings, errors.
> 
> Have you been able to see if you have some connected peers ?

No, after warning there is no response on get_status, but logs show that node is keep connecting to different peers. 

Update:
In the last 24 hours, my node produced 100% of blocks on selected slots without any errors and warnings with a closed bootstrap port.

**Comment by AureliaDolo** [comment]
Do you know if your node was shared for other to bootstrap from ? Bootstrapping is not quite optimized yet, so it may indeed be that it's putting to much pressure on you node.

**Comment by synchroph** [comment]
> Do you know if your node was shared for other to bootstrap from ? Bootstrapping is not quite optimized yet, so it may indeed be that it's putting to much pressure on you node.

Don't know.

I'm currently running two nodes on my server and only Massa on validator mode.

2x XEON 5218, 64GB of ram, 2TB SAS SSD and 1gbit internet.

**Comment by synchroph** [comment]
> > > > I have the same problem with the attack, desynchronization again. Local RPC stop responding and the node is going on restart after a while. There are many messages in Discord with the same errors which I had earlier. Looks like the problem is only appearing when bootstrap port 31245 is open.
> > > 
> > > 
> > > Do you have any evidence supporting this claim ? It would help us investigate.
> > 
> > 
> > I have only logs from my node, they are similar to logs from my screens, but this time without crashing. Current practice shows me that when a node is behind a firewall or only the p2p port is open I had 0 warnings, errors.
> 
> Do you mean closing bootstrap port only or also making your node non-routable ? In that case it would reduce the bandwidth usage so it's not exactly a fair comparison.

Half routable, so count as non-routable. 
Yes, there is an average 10 Mb/sec difference. 
35 routable, 25 in my case.

I had 55Mb/sec average in testnet 7.

**Comment by synchroph** [comment]
Ok, I can try to change settings to reduce bandwidth and load on the bootstrap port to have another full-routability attempt if the problem is only with optimization.

**Comment by synchroph** [comment]
Looks like the issue is completely gone with testnet 9.2. Great job.
