### ISSUE TITLE
Bug: cannot execute at a slot before finality

### ISSUE THREAD

**Issue by sebastien-forestier** [massalabs/massa#2386]
A `get_addresses` request from the API did not answer, and at that time the node showed this log:

```
thread 'tokio-runtime-worker' panicked at 'cannot execute at a slot before finality', massa-execution-worker/src/execution.rs:204:13
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

**Comment by AureliaDolo** [comment]
Looks like the error message is confusing. It happens when we try to get_accumulated_active_changes_at_slot for a slot that happened before the current final cursor.

**Comment by sebastien-forestier** [comment]
It happened on another node, without any request:

```
thread 'tokio-runtime-worker' panicked at 'cannot execute at a slot before finality', massa-execution-worker/src/execution.rs:204:13
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

**Comment by damip** [comment]
I'm not sure I fully solved it, but at least we will get more precise panics if it happens again !
