### ISSUE TITLE
Document avaible features

### ISSUE THREAD

**Issue by AureliaDolo** [massalabs/massa#2391]
Any ideas on where to do that ?

@yvan-sraka suggested doing that in the workspace cargo toml and referencing that in every other cargo toml

feel free to complete the descriptions

* [ ] sandbox: to launch a standalone node with a generated genesis timestamp for test purpose
* [ ] instrument
* [ ] beta
* [ ] hash-prefix: to display (and parse) the prefix for hashes in the cli
* [ ] testing

**Comment by AureliaDolo** [comment]
@massalabs/core-team

**Comment by AurelienFT** [comment]
We can reopen @AureliaDolo  ?

**Comment by AureliaDolo** [comment]
It was closed because it was resolved by the documentation pr

**Comment by AurelienFT** [comment]
Oh yes my bad.
