### ISSUE TITLE
Harmonize SCELedgerInfo and SCELedgerEntry

### ISSUE THREAD

**Issue by AureliaDolo** [massalabs/massa#2397]
Why not having the same type in ledger info and ledger entry ? For example having a BTreeMap on LedgerInfo to avoid this conversion very costly. (except if rust optimize it)

_Originally posted by @AurelienFT in https://github.com/massalabs/massa/pull/2359#discussion_r822521810_

**Comment by damip** [comment]
not relevant anymore
