### ISSUE TITLE
Where should high level documentation go ?

### ISSUE THREAD

**Issue by AureliaDolo** [massalabs/massa#2398]
As a user when I started to use the client I didn't understand the difference between candidate and final. Now that we split more of information between this two category it will be nice to have a line to explain when making a command that returning final and candidate things.

_Originally posted by @AurelienFT in https://github.com/massalabs/massa/pull/2359#discussion_r822525305_

**Comment by AurelienFT** [comment]
It now goes to https://github.com/massalabs/massa-docs
