### ISSUE TITLE
Improve written english

### ISSUE THREAD

**Issue by sebastien-forestier** [massalabs/massa#2405]
There are many english writting mistakes in the codebase, in comments, API, logs etc, e.g. `insufisant -> insufficient`.

What is the best way to detect/correct them ?

**Comment by AurelienFT** [comment]
In VS Code there is an extension called "Spell Checker" I think everybody should install it.

**Comment by damip** [comment]
adding cargo-spellcheck to the CI could be nice to prevent having to go through this again

**Comment by AureliaDolo** [comment]
I'm correcting/ reformulating quite a bit at #2416, it would be nice to wait for that to merge first

**Comment by AurelienFT** [comment]
> I'm correcting/ reformulating quite a bit at #2416, it would be nice to wait for that to merge first

No problem. We can put this one in stand-by. Maybe cool if you have a mergeable version that don't update to be able merged directly after operations/storage and you continue on a sub PR maybe because yours start to become big. Maybe one per module.
