### ISSUE TITLE
Shared storage: manage block as it is processed in system

### ISSUE THREAD

**Issue by gterzian** [massalabs/massa#2406]
Previously, as a block was received over the network, it would "travel" across the system in immutable form from stage to stage, more or less `network => protocol => consensus`, and various checks would be applied to it along the way,  with the block only making it to the next stage when those checks passed. Invalid blocks would be discarded along the way, and even valid blocks making it to `consensus` would eventually be pruned.

In the current proposal in https://github.com/massalabs/massa/pull/2233, the block is initially stored in shared storage when first received over the network, and then retrieved when needed somewhere in a processing step, and finally discarded as part of [pruning](https://github.com/massalabs/massa/pull/2365).

So it is not an immutable block that is processed along a pipeline anymore, it is now rather a block ID, with the actual block stored/retrieved from a shared and mutable storage.

The current situation is problematic, for the following reasons:

1. A block could be overwritten in storage if received multiple times over the network. This could even result in a block ID "passing various checks", all the way to let's say `execution`, and then actually being replaced with some invalid block in storage at the level of `network`, with that invalid block then being retrieved for execution.
2. If a block if found invalid before reaching `consensus`, it isn't discarded from storage, and also will never be pruned.

The solution would be to more carefully manage a block in shared storage. For example:

1. Prevent a new entry from overwriting a currently stored entry, at https://github.com/massalabs/massa/pull/2233/files#diff-dc6d1c306121e17c2c4f8de4f32d293dc7bd8776b5da3372f172e0a98962a280R18
2. Discard, or mark as invalid, an entry if it fails a check somewhere in the system. See for example `note_block_from_node` in `protocol_worker`.

**Comment by gterzian** [comment]
cc @massalabs/core-team

**Comment by AurelienFT** [comment]
For the first problem can we just add verification of the blockID in the store block. (if it's not too big calculation)
For the second we could add a field in the storage which is invalid and so when the modules tries to fetch it they know it's invalid and when we prune the blocks (where we already do it) we discard all the blocks that are invalid.

**Comment by damip** [comment]
Here is how I see it short term:
* when a block/header is received in protocol and its integrity (hash) verified, it should be added to the storage if not already present. If only the header was present, the full block can be added to storage. If what we want to add is already present, it should not be added (this can happen if the protocol cache overflowed).
* consensus should notify storage of the latest_final_periods, and storage should remove all blocks B for which B.period < latest_final_periods[B.thread] - config.force_keep_final_periods (this config parameter already exists in consensus) 


Here is how I see it in the long run:
* asking for missing dependencies etc.. should be done in the protocol part. Then, only blocks that have no missing dependencies are sent by message to Consensus, consensus will try to integrate them into the graph. If it fails, it will notify protocol of the failure.  If it succeeds, it will notify protocol of the success and store the full block in Storage once and for all.
* The special case of double stake protection should be studied on its own

**Comment by gterzian** [comment]
> when a block/header is received in protocol and its integrity (hash) verified, it should be added to the storage if not already present.

Makes sense, in the current proposal it's `network` storing, and it does make sense to move that up one step to `protocol`. 

> If only the header was present, the full block can be added to storage.

Currently we don't store headers only. 

> consensus should notify storage of the latest_final_periods, and storage should remove all blocks B for which

Also makes sense, and it's consensus that can just call a method on storage, since it has direct access to it.
