### ISSUE TITLE
Ban/ Unban by node id in api/client

### ISSUE THREAD

**Issue by AureliaDolo** [massalabs/massa#2411]
There is already a Ban(nodeid) network command (and associated method)

* [ ] add Unban(NodeId) network command and associated method (see Unban(Vec<IpAddr>))
* [ ] add node_ban_by_id api endpoint and associated cli command
* [ ] add node_unban_by_id api endpoint and associated cli command 
* [ ] open up and monitor the api wiki update related issue

For the client command enum, watch where you add it, it matters for the help display

**Comment by aoudiamoncef** [comment]
Hi @AureliaDolo, 

I'm interested by this issue, is there any work in progress on it ?

**Comment by AureliaDolo** [comment]
Hello, To my knowledge, there is no work on that. For the review part, I'll let @yvan-sraka and @damip have a look :)
