### ISSUE TITLE
Disconnect from a node when we receive corrupted data

### ISSUE THREAD

**Issue by AurelienFT** [massalabs/massa#2412]
I tried to run a node on the testnet and received some corrupted data from others node but I didn't have any print about banning this node. Screenshot :

<img width="1133" alt="Screenshot 2022-03-14 at 12 05 03" src="https://user-images.githubusercontent.com/32803821/158159862-04954b6e-30e3-4efd-b413-a45363cc79b0.png">

I don't receive any corrupted data from this node in the future so maybe I have disconnected from her but I don't have any print.

**Comment by AureliaDolo** [comment]
Related #2411

**Comment by AurelienFT** [comment]
> Related #2411

Is more for commands. Here it should be automatically ban adn disconnect, no?

**Comment by AurelienFT** [comment]
> It should ban automatically
> 
> https://github.com/massalabs/massa/blob/fb6c4426d5c5938384bf937c4943736c34746216/massa-protocol-worker/src/protocol_worker.rs#L1395-L1396

So we have a lack of logs then.

**Comment by AureliaDolo** [comment]
> So we have a lack of logs then.

Not sure, further logs are at trace level.

**Comment by damip** [comment]
The main problem we observe here is that the node is actually not banned when it should be: we reconnect back to it and it continues sending us invalid data.
