### ISSUE TITLE
Why initial_sce_ledger and initial_ledger don't have the same format ?

### ISSUE THREAD

**Issue by AurelienFT** [massalabs/massa#2426]
The file names seems similar and their usage also why we have two different format ?

`initial_sce_ledger.json`: https://github.com/massalabs/massa/blob/main/massa-node/base_config/initial_sce_ledger.json
`initial_ledger.json`: https://github.com/massalabs/massa/blob/main/massa-node/base_config/initial_ledger.json

**Comment by AurelienFT** [comment]
Also in `initial_rolls` we have the amount in number format and in `initial_sce_ledger` and `initial_ledger` we have it as string. It's also an inconsistency.

**Comment by AureliaDolo** [comment]
Because we initialize the sce ledger with just balances, that are not the real datastructures, whereas for the consensus ledger we initialize it with LedgerData structs that contains only one field: balance

But it would be worth taking a look at all the redundant data structs we have everywhere

**Comment by AurelienFT** [comment]
> Because we initialize the sce ledger with just balances, that are not the real datastructures, whereas for the consensus ledger we initialize it with LedgerData structs that contains only one field: balance
> 
> But it would be worth taking a look at all the redundant data structs we have everywhere

Yes I know that initialization behind the scene are not the same but we expose the files and we have docs to update them to create your proper network and so it should be consistent for the end-user.

**Comment by AurelienFT** [comment]
Balances has been unified since https://github.com/massalabs/massa/pull/3012
