### ISSUE TITLE
API endpoints need phantom data

### ISSUE THREAD

**Issue by AurelienFT** [massalabs/massa#2436]
Now that the Signature has been refactor we use PhantomData in structure.

The problem is that we don't want user to have to provide this type as it's only a PhantomData and it break the current format of the API.

Solution : https://play.rust-lang.org/?gist=cbfadccf2dc1a3b4b4eb2279be2a4535&version=stable

**Comment by AureliaDolo** [comment]
https://github.com/massalabs/massa/blob/c055c97d48139e9cd30bd88cdb57bb5efdf57f3d/massa-network-exports/src/peers.rs#L129-L138

This kind of stuff wouldn't be enough ?
