### ISSUE TITLE
Create a self-contained documentation

### ISSUE THREAD

**Issue by qdrn** [massalabs/massa#2460]

**Comment by qdrn** [comment]
Basically creating a Read The Doc documentation instead of having the documentation scattered across many repos.

This was discussed here: https://github.com/massalabs/massa/discussions/2247#discussioncomment-2405533

**Comment by AureliaDolo** [comment]
For reference, I had to `pip install sphinx` and `pip install sphinx_rtd_theme` to `make html` in your branch
