### ISSUE TITLE
OpenRPC Specification

### ISSUE THREAD

**Issue by aoudiamoncef** [massalabs/massa#2462]
Related to #1058 

Example with [Ethereum ](https://playground.open-rpc.org/)

May be convert Wiki documentation to OpenRPC spec ? 

![openrpc](https://user-images.githubusercontent.com/22281426/160298385-b2db7a93-2dce-4f17-b65e-69a2e576496f.png)

I'm waiting for feedback

Thanks

**Comment by damip** [comment]
Thanks for the idea.

@yvan-sraka  you were mentionning using a swagger-like description. Would that be of interest?

**Comment by aoudiamoncef** [comment]
It will be my next contribution to Massa. It's in progress

**Comment by qdrn** [comment]
> It will be my next contribution to Massa. It's in progress . Its painfull to write it in raw JSON. We could cheat and made it with existing OpenAPI GUI tools like [ApiCurio](https://www.apicur.io/studio/) . At the end, OpenRPC is similare to a POST based OpenAPI spec.

Nice. Thanks for the update!

**Comment by aoudiamoncef** [comment]
Hi,

With the help of @rykcod, we finished the first step which consists of translating current documentation to OpenAPI format.

Now we should validate it together before translating to OpenRPC. 

@qdrn if you are interested to review the current work, I'll send you an invitation link to join us.

**Comment by damip** [comment]
Let's make sure the spec is hosted in the massa repo, docs folder and that the CI updates everything auomatically.

**Comment by aoudiamoncef** [comment]
We have an draft OpenRPC spec, we should enrich it to be complete. 

Some useful links: 
[OpenRPC spec](https://github.com/Mermade/open-rpc-spec)
[Ethereum OpenRPC spec](https://github.com/etclabscore/ethereum-json-rpc-specification/blob/master/openrpc.json)
[Playground OpenRPC](https://playground.open-rpc.org/)

**Comment by qdrn** [comment]
> Hi,
> 
> With the help of @rykcod, we finished the first step which consists of translating current documentation to OpenAPI format.
> 
> Now we should validate it together before translating to OpenRPC.
> 
> @qdrn if you are interested to review the current work, I'll send you an invitation link to join us.

That would be nice.

**Comment by aoudiamoncef** [comment]
Hi @qdrn,

I've added a minimale [Massa OpenRPC spec](https://raw.githubusercontent.com/aoudiamoncef/massa/feature/openrpc/docs/technical-doc/openrpc.json). We need some testing on a running node. We have to gather feedback and improve the spec. 

IMHO, we should merge It to avoid offset with the raw documentation, any changes should be reported on this contract.
