### ISSUE TITLE
Simple refactor for NodeEventType

### ISSUE THREAD

**Issue by adrien-zinger** [massalabs/massa#2467]
It's probably an error to use that name for NodeEvent content. As said, `NodeEventContent` could make more sens.

Rename NodeEventType to NodeEventContent https://github.com/massalabs/massa/blob/b15ca57dcdc2d1b701d76aa5661511885f6e5562/massa-network-exports/src/commands.rs#L112

**Comment by Eitu33** [comment]
@damip @AurelienFT what do you think? Trying to go through some old issues rn.

**Comment by Eitu33** [comment]
I personally don't think this would make sense.

**Comment by AurelienFT** [comment]
Personally, I don't have strong opinion on that.

**Comment by Eitu33** [comment]
@adrien-zinger I am closing in an effort to have interesting good first issues for the dev community, if you feel like this truly needed, please re-open and remove the "good first issue" tag 👍
