### ISSUE TITLE
Move mocks in appropriate crates

### ISSUE THREAD

**Issue by AureliaDolo** [massalabs/massa#2468]
- Move the mocks in the appropriate test export crate
- Example: MockNetworkController is in Protocol test export but it should be in network test exports

**Comment by modship** [comment]
Checked all `Mock*`, they are in the right place. 

About `MockNetworkController`, with the refactoring and PeerNet integration i think it is now in the right place in `massa-protocol-worker/src/tests`.

**Comment by AurelienFT** [comment]
We can close
