### ISSUE TITLE
Cache of speculative execution reset

### ISSUE THREAD

**Issue by AurelienFT** [massalabs/massa#2469]
When running on #2428 each time I have a batch of operation coming into the node from the API I have this print multiple times : 

```
2022-03-29T08:33:01.033809Z  INFO massa_execution_worker::worker: speculative execution cache mismatch: resetting the cache
```

I link the full logs of the node (the messages are in the middle but also in the last lines) :
[logs_169.202.0.2.txt](https://github.com/massalabs/massa/files/8369826/logs_169.202.0.2.txt)

**Comment by damip** [comment]
Under "legal" circumstances, this message should appear:
* once when starting the execution module (initializing the blockclique)
* if the whole blockclique suddenly changes (this should actually never happen !)

What could be done:
* in the info message, actually print the first element (or None if absent) of the history if it mismatches the expected one

**Comment by Eitu33** [comment]
https://github.com/massalabs/massa/pull/2428#discussion_r838245744

**Comment by damip** [comment]
The main execution loop seems to roll all the time really fast, 100% cpu

**Comment by gterzian** [comment]
It may actually be that using the `BlockId` instead of cloning blocks, slightly changes the timing of something, or makes things run slightly faster which exposes a problem that was there already...
