### ISSUE TITLE
Serialization error

### ISSUE THREAD

**Issue by damip** [massalabs/massa#2479]
```
[2m2022-03-30T17:19:47.978444Z[0m [35mTRACE[0m [2mmassa_network_worker::network_cmd_impl[0m[2m:[0m massa:network_worker.manage_network_command receive NetworkCommand::AskForBlocks:{"hashlist":["LDJzwBCr9REUueEU72kJ798zKDzZMhaHVoQpKjzHATqKWrxRL","CLESGvoUxnz8yiQbdFQLGVyboT6XcPoSbwNNrqXAhk1PNw8LR","ZPv14Fhk3TGN3vx3xnWxJRVe9ZZ9qwWXz6hZV2uUZb2CoNUK3","2Gc9rskvPK4VnwGcRxKadKKCgjbkH971npbKboa79E67RwfV9V","T7j1nojAjMqPxZkWyrNDE68i9z9Ydef8Qs7hoF42WJmzr31JE","146CHFCb15rxVMxTk8nk1qxEWpos611FhrCpE3unwxNUPCTUS","bgTAHPcyvaV17zxWbFzfqGfEJKh4PvaKbFdENTsu3mUATg6uP","27eRFEi6zoKyhLcEfj7A7dhfQjLsC9HEZBYyuisgCQgAzsdnhd","2upLptwVtN1m3dzmxJiycBiexwtvveMN9ZQZjxJtvsfLbM8o4b","8hsx2Yde4Kavj9PwUJY8o2c4aM8vZG5kZrvU343weXY5u8pxW","25R7s6xGSbeVVmLH7wSbaeknKoDJSjNLMLhSwoVuv2dgTzp7FG","KDr5xDXicsZJDMgjz9KSANs2tL4NRdXnv59kNtDMtrRrUMT77","o39T5a9yWiRVhaCuxdpEvJhBadZke3RP4wNxf6HmabgsmbF8Y","4GcqLbt9zguZhtZzk8kseEdjAMJxMbaVgx9vQnKS6MueWdxGv"],"node":"5fZSpHLvsXYAUCcLLE5JxwACUSbS9sNnXqLDFnVWbXUB2i6E4t"}
[2m2022-03-30T17:19:47.978511Z[0m [35mTRACE[0m [2mmassa_network_worker::node_worker[0m[2m:[0m massa:node_worker.run_loop. send Message::AskForBlocks:{"hashlist":["LDJzwBCr9REUueEU72kJ798zKDzZMhaHVoQpKjzHATqKWrxRL","CLESGvoUxnz8yiQbdFQLGVyboT6XcPoSbwNNrqXAhk1PNw8LR","ZPv14Fhk3TGN3vx3xnWxJRVe9ZZ9qwWXz6hZV2uUZb2CoNUK3","2Gc9rskvPK4VnwGcRxKadKKCgjbkH971npbKboa79E67RwfV9V","T7j1nojAjMqPxZkWyrNDE68i9z9Ydef8Qs7hoF42WJmzr31JE","146CHFCb15rxVMxTk8nk1qxEWpos611FhrCpE3unwxNUPCTUS","bgTAHPcyvaV17zxWbFzfqGfEJKh4PvaKbFdENTsu3mUATg6uP","27eRFEi6zoKyhLcEfj7A7dhfQjLsC9HEZBYyuisgCQgAzsdnhd","2upLptwVtN1m3dzmxJiycBiexwtvveMN9ZQZjxJtvsfLbM8o4b","8hsx2Yde4Kavj9PwUJY8o2c4aM8vZG5kZrvU343weXY5u8pxW","25R7s6xGSbeVVmLH7wSbaeknKoDJSjNLMLhSwoVuv2dgTzp7FG","KDr5xDXicsZJDMgjz9KSANs2tL4NRdXnv59kNtDMtrRrUMT77","o39T5a9yWiRVhaCuxdpEvJhBadZke3RP4wNxf6HmabgsmbF8Y","4GcqLbt9zguZhtZzk8kseEdjAMJxMbaVgx9vQnKS6MueWdxGv"],"node":"5fZSpHLvsXYAUCcLLE5JxwACUSbS9sNnXqLDFnVWbXUB2i6E4t"}
[2m2022-03-30T17:19:47.978581Z[0m [35mTRACE[0m [2mmassa_network_worker::node_worker[0m[2m:[0m massa:node_worker.run_loop.loop.writer_command_rx.recv.send.ok:{"msg_id":4,"node":"5fZSpHLvsXYAUCcLLE5JxwACUSbS9sNnXqLDFnVWbXUB2i6E4t"}
[2m2022-03-30T17:19:48.039099Z[0m [35mTRACE[0m [2mmassa_network_worker::node_worker[0m[2m:[0m massa:node_worker.run_loop.self.socket_reader.next(). receive error:{"error":"models error: buffer error: slice too small to extract array"}
```

**Comment by gterzian** [comment]
So the error originates at 

https://github.com/massalabs/massa/blob/fb495e11ef34d4b4f634239ce7577b9c15e7717b/massa-models/src/serialization.rs#L168

Some new code using this since testnet 8:

- https://github.com/massalabs/massa/blob/fb495e11ef34d4b4f634239ce7577b9c15e7717b/massa-models/src/signed.rs
- https://github.com/massalabs/massa/blob/fb495e11ef34d4b4f634239ce7577b9c15e7717b/massa-network-worker/src/messages.rs#L63 (introduced by storage)

How about we `expect` inside `array_from_slice` as opposed to returning an error? The serialization steps themselves are not async so we should be able to get a pretty good traceback, and I don't think those errors are handled anywhere.

**Comment by damip** [comment]
@gterzian  I don't see the problem in that function... note that if we have a deserialization error involving for example a missing cursor update, the error won't necessarily come from that place, but from the next object being deserialized from a shifted buffer.

>How about we expect inside array_from_slice as opposed to returning an error?

We must never panic on untrusted input validation.  Otherwise someone can just send an invalid packet to a node and kill it

**Comment by AurelienFT** [comment]
I know that I have made a change in the serialization and deserialization of operations ids and operations

**Comment by AurelienFT** [comment]
I have checked all the changes made in the two main features storage and operation batch and I don't see any bad serialization/deserialization....

**Comment by Eitu33** [comment]
Same, didn't find any. I even checked the async messages changes (you never know) and nothing still. I am currently double-checking though.

**Comment by AureliaDolo** [comment]
Time to write more tests x)

**Comment by AureliaDolo** [comment]
I'm not sure we check for the length when serializing, but we check it when deserializing, so maybe there is an inconsistency here (see https://github.com/massalabs/massa/issues/1200)

**Comment by damip** [comment]
I can't find any bug either :(

**Comment by damip** [comment]
My suspicions are on deserialize_message_with_optional_serialized_object

**Comment by AurelienFT** [comment]
I have added more logs and the extend with the serialized version pass well but the deserialization of the block fail at block header.
I just discovered that the buffer on the deserialize part have a length of 0. Maybe it's when serializing then.

**Comment by AurelienFT** [comment]
I think it's the mem::take in ToSend::Block that send no value because serialized is not set. Will verify.

**Comment by AurelienFT** [comment]
I can confirm the serialized of the block is empty and then send it empty to the network. Two solutions:

- Track where we have an empty serialized in storage (shouldn't be possible)
- More temporary one re-serialize the block here instead of using his already serialized version

**Comment by Eitu33** [comment]
I think we should try the nasty solution first and see how it behaves, then track the storage issue.

**Comment by AurelienFT** [comment]
Ah but I have found why it's because we are doing a memtake so the second time we send it the buffer is empty. But why we are doing a mem::take is there a specific reason or I can replace with a copy ?

**Comment by Eitu33** [comment]
I reckon you can just replace it with a copy, I didn't notice the loop before but mem::take is not to be used it.
