### ISSUE TITLE
The cat stopped dancing

### ISSUE THREAD

**Issue by damip** [massalabs/massa#2487]
See ? http://145.239.66.206/cryptocat/

**Comment by qdrn** [comment]
Maybe related: https://github.com/massalabs/massa/issues/2488

**Comment by damip** [comment]
Basically after running a few times, smart contracts start crashing with:
```
massa_execution_worker::execution: failed executing async message: Runtime error: async message runtime execution error: Insufficient resources: Failed to create memory: Error when allocating memory: Invalid argument (os error 22)
```

note: there is plenty of available host memory
