### ISSUE TITLE
Create a dedicated Massa status page

### ISSUE THREAD

**Issue by aoudiamoncef** [massalabs/massa#2490]
Between two tests phases, there is people who tries to join Massa network and/reward program. It could be interesting to create a dedicated status page for testnet

![Screenshot_20220404-093033.jpg](https://user-images.githubusercontent.com/22281426/161494996-b356d95b-472c-4fa7-9900-cecd1a1d3636.jpg)

Please see [Solana](https://status.solana.com/)

**Comment by damip** [comment]
We already have one :) we just forgot to set it up. 

Done: https://test.massa.net/#explorer
