### ISSUE TITLE
Improve return message when failed bootstrap 

### ISSUE THREAD

**Issue by AurelienFT** [massalabs/massa#2508]
Bootstrap is the only step where people without technical knowledge read the logs and cares about it but it's also the step where there is less explicit logs.

We should always return in the socket a reason why we close it during bootstrap/connection to bootstrap and print it in the client. So that the people understand better why they can't bootstrap and also if there is no message we can consider it as a bug from us.

**Comment by damip** [comment]
Also, the server should try to send a reason of the failure (with a short timeout like 200 milliseconds)  before closing the connection. This is not a breaking change: non-updated nodes will just complain about an invalid message before closing, and updated nodes will be able to display the reason

**Comment by aoudiamoncef** [comment]
We could extend this to `massa-client` which throw a generic error message when `massa-node` is not available.
