### ISSUE TITLE
Graph: return error on indices mismatch

### ISSUE THREAD

**Issue by gterzian** [massalabs/massa#2511]
In the graph, we use a bunch of indices, presumably to speed up search operations. 

For example, the `active_index`:

https://github.com/massalabs/massa/blob/bc01f8cb936ba23b042263cf04a3f5246ace27d1/massa-graph/src/block_graph.rs#L291

However, when using the index, in this case of fetch an active block, we ignore cases where the index and the actual thing that is indexed are out of sync. 

For example:

https://github.com/massalabs/massa/blob/bc01f8cb936ba23b042263cf04a3f5246ace27d1/massa-graph/src/block_graph.rs#L1175

Logically, if we have a block id in `active_index`, then a call to `self.block_statuses.get(b_id)` should return `Some(BlockStatus::Active(active_block))`, otherwise the index is somehow out of sync. 

To improve our ability to debug the code, we should explicitly fail in these cases, instead of silently ignoring the `None` case.

**Comment by damip** [comment]
This is redundant with https://github.com/massalabs/massa/issues/4018
