### ISSUE TITLE
Problem with arguments order?

### ISSUE THREAD

**Issue by Vadiml1024** [massalabs/massa#2518]
https://github.com/massalabs/massa/blob/040cb8d92cf31731be967ee8212c74c8c17a15b4/massa-execution-worker/src/execution.rs#L423

I'm really not a Rust guru but it seems to me that arguments of pattern match statement, do not corresponds
to the structure of **OperationType::CallSC**

**Comment by damip** [comment]
@Vadiml1024  pattern matching for structures in rust is based on name, not order :)
