### ISSUE TITLE
Improve connected nodes informations

### ISSUE THREAD

**Issue by AurelienFT** [massalabs/massa#2520]
In the `get_status`, we can't see if a connected peers is in a out or in connection.

We could add this information to have something like : 
```
Node's ID: xxxxxx / IP address: 000.000.000.00 / Out connection
Node's ID: xxxxxx / IP address: 000.000.000.00 / In connection
```

**Comment by aoudiamoncef** [comment]
Hi @AurelienFT,

I tried to find how could we get connection type, but it seems little bit trickier(for someone external). 


```rust
/// All information concerning a peer is here
#[derive(Clone, Copy, Serialize, Deserialize, Debug)]
pub struct PeerInfo {
  ....
    #[serde(default = "usize::default")]
    pub active_out_connection_attempts: usize,
    /// Current number of active out connections with that peer.
    /// Isn't dump into peer file.
    #[serde(default = "usize::default")]
    pub active_out_connections: usize,
    /// Current number of active in connections with that peer.
    /// Isn't dump into peer file.
    #[serde(default = "usize::default")]
    pub active_in_connections: usize,
}
```
How could we get this information ?

Thanks

**Comment by AurelienFT** [comment]
I'm not very familiar with this part of the code but I think you can check if `active_out_connections` or `active_in_connections` is positive is a good check. I think you should make some tests but it could be a solution.

**Comment by damip** [comment]
@aoudiamoncef basically here:

https://github.com/massalabs/massa/blob/main/massa-api/src/public.rs#L278

the `_` is a boolean telling us whether the  connection is outgoing (true) or incoming (false)

**Comment by aoudiamoncef** [comment]
@damip I was a little bit confusing:

```rust
...
    /// corresponding nodes (true if active)
    pub active_nodes: Vec<(NodeId, bool)>,
```

The documentation is wrong ?
