### ISSUE TITLE
Node crash without reason

### ISSUE THREAD

**Issue by JeromeSi** [massalabs/massa#2521]
The node work fin 2 hours and suddenly crash

- OS: Ubuntu 20.04 in Docker
- XPS 8940 i7-11700 / 32Gb
And the logs
[nohup.out.tar.gz](https://github.com/massalabs/massa/files/8456706/nohup.out.tar.gz)

**Comment by JeromeSi** [comment]
And after I don't have implicit role sale... at this moment
Production stats:
	 produced 0 and failed 0 at cycle 65 (final)
	 produced 35 and failed 0 at cycle 66 (final)
	 produced 21 and failed 0 at cycle 67 (final)
	 produced 0 and failed 19 at cycle 68 (final)
	 produced 16 and failed 5 at cycle 69 (final)
	 produced 6 and failed 0 at cycle 70 (non-final)

**Comment by JeromeSi** [comment]
address 2hST5GgbAMAHvUe9JK3MDidt9ppPPMMViTRoN6ZMBYi2mjn34A is subject to an implicit roll sale at cycle 71. Check the stability of your node/connection to avoid further misses, then buy rolls again.

**Comment by damip** [comment]
should be corrected, closing for now, feel free to reopen if the problem reappears
