### ISSUE TITLE
get_status command error

### ISSUE THREAD

**Issue by ZeBobo5** [massalabs/massa#2523]
Tested after a period, the get_status command is in timeout error while my node is running well

✔ command · get_status
Error: check if your node is running: Client error: timeout during get_status: deadline has elapsed
✔ command · get_addresses 27GeuRmcuN41jJ8LVdrZYzXmKhunEg5QTir9Jb4rYRMJ6aEwQQ
Address: 27GeuRmcuN41jJ8LVdrZYzXmKhunEg5QTir9Jb4rYRMJ6aEwQQ
Thread: 18
Sequential balance:
        Final balance: 67.78
        Candidate balance: 67.90
        Locked balance: 0

Final Parallel balance:
        Balance: 0

Candidate Parallel balance:
        Balance: 0

Rolls:
        Active rolls: 3
        Final rolls: 0
        Candidate rolls: 0

Block draws:

Endorsement draws:

Blocks created:
    2QzCidVjeciVqZe3WspnePqo6pR1rqXtzUxWqNbsLBk87JCvnq    gG2M31opaqimiEGtjqN8YdtFfQRcSFfVJ2Za5V6yPmjS7KCbL
Involved in endorsements:
    26PKR8iWXmaxPnZkSQpyq2gSVVc2ZAjPvCw6ybwq3HCzGDx7sx    2gfoW3EpS1VphJMRafzuBwW2Bw9ezT5iL2teZWeWZcx71MABJQ    24AwqLQ9kkd5HHpDRrpSahAeCLBeAa5XiqupFrUJsjgA8vZPRS    25SJ2hL9k8RisRwg2Eab7PtLnoF6uKGhKTQ3NN5SMYKGRE7vmk    dTSEoD2tyCkhKiuFnt1mjrk8ZaWTrh37fpK1WVuqgYfQjss8h    mzHSYbVRnAFdjesZobZC52i4JyDeygWuLFaYzjBxMrxZxSW6y    2P6SfQeq8jNyrkcjtrEJJaJLQmtmmXverEnBBJqP2GytQkvnxy    2PrjVE897iqmPtnsUfv6NDGNydaxkLvciJVbECUsatQTqF53wx    ZFceV13qH495H2Yj6yfKMmTzEEDiyXvkAfJRdtBd1sGSsJkgC
Involved in operations:

Production stats:
         produced 0 and failed 0 at cycle 153 (final)
         produced 0 and failed 1 at cycle 154 (final)
         produced 0 and failed 4 at cycle 155 (final)
         produced 4 and failed 0 at cycle 156 (final)
         produced 2 and failed 0 at cycle 157 (non-final)

**Comment by AurelienFT** [comment]
Do you have the logs of your node when you made this client command ?

**Comment by damip** [comment]
closing for now, let's see if it happens again after testnet14 chnges
