### ISSUE TITLE
Send network event failed An error occurred during channel communication: Failed to send event.

### ISSUE THREAD

**Issue by moonshot211** [massalabs/massa#2525]
Description: 

This message is displayed once the node is launched after a few hours and is spammed until the node stops working. I noticed that as soon as this message appears, all the blocks are missed. It is only since version 9.0/9.1 that this message is displayed. My node can't run for more than 6 hours.

- Device: VPS
- OS: Ubuntu
- Version: Massa 9.1

Logs:
[logs.txt](https://github.com/massalabs/massa/files/8466173/logs.txt)
![Error event](https://user-images.githubusercontent.com/103446567/162790248-bd58696b-8244-40c4-9b6f-3e085155c142.PNG)

**Comment by damip** [comment]
can you try with TEST.9.2 ?

**Comment by moonshot211** [comment]
I updated to 9.2 but the error still persists

**Comment by AurelienFT** [comment]
We are seeing this type of message anymore. We fixed it in previous testnets. Thanks for your reporting. I close this
