### ISSUE TITLE
Unify pool and protocol checked operations pruning

### ISSUE THREAD

**Issue by gterzian** [massalabs/massa#2531]
Currently:

- Protocol adds ids to [`checked_operations`](https://github.com/massalabs/massa/blob/ad0d81d5b69b523012eb136959efc24a40b6334f/massa-protocol-worker/src/protocol_worker.rs#L519) in response to receiving a propagate message from pool
- Protocol prunes [`checked_operations`](https://github.com/massalabs/massa/blob/ad0d81d5b69b523012eb136959efc24a40b6334f/massa-protocol-worker/src/protocol_worker.rs#L954) according to a setting.
- Operation pool prunes itself.

Instead of having two separate pruning logic, operation could simply send a list of pruned operations in a message to protocol, who could then prune `checked_operation` according.

**Comment by aoudiamoncef** [comment]
@AurelienFT, have any updates about this issue ?

**Comment by AurelienFT** [comment]
I don't understand what you mean by "update" in this context. I think this issue should wait the network refactor to be merged before. It may not conflict but it's not sure.

**Comment by damip** [comment]
I think that the pruning logic in the pool (remove least fknancially attractive operations to optimize block reward) should remain independent from the protocol cache pruning logic (keep recently announced operation hashes to prevent network bounces)
