### ISSUE TITLE
Crash Node 

### ISSUE THREAD

**Issue by Gui051** [massalabs/massa#2533]
**Describe the bug**
Ubuntu 20.04LTS, 6 cores, 8 GB ram, internet with fiber
Hi, second time node crash without reason, like a killer processus (Ctrl+C), no "warn" before.
On screenshot we can see restart... 
Thx for looking and go Massa :)

![unknown](https://user-images.githubusercontent.com/103699228/163489883-0500f9d1-513f-4027-bf9b-a39d78ac9756.png)

**Comment by Gui051** [comment]
Same issue today when i start firefox. Perhaps not enough ram...

**Comment by damip** [comment]
Looks like we have a rare memory leak

**Comment by Max17777** [comment]
Hello developers! The case with memory is not so frequent, but it is not rare either. I also encountered a memory leak. I tried to solve the problem using the "htop" utility and the "kill" command to close the hung processes in memory. This method helps, but after the kill command, the node turns off, you have to re-register the bootstrap knife list and restart the node. Or I'm doing something wrong. On my own, I will add that despite the problem found, the node works much more stable. I noticed that the leak is less if, after working with the node, I turn off the terminal, and do not leave it open in standby mode for several days. P. S. Tell me, in what season do you plan to increase the load to 10,000 transactions?)

**Comment by Max17777** [comment]
Hello everyone. I will add my review. I found a way to gently remove the memory leak without stopping the node. You need to go to htop and select a memory-consuming process. Then send a SIGQUIT signal to this process, as a result of which the node does not fall, but gently restarts without going into bootstrap🙂

**Comment by damip** [comment]
Recent changes should have corrected this. Will close if we confirm it's OK during testnet 12
