### ISSUE TITLE
Improve test coverage of operations propagation

### ISSUE THREAD

**Issue by gterzian** [massalabs/massa#2534]
I'm surprised the changes at https://github.com/massalabs/massa/pull/2527 didn't break any tests, and I think we should improve coverage.

**Comment by AurelienFT** [comment]
@gterzian Do you think the tests are now enough ?

**Comment by AurelienFT** [comment]
In the lasts months and especially with the network refactoring all the tests regarding operations propagations has been greatly improved and without new comments since few months, I close this.
