### ISSUE TITLE
'main' panicked at 'consensus shutdown failed: GraphError(MissingBlock)'

### ISSUE THREAD

**Issue by arhuman** [massalabs/massa#2535]
Since few days after the episode start, my node keep crashing.
 
All I have to do to reproduce, is launch node, buy rolls and wait.

My node (compiled TEST.9.2) is running on Ubuntu 20.04.4 LTS
The server specs are:
_ 10 cores Intel(R) Xeon(R) CPU E5-2630 v4 @ 2.20GHz
_  256GB RAM

Please find attached an extract (last 1000 lines) of the logs.
I have more log (50G) available upon request

**Comment by arhuman** [comment]
[small_log_extract.txt](https://github.com/massalabs/massa/files/8494956/small_log_extract.txt)

**Comment by arhuman** [comment]
[2m2022-04-15T07:52:14.305213Z[0m [34mDEBUG[0m [2mmassa_network_worker::node_worker[0m[2m:[0m Failed to send NodeEvent due to timeout: NodeEvent(87zgw9CcPhFAPdNFuqgKwpquvYYkZfu5DYtSMzpyVCgMBXp6Hp, ReceivedEndorsements([Signed { content: Endorsement { sender_public_key: PublicKey(PublicKey(60ee80e0bbd83de8d14deb0acc3c2ce9991bb3e305b920c31f4d5efb62bda29edfcc4ea301a19272c7eefbad23ca6934704ad2e544aad4fe552386abc50100a9)), slot: Slot { period: 40695, thread: 27 }, index: 1, endorsed_block: DhDnRqJADfb5x9NWLUKnuA8sesiJdYQQ7e84RZ54zt2huY2zB }, signature: Signature(30440220359f2fbaa029af586cadbd064b213695649e3c404348d4f90452b758b4992af102204f36bec739f938ff26a7b2ac80a98680689bb8ff7b17f30d32e68ede5b6420f6), phantom: PhantomData }])).
[2m2022-04-15T07:52:14.307762Z[0m [34mDEBUG[0m [2mmassa_network_worker::node_worker[0m[2m:[0m Failed to send NodeEvent due to timeout: NodeEvent(7GFRd82oA38mV75PJRuYmmqo2tZByqpCpNVM6vHdoejRDdruag, ReceivedOperationAnnouncements({1GBrwrdLhiUVgFwcLctBfHQUHDKeDGpswno75bX4j4CuagPiG, 2qWcZVCqHqmUWyok18P945nejAPKaUPX5oRKm2PBkb9dVFoh5J, 2mqbPdNd5RiRf38PyPHf79nHaGtHZAZNNdYepX5bNywmGsboQF, a74oC3RKvztA6nj3MMK9iPZuECPvzF4yPZHKjUYzBRrr4Kp6z, 2KVpgnWx2m6C43sUkdbeuzeQjkR8zG9yGZ1usd9RAd18a8sJWZ, TKauLeEX9MJgGjMZGUDQfP4o78SUPcqwiHjBNoxTAMtJgCwut, 2gt7WDmDw4ViuNjDcoVGTy4Gmcs3o5GX7P2cQs9T62Mgvtjzaj, zyWK8drJM3hnGNgbZrft4N5AnW46Px8c4632x4SSCPgJw2gtZ, NNeSjaWVHV8CUJFZ6MYdpb1i6cXoBi6bDJ5hrFfXxL8oQnacw, 2MqUVscPJGgbGDC8EDaf5y9vHGGSk93f7ufH4ThoF3YM4mwQ5f, 6hKw8ZP3177YkD24g1AMkRgbinmkGv861JxXm2RU1E661jorP, 2vezdix79V1qL22vGEgeNJXdhdwBCUCWjLyzm6xyxMMxpPYqQ1, 2Gnwe33Xc5WN2tq2SjvaYmXd2pFqgtauRnWGKRpBMovUzfXske, d9aPaJmwL2sgpGWbYA9Lj4ywJEj2xG2fmAWd1FvfTNw8UTbwS, FRuk8siZwtCxEDv3VP7LZgcE6Wa4sbBtM3jZkDvh6Z5tsnyMj, 2Vm9AatTo4FEruYzAcGG7xA8oLvrLoo92BhNnqRiThkotMW9Wg, 7PTTCgLQH5DK5xCJkb3ZhAGWHaB2iWUjCZbeyg2ppjNAUyLrY, 2oEm15zG5Jg7pTzPtqsBegKdYa8ssqiYouZb6TMtGTYJiqWqMx, 2WYrMLRPFGyGxNMa8WdSNGUHyrH7aM8jdQTF7gKsH2K5TDYUi, VtZyAyC9BSXr6hc5LPKkNy46xrwf6BVzmw8mGxA1jq5rt8P5E, NPF3JW8PWRqdJDNJgTzHaHRd7QWSYrWRhuet5GjQP1YS3bRgw, 2tBbH5U4i1JndVHJU48iabXRm6BdrkVugFRsCig6s6wxX4gUhL, SbnqDT3ggSUJsyU5KDPxd6LiS2PwsoyvTTMEBAe2ZfgCQqQ45, obqbStYhDmDm6yot5WX4Q55RMubpyHLF9ft1GWiopaTDR6vR2, KTF1ys7BR7nATPctmFygAMnDgTepjSadVh1BJP38KnWiJ4Skx, mevsPk4kMqqnbFjDQVyC7pWXjvsoEJkEPAjmQs9tkPRqMxboU, 28FyyViUwSeCAgWMpLQHgfiwpiTdgEwivAKKbdL39FJBCj9Bp6, xPkjDgMUehUhWmbXRw1fthv18pwq2AtYF4RNyYz3HWmWvsp1a, WYka31fsswz9dCe79NvkLThx5Gv6ciE53WV7TGCQHXCuavgb9, rx6D34kzkHh3dCzHzR8vCPAEnRY7i6amvRnkCC9UCoaZBKrUP, ENmqQwEV8erZoYP6ka8292PZXbD4MyCzDR2GxAU3efnqxEDX9, Sobszv9VxrU6jXpEtaCZC61WYQDseHdM5GyGsZEqkpWjqgDMc, 2iubpXEyHBUCMQdDxvquUPnZXvP4edDvhxBgkWMZNyMkSQUtei, 5UQqRXW316PginMazYDioFTmTHCrzq7tUySDUrzSTiBqvWTNk, 9iTm6sJHJJYx5376ntNPYjWj5CKG3rtjDfFJwCi1B1bF1zF3j, xVf9JkPML23P7PhXsDLT1r6MnrKdZ21ua5cYPWGu8YWpi9w1R, vJ9Ba9fSNtqs5RLZyokQA5LWwJLctzGT8L5mRt8u3ESLDxsuN, 22sQZ89NTyTGFKMcf72EfBr7MSCxQ2UfT445LfVNRri6gF9vEx, 2o3cXWkmRzLRE61sUiQUkMy9rxzv8XZ7aPQ4GZ87stRLoqqQz9, VTnemgohb1PvdmfDCoW25tWqXjZQxv42L1VezGQMkTm2Rssfh, 7vLgiV6ZnXbY5wQTHf2d3gNUQ1yQenEk9WMF37E9PQETa9sVU, 2dR4EE8KaiD73eYXYUnrotazMSzd7KW22zUvAShvMhHfyvdSpC, 2c2gkGareG4xrzyEvvm7TXXb4zvAuGXF3xPEPfgSDLeks8UrFj, PoAJarCjdqA3kM2h99ttR1PoidGUED85L5sv56wSMCxXLFkwB, 2kffr9pAc5EBn4ZRfr1c35qmyZCoQPYzz3SFARJQ9yL2CGi94n, 2kZJgQnJQAWgMV3zWt58yqWQx7baRpYdJ4AAJooE6cfB4vrwPN, 2R5PwKzj4m6fJQtFGeyKc59GfS2HAW3nDQH189UVVGxXWzyVJL, 2vXM4yaHWrPx9LLzFN4EhgUUY18kWzY8mz5iDiF4Queuxt48e7, 63a1aLuAYu9jsbp3q6or5de1VyKxFodzQzNzaWdZ6Erxs7tji, apBjfarHFhdeB3EtECLJi5j5Q2nV32JarTeg9VxTL5SoddGq6, 219nyyzcbpCSrb9WeGb1NPHFrLTMJLtXhxPAziv5iAaTyVBRcN, 2FRPqi9uYyNzJ3avznRWMGhm5RHndg3RdY2WcR33LX3b6JGYv8, aTQj9n5YnwySy8XJmkUiMzfpiEFz7rBn4kYww8TT34xJrTpNL, 2U7hPN2Ngoebabh5FUTWw1cQ4ZD1jwvdZ26chrsA3eQGzB2vuY, 2qBWQSLTGBbeyW3rXRfSJ1ZSdpjpbdsyLVdFfCqMpRGjyoUjXa, rZ4ff39kBZ6ybzjorQ8URabkhDUeJeQZ5LhktkahVR7EVqXBr, 2QMG48SiwD7YTddP9FKaxExcxWkP3sUtvTKRXpkbm6YJ85kTkC, 27DtCYZAL3EyEwHCvGCM2kBnqTEpGsdarHQWWZ7JQPmkQ6r4ua, 4pF36Jkvy7fZrYa4xTPWTHJ4fjYiHUz9FeaEGAjWy9HQLacwi, iXSFV1GfRuRjGdjaQm1XW3oATEYG4EZX3sb3HcrD4mvARmLX7, 2rAQn9BbmzH4nJMZvPsYHZhrw55V6DD4FsbLtbHaymyyDpHkVC, 2Eribzr42ti8hRmx2mBmeTxvsQzQv6defFJNHzDy3QSE6yWnXW, 2AhBkRPoWNazJat5h6WbzYuqPiYCPXyvLi6Mbc2pxBRxqMnaT9, moKAEVZp1EoT2ENcX9de9BXerrU8tUjD4mQkayQorPoCCJtfH, 3ywLhzQdYokWv2bqHi7sQjX9DHCXRYYTmJKSrpHcWkDXpSwpJ, iFk4xWEd5sDxZTRK7EsUCXigzgXndDwFoqh9jxMJBmh2xZfBD, 2QhppPqRB13TimycjpmcCnVEWTfkcAaJdrTDwhN6EzfY7Z7x2o, Fgu1oCcwoREV7theym1Uz6cobSXDqVQLDuDL8GUgfNoBkToFm, YRRNrz4KqAsSRFVDFV41k1zVtfD1d7vhFKe2TRv5nyyuewkrY, K4QhxceJTukh76U4zyMMmyg3gpKMy3ETnPcdTWjdSo9qD7Aua, WqB5uB8dYiwAnvBg9WTsbLtpkEyDTE6U6wse1SAZuKDYCyRKe, 2aaxTmS2vP1jzi6XS6EHAGyzwSNKQEX6brgGgj6EjTeF287Jd3, 2jGbqDVkCQFLJFNh3KKE8zuctzBakZfTHUTwPowcxnnXQoZrKE, 28ZBwQ5tqtpdbRS96a6Kdd5Au66HTkv8ARWrFgWsKz7H8EK5fY, v1bxjJCDvhupaBCfackgfHRM6MbWo9LfeucKFtSa6jWk4tXfD, xp5v7FCz9oh1Pg49P6LkTrTRSJXqDhruTEeJ896APeST55NwR, 2HBCPcJS9NrXUJ4TpZPXV76686Y7RvpWodiho2sHeERVZZXfWR, 2ssB3SH79dD6hwb4UWDKXqXvK2aWfJEH2YspdYS8j2UDBRACYk, 2UJqYxvpy5ooFMvCtSPoM3SB1aY3DvhLQbJctTXxw5qVM49SSE, GJ4k8UC7Y4bmvHHnd7ryTmzupYXoNRupwAWyGa6otukcaHtwH, p1TZro5wGSBtZL4vvfRN4badCt6mKsprAi1p4htHbt2aBPCQo, J72hJCQimXDdoXeNhUFGP64PnHDzbYpRZ7vg9eh4JzNb77tG1, 275scWrfisqeZBwyougLp3HXGv8NCXVUJysab6ZWGMqkaazcYk, sCsAwdfyA8tJUNAvdBegJ2aezfS5Y5LNsfeFJs3DaehDcj9Py, d4sFe63kkhrgq8bffUW1MddKeNc2DExkWLJ5C5Xeh4tj85Ssr, bRGXotgonZL4yPdqJeBezk4oyzEFTYFBTHAFTU5bkGXKGe9Xw, 2sbZe7aTVFH2ExPr1zCjeZNsnJs8etdL3vURJYi9UdRXgWmve5, 226WbyNdHYQR9qp7KhGbXbx87hpye9a5Hh8ktP2JJhPRVLCthU, DZSia1ocDWKfpTcRLzgH3foH6j9aNr5pSdLT1tfTKUsy1HcFj, VCr6MEmpjHygPYDJdgYPrXRUPpW23rZwPaMnTkKUFr9FjRRB8, 2GxsLkq6DF8S7bDtXEtb2CeJcfwkyi6o67w1fUWg6N69BbYXti, Q81MQtKdJwJSecuapfH6xngaFeciS1TNNnE2dPvYAQV8JHPuK, 2W7i6frAyJvCdRYi8VatCtHU9xHhvnNuX4Q3oMLDvdcirLj144, 2vB3RiWmQDJX7PS2vpUq8hHxjsS1vvhpFMHe3UvmCK934HmqeM, 2u9CHDPK5fcsA1NCB5E6VYLJVbDoe3mCFS5XtMQZU1nacgCUpo, 2jHeyyptEnDfBS1ZhfkDqcjtGbFjzjfBaeHzuhAbb6GD5o7b13, 2KkerFPX3YoxMQMDbim3wq4CKh9CygzqRrAUCR6TUY7X9gUosE, 2iAYr3orCrMTqGEG6UQmdde8d2jT73x9U7WcCJZeNtrcDg8dEG, 2rZveXWYTeooavsPHWBUHnf7PkU2NDnR175JHVgVi3VBRTeVK2, a8WYtLVKotmJkYm5A4sZvxQkujcAavveLShHhVQ9krtS4m9pd})).
[2m2022-04-15T07:52:14.309863Z[0m [34mDEBUG[0m [2mmassa_network_worker::node_worker[0m[2m:[0m Failed to send NodeEvent due to timeout: NodeEvent(7GFRd82oA38mV75PJRuYmmqo2tZByqpCpNVM6vHdoejRDdruag, ReceivedEndorsements([Signed { content: Endorsement { sender_public_key: PublicKey(PublicKey(60ee80e0bbd83de8d14deb0acc3c2ce9991bb3e305b920c31f4d5efb62bda29edfcc4ea301a19272c7eefbad23ca6934704ad2e544aad4fe552386abc50100a9)), slot: Slot { period: 40695, thread: 27 }, index: 1, endorsed_block: DhDnRqJADfb5x9NWLUKnuA8sesiJdYQQ7e84RZ54zt2huY2zB }, signature: Signature(30440220359f2fbaa029af586cadbd064b213695649e3c404348d4f90452b758b4992af102204f36bec739f938ff26a7b2ac80a98680689bb8ff7b17f30d32e68ede5b6420f6), phantom: PhantomData }])).
[2m2022-04-15T07:52:14.311100Z[0m [34mDEBUG[0m [2mmassa_network_worker::node_worker[0m[2m:[0m Failed to send NodeEvent due to timeout: NodeEvent(5zRyerpUbWaSxj8b1e2xtdCSwbGiGCYyTycdaHPEo1bfZNH9yR, ReceivedEndorsements([Signed { content: Endorsement { sender_public_key: PublicKey(PublicKey(60ee80e0bbd83de8d14deb0acc3c2ce9991bb3e305b920c31f4d5efb62bda29edfcc4ea301a19272c7eefbad23ca6934704ad2e544aad4fe552386abc50100a9)), slot: Slot { period: 40695, thread: 27 }, index: 1, endorsed_block: DhDnRqJADfb5x9NWLUKnuA8sesiJdYQQ7e84RZ54zt2huY2zB }, signature: Signature(30440220359f2fbaa029af586cadbd064b213695649e3c404348d4f90452b758b4992af102204f36bec739f938ff26a7b2ac80a98680689bb8ff7b17f30d32e68ede5b6420f6), phantom: PhantomData }])).
[2m2022-04-15T07:52:14.314624Z[0m [31mERROR[0m [2mmassa_consensus_worker::tools[0m[2m:[0m consensus worker crashed: Graph error: missing block
thread 'main' panicked at 'consensus shutdown failed: GraphError(MissingBlock)', massa-node/src/main.rs:292:10
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
[2m2022-04-15T07:52:14.340526Z[0m [31mERROR[0m [2mmassa_protocol_worker::protocol_worker[0m[2m:[0m protocol worker crashed: An error occurred during channel communication: ask for block node command send failed
[2m2022-04-15T07:52:14.743168Z[0m [32m INFO[0m [2mmassa_pool::pool_controller[0m[2m:[0m pool worker finished cleanly

**Comment by AurelienFT** [comment]
Can you send the logs just before the all the `Failed to send` ?

**Comment by arhuman** [comment]
[small_logs_failed.txt](https://github.com/massalabs/massa/files/8509754/small_logs_failed.txt)

**Comment by damip** [comment]
should not happen anymore with the new storage system in v14. Closing for now
