### ISSUE TITLE
Possible memory leak

### ISSUE THREAD

**Issue by vladimirdotk** [massalabs/massa#2536]
Some people in telegram chats reported about high memory consumption (even more than 8-10GB) that grows over time in 9-th episode.
Here are 2 screenshots of running htop on the same node. Difference between them is about 1,5 hours.
Nothing strange in logs, just a couple of `INFO massa_network_worker::network_event::event_impl: Send network event failed An error occurred during channel communication: Failed to send event.`

What else could I provide to help in bug finding?

![scr1](https://user-images.githubusercontent.com/8599007/163596043-ccea135e-80e5-4992-8a32-f29fc64b98d5.jpg)
<img width="969" alt="scr2" src="https://user-images.githubusercontent.com/8599007/163596054-34d6088d-441c-4f51-9711-02b2e224fd6d.png">

**Comment by AurelienFT** [comment]
Maybe related to #2533

**Comment by damip** [comment]
should be corrected now
