### ISSUE TITLE
Fix massa_logging deps

### ISSUE THREAD

**Issue by gterzian** [massalabs/massa#2543]
Using `massa_logging` requires adding `serde_json` and `tracing` separately to cargo(see for example https://github.com/massalabs/massa/pull/2538/commits/5791032f3076271a2fe21591602daa9ae549a8c8, which was necessary for the change to compile). 

It would seem to me that those dependency should be self-contained in the logging crate.

**Comment by AurelienFT** [comment]
Done in https://github.com/massalabs/massa/pull/3921 by @Ben-PH
