### ISSUE TITLE
Analysis of RAM usage

### ISSUE THREAD

**Issue by sebastien-forestier** [massalabs/massa#2553]
Here is a tentative analysis of what's taking so much RAM after a few days running the node, with abrupts increase and decreases in RAM.
Usually, the RAM usage is around 2GB, with small and big "random" increments up to 8GB and sometimes but not always, decrements back to ~2GB.

Here is the last 2 days on my node, gray curve is the RAM usage:
![ram](https://user-images.githubusercontent.com/11048486/164190069-ce5562fc-6b86-48f8-9444-84957acdf794.png)

During this time I launched [heaptrack](https://github.com/KDE/heaptrack) with
```
heaptrack --pid $(pidof massa-node)
heaptrack_print heaptrack.massa-node.3640803.gz --flamegraph-cost-type peak -F peak.txt
./flamegraph.pl --title "heaptrack: peak" --colors mem --countname allocations < peak.txt > heaptrack.peak.svg
```
`./flamegraph.pl` comes from [here](https://github.com/brendangregg/FlameGraph), but you can also use `heaptrack_gui` instead of print+flamegraph.

Here is the result:
![heaptrack peak](https://user-images.githubusercontent.com/11048486/164191162-8c03a68e-986a-4c7d-91d0-279ebcee40f4.svg)
You can open it with `firefox heaptrack.peak.svg` to be able to zoom etc.

If I understand well, it shows the memory usage at the peak of 4.5GB.
So it seems too much RAM is allocated in https://github.com/massalabs/massa/blob/main/massa-protocol-worker/src/node_info.rs#L133

**Comment by AurelienFT** [comment]
@gterzian is working a lot on improving the operations system. I think his thought on that would be nice to hear !

**Comment by damip** [comment]
Note: currently we have `max_known_ops_size = 10024`

**Comment by gterzian** [comment]
The function at the top of the graph corresponds to [`reserve_rehash`](https://github.com/rust-lang/hashbrown/blob/21bfd9aff79ebcfec29143a14b18d8c7bb2bac5c/src/raw/mod.rs#L676) in the std. 

In the current code, once `max_known_ops_size` has been reached, the new operation is first inserted, and then the oldest one removed. Since at that point the capacity of the set has been reached, it will re-allocate. 

The fix I propose in https://github.com/massalabs/massa/pull/2556 is to do the removal before the insertion, keeping capacity constant and therefore avoiding allocations.

**Comment by qdrn** [comment]
Reducing `max_known_ops_size` seemed to reduce the RAM usage on my node. I think we set it purposely very high during the debug of the operation propagation and forgot to reduce it afterwards.

**Comment by damip** [comment]
here is a proposal: https://github.com/massalabs/massa/pull/2558

**Comment by gterzian** [comment]
> Reducing max_known_ops_size seemed to reduce the RAM usage on my node.

Does the memory usage still jump sometimes? The current problem seems to be that we would still add one element to the set when capacity had been reached, which would result in a re-allocation for a higher capacity(I think it doubles each time). 

So yes reducing the initial capacity, by reducing `max_known_ops_size`, should reduce memory usage, although not fix the problem.

**Comment by AurelienFT** [comment]
The RAM usage is now stable even with some thousands txps. It still uses too much 4GO for 2k5 txps an issue exists for that : #3142. Closing this.
