### ISSUE TITLE
The keyboard shortcuts don't work on CLI

### ISSUE THREAD

**Issue by AurelienFT** [massalabs/massa#2571]
When we want to fast forward on left or right in a command in most of CLI we can use keyboard shortcuts that are faster than arrows. This shortcuts don't work on the client it would be nice to implement them.

**Comment by aoudiamoncef** [comment]
Hi, 

[Rustyline](https://github.com/kkawakam/rustyline) could helps

**Comment by AurelienFT** [comment]
Done in https://github.com/mitsuhiko/dialoguer/pull/231
