### ISSUE TITLE
Memoize signature verification

### ISSUE THREAD

**Issue by sebastien-forestier** [massalabs/massa#2583]
Right now (at 2000tx/s), the signature verification takes about 50% of cpu time, but each op sig is verified twice:
- once in the operation pool,
- once when we verify a new block.

We still need to check the hash twice, but we can memoize the signature verification, e.g. with a cache of 1 million items, which we completely clear when it's full, or a cache that we clear each X minutes.

**Comment by damip** [comment]
My bad, it is already cached ! (uses note_operations_from_node)
