### ISSUE TITLE
Reduce operation id size

### ISSUE THREAD

**Issue by sebastien-forestier** [massalabs/massa#2584]
To reduce RAM, bandwidth and maybe some cpu, one little thing we can do is to reduce the size of the id of operations.
Right now it's 256 bits, but we probably don't need the same security level as for instance signature verification, maybe 64 or 128 bits is enough.

Several points to figure out :
- What are the consequences of an op id collision in the code ? 
- What can do an attacker with the power to find a collision ? Only censoring the propagation of a target op for some time ?
- How frequent a collision can be found by an attacker with X money to spend and with Y bits of security ?
- Does a 256 bits op id really takes 256 bits of bandwidth and RAM or is it encoded in a string format using more space ?

**Comment by sebastien-forestier** [comment]
It seems incompatible with https://github.com/massalabs/massa/issues/2583 : if an op in the pool is successfully verified and that result put in a cache like opid->valid, and then an attacker finds a collision and includes the new op with same opid in a block, this new op will not be verified, and this op can send money from any account to the attacker ...

**Comment by sebastien-forestier** [comment]
Proposal mainly to reduce bandwidth: use a short-lenght hash only when announcing opid to peers (and in the cache of received operations) but not in the other places (e.g. cache of verified operations).
This can be a parameter (not a config one), set to 8 bytes for now.

**Comment by damip** [comment]
Warning: Within the context of https://github.com/massalabs/massa/discussions/2706 this allows the following attack:
* I forge two operations Op1 and Op2 with the same hash prefix
* I propagate Op1 to one half of the network, and Op2 to the other half
* This results in half of the network having one op, and the other half having the other (propagation does not go further)
* I add Op1 to a block B I created
* An honest node H connected only to nodes having Op2 will not be able to retrieve the dependencies block B

**Comment by adrien-zinger** [comment]
I have a point about the implementation. In the initial algorithm, there is a case where we pass:

```py
    if not is_op_received(op_id):
```

I'm thinking about how should I do that check if I receive only a reduced operation id. I see some possibilities of replacement:
1. I check if I know almost one OperationId that correspond, it means that if there is a collision between the little ids, we can miss an Operation.
2. I replace that check with a probability check, for example it's almost impossible to have 3 equal sequences of 20 bytes, but two are acceptable.
3. I remove the check.
4. I enter a new phase where I ask for the full id and check if I know it or not.

**Comment by sebastien-forestier** [comment]
> * I check if I know almost one OperationId that correspond, it means that if there is a collision between the little ids, we can miss an Operation.

yes

> * I replace that check with a probability check, for example it's almost impossible to have 3 equal sequences of 20 bytes, but two are acceptable.

I don't know what you would do

> * I remove the check.

No, we would ask all operations to all peers, and use 25x more bandwidth

> * I enter a new phase where I ask for the full id and check if I know it or not.

I think the gain vs complexity is not worth

**Comment by sebastien-forestier** [comment]
> Warning: Within the context of #2706 (which also does a 50% reduction in bandwidth) this allows the following attack:

Yes, so in #2706 , when we ask/receive the block opid list, we should use 32 bytes, but we can still use a lower size for naked mempool ops.

Therefore I suggest to set
 `OPERATION_ID_PREFIX_SIZE_BYTES = 10` 
 because this does not need to be collision resistant, and it does not even need to be pre-image resistant in general, but pre-image resistant for attacks lasting at most 1sec with a probability >50%

**Comment by damip** [comment]
Two possible attacks:
- the attackers create 2 tx with the same prefix hash and send them to different nodes: the tx will not propagate well but this will only be a problem to the attackers themselves
- the attackers do a preimage attack on an existing tx (for long term recurring txs, the attackers can know their hash long in advance) : this will censor the transaction.

So we should always make sure that the prefix is pre-image resistant but not necessarily collision resistant

**Comment by damip** [comment]
After discussing with Sebastien, we have the following votes:
* Sebastien: 16 bytes
* Damir: 17 bytes

**Comment by sebastien-forestier** [comment]
Here is an easier way to compute the risk in terms of $ cost of censoring one transaction:

With 1 dollar of energy, we can get 60 MJ, and with 1J we can compute ~36GH with current sha256 asics, so with 1$ we can compute 2*10^61 sha256 hashes.
If we assume someone can build asics for blake3 64x faster than for sha256, they can compute 2^67 blake3 hashes for 1$ of energy (not including the cost of building asics). 
If we assume that second pre-image attacks can work, and the worst case of a 500kB message, then we loose 13 bits.

So 1$ of energy can compute 2^80 hashes.
If we want the attack to cost 50 b$ (excluding hardware), then we can use 116 bits.
So I guess we're fine with `OPERATION_ID_PREFIX_SIZE_BYTES = 15`, maybe lower if second pre-image attacks don't work because the transaction must be valid.

**Comment by damip** [comment]
done
