### ISSUE TITLE
Gitpod integration

### ISSUE THREAD

**Issue by aoudiamoncef** [massalabs/massa#2585]
IMHO it could be interesting to add [Gitpod](https://www.gitpod.io/docs/languages/rust). It'll make easier the process of contribution, specially small ones(50 hours peer month).

I'm waiting for feedback

**Comment by qdrn** [comment]
WDYT @AurelienFT @damip @Eitu33 ?

**Comment by aoudiamoncef** [comment]
As you know, building Massa projet in local machine is quite heavy and need to setup Rust toolchain.

With Gitpod integration, you have already a an IDE hosted in a remote server with project specific settings.

Just give a try, open my fork in Gitpod.

**Comment by Eitu33** [comment]
I understand the use cases and it seems like a useful tool, but I'm not a big fan of using this for this project seeing as the only setup requirement is the rust tool chain which can be installed on any OS with a one liner.

**Comment by aoudiamoncef** [comment]
It's not about complexity, it's about client side vs server side development. Gitpod or other server side IDE should setup Massa project requirements separately which is a waste of time(docker based IDE). This shared configuration in the main repository will make it easy. 

There is more and more opens source projects  which integrated Gitpod. Example [spring-cloud-aws](https://github.com/awspring/spring-cloud-aws)

**Comment by Eitu33** [comment]
I get your point but disagree with the "waste of time", I do not feel like building massa is neither long nor complex. It would be justified if the project requirements setup becomes too heavy, but It is one of our goal to keep it as simple a possible, and this simplicity shouldn't be achieved through a third party software IMHO.

**Comment by aoudiamoncef** [comment]
I understand your fear third party coupling, but this is not one, it's just a set of config files that makes life of server side IDE developer easier.  Believe me, I have a decent machine and building/compiling any Rust based project is a heavy task. This is why it's suitable to give contributors the possibility of using Gitpod or any other server side IDE. It's a nice to have, not a requirement* IMHO.

*It's a opiniated choice, so there is not a wrong or bad one.
