### ISSUE TITLE
Crash node on connection fails to bootstrap node

### ISSUE THREAD

**Issue by pgulyaev88** [massalabs/massa#2599]
Crash node on connection fails to bootstrap node.
NAME="Ubuntu"
VERSION="20.04.4 LTS (Focal Fossa)"
PRETTY_NAME="Ubuntu 20.04.4 LTS"
VERSION_ID="20.04"

`2022-05-06T12:55:03.229329Z  INFO massa_node: Node version : TEST.10.0
2022-05-06T12:55:03.229374Z  INFO massa_bootstrap: Start bootstrapping from 161.97.180.22:31245
thread 'main' panicked at 'critical error detected in the bootstrap process: io error: Connection refused (os error 111)', massa-node/src/main.rs:90:25
stack backtrace:
   0:     0x564bf2b2e95c - std::backtrace_rs::backtrace::libunwind::trace::h7c6a0b6bbcfb15e0
                               at /rustc/5d8767cb229b097fedb1dd4bd9420d463c37774f/library/std/src/../../backtrace/src/backtrace/libunwind.rs:93:5
   1:     0x564bf2b2e95c - std::backtrace_rs::backtrace::trace_unsynchronized::h738fa839c025d88e
                               at /rustc/5d8767cb229b097fedb1dd4bd9420d463c37774f/library/std/src/../../backtrace/src/backtrace/mod.rs:66:5
   2:     0x564bf2b2e95c - std::sys_common::backtrace::_print_fmt::h4f98563e03fd77a0
                               at /rustc/5d8767cb229b097fedb1dd4bd9420d463c37774f/library/std/src/sys_common/backtrace.rs:66:5
   3:     0x564bf2b2e95c - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::h4537eb61bdce6f6b
                               at /rustc/5d8767cb229b097fedb1dd4bd9420d463c37774f/library/std/src/sys_common/backtrace.rs:45:22
   4:     0x564bf2b5635c - core::fmt::write::he1e8f14e90f89497
                               at /rustc/5d8767cb229b097fedb1dd4bd9420d463c37774f/library/core/src/fmt/mod.rs:1190:17
   5:     0x564bf2b27588 - std::io::Write::write_fmt::ha9d438e87e29cf6e
                               at /rustc/5d8767cb229b097fedb1dd4bd9420d463c37774f/library/std/src/io/mod.rs:1657:15
   6:     0x564bf2b30e57 - std::sys_common::backtrace::_print::h587a4663357bac6f
                               at /rustc/5d8767cb229b097fedb1dd4bd9420d463c37774f/library/std/src/sys_common/backtrace.rs:48:5
   7:     0x564bf2b30e57 - std::sys_common::backtrace::print::h8dbaaebd1b6f9c35
                               at /rustc/5d8767cb229b097fedb1dd4bd9420d463c37774f/library/std/src/sys_common/backtrace.rs:35:9
   8:     0x564bf2b30e57 - std::panicking::default_hook::{{closure}}::h11ab986bd24269f7
                               at /rustc/5d8767cb229b097fedb1dd4bd9420d463c37774f/library/std/src/panicking.rs:295:22
   9:     0x564bf2b30b1f - std::panicking::default_hook::h23b7cddda18cff14
                               at /rustc/5d8767cb229b097fedb1dd4bd9420d463c37774f/library/std/src/panicking.rs:314:9
  10:     0x564bf2b315ba - std::panicking::rust_panic_with_hook::heed66b7b6ebf7046
                               at /rustc/5d8767cb229b097fedb1dd4bd9420d463c37774f/library/std/src/panicking.rs:698:17
  11:     0x564bf2b312a7 - std::panicking::begin_panic_handler::{{closure}}::h4a817fb4518b6940
                               at /rustc/5d8767cb229b097fedb1dd4bd9420d463c37774f/library/std/src/panicking.rs:588:13
  12:     0x564bf2b2ee04 - std::sys_common::backtrace::__rust_end_short_backtrace::hcbda452eda268a56
                               at /rustc/5d8767cb229b097fedb1dd4bd9420d463c37774f/library/std/src/sys_common/backtrace.rs:138:18
  13:     0x564bf2b30fa9 - rust_begin_unwind
                               at /rustc/5d8767cb229b097fedb1dd4bd9420d463c37774f/library/std/src/panicking.rs:584:5
  14:     0x564bf226b063 - core::panicking::panic_fmt::h4d140668741c6a4f
                               at /rustc/5d8767cb229b097fedb1dd4bd9420d463c37774f/library/core/src/panicking.rs:143:14
  15:     0x564bf2347610 - massa_node::launch::{{closure}}::h35abfd032349c31d
  16:     0x564bf23eacf0 - <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll::hcf08168a22571c23
  17:     0x564bf22b327b - tokio::park::thread::CachedParkThread::block_on::h3eabd188fea78886
  18:     0x564bf22ba71d - tokio::runtime::thread_pool::ThreadPool::block_on::hae3fa69d50a4581d
  19:     0x564bf229755b - tokio::runtime::Runtime::block_on::h591be0176649b1fe
  20:     0x564bf237b3d9 - massa_node::main::h8fc9412ec7a02ff6
  21:     0x564bf22b9d63 - std::sys_common::backtrace::__rust_begin_short_backtrace::hf6567f0b32ffc996
  22:     0x564bf22f80b9 - std::rt::lang_start::{{closure}}::hf28739b98de45cd9
  23:     0x564bf2b2e041 - core::ops::function::impls::<impl core::ops::function::FnOnce<A> for &F>::call_once::hcd21df63a0af83f8
                               at /rustc/5d8767cb229b097fedb1dd4bd9420d463c37774f/library/core/src/ops/function.rs:259:13
  24:     0x564bf2b2e041 - std::panicking::try::do_call::h5801bf97add122d3
                               at /rustc/5d8767cb229b097fedb1dd4bd9420d463c37774f/library/std/src/panicking.rs:492:40
  25:     0x564bf2b2e041 - std::panicking::try::h3f3fad97cc54d848
                               at /rustc/5d8767cb229b097fedb1dd4bd9420d463c37774f/library/std/src/panicking.rs:456:19
  26:     0x564bf2b2e041 - std::panic::catch_unwind::h79036e40b0403478
                               at /rustc/5d8767cb229b097fedb1dd4bd9420d463c37774f/library/std/src/panic.rs:137:14
  27:     0x564bf2b2e041 - std::rt::lang_start_internal::{{closure}}::hb92279f48d1e9fe1
                               at /rustc/5d8767cb229b097fedb1dd4bd9420d463c37774f/library/std/src/rt.rs:128:48
  28:     0x564bf2b2e041 - std::panicking::try::do_call::h425680a92bbfa8ea
                               at /rustc/5d8767cb229b097fedb1dd4bd9420d463c37774f/library/std/src/panicking.rs:492:40
  29:     0x564bf2b2e041 - std::panicking::try::hb1c8b961f16bc4ea
                               at /rustc/5d8767cb229b097fedb1dd4bd9420d463c37774f/library/std/src/panicking.rs:456:19
  30:     0x564bf2b2e041 - std::panic::catch_unwind::hb06f44bc71aebc22
                               at /rustc/5d8767cb229b097fedb1dd4bd9420d463c37774f/library/std/src/panic.rs:137:14
  31:     0x564bf2b2e041 - std::rt::lang_start_internal::hd568c0eec8d53c6b
                               at /rustc/5d8767cb229b097fedb1dd4bd9420d463c37774f/library/std/src/rt.rs:128:20
  32:     0x564bf23f6ad2 - main
  33:     0x7f97801f40b3 - __libc_start_main
  34:     0x564bf226b8ee - _start
  35:                0x0 - <unknown>
`

**Comment by looksnap** [comment]
I was able to resolve this by rotating my VPN connection.

**Comment by damip** [comment]
Found the problem: in bootstrap get_state we have:

```rust
                let mut connector = establisher
                    .get_connector(bootstrap_settings.connect_timeout)
                    .await?; // cancellable
                let socket = connector.connect(*addr).await?; // cancellable
```


which quits the whole program if connecting fails during bootstrap.

Idea: wrap the whole content of the bootstrap loop into a function in which we can use "?" safely
