### ISSUE TITLE
Testnet 10 - get_status ipv6 node connected format

### ISSUE THREAD

**Issue by rykcod** [massalabs/massa#2606]
The get_status connected node format return is well to directly integrate nodes to config.toml but look the return for ipv6 connected node. The ipv6 node stay in a wrong format. Example:
["2a05:f480:2800:1c10:5400:3ff:fefb:2048:31245", "7gLVugq6NXt32uv9tCmJZYMBqbdoizvGY75E9e8gBdZ2AJEkVH"],
Instead of the right format
["[2a05:f480:2800:1c10:5400:3ff:fefb:2048]:31245", "7gLVugq6NXt32uv9tCmJZYMBqbdoizvGY75E9e8gBdZ2AJEkVH"],

**Comment by AurelienFT** [comment]
@rykcod We have choose to remove the port from the print because a peer that is connected to you is not always a peer that propose bootstrap and moreover the bootstrap can be in another port and the node can't know that so the print will be wrong.

**Comment by rykcod** [comment]
Its a new decision?
Because today the format stay:

```
Connected nodes:
        ["157.90.244.77:31245", "6sAmEs7bZzepYGH5RtptxfJPVow6n1eLb2hpWYxTcTSVyw4fLd"],
        ["2a05:f480:2800:1c10:5400:3ff:fefb:2048:31245", "7gLVugq6NXt32uv9tCmJZYMBqbdoizvGY75E9e8gBdZ2AJEkVH"],
```

But i understand, i think i will include a test on my automate to test 31245 port of connected node before include it to my config.toml

**Comment by AurelienFT** [comment]
> Its a new decision? Because today the format stay:
> 
> ```
> Connected nodes:
>         ["157.90.244.77:31245", "6sAmEs7bZzepYGH5RtptxfJPVow6n1eLb2hpWYxTcTSVyw4fLd"],
>         ["2a05:f480:2800:1c10:5400:3ff:fefb:2048:31245", "7gLVugq6NXt32uv9tCmJZYMBqbdoizvGY75E9e8gBdZ2AJEkVH"],
> ```
> 
> But i understand, i think i will include a test on my automate to test 31245 port of connected node before include it to my config.toml

It will be on the 10.1
