### ISSUE TITLE
Need ipv6 bootstrap address

### ISSUE THREAD

**Issue by rykcod** [massalabs/massa#2608]
It's possible to create an offical ipv6 node? Because for ipv6 only user node, its impossible to bootstrap without add a community ipv6 node in the custom config.toml

**Comment by damip** [comment]
We need to figure this out.

**Comment by AurelienFT** [comment]
First step here is to test if it really don't work.

**Comment by Leo-Besancon** [comment]
I did reproduce the issue. A client with IPv6 only interface can't connect to a bootstrap server using the IPv4 protocol (for example, see [this link](https://serverfault.com/questions/1102241/purpose-of-ipv4-mapped-ipv6-address).

This means that we should:
- [ ] Let our bootstrap servers expose both an IPv4 and IPv6 address
- [ ] Then, we can put both addresses in the bootstrap ip list
- [ ] Finally, filter the bootstrap ip list based on the available interfaces of the node
