### ISSUE TITLE
Peers information from get status - Separate In and Out connections

### ISSUE THREAD

**Issue by Gnomuz** [massalabs/massa#2614]
When using the "get_status" command, all connected peers are listed. Ex :
`Connected nodes:
        ["75.119.146.74", "8M89Z2niSctcBuhda8CSBjR7KpEPW47PFuxGEsbntf8mMKFRKi"],
        ["95.217.209.197", "5eB2U9SEPu9DEcA4YKRgmQSjzto1gczFapDxdtgznA96EA9mTV"],`

One of the possible (and common) usage of this list is to populate config.toml with potential community bootstrap nodes. To better target these nodes, it would be useful to somehow distinguish in the output between In and Out connections, as an Out conection proves the node is routable, which makes it a better bootstrap candidate.

**Comment by aoudiamoncef** [comment]
related to #2520 https://github.com/massalabs/massa/issues/2520

**Comment by AurelienFT** [comment]
Merged in #2628
