### ISSUE TITLE
 Error while bootstrapping: io error: bootstrap state read timed out

### ISSUE THREAD

**Issue by pgulyaev88** [massalabs/massa#2615]
Node not loading with error "Error while bootstrapping: io error: bootstrap state read timed out"
[massa.log](https://github.com/massalabs/massa/files/8665533/massa.log)
[strace_massa.log](https://github.com/massalabs/massa/files/8665534/strace_massa.log)
[config.log](https://github.com/massalabs/massa/files/8665536/config.log)

**Comment by pgulyaev88** [comment]
why in listing port 3450?

![изображение](https://user-images.githubusercontent.com/17798697/167925811-c042e599-09ad-4f55-bc3a-84ec2f322eab.png)

**Comment by AurelienFT** [comment]
The bootstrap has been refactor since. Open a new issue if you still have problems
