### ISSUE TITLE
Add test tool for receiving outgoing messages

### ISSUE THREAD

**Issue by gterzian** [massalabs/massa#2616]
See TODO at https://github.com/massalabs/massa/pull/2587/files#diff-10f4bf29452214d334b30949ce3e897bbbbab2bd62aba00f4af1f85f76d54faaR170

The goal would be to be able to "easily" receive the outgoing messages sent by the node worker, to make assertions about them(for example about the proper inclusion of objects added to shared storage).

**Comment by AurelienFT** [comment]
It's possible now with the tests of the new network refactoring. Closing it.
