### ISSUE TITLE
Port 31244&5 KO for some ipv4 windows host nodes - 33035 OK

### ISSUE THREAD

**Issue by rykcod** [massalabs/massa#2617]
Some persons which host their node on Windows have an issue with their 31244 & 31245 service port on their ipv4 despite OS firewall OFF, port redirection on host OK.
Contrary to the port 33035 --> No problem with the 33035 which is listenning.
After a lot of tests, the problem is the node only listen on ipv6 address of their Windows server,
For example:

- FE80... 31244&5 return OK
- 2a01:... 31244&5 return OK
- 192.168.1.10 31244&5 return KO
- 192.168.1.10 33035 return OK
- 127.0.0.1 31244&5 return KO

I invited the impacted users to try to change some of properties of the `./massa-node/config/config.toml`:
https://discord.com/channels/828270821042159636/866464478828036126/974309233547956254
>     # port on which to listen for protocol communication
>     bind = "[::]:31244"
BY
>     # port on which to listen for protocol communication
>     bind = "0.0.0.0:31244"
And
>     # [optionnal] port on which to listen for incoming bootstrap requests
>     bind = "[::]:31245"
BY
>     # [optionnal] port on which to listen for incoming bootstrap requests
>     bind = "0.0.0.0:31245"

In result, it solved the issue for the ipv4 users, but i think its not the best solution because of course, for Windows ipv6 users, massa-node stop listening to this ports on ipv6 interface.
Today another case https://discord.com/channels/828270821042159636/866464478828036126/974628827512852490
Of course this issue occur only for Windows users.

**Comment by AurelienFT** [comment]
Some resources about this : 
- https://serverfault.com/questions/21657/semantics-of-and-0-0-0-0-in-dual-stack-oses
- https://users.rust-lang.org/t/how-to-listen-on-all-interfaces-with-tcplistener-solved/12269

**Comment by rykcod** [comment]
Another case today with a Windows host, same issue -> same solution

**Comment by AurelienFT** [comment]
@Leo-Besancon You are on windows ? If yes can you check if this is still relevant ?

**Comment by Leo-Besancon** [comment]
> @Leo-Besancon You are on windows ? If yes can you check if this is still relevant ?

Indeed I'm on windows, I don't think I had trouble with IPv4 only nodes but I'll have some make some more tests

**Comment by AurelienFT** [comment]
Any news on that ?

**Comment by Leo-Besancon** [comment]
I just read some documentations regarding this issue. I will first try and replicate it, and then manually set the IPV6_V6ONLY flag to false (defaults to true on windows), and test the changes!

**Comment by Leo-Besancon** [comment]
Completed in #3590
