### ISSUE TITLE
Re-use serialized operations as received in blocks

### ISSUE THREAD

**Issue by gterzian** [massalabs/massa#2622]
https://github.com/massalabs/massa/pull/2587 re-uses serialized operations when they are received as operations, but not when they are received as a part of a block. We should look into re-using the serialized forms of operations also when they are received inside a block. 

See https://github.com/massalabs/massa/pull/2587/files/0b7336b38e7dbb969eedf81257d272463f157b76#discussion_r873787328

**Comment by damip** [comment]
@gterzian  is this still relevant ?

**Comment by gterzian** [comment]
Done.
