### ISSUE TITLE
Improve Operations serialization

### ISSUE THREAD

**Issue by gterzian** [massalabs/massa#2626]
# context

Here is how I would see it, of course we can adapt it. Basically it allows getting rid of the ad-hoc message deserialization function that extracts the raw bytes.

# operation rust structure

Have a richer Operation structure preventing useless copying, re-hashing, re-serializing etc...

```
struct Operation {
    id: OperationId,
    serialized_data: [u8],
    signature: Signature,
    sender_addr: Address,
    sender_pubkey: PublicKey,
    thread: u8,
    expire_period: u64,
    op: OperationType,
}
```

This structure can be stored as-is in Storage

# operation serialized representation

Not all fields need to be serialized as non-serialized fields can be deduced:

```
[signature]
[sender_pubkey]
[expire_period: varint]
[op serialization]
```

Note that for a JSON representation, simply serialize those fields as JSON. 

# operation deserialization

Instead of the ad hoc function that deserializes specific messages while returning the serialized version:

* remove the DeserializeCompact trait from operations, use a deserializer instead (see https://github.com/massalabs/massa/issues/1200)
* when deserializing an operation, the deserializer does the following:
  * deserializes basic the serialized fields using `nom` (see https://github.com/massalabs/massa/pull/2576 )
  * deduce other useful fields from the serialized ones (eg: sender address deduced from sender pubkey, thread is deduced from sender address etc...)
  * sets a `serialized_data: [u8]` field in the Operation containing a copy of the serialized data
  * sets a `id` field in the Operation containing the OperationID deduced by hashing `serialized_data`
* signature verification: `&serialized_data[SIGNATURE_SIZE..]` must be signed by the deserialized public key to obtain the deserialized signature
  
That way, fields like "thread" don't need to be recomputed whenever they are needed.

# operation serialization

Serializing an Operation would just mean accessing its `serialized_data` field. For example when creating a block, we could build its serialized version as we add operations by simply concatenating the saved serialized representations of the operations.

# operation creation

when creating an operation:
  * concatenate the serialized representation of all serialized fields except the signature to obtain `serialized_data`
  * sign  `serialized_data` and prepend  `serialized_data` with the resulting signature

_Originally posted by @damip in https://github.com/massalabs/massa/issues/2587#issuecomment-1128845365_

**Comment by gterzian** [comment]
I think we can address this once the new serialization framework started at https://github.com/massalabs/massa/pull/2625 settles down. 

For example a `OperationSerializer` could retain the raw input and make it available so it can be stored in shared storage.

**Comment by damip** [comment]
Done in v14
