### ISSUE TITLE
Use bs58_check functions exclusively for debug purposes

### ISSUE THREAD

**Issue by Eitu33** [massalabs/massa#2627]
## Context

Address human-readable format is now handled through ToString and FromStr traits implementations. There is no purpose (debug excepted) for bs58_check functions anymore.

## TODO

- [ ] Set all the Adresses bs58_check functions as private
- [ ] Make sure they are no external occurrences of them

**Comment by setar** [comment]
Hi, i have this problem on last branch of testnet ( fa6bdbf84e642f004b34c1103e1f2f0cbe2a2d06 ) 
```
massa@massa-node:~/massa/massa-node$ cargo run --release
warning: /home/massa/massa/massa-node/Cargo.toml: unused manifest key: build
    Finished release [optimized] target(s) in 4.04s
     Running `/home/massa/massa/target/release/massa-node`
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: parsing error : public key bs58_check parsing error: ... 
--- skipped ---
```

Any idea to solve it ?

**Comment by Eitu33** [comment]
@setar Public keys format has changed, if you are using a PubKey, PrivKey, or Address from the previous episode your node won't work

**Comment by setar** [comment]
Thanks, resolved via regenerate new keys

**Comment by adrien-zinger** [comment]
@Eitu33 it looks like a good first issue, right?

**Comment by AurelienFT** [comment]
Done in #3266
