### ISSUE TITLE
Define a maximum value in deserialization instead of u64::MAX

### ISSUE THREAD

**Issue by AurelienFT** [massalabs/massa#2654]
In all new low-level deserializer that we created we added limits for maximum value that we can parameterized such as the len of a vector. 

We have put u64::MAX everywhere there is no clear value but this is not a solution since it allow user to send us really big object and explode the RAM. So we need to defined coherent values for each case.

I'll write a list here when all deserialization is done.

**Comment by adrien-zinger** [comment]
Could you leave some context? :slightly_smiling_face:

**Comment by AurelienFT** [comment]
> Could you leave some context? 🙂

Done :)

**Comment by AurelienFT** [comment]
Close in favor of #2863
