### ISSUE TITLE
Node asks op that it knows

### ISSUE THREAD

**Issue by sebastien-forestier** [massalabs/massa#2686]
This seems to happen often based on analysis of performance regression in 11.1 with 50% time spent in remove_known_ops.

We should investigate this together with the number of op re-asks.

**Comment by gterzian** [comment]
@sebastien-forestier What do you mean with `remove_known_ops`? Perhaps [this](https://github.com/massalabs/massa/blob/main/massa-protocol-worker/src/node_info.rs#L141)?

**Comment by AurelienFT** [comment]
Following the last perf we don't spend time on those workflows. closing it.
