### ISSUE TITLE
Use KeyPair instead of private/public key

### ISSUE THREAD

**Issue by AurelienFT** [massalabs/massa#2714]
In some signatures algorithms the public key isn't derivable from the Private key. To have more flexibility instead of having always a PrivateKey and derive the PublicKey from it we should have a KeyPair structure so that we can always have access to both

**Comment by damip** [comment]
More precisely:
* every time we currently use a PrivateKey (for signing, wallet dump/load etc...), we should use a KeyPair instead
* every time we use a PublicKey alone (for verification), we should continue using a PublicKey alone

That way we will remove the following two constraints on the signature algorithm:
* the public key can be (cheaply) derived from the private key
* the public key is not needed to sign

And by removing those assumptions, we will reduce coupling in the code and get a wider choice of signature algorithms.
