### ISSUE TITLE
Encrypt private API communications

### ISSUE THREAD

**Issue by damip** [massalabs/massa#2719]
Use TLS with public key auth to cypher and authenticate the communication with the private API of the node

**Comment by aoudiamoncef** [comment]
Partially resolved in https://github.com/massalabs/massa/pull/3908 in gRPC side.

- [ ] mTLS in gRPC 
- [ ] Add authorisation to restrict access certain methods. 

What about jsonrpsee ? 

IMHO, it's far better to focus on gRPC and robustify It than try to maintain jsonrpsee side.

**Comment by AurelienFT** [comment]
There is private separate API on our grpc stack ?

**Comment by aoudiamoncef** [comment]
We'll have protected methods, we should provide a minimalist and robust way to protect the node without putting it behind a proxy. 

A combo of mTLS+authorisations(whitelist of generated keys which are allowed to access the private methods)

**Comment by aoudiamoncef** [comment]
@damip 

- When we would access private methods for node management, we should both make mTLS + Auth mandatory ? 
- We could make communication between massa client and massa node mTLS by default with autogenerated certificats ?

**Comment by damip** [comment]
Hello ! Yes that would be cool, maily for auth on the private api

**Comment by aoudiamoncef** [comment]
Hi @gregLibert, we have two solutions to achieve this. 

1. Make mTLS mandatory with for both public and private methods.
2. Make mTLS mandatory for private methods only, this imply that we'll have two instances of gRPC in different ports. 

Make mTLS fully automated with autogeneration at startup.

Security will increase the complexity of using Massa, but we are trying to our best to make It easier

**Comment by gregLibert** [comment]
> Hi @gregLibert, we have two solutions to achieve this.
> 
> 1. Make mTLS mandatory with for both public and private methods.
> 2. Make mTLS mandatory for private methods only, this imply that we'll have two instances of gRPC in different ports.
> 
> Make mTLS fully automated with autogeneration at startup.
> 
> Security will increase the complexity of using Massa, but we are trying to our best to make It easier

From a security and server administration point of view I would say that having two different endpoints is better.

If we go in that direction, I would do:
- mTLS for the private API
- TLS with self-signed certificate for the public API. We maybe can use the node staking keys of the node to sign it

**Comment by AurelienFT** [comment]
@aoudiamoncef is this done ?

**Comment by aoudiamoncef** [comment]
We implemented 99% of this feature. Feel free to close It 

The only missing part is mTLS certificate revocation which is not urgent
