### ISSUE TITLE
Failed bootstraps

### ISSUE THREAD

**Issue by sebastien-forestier** [massalabs/massa#2723]
Bootstrap fails, then bootstrap succeeds but with weird behavior, speculative execution cache empty, send queue fulll, etc

[failed_bootstraps_logs.txt](https://github.com/massalabs/massa/files/8956335/failed_bootstraps_logs.txt)

**Comment by damip** [comment]
Duplicate of https://github.com/massalabs/massa/issues/2722

**Comment by AurelienFT** [comment]
Close in favor #2722
