### ISSUE TITLE
RAM usage increasing

### ISSUE THREAD

**Issue by sebastien-forestier** [massalabs/massa#2724]
Here is the evolution of the RAM usage of one node (grey curve):

![RAM](https://user-images.githubusercontent.com/11048486/174999183-e4b94017-5a4b-46ca-a8a3-4711c08b45c3.png)

**Comment by damip** [comment]
This PR hopefully solves the problem: https://github.com/massalabs/massa-sc-runtime/pull/138

**Comment by damip** [comment]
Apparently the problem might be coming from somewhere else: even with normal (non-SC) transaction flooding, RAM usage increases. 
Maybe op storage not being cleared ?
