### ISSUE TITLE
Crypto: move to Ed25519

### ISSUE THREAD

**Issue by damip** [massalabs/massa#2743]
### Discussed in https://github.com/massalabs/massa/discussions/2733

<div type='discussions-op-text'>

<sup>Originally posted by **damip** June 27, 2022</sup>
Consider switching from secp256k1 ECDSA to Ed25519 EdDSA because:

* has better security features than secp256k1: http://safecurves.cr.yp.to/
* most commonly used scheme in Tezos, default on Solana and m any others
* Faster than secp256k1 https://justmoon.github.io/curvebench/benchmark.html
* safer and more standardized Schnorr / multisig implementations

Some info: https://soatok.blog/2022/05/19/guidance-for-choosing-an-elliptic-curve-signature-algorithm-in-2022/
</div>

**Comment by damip** [comment]
@gregLibert  https://pkg.go.dev/crypto/ed25519  

This should solve all your problems, my friend !

**Comment by Eitu33** [comment]
This has been done in https://github.com/massalabs/massa/pull/2744, can we close @damip?
