### ISSUE TITLE
Restructure Protocol workflow for blocks without operations

### ISSUE THREAD

**Issue by gterzian** [massalabs/massa#2747]
Part of https://github.com/massalabs/massa/issues/2735

New workflow:
* a header is announced
* the op hash list is asked for that header
* the op hash list is sent for that block (non-truncated hashes must be used)
* the op hash list is received, deserialized, and the total op hash is checked against the one in the header
* the hash list is compared to the operations cache
  * the list of missing ops is asked to the sender (non-truncated hashes must be used)
    * this must be prioritized over normal op propagation
  * once we have all ops, the block is processed
  * if the remote node fails to send us all missing ops after a timeout (or if any is invalid):
    * ban the node and disconnect from it
    * ask for missing ops from another node that announced the block (if any, otherwise just forget about that block for now)

**Comment by damip** [comment]
done for v14
