### ISSUE TITLE
Sync wallet encryption with tooling

### ISSUE THREAD

**Issue by damip** [massalabs/massa#2755]
Let's make sure that the encryption scheme we are using for wallets has safe implems in:
* rust
* golang
* python
* JS

If not, let's switch now

**Comment by Eitu33** [comment]
After a discussion with @gregLibert, we agreed on using AES-GCM for the following reasons:

- Confidentiality is a must
- Authenticity improves the user experience
- It has been audited
- It is widely used and has stable implementation across different languages

**Comment by damip** [comment]
> @damip we didn't forget it:
> 
>     * https://github.com/massalabs/massa/blob/main/massa-cipher/src/encrypt.rs#L48
> 
>     * https://github.com/massalabs/massa/blob/main/massa-cipher/src/decrypt.rs#L23-L28

Thanks for the reminder, my bad !
