### ISSUE TITLE
Update the api documentation to reflect the changes made on the massa api

### ISSUE THREAD

**Issue by jwmdev** [massalabs/massa#2762]
The latest version of massa  has some changes on the api structure, however, they are not reflected on the user api documentation.
For instance, using the existing api documentation, when using the send operation results into the following error:
` Invalid params: missing field creator_public_key`  also `content` has change to `serialized_content`, etc

**Comment by AurelienFT** [comment]
@jwmdev The documentation has been updated with the changes for the endpoint send_operations : https://massa.readthedocs.io/en/latest/technical-doc/api.html#send-operations

Tell us if something is missing :)

**Comment by jwmdev** [comment]
> @jwmdev The documentation has been updated with the changes for the endpoint send_operations : https://massa.readthedocs.io/en/latest/technical-doc/api.html#send-operations
> 
> Tell us if something is missing :)

Thanks for the reply @AurelienFT ...   The documentation covers everything. This was due to the fact that the changes was not published on [massa doc](https://massa.readthedocs.io).
