### ISSUE TITLE
Document Block and Operation propagation

### ISSUE THREAD

**Issue by gterzian** [massalabs/massa#2775]
As part of https://github.com/massalabs/massa/pull/2753/, I'll try to document what we exactly do in terms of block and operation propagation, here in this issue with links to the code. 

This seems necessary, because as I try to implement the changes of that PR, I find that there are many concepts and that mapping them would be useful in order to successfully make the proposed changes.

**Comment by gterzian** [comment]
When a block is [integrated](https://github.com/massalabs/massa/blob/d388f2e2182168dcd8a5b9a8a54ac0f9b6c384ad/massa-protocol-worker/src/protocol_worker.rs#L354)(via `ProtocolCommand::IntegratedBlock`) in the graph:
    - for all actives nodes with `NodeInfo.`:
        - The block is [sent](https://github.com/massalabs/massa/blob/d388f2e2182168dcd8a5b9a8a54ac0f9b6c384ad/massa-protocol-worker/src/protocol_worker.rs#L383) via [`NetworkCommand::SendBlock`](https://github.com/massalabs/massa/blob/d388f2e2182168dcd8a5b9a8a54ac0f9b6c384ad/massa-network-exports/src/commands.rs#L150)
    - for all other active nodes:
        - The header is [sent](https://github.com/massalabs/massa/blob/d388f2e2182168dcd8a5b9a8a54ac0f9b6c384ad/massa-protocol-worker/src/protocol_worker.rs#L397) via [`NetworkCommand::SendBlockHeader`](https://github.com/massalabs/massa/blob/d388f2e2182168dcd8a5b9a8a54ac0f9b6c384ad/massa-network-exports/src/commands.rs#L157)

**Comment by gterzian** [comment]
When a block is [received](https://github.com/massalabs/massa/blob/d388f2e2182168dcd8a5b9a8a54ac0f9b6c384ad/massa-protocol-worker/src/protocol_worker.rs#L1237):

  - Block is noted from node.
  - stop asking for that block.
  - [Send to graph](https://github.com/massalabs/massa/blob/d388f2e2182168dcd8a5b9a8a54ac0f9b6c384ad/massa-protocol-worker/src/protocol_worker.rs#L1250) via `ProtocolEvent::ReceivedBlock`.
  - Update "ask block" workflow.

**Comment by gterzian** [comment]
When the block wish-list is [updated](https://github.com/massalabs/massa/blob/d388f2e2182168dcd8a5b9a8a54ac0f9b6c384ad/massa-protocol-worker/src/protocol_worker.rs#L505) by graph:
  - Stop asking for blocks that have been removed from the wish-list
  - Extend the wish-list with the blocks that have been added.
  - Update "ask block" workflow.

**Comment by gterzian** [comment]
When running the [`ask  block workflow`](https://github.com/massalabs/massa/blob/d388f2e2182168dcd8a5b9a8a54ac0f9b6c384ad/massa-protocol-worker/src/protocol_worker.rs#L587):

  - Determine which blocks should be (re-)asked, and
  -  [Ask them](https://github.com/massalabs/massa/blob/d388f2e2182168dcd8a5b9a8a54ac0f9b6c384ad/massa-protocol-worker/src/protocol_worker.rs#L761)


When a node [receives](https://github.com/massalabs/massa/blob/d388f2e2182168dcd8a5b9a8a54ac0f9b6c384ad/massa-protocol-worker/src/protocol_worker.rs#L1263) such a "ask for blocks" request(via `NetworkEvent::AskedForBlocks`):

  - Add the "wanted blocks" info to NodeInfo.
  - Ask for the blocks to graph. 

When the result of asking for the blocks from graph is [received](https://github.com/massalabs/massa/blob/d388f2e2182168dcd8a5b9a8a54ac0f9b6c384ad/massa-protocol-worker/src/protocol_worker.rs#L438):
  - for all active nodes that asked for the block:
    - If the block was found:
      - Update node info(assuming node from then on knows of block).
      -  Send block to to node. 
    - If the block was not found:
      - Send block not found message to node.

**Comment by AurelienFT** [comment]
Docs has been written here : https://docs.massa.net/en/latest/general-doc/architecture.html
