### ISSUE TITLE
Can't produce blocks but no error in logs

### ISSUE THREAD

**Issue by arhuman** [massalabs/massa#2781]
I get my rolls autoselled without any (given) reasons in the logs

Everytime I buy rolls (I started with one, then 2), I failed to produce blocks (according to https://paranormal-brothers.com/massa/#monitor) but I have no explanation in the logs.
The server used is over dimensioned (Intel Xeon E5 2630v4 (10 x 2.20 GHz), 256G RAM) and routinely missed zero blocks under heavy loads in previous episode (with 27+ rolls)

I set logging to debug with
```
[logging]
level = 3
```
But see nothing special (no ERROR) in logs except maybe :
```
ESC[2m2022-07-11T02:00:26.327902ZESC[0m ESC[32m INFOESC[0m ESC[2mmassa_bootstrap::clientESC[0mESC[2m:ESC[0m Start bootstrapping from 54.36.174.177:31245
ESC[2m2022-07-11T02:00:26.925891ZESC[0m ESC[34mDEBUGESC[0m ESC[2mmassa_bootstrap::clientESC[0mESC[2m:ESC[0m Received ledger batch from None to Some(
    Some(
        A12p8v9V68SiehQb2Syzy6smfv9NTCJh2p6JPbsacy7PaGRw39uH,
    ),
), an async pool batch from None to None a batch of ledger changes of size 0 and a batch of async pool changes of size 0. for slot: Slot {
    period: 11699,
    thread: 18,
}
```

I don't understand why I don't produce ANY block anymore

OS: Ubuntu 20.04.4 LTS
Node version : TEST.12.0
Build from source (commit 3200f282058145a2c135e13a7d96958de2d43461 (HEAD, tag: TEST.12.0, origin/testnet))

![VirtualBox_Debiangtop_11_07_2022_06_17_18](https://user-images.githubusercontent.com/283991/178187722-a0153dc8-d2ea-4c35-8119-9da120d07cad.png)

![Capture d’écran (12)](https://user-images.githubusercontent.com/283991/178187799-a1d968a9-ae42-4a75-a616-c3f7f6bea486.png)

**Comment by arhuman** [comment]
Additional odd things found in log (btw labelling *all* errors as WARNING or ERROR could may be help to spot):

```
ESC[2m2022-07-11T02:00:30.367970ZESC[0m ESC[34mDEBUGESC[0m ESC[2mmassa_network_worker::handshake_workerESC[0mESC[2m:ESC[0m starting handshake with connection_id=12
ESC[2m2022-07-11T02:00:30.382171ZESC[0m ESC[34mDEBUGESC[0m ESC[2mmassa_network_worker::network_workerESC[0mESC[2m:ESC[0m handshake failed with connection_id=12: models error: massa_signature error: parsing error : signature error: Cannot decompress Edwards point
```

```
ESC[2m2022-07-10T12:11:27.452762ZESC[0m ESC[33m WARNESC[0m ESC[2mmassa_bootstrap::clientESC[0mESC[2m:ESC[0m Error while bootstrapping: general bootstrap error: Parsing Error
: Failed BootstrapServerMessage deserialization / Failed u32 deserialization / Fail / Input: [114, 89, 111, 117, 114, 32, 108, 97, 115, 116, 32, 98, 111, 111, 116, 115, 116,
 114, 97, 112, 32, 111, 110, 32, 116, 104, 105, 115, 32, 115, 101, 114, 118, 101, 114, 32, 119, 97, 115, 32, 49, 52, 54, 56, 56, 46, 51, 48, 51, 53, 53, 48, 55, 56, 55, 115,
 32, 97, 103, 111, 32, 97, 110, 100, 32, 121, 111, 117, 32, 104, 97, 118, 101, 32, 116, 111, 32, 119, 97, 105, 116, 32, 50, 56, 53, 49, 49, 46, 54, 57, 54, 52, 52, 57, 48, 5
4, 51, 115, 32, 98, 101, 102, 111, 114, 101, 32, 114, 101, 116, 114, 121, 105, 110, 103, 46]
ESC[2m2022-07-10T12:11:27.452854ZESC[0m ESC[32m INFOESC[0m ESC[2mmassa_bootstrap::clientESC[0mESC[2m:ESC[0m Bootstrap from server 198.27.74.5:31245 failed. Your node will tr
y to bootstrap from another server in 6s.
```

**Comment by arhuman** [comment]
Ok this is NOT a bug.
Seems that I missed one configuration step (node_add_staking_secret_keys ?) because redoing the whole install fixed it.

As a suggestion,  may be an additional check when buying rolls on the client side (checking that the configuration is complete to start staking) or a display on the get_status (checking that all the wallet/node config is ok for staking) stating if a step was forgotten, could prevent others to do the same mistake.

**Comment by damip** [comment]
We will add a message on buy rolla like we did here:

https://github.com/massalabs/massa/blob/main/massa-client/src/cmds.rs#L602
