### ISSUE TITLE
No history of command in massa-client for binaries version

### ISSUE THREAD

**Issue by JeromeSi** [massalabs/massa#2782]
**Describe the bug**
You don't have access to the history of command in massa-client (binaries version)

**Expected behavior**
when you restart massa-client you don't have the history of command

**Desktop (please complete the following information):**

- OS: Ubuntu 22.04 / Debian 11

**Additional context**
The directory `massa-client/config`are not present in archive file (Windows / Linux / MacOS)

**Comment by damip** [comment]
@massalabs/core-team  looks like a problem with persistent history in the client ?

**Comment by JeromeSi** [comment]
A directory is missing (config in massa-client )
I add it by and history in massa-client work fine

**Comment by damip** [comment]
> A directory is missing (config in massa-client ) I add it by and history in massa-client work fine

So the folder is missing in the binary version ? We should correct that. Thanks for the heads up!

**Comment by JeromeSi** [comment]
you're welcome
ggcom ;)
