### ISSUE TITLE
client: remind to add staking keys on buy rolls

### ISSUE THREAD

**Issue by damip** [massalabs/massa#2788]
Currently we do this on key generation: https://github.com/massalabs/massa/blob/main/massa-client/src/cmds.rs#L602

We should rather do it on roll_buy ! (but only in REPL mode)

This will avoid many implicit roll sells in the community

**Comment by arhuman** [comment]
I'd like to take on this.

**Comment by damip** [comment]
> I'd like to take on this.

here you go :)
