### ISSUE TITLE
Format wallet_info in client

### ISSUE THREAD

**Issue by damip** [massalabs/massa#2794]
Currently, when there are multiple keys in the wallet, they are printed this way, without any separation:
```
publickey1
secretkey1
address1
publickey2
secretkey2
address2
publickey3
secretkey3
address3
```

It's very hard to know where one entry ends and another starts.

Print them better by skipping a line.

Also, when there are no keys, print "Your wallet does not contain any key, use XXXXXX to generate a new key and add it to your wallet" instead of printing a blank line. Note: this print should happen only in REPL mode

**Comment by arhuman** [comment]
Which branch am I supposed to work on?
Currently on TEST.12.1 the display in client for wallet_info is rather like :

```
WARNING: do not share your key
Secret key: S1yTxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
Public key: P127yyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyy
Address: A126zzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzz
Thread: 17
Parallel balance:
	Final: 0
	Candidate: 0

Sequential balance:
	Final balance: 0
	Candidate balance: 0
	Locked balance: 0

Rolls:
	Active rolls: 0
	Final rolls: 0
	Candidate rolls: 0



=====


Secret key: S12Sxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
Public key: P12yyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyy
Address: A121zzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzz
Thread: 16
Parallel balance:
	Final: 0
	Candidate: 0

Sequential balance:
	Final balance: 0
	Candidate balance: 0
	Locked balance: 0

Rolls:
	Active rolls: 0
	Final rolls: 0
	Candidate rolls: 0



=====

```

**Comment by damip** [comment]
> Which branch am I supposed to work on? Currently on TEST.12.1 the display in client for wallet_info is rather like :
> 
> ```
> WARNING: do not share your key
> Secret key: S1yTxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
> Public key: P127yyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyy
> Address: A126zzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzz
> Thread: 17
> Parallel balance:
> 	Final: 0
> 	Candidate: 0
> 
> Sequential balance:
> 	Final balance: 0
> 	Candidate balance: 0
> 	Locked balance: 0
> 
> Rolls:
> 	Active rolls: 0
> 	Final rolls: 0
> 	Candidate rolls: 0
> 
> 
> 
> =====
> 
> 
> Secret key: S12Sxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
> Public key: P12yyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyy
> Address: A121zzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzz
> Thread: 16
> Parallel balance:
> 	Final: 0
> 	Candidate: 0
> 
> Sequential balance:
> 	Final balance: 0
> 	Candidate balance: 0
> 	Locked balance: 0
> 
> Rolls:
> 	Active rolls: 0
> 	Final rolls: 0
> 	Candidate rolls: 0
> 
> 
> 
> =====
> ```

Oh, then we don't need it, it was already solved :)
