### ISSUE TITLE
Migrate JSON RPC server implementation

### ISSUE THREAD

**Issue by aoudiamoncef** [massalabs/massa#2799]
Migrate [jsonrpc](https://github.com/paritytech/jsonrpc/) is deprecated and not maintained to [jsonrpsee](https://github.com/paritytech/jsonrpsee).

**Comment by damip** [comment]
Let's also add the following endpoints:
* [ ] send endorsements
* [ ] send block
* [ ] get executed operations

As well as websocket streaming for:
* [ ] new operations
* [ ] new endorsements
* [ ] execution event changes


This will pave the way towards https://github.com/massalabs/massa/issues/2903 in particular, and also help @BatiGencho with execution event streaming for web3

**Comment by aoudiamoncef** [comment]
It could be interesting to add `GET` request proxing to RPC methods. This feature could simplify frontend queries and allow URIs pining. 

[JSONRPSEE HTTP PROXY](https://github.com/paritytech/jsonrpsee/blob/master/examples/examples/http_proxy_middleware.rs)

**Comment by aoudiamoncef** [comment]
To get both HTTP + WS server support, we have to wait until this [PR](https://github.com/paritytech/jsonrpsee/pull/863) will be merged.

**Comment by aoudiamoncef** [comment]
@AurelienFT IMHO we could close this, as we already did the migration.

**Comment by AurelienFT** [comment]
https://github.com/massalabs/massa/issues/2799#issuecomment-1227185289 we need to keep this Todo list somewhere
