### ISSUE TITLE
Add back T0 and THREAD_COUNT sandbox capabilities

### ISSUE THREAD

**Issue by qdrn** [massalabs/massa#2807]
> I don't like the fact that you just removed the possibility to change T0 and THREAD COUNT in runtime in sandbox. I know it was messy but I think we can find a good way to make the switch one time in the code and clean rather then removing the feature that we discussed that could be cool to have to make experiments etc

Sure, we can add it back as a followup in a cleaner way (feel free to open an issue). In the meantime, the emergency is to make the sandbox compile again, and to remove some dangerous practices in the config

_Originally posted by @damip in https://github.com/massalabs/massa/issues/2806#issuecomment-1184163419_

**Comment by damip** [comment]
In the end, was this used at any point ? if not, we can close

**Comment by AurelienFT** [comment]
Will be used in simulations no ?

**Comment by damip** [comment]
possible, then let's keep it

**Comment by AurelienFT** [comment]
Should be done in the simulators
