### ISSUE TITLE
Node crash at 2k txps.

### ISSUE THREAD

**Issue by AurelienFT** [massalabs/massa#2810]
node crashed at 2k txps. testnet 3.

Logs
[logs.txt](https://github.com/massalabs/massa/files/9111833/logs.txt)

**Comment by bartouse01** [comment]
![image](https://user-images.githubusercontent.com/40664102/178993273-5fbf5960-e7a1-4d21-b3ba-2c5d59be8ec8.png)

**Comment by fsidhoum** [comment]
![image](https://user-images.githubusercontent.com/4265519/178995006-da0bf78e-d25f-4ae2-b658-7fc2d5014603.png)

**Comment by bartouse01** [comment]
csv files for any helpful details needed to analyse this issue

[Network Traffic Tx by Bytes-data-2022-07-14 15_42_05.csv](https://github.com/massalabs/massa/files/9112293/Network.Traffic.Tx.by.Bytes-data-2022-07-14.15_42_05.csv)
[Network Traffic Rx by Bytes-data-2022-07-14 15_42_05.csv](https://github.com/massalabs/massa/files/9112294/Network.Traffic.Rx.by.Bytes-data-2022-07-14.15_42_05.csv)
[CPU Busy-data-2022-07-14 15_39_50.csv](https://github.com/massalabs/massa/files/9112295/CPU.Busy-data-2022-07-14.15_39_50.csv)
[Memory Basic-data-2022-07-14 15_36_44.csv](https://github.com/massalabs/massa/files/9112296/Memory.Basic-data-2022-07-14.15_36_44.csv)

**Comment by qdrn** [comment]
Two other nodes crashed as well. Might be related. Here are the logs: https://file.io/3y5PK8lfcnEH

**Comment by rykcod** [comment]
Same issue here, Yesterday at 14h33, ram consumption exceed 26gB

**Comment by damip** [comment]
Didn't manage to reproduce it on the tesnet with heaptrack running.

![export2](https://user-images.githubusercontent.com/10211103/179767691-23111ad5-c2f7-4b2d-9fdc-e8ab6de1ad91.jpg)
![export1](https://user-images.githubusercontent.com/10211103/179767697-fc3e3105-a983-456f-969e-319df7298127.jpg)

**Comment by AurelienFT** [comment]
This memory issue as been fixed in newer testnet.
