### ISSUE TITLE
Medium scale simulation

### ISSUE THREAD

**Issue by damip** [massalabs/massa#2813]
## Description

In the following cases, the testnet is not flexible enough, the labnet is too small, and the docker simulations are not powerful enough:
* git bisect to find bugs such as https://github.com/massalabs/massa/issues/2810
* realistic CI-based performance evaluation

## Requirement

We need a middle ground.

Have 30 servers following the expected node specs, and a script allowing to:
* deploy a network at a given commit on the 30 servers
* run transaction spam
* monitor the nodes and gather performance reports
* present the reports in a way that allows comparing with other runs (eg. to detect changes and regressions, and to make bisects)

**Comment by damip** [comment]
We might already need this thing to debug https://github.com/massalabs/massa/issues/2810

**Comment by AurelienFT** [comment]
Closing now that this simulator exist here : https://github.com/massalabs/massa-k8s-simulator . If features on this are needed create an issue on this repository
