### ISSUE TITLE
Endpoint for Kyve

### ISSUE THREAD

**Issue by qdrn** [massalabs/massa#2830]
@fabianriewe

**Comment by johnletey** [comment]
Hey, @qdrn 👋🏻  Thanks for opening this issue!

On our side - we need an endpoint to be able to fetch a block by a specific height.

The current way of doing this is by fetching all blocks produced during a specific timeframe, which isn't optimal for us.

**Comment by damip** [comment]
So basically fetch the blockclique block that is at a given slot, if any ?

**Comment by qdrn** [comment]
> Hey, @qdrn 👋🏻 Thanks for opening this issue!
> 
> On our side - we need an endpoint to be able to fetch a block by a specific height.
> 
> The current way of doing this is by fetching all blocks produced during a specific timeframe, which isn't optimal for us.

There is not a height in our architecture. The closest thing is the period and thread. You could in principle define a height by `height = period * 32 + thread`.

**Comment by damip** [comment]
Such an endpoint will be available in v14

**Comment by damip** [comment]
done for v14
