### ISSUE TITLE
Execution thread panicked

### ISSUE THREAD

**Issue by damip** [massalabs/massa#2840]
Execution was very late because it was running to slowly.

Then, the execution thread panicked:

```
thread '<unnamed>' panicked at 'Missing block in storage.', massa-execution-worker/src/execution.rs:639:25
```

but the program didn't stop.

TODO:
* ensure that when the execution thread (and other threads) panic, the whole program stops
* ensure that the execution thread does not panick if it's too late. Make it force-keep the blocks in storage (prevent their removal) and print a warning

**Comment by damip** [comment]
@gterzian can you take a look ?

**Comment by gterzian** [comment]
> ensure that when the execution thread (and other threads) panic, the whole program stops

I think we can look into using https://doc.rust-lang.org/beta/std/panic/fn.set_hook.html (see the example mentioned at https://stackoverflow.com/questions/66790155/what-is-the-recommended-way-to-propagate-panics-in-rust-tokio-code)


> ensure that the execution thread does not panick if it's too late. Make it force-keep the blocks in storage (prevent their removal) and print a warning

I think this one can be done as part of a general change of how shared storage prunes, see
https://github.com/massalabs/massa/issues/2750
