### ISSUE TITLE
Add ARM build in CI for release.

### ISSUE THREAD

**Issue by AurelienFT** [massalabs/massa#2854]
Hello the Massa team,

It would be great if, when you release a new version, a package with ARM architecture compatible binaries is also generated.

This is not a blocking issue because ARM processor users can build the binaries directly from the sources but it would be more convenient if the binaries would be included in the release.

_Originally posted by @fsidhoum in https://github.com/massalabs/massa/discussions/2812_

**Comment by fsidhoum** [comment]
I am working in this issue.

Should we generate an ARM64 package for windows and macOS too, or only for linux ?

**Comment by AurelienFT** [comment]
> I am working in this issue.
> 
> Should we generate an ARM64 package for windows and macOS too, or only for linux ?

The more it's the best IMO

**Comment by qdrn** [comment]
> I am working in this issue.
> 
> Should we generate an ARM64 package for windows and macOS too, or only for linux ?

It is likely that you will need to update the docker image that is currently used by the CI/CD. If that's the case then ping me so that I can update it.

**Comment by fsidhoum** [comment]
> > I am working in this issue.
> > Should we generate an ARM64 package for windows and macOS too, or only for linux ?
> 
> It is likely that you will need to update the docker image that is currently used by the CI/CD. If that's the case then ping me so that I can update it.

I managed to build an ARM package for linux. To do so, I didn't change the Docker image used by Github Actions. I used the argument "use-cross" in the "actions-rs/cargo@v1" step.

Changing the "ubuntu-18.04" image will not have any affect while the Github Actions runner use an x86_64 architecture. And there is not arm64 public runner available.

I have done some tests with the arm64 binairies : this works great.
I have to do some more for x86_64 binairies, then I will be ready to do a pull request.

**Comment by qdrn** [comment]
> > > I am working in this issue.
> > > Should we generate an ARM64 package for windows and macOS too, or only for linux ?
> > 
> > 
> > It is likely that you will need to update the docker image that is currently used by the CI/CD. If that's the case then ping me so that I can update it.
> 
> I managed to build an ARM package for linux. To do so, I didn't change the Docker image used by Github Actions. I used the argument "use-cross" in the "actions-rs/cargo@v1" step.
> 
> Changing the "ubuntu-18.04" image will not have any affect while the Github Actions runner use an x86_64 architecture. And there is not arm64 public runner available.
> 
> I have done some tests with the arm64 binairies : this works great. I have to do some more for x86_64 binairies, then I will be ready to do a pull request.

Great!

**Comment by fsidhoum** [comment]
I have opened a new pull request [here](https://github.com/massalabs/massa/pull/2864).

**Comment by damip** [comment]
this was merged :) congrats
