### ISSUE TITLE
Extend getSmartContractEvents filter to include candidate and final states (separately and both)

### ISSUE THREAD

**Issue by BatiGencho** [massalabs/massa#2857]
Currently the event filter looks like this:
`
export interface IEventFilter {
    start: ISlot;
    end: ISlot;
    emitter_address: string;
    original_caller_address: string;
    original_operation_id: string;
}
`
It would be splendid to add a new key called e.g. `state` which could be an `enum State { Candidate, Final}` mapping to 0, 1 e.g. over RPC. This way the new filter will allow a selection of either events in the candidate/final states. Not providing a filter should return both which is the current behavior right now.

**Comment by Eitu33** [comment]
This has been done in https://github.com/massalabs/massa/pull/2862 at commit [3932bfd](https://github.com/massalabs/massa/pull/2862/commits/3932bfd20638bc58b504e18ddf448af03c202bdf)

**Comment by Eitu33** [comment]
https://github.com/massalabs/massa/pull/2875

**Comment by Eitu33** [comment]
@BatiGencho there should be a new field called `candidate` which can be:

- true => resolves to only candidate events
- false => resolves to only final events
- null => resolves to final _and_ candidate events

**Comment by damip** [comment]
Let's also add a `is_final` boolean in the elements of the returned list of events

**Comment by BatiGencho** [comment]
@Eitu33 ok, np, I will change it. Is the labnet also up-to-date with the new key ? If not, can you please deploy it ?
