### ISSUE TITLE
Operation serialization doesn't use shared storage anymore

### ISSUE THREAD

**Issue by gterzian** [massalabs/massa#2858]
See the change at https://github.com/massalabs/massa/commit/dee19b7101ecc044cb09ebd130b2c454ff1a2aa8#diff-2350ca2a3fef681c7029e38fa91036024b30b38322f5807357e98ec037030873R197

I'm wondering why that is? cc @AurelienFT

**Comment by gterzian** [comment]
Also in the binder, when receiving a message, we don't use shared storage to store the serialized form, see https://github.com/massalabs/massa/commit/d8f02c2b3215163e7bbc5b6790086adc35edf471#diff-bf77be238d8a5b9bee3a957cdc4cd0532bfbcff273505b3227b0bfd65ab5f91eR156

**Comment by AurelienFT** [comment]
> See the change at [dee19b7#diff-2350ca2a3fef681c7029e38fa91036024b30b38322f5807357e98ec037030873R197](https://github.com/massalabs/massa/commit/dee19b7101ecc044cb09ebd130b2c454ff1a2aa8#diff-2350ca2a3fef681c7029e38fa91036024b30b38322f5807357e98ec037030873R197)
> 
> I'm wondering why that is? cc @AurelienFT

The operations now have their serialized form stored with them directly as they are `WrappedOperation`.

**Comment by gterzian** [comment]
Thanks for the info!
