### ISSUE TITLE
Storage indexing

### ISSUE THREAD

**Issue by damip** [massalabs/massa#2866]
Currently, the API allows retrieving a block by ID, searching for all the operations emitted by a given address, listing blocks within a slot range etc... Those searches are done by interrogating many modules.

To simplify things, Storage should perform this indexing.

The current implementation

```rust
pub struct Storage {
    // ...
    operations: Arc<RwLock<Map<OperationId, WrappedOperation>>>,
   // ...
}
```

can be changed to

```rust
pub struct Storage {
    // ...
    operations: Arc<RwLock<OperationIndex>>,
   // ...
}

pub struct OperationIndex {
    operations: Map<OperationId, WrappedOperation>,
    index_by_creator: Map<Address, OperationId>,
   //...
}
```

Such an indexing will allow the API to directly call things like `let search_result: HashSet<Address> = storage.get_operations_created_by(addr)` without interrogating other modules.

Required indices:

- [x]  operations by creator addr
- [x]  endorsements by creator addr
- [x]  blocks by creator addr
- [x]  blocks by slot (to retrieve lists of blocks by slot range)
- [x]  endorsements by block id in which they are included
- [x]  operations by block id in which they are included

Open PR towards `release_testnet_14`

**Comment by adrien-zinger** [comment]
https://github.com/massalabs/massa/pull/2862/commits/6815a2ef0d8b38a08ed4d0f31b65f8f319c875e1

**Comment by damip** [comment]
> code here [6815a2e](https://github.com/massalabs/massa/commit/6815a2ef0d8b38a08ed4d0f31b65f8f319c875e1)

Nice !

For clarity I would recommend declaring batch_insert and batch_remove functions in `impl OperationIndex` instead of directly inserting/deleting from that structure. Also maybe moving everything related to operationindex to a new file for clarity
