### ISSUE TITLE
get_blockclique_block_at_slot

### ISSUE THREAD

**Issue by damip** [massalabs/massa#2869]
Implement `get_blockclique_block_at_slot(slot: Slot) -> Option<BlockId>` (currently a skeleton in `release_testnet_14`) that returns the blockclique block ID (or None if there is none) at the provided slot.

Before https://github.com/massalabs/massa/issues/2866 is implemented, this can be done naively by scanning all the blocks in the blockclique within `consensus.block_db` and returning the ID of the one (if any) that matches the desired slot.

Once https://github.com/massalabs/massa/issues/2866 is implemented, Storage can be interrogated directly for the list of all block IDs that belong to the target slot. Then only the one (if any) that is present inside the blockclique should be conserved.

Open a PR towards `release_testnet_14`

**Comment by AurelienFT** [comment]
First implementation made #2862
