### ISSUE TITLE
Ensure that Storage and Pool are used properly in the Protocol module

### ISSUE THREAD

**Issue by gterzian** [massalabs/massa#2883]
Part of https://github.com/massalabs/massa/pull/2862

**Comment by gterzian** [comment]
Note that the interface to pool has changed, actually in the [new interface](https://github.com/massalabs/massa/pull/2862/files#diff-fdd55872f57360f9a4ae73ab6a3988a750d5d35c9786f104f883f99936e353c4R16) I don't see a mechanism currently that matches the previous "propagate these operations" as was available in https://github.com/massalabs/massa/blob/d315aadbdc25a91b4bb160952c56d7026748fcef/massa-pool/src/pool_worker.rs#L326

Should we add such a mechanism? It could be used to avoid propagating operations received inside the new "block info" workflow(see https://github.com/massalabs/massa/pull/2862/files#diff-cd40aa0563a3ce2721769e8d6fb242a0e813ab40a0c119977fc9b144505ba7cdR58).  cc @massalabs/core-team

**Comment by damip** [comment]
> Note that the interface to pool has changed, actually in the [new interface](https://github.com/massalabs/massa/pull/2862/files#diff-fdd55872f57360f9a4ae73ab6a3988a750d5d35c9786f104f883f99936e353c4R16) I don't see a mechanism that matches the previous "propagate these operations" as was available in
> 
> https://github.com/massalabs/massa/blob/d315aadbdc25a91b4bb160952c56d7026748fcef/massa-pool/src/pool_worker.rs#L326
> 
> Should we add such a mechanism? It could be used to avoid propagating operations received inside the new "block info" workflow(see https://github.com/massalabs/massa/pull/2862/files#diff-cd40aa0563a3ce2721769e8d6fb242a0e813ab40a0c119977fc9b144505ba7cdR58). cc @massalabs/core-team

We need something more advanced, see followup: https://github.com/massalabs/massa/issues/2904
