### ISSUE TITLE
Use new storage system for protocol -> network

### ISSUE THREAD

**Issue by gterzian** [massalabs/massa#2886]
I don't understand where the actual operations are sent.
Shouldn't this be `Operations(Vec<WrappedOperation>),` ?

_Originally posted by @damip in https://github.com/massalabs/massa/pull/2862#discussion_r947139131_

**Comment by damip** [comment]
done in https://github.com/massalabs/massa/pull/2888

**Comment by damip** [comment]
Let's keep full objects in network (no Storage)
