### ISSUE TITLE
Reinstate header checks by Consensus

### ISSUE THREAD

**Issue by damip** [massalabs/massa#2900]
We used to have the following workflow:
* receive a header from a node in Protocol => check the header by sending it to Consensus
* Consensus then responds with a wishlist of what we need to get (other headers, full blocks, or just nothing if the header was stale/invalid within the graph)

We seem to have lost this at some point, and now we always download the whole blocks before checking that their header fits in the graph. As a consequence, whenever we are connected to a desync node, we will download all its stale blocks in full.

TODO: put back this workflow

**Comment by gterzian** [comment]
It looks like the workflow is still in place, as part the testnet 14 branch:

1. When we [receive a header](https://github.com/massalabs/massa/blob/48c525fa071c19176858d7712ae1c39226903cf1/massa-protocol-worker/src/protocol_network.rs#L85), we send it to consensus.
2. When consensus [sends us an updated wishlist](https://github.com/massalabs/massa/blob/48c525fa071c19176858d7712ae1c39226903cf1/massa-protocol-worker/src/protocol_worker.rs#L396), we add the block to the "ask block workflow".

**Comment by damip** [comment]
> It looks like the workflow is still in place, as part the testnet 14 branch:
> 
>     1. When we [receive a header](https://github.com/massalabs/massa/blob/48c525fa071c19176858d7712ae1c39226903cf1/massa-protocol-worker/src/protocol_network.rs#L85), we send it to consensus.
> 
>     2. When consensus [sends us an updated wishlist](https://github.com/massalabs/massa/blob/48c525fa071c19176858d7712ae1c39226903cf1/massa-protocol-worker/src/protocol_worker.rs#L396), we add the block to the "ask block workflow".

You're right, I missed it in the code. Thanks !
