### ISSUE TITLE
Repair pool tests

### ISSUE THREAD

**Issue by damip** [massalabs/massa#2906]
All pool tests were commented in https://github.com/massalabs/massa/pull/2888

TODO: reinstate them

**Comment by Ben-PH** [comment]
https://github.com/massalabs/massa/pull/2888/files?diff=split&w=1#diff-a4f37a39fbaab187eddc99f26c53ab25fcf38954ffc9c4f7b2233fbf7b988aed

**Comment by Ben-PH** [comment]
#3846 should close this one.

**Comment by Ben-PH** [comment]
Closed by linked PR merging. In process of follow-up PR which is non-functional cleanup.
