### ISSUE TITLE
Critical Protocol unit tests

### ISSUE THREAD

**Issue by damip** [massalabs/massa#2907]
We need to add the most critical unit tests to Protocol, especially to test the new block propagation with different edge cases.

@gterzian can you take care of it with a end-of-the-week deadline so that we can spend next week running end-to-end testing ?

**Comment by gterzian** [comment]
Yes, don't think it can be done by the end of the week, and I don't see why it cannot be done in parallel to end-to-end testing...

**Comment by damip** [comment]
> Yes, I'll start to go through the still ignored tests, and I think it will have to be finished next week in parallel to end-to-end testing(which will probably reveal edge cases for which we'll have to write tests and fixes)...

OK, let's just make sure that we have at least 1 or 2 critical tests passing (eg. block propagation) before the week end, then we will continue with the rest (eg. edge cases) next week.

> Do you have any specific edge cases in mind?

For the edge cases, mostly unexpected node disconnection, nodes sending unexpected stuff, storage drop midway etc...
