### ISSUE TITLE
Protocol problems

### ISSUE THREAD

**Issue by damip** [massalabs/massa#2935]
* objects must not be sent to Storage before their signatures are verified. Signature verif happens in Protocol (with cache control). Therefore, only full objects must be transferred between Protocol and Network.
* Network uses an overcomplicated and redundant sending/receiving system that was created at the beginnings of Storage. It should be refactored back to simply sending/receiving serializable `Message`s. All links with Storage should be removed in Network.
* Many memory leaks in Storage management within Protocol. For example, full blocks and their dependencies are added to self.storage when they need to be propagated, but only operations removed from the signature verif cache are ever removed from self.storage
* Signature verification caches (eg. checked_headers) are misused for block retrieval status management and could be cleared anytime

**Comment by gterzian** [comment]
Thanks for noting.

**Comment by gterzian** [comment]
> objects must not be sent to Storage before their signatures are verified. Signature verif happens in Protocol (with cache control). Therefore, only full objects must be transferred between Protocol and Network.

> 
Network uses an overcomplicated and redundant sending/receiving system that was created at the beginnings of Storage. It should be refactored back to simply sending/receiving serializable Messages. All links with Storage should be removed in Network.

I think these two were done already by @AurelienFT in https://github.com/massalabs/massa/pull/2937

**Comment by gterzian** [comment]
> Many memory leaks in Storage management within Protocol. For example, full blocks and their dependencies are added to self.storage when they need to be propagated, but only operations removed from the signature verif cache are ever removed from self.storage

I think it's a good example of a problem introduced by the current "per component" approach to manage the lifetime of objects in storage. 

It's quite hard to know when a block can be "dropped" locally by protocol, for example: Should it be done when all active nodes have been noted as knowing about it? What about if a new node connects, and the block is actually still relevant? 

On the other hand, consensus can know when a block is so old that no node should ever need it anymore. 

And protocol can just "check storage" when a node asks about something, and if it's gone, just answer "not found". 

So protocol uses storage in a "dumb" way, without knowing when objects are to be dropped. 

On the other hand, something like execution can keep an `Arc` to a block it still needs to execute, so that even if consensus removes it from storage it can still be executed(if execution is very busy or something, although the other problem then could be running out of memory). 

@damip

**Comment by damip** [comment]
> > Many memory leaks in Storage management within Protocol. For example, full blocks and their dependencies are added to self.storage when they need to be propagated, but only operations removed from the signature verif cache are ever removed from self.storage
> 
> I think it's a good example of a problem introduced by the current "per component" approach to managing the lifetime of objects in storage.
> 
> It's quite hard to know when a block can be "dropped" locally by protocol, for example: Should it be done when all active nodes have been noted as knowing about it? What about if a new node connects, and the block is actually still relevant?
> 
> On the other hand, consensus can know when a block is so old that no node should ever need it anymore.
> 
> And protocol can just "check storage" when a node asks about something, and if it's gone, just answer "not found".
> 
> So protocol could use storage in a "dumb" way, without knowing when objects are to be dropped.

Basically from what I understand, in protocol we should just not use `self.storage` for storing things, just ignore them if they are absent at the moment of handling them.

See https://github.com/massalabs/massa/pull/2948

Maybe just in the case of the block retrieval process, keep the accumulated storage of the ops we "already have so far for this block".

> 
> On the other hand, something like execution can keep an `Arc` to a block it still needs to execute, so that even if consensus removes it from storage it can still be executed(if execution is very busy or something, although the other problem then could be running out of memory).
> 
> @damip

@gterzian  another thing: what happens when the remote node disconnects or just stops responding to our requests at a given step of the block retrieval process ? is it properly handled ? do we ask another node ? or does the block just remain in the wishlist forever without being retrieved ?

**Comment by gterzian** [comment]
> Basically from what I understand, in protocol we should just not use self.storage for storing things, just ignore them if they are absent at the moment of handling them.

Yes I think so. 

> Maybe just in the case of the block retrieval process, keep the accumulated storage of the ops we "already have so far for this block" as it was done by adding a storage to wishlist elements.

I sort of prefer using something like `checked_headers` that contains the necessary info, as opposed to the stuff in storage directly. That way it's one concurrency thing less to worry about. 

> as it was done by adding a storage to wishlist elements.

Yes actually I saw that, and was wondering what it was for, as I think it's not actually used right now.
