### ISSUE TITLE
Read-only `execute_read_only_call`s need to return serialized data in the response the right way

### ISSUE THREAD

**Issue by BatiGencho** [massalabs/massa#2951]
Some smart contracts have read-only view functions like:

```
export function getSomeData(address: string): string {
  const data = Storage.get("KEY");
  generateEvent(data);

  return data;
}
```

which currently require us to generate an event and this way return the data we want. The data is then under: `data.output_events`. Now, we want the vm execution output to be a string forwarded over rpc to the caller. If the user wants, he could serialize more complex objects on the AS side using as-json. On the receiver side (massa-web3), the returned string will be deserialized into whatever object we are expecting. The web3 call will thus be parametrized over T, such that:

```
function readSmartContract<T>(...): T {
  // do the Json rpc call
  
  const jsonRpcCallReturnedData = await rpc_call().;
  return  JSON.parse<T>(jsonRpcCallReturnedData.return_value); // here return_value can be a new key in the response ????
}
```

This new approach will require core changes but will eliminate the necessity to generate events with the returned data as we have to do right now.

**Comment by AurelienFT** [comment]
Fixed in https://github.com/massalabs/massa/pull/3339
