### ISSUE TITLE
Add checks on object deserialization

### ISSUE THREAD

**Issue by damip** [massalabs/massa#2953]
* inside block header deserialization add the following checks:
  * check the signature (now we can because we see each object only once)
  * check that (parents.count == 0) == (slot.period == 0)
  * check that if slot.period == 0 we have no endorsements
  * check the signatures of the endorsements
  * check that the endorsements all target the parent block in the same thread (if not genesis)
  * check that the `index` of every endorsement does not repeat 
  * check that the `index` of every endorsement does not overflow endorsement_count-1

* inside op deserialization:
  * check signature

* inside endorsement deserialization:
  * check signature

**Comment by AurelienFT** [comment]
Most of the checks are maybe implemented. A verification needs to be done to know what needs to be updated.

**Comment by Ben-PH** [comment]
is `(parents.count == 0) == (slot.period == 0) ` evals to true, that's an error?

**Comment by AurelienFT** [comment]
> is `(parents.count == 0) == (slot.period == 0) ` evals to true, that's an error?

No because it's a special case the genesis blocks that don't have parents. They are identified by having no parents.

**Comment by Ben-PH** [comment]
#3364

**Comment by Ben-PH** [comment]
also check if slot !=0 that parent count == thread count
