### ISSUE TITLE
Make tests compile and pass

### ISSUE THREAD

**Issue by damip** [massalabs/massa#2961]
* [x] consensus tests don't compile @gterzian 
* [x] factory tests timeout @Eitu33 
* [x] final-state tests don't compile @Eitu33 
* [x] massa-ledger tests don't compile
* [x] network tests don't compile @gterzian 
* [x] pool tests don't pass
* [x] PoS tests don't compile

**Comment by Eitu33** [comment]
FI I'm taking factory final state and ledger for now.

**Comment by damip** [comment]
@gterzian can you take care of consensus and network ?

**Comment by gterzian** [comment]
@damip I'll do network first, I haven't been much involved with the consensus changes so perhaps the relevant person can do it? Otherwise I'll give it a try after network...

**Comment by Eitu33** [comment]
For anyone that will work on it since I will be moving on to something else, the branch I worked on for the Factory, Final state and Ledger tests is `fix-factory-ledger-state-tests`. Final state and Ledger tests are ok but Factory tests still need some changes.
