### ISSUE TITLE
Disapperaing checks on operations

### ISSUE THREAD

**Issue by gterzian** [massalabs/massa#2963]
While working on https://github.com/massalabs/massa/pull/2946

I've noticed the following checks on incoming operations have gone missing:

1. Validity period
2. Duplicates
3. Correct thread

I've re-added the thread check, not sure about the others.

**Comment by damip** [comment]
@gterzian 

As per https://github.com/massalabs/massa/pull/2727#issuecomment-1179096745 those checks shouldn't invalidate the block, they were removed from protocol and moved to this function: https://github.com/massalabs/massa/blob/release_testnet_14/massa-execution-worker/src/execution.rs#L267 

So it's important to keep those tests outside of protocol

**Comment by gterzian** [comment]
Ok, thanks for the info, removed from https://github.com/massalabs/massa/pull/2946
