### ISSUE TITLE
Network: maybe missing check on serialization of AskForBlocks

### ISSUE THREAD

**Issue by gterzian** [massalabs/massa#2971]
> i don't understand what we are not checking ? The number of informations asked ? In serialization/deserialization

Yes it's the number of asks, in the serialization. Compare how the de-serializer uses `max_ask_block` in the `U32VarIntDeserializer`.  @AurelienFT

_Originally posted by @gterzian in https://github.com/massalabs/massa/issues/2967#issuecomment-1239010256_

**Comment by AurelienFT** [comment]
We never have limits on the serializers because they are used with internal data.

**Comment by damip** [comment]
Bottomline: we trust our own data, so no serialization checks. We don't trust incoming data: we check on deserialization
