### ISSUE TITLE
error[E0658]: `let` expressions in this position are unstable

### ISSUE THREAD

**Issue by hicaru** [massalabs/massa#2974]
`rustc 1.63.0 (4b91a6ea7 2022-08-08)`
`cargo 1.63.0 (fd9c4297c 2022-07-01)`

add to `massa-bootstrap/src/lib.rs` `#![feature(let_chains)]` to avoid `E0658 error`

**Comment by damip** [comment]
Recently rust dropped support for if let chains, and put them back as experimental after finding some bugs.
We added back the feature for the testnet 14.

If you want it to work with testnet 13, you need to either pin your rustc version to an older one, or enable the features as you said

**Comment by hicaru** [comment]
Got it, thanks for quick answer)
