### ISSUE TITLE
Change endorsements

### ISSUE THREAD

**Issue by qdrn** [massalabs/massa#2976]
Endorsements should satisfy the following constraints:
- Endorsements should be created and propagated to the network by endorsers at half-slot time.
- Endorsements should endorse the best parent in the given thread as seen by the endorser at this timestamp.
- Endorsements created at a half-period can only be included in the block of the next period.

Side note: currently when we include the endorsements in a block we verify that they endorse the parent of the created block in this thread.

cc @sebastien-forestier @leoloco

**Comment by damip** [comment]
## Current implementation

Currently, we PoS-select endorsement creators targeting the blockclique block at slot `(period, thread)` if any.
The endorsements selected at `(period, thread)` are created/emitted at time `genesis_timestamp + period * t0 + thread * (t0/thread_count) + t0/2`.

## Implementation change

We need to PoS-select endorsement creators that are allowed to be included in blocks at slot `(period, thread)`.
The endorsements selected at `(period, thread)` are created/emitted at time `genesis_timestamp + period * t0 + thread * (t0/thread_count) - t0/2` and endorse the best_parent of their thread.

**Comment by sebastien-forestier** [comment]
One additionnal change to be discussed: take into account the compatible endorsements in the pool to compute the cliques fitness

**Comment by qdrn** [comment]
> One additionnal change to be discussed: take into account the compatible endorsements in the pool to compute the cliques fitness

What cases do you have in mind ? If you create a block you create the one that gives the clique with the highest fitness (I guess ?). If you create endorsements then you probably don't have the other endorsements.

**Comment by damip** [comment]
Part 1 is done here: https://github.com/massalabs/massa/pull/3004
Not merging yet (breaking)

**Comment by AurelienFT** [comment]
Waiting for feeedback from research team.

**Comment by qdrn** [comment]
I think we can close this one. Right ?

**Comment by AurelienFT** [comment]
> take into account the compatible endorsements in the pool to compute the cliques fitness

This hasn't been discuss but could be moved to a discussion

**Comment by qdrn** [comment]
> 

Yeah, I don't think it belongs to an issue.
