### ISSUE TITLE
Improve documentation regarding SCs

### ISSUE THREAD

**Issue by qdrn** [massalabs/massa#2996]
I find it weird to use `npx as init .` to initialise the SC folder in the doc (https://docs.massa.net/en/latest/smart-contracts/getting-started.html) as we have a custom npx command `npx massa-sc-create your-sc` to initialise a directory with the right `package.json` file. It would probably better to update the `massa-sc-template` folder if we find it does not suit our needs.

Also the second line of these commands does not work (on my computer)
```
npx asinit .
npx asp --init
```
I get the following error:
```
npm ERR! could not determine executable to run

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/adrien/.npm/_logs/2022-09-12T12_18_34_188Z-debug-0.log
```

wdyt @gregLibert @AurelienFT ?

**Comment by gregLibert** [comment]
I'm not using massa-sc-create.
But if you want to do a barebone install, before using `npx asinit .`you should first do:
```shell
npm init
npm install --save-dev assemblyscript
```

Source [here](https://www.assemblyscript.org/getting-started.html#setting-up-a-new-project).

**Comment by AurelienFT** [comment]
I think massa-sc-create could be a really help for developers if it works well.

We should maintain it update to date and make it a one-liner.

**Comment by qdrn** [comment]
> I'm not using massa-sc-create. But if you want to do a barebone install, before using `npx asinit .`you should first do:

I know. That's my point. Why using `npx asinit .` when we can use `npx massa-sc-create xxx` ? It serves almost the same purpose. Except that in the case of `massa-sc-create` we can tailor it to our needs.
