### ISSUE TITLE
Double-endorsement denunciations

### ISSUE THREAD

**Issue by damip** [massalabs/massa#3022]
When the same staker produces two different endorsements for the same (slot, index), allow propagating a proof of the cheating. This proof can be included in blocks to slash the offender and credit the block producer.

**Comment by AurelienFT** [comment]
Blocked waiting for network refactor and feedback from research team

**Comment by qdrn** [comment]
This part will probably be needed in any case. It's probably how it's used elsewhere that'll probably change.

**Comment by AurelienFT** [comment]
This has been done in TEST.22 with denunciation implementation
