### ISSUE TITLE
Block finality too slow

### ISSUE THREAD

**Issue by damip** [massalabs/massa#3036]
We observed on the testnet 14 that block finality takes 8 cycles instead of 2, and there are all the time 3-4 cliques instead of 1.

This may stem from problems in block propagation (most likely), untimely or wrong-parent block production, or consensus (least likely since everyone seems to keeps their block list in sync).

This can also be at the origin of the slow-execution problem: if finality time explodes and cliques switch all the time, it might require a lot of re-executions.

Note that https://github.com/massalabs/massa/issues/3033 does not solve potential block propagation problems because if a node A announces a block to a node B, it means that node A has all the operations of that block and B should promptly get all the operations it lacks from A through the block retrieval process.

**Comment by AurelienFT** [comment]
It seems that each time someone double stake. It creates a new clique that take an enormous amount of time to "disappear" (have a fitness of 0) (like 20 seconds).

**Comment by AurelienFT** [comment]
I think the problem is the same with endorsements as for operations.

**Comment by damip** [comment]
Good catch @AurelienFT
