### ISSUE TITLE
PoS bootstrap fails in the 3 first cycles

### ISSUE THREAD

**Issue by damip** [massalabs/massa#3037]
We observe in testnet 14 that bootstrapping during the first 3 cycles immediately yields a wrong set of draws. This does not happen to nodes that didn't bootstrap. It also doesn't happen after the first 3 cycles anymore.

**Comment by AurelienFT** [comment]
This message is triggered on the first blocks received : Bad creator turn for the slot:

**Comment by damip** [comment]
In the end, it wasn't an error, but a local problem of config files
