### ISSUE TITLE
Robustify testnet15 feature Ledger Hash

### ISSUE THREAD

**Issue by damip** [massalabs/massa#3050]
* [x] document all added functions
* [x] try in sandbox/simulation/labnet:
  * hash matching after bootstrap
  * operations and their effects on the hash
  * hashes matching between nodes after smart contract interactions
* [x] add unit tests on the added features
* [x] add logs allowing easy debugging in case the changes caused problems

**Comment by Eitu33** [comment]
- [ ] Ledger hash unit tests
- [ ] Executed ops unit tests

**Comment by Eitu33** [comment]
- [ ] try in sandbox
- [ ] try in simulation

**Comment by Eitu33** [comment]
Everything works 🚀
