### ISSUE TITLE
Robustify testnet15 feature ExecuteSC datastore

### ISSUE THREAD

**Issue by damip** [massalabs/massa#3051]
* [x] document all added functions
* [x] try in sandbox/simulation/labnet:
  * bootstrap
  * client
  * try executing some ExecuteSC operations with datastore interactions
* [x] add unit tests on the added features
* [x] add logs allowing easy debugging in case the changes caused problems

**Comment by sydhds** [comment]
Forgot some hardcoded values, @ this line:

let deserializer = DatastoreDeserializer::new(10000, 255, 10000);

**Comment by sydhds** [comment]
Unit ests have been already merged

**Comment by sydhds** [comment]
Using curl + public abi demonstrate an issue in a massa-sc-runtime SC (op_fn.ts). Currently investigating the issue...

**Comment by sydhds** [comment]
* https://github.com/massalabs/massa-sc-runtime/pull/151
* https://github.com/massalabs/massa/pull/3088/files
