### ISSUE TITLE
Refund part of gas when operation don't use all.

### ISSUE THREAD

**Issue by AurelienFT** [massalabs/massa#3063]
**Is your feature request related to a problem? Please describe.**
If we create a SC that make little operations that cost only 10 gas for example and set up a max_gas to 10_000 we will be debited of 10_000 and not only 10

**Describe the solution you'd like**
We have to refun the 9_990 left

**Describe alternatives you've considered**
/

**Additional context**
/

**Comment by damip** [comment]
Fundamental problem: for a block producer to be able to choose which operations to include, they will have to run every SC operation to see how much fees they will pocket vs how much will be reimbursed to the operation sender

**Comment by damip** [comment]
> > Fundamental problem: for a block producer to be able to choose which operations to include, they will have to run every SC operation to see how much fees they will pocket vs how much will be reimbursed to the operation sender
> 
> Ok so it will be to the dApps and wallet to choose how much max_gas to send in their operations depending on the SC they execute ? To avoid their users to spend too much ?

Ideally they can use a readonly execution to estimate, or we provide something like https://docs.ethgasstation.info/

**Comment by AurelienFT** [comment]
Ok I close this then. Thanks for explanations.
