### ISSUE TITLE
Check signature verif performance

### ISSUE THREAD

**Issue by damip** [massalabs/massa#3071]
Bench with ed25519_dalek: 10 000 000 verifs in 377359 milliseconds. That's 190 milliseconds to verify a full block (5000 + 1 + 9 signatures)

TODO: are there faster crates implementing the same algo ? 

TODO: is there a way to parallelize verif ?

TODO: use [ed25519_dalek](https://docs.rs/ed25519-dalek/latest/ed25519_dalek/index.html)::[verify_batch](https://docs.rs/ed25519-dalek/latest/ed25519_dalek/fn.verify_batch.html) ?

(eg. is https://docs.rs/ring-compat/latest/ring_compat/ a good alternative ? or https://github.com/jedisct1/rust-ed25519-compact ?)

Also, we shouldn't be using the crypto implem directly, but through https://docs.rs/ed25519/latest/ed25519/ which allows supporting HSM and other things

**Comment by gterzian** [comment]
Operation verification for a block occurs there:

https://github.com/massalabs/massa/blob/88f833185ff2bdc177dfc7ab9e0d02f5b5fd8204/massa-protocol-worker/src/protocol_worker.rs#L930

I propose we simply create a vector of operations to verify(those not found in `checked_operations`), and to the verification using a [parallel iterator](https://docs.rs/rayon/latest/rayon/iter/index.html) from rayon.

[ed25519_dalek](https://docs.rs/ed25519-dalek/latest/ed25519_dalek/index.html)::[verify_batch](https://docs.rs/ed25519-dalek/latest/ed25519_dalek/fn.verify_batch.html) seems to come with all kinds of warnings on how to use it, so I propose we look into that only later if necessary.

**Comment by damip** [comment]
> Operation verification occurs there:
> 
> https://github.com/massalabs/massa/blob/88f833185ff2bdc177dfc7ab9e0d02f5b5fd8204/massa-protocol-worker/src/protocol_worker.rs#L930
> 
> I propose we simply create a vector of operations to verify(those not found in `checked_operations`), and do the verification using a [parallel iterator](https://docs.rs/rayon/latest/rayon/iter/index.html) from rayon.

That's cool

> 
> [ed25519_dalek](https://docs.rs/ed25519-dalek/latest/ed25519_dalek/index.html)::[verify_batch](https://docs.rs/ed25519-dalek/latest/ed25519_dalek/fn.verify_batch.html) seems to come with all kinds of warnings on how to use it, so I propose we look into that only later if necessary.

Those warnings are the same as the ones on the nornal "verify" so no extra danger here, and using it is probably a good idea for batches in rayon

**Comment by damip** [comment]
The underlying problem we have is that we don't batch operation announcement / asking properly (we do it only when asking ops for blocks). And using rayon on just 1 verif will actually decrease performance

**Comment by gterzian** [comment]
>  we don't batch operation announcement / asking properly 

How about we switch to periodically sending announcements(as opposed to immediately), and the current call to `propagate_ops` would only add them to a local structure, that would be drained when the next time comes to announce ops?

**Comment by sebastien-forestier** [comment]
Is sig verification actually slower compared to say testnet 11 ? Or similar or faster ?

Parallelization will not reduce cpu usage, maybe even increase it a bit, but it will reduce latency, which I don't think is the problem here.

**Comment by gterzian** [comment]
> It's a path to explore, but It should be studied a bit because it would have an impact on propagation latency

@damip trying it out in https://github.com/massalabs/massa/pull/3086

**Comment by damip** [comment]
![Screenshot from 2022-09-30 13-51-00](https://user-images.githubusercontent.com/10211103/193263756-42e8c46d-b919-4eba-a2b6-d41df85e7058.png)
