### ISSUE TITLE
Name threads and tasks

### ISSUE THREAD

**Issue by damip** [massalabs/massa#3073]
* [x] Use https://doc.rust-lang.org/std/thread/struct.Builder.html#method.name to name every spawned thread in the program
* [x] For tokio threads, use https://docs.rs/tokio/latest/tokio/runtime/struct.Builder.html#method.thread_name_fn in the builder to identify the system threads managed by tokio.
* [x] Check if there is a way to name tokio tasks spawned using tokio::spawn and if so, implement it

**Comment by aoudiamoncef** [comment]
Related to #2836

**Comment by aoudiamoncef** [comment]
Tokio have an unstable and tracing only feature which allows us explicite [task naming ](https://docs.rs/tokio/latest/tokio/task/struct.Builder.html). It could help us in the future.
