### ISSUE TITLE
Update TS source tests 

### ISSUE THREAD

**Issue by AurelienFT** [massalabs/massa#3082]
The sources of the tests that use SCs aren't up to date. We need to update them now that modules in TS has changes (from massa-sc-std to massa-as-sdk).

Maybe related to : #3045

**Comment by sydhds** [comment]
There is an existing issue (and I'm already assigned to it): https://github.com/massalabs/massa/issues/3045

**Comment by AurelienFT** [comment]
Source of tests are now up to date and hosted here : https://github.com/massalabs/massa-unit-tests-src
