### ISSUE TITLE
Implement support for gas-less transactions (aka meta transactions)

### ISSUE THREAD

**Issue by leoloco** [massalabs/massa#3089]
**Is your feature request related to a problem? Please describe.**
Decentralized applications are a wonderful gateway for blockchain mass adoption. In order to use decentralized applications, users have to pay with crypto-currency for smart contract execution. This greatly limit new users on-boarding as, by definition, they don't own any crypto-currency. Thus it would be great to implement a solution that would allow new comers to use decentralized application without having to pay for gas fees. It would encourage them to set up a wallet and hopefully join the web3 revolution !

**Describe the solution you'd like**
Such systems have already been implemented in other blockchains systems. They are called meta transaction. The principle is as follow: A is a new user. He has no wallet nor crypto-currency but he wishes to use some smart contract SC. To do so, A will set up a wallet and create a transaction message. Because A has no coins, he cannot pay for the gas fees. So A sends his signed transaction message to a relayer B. The role of the relayer B is to forward A's transaction message to the blockchain network by paying for the transaction fees. To do so, B will take A's transaction message and wrap it inside a new transaction. He then sends the transaction to SC. SC implements an interface that allows B to specify that a transaction is a forwarded transaction. If so, it unwraps B's transaction to get A's transaction message and executes it. 

An example of such a system has been implemented by Openzepplin for solidity compliant blockchains : https://docs.openzeppelin.com/contracts/4.x/api/metatx#MinimalForwarder-verify-struct-MinimalForwarder-ForwardRequest-bytes-

**Comment by damip** [comment]
That's gonna be fundamentally tough because EOW operations cannot be executed from other threads for security reasons

**Comment by leoloco** [comment]
Yes Indeed. I guess we can find a workaround, like using an ASC as proxy, but that's going to be harder than in sequential chains.

**Comment by damip** [comment]
yeah, let's close the issue until you figure something out ;)
