### ISSUE TITLE
Max operation size in protocol

### ISSUE THREAD

**Issue by damip** [massalabs/massa#3090]
If an operation is strictly bigger than MAX_BLOCK_SIZE, it is considered invalid => ignore and ban sender

**Comment by aoudiamoncef** [comment]
In protocol, we receive a Vec of operations from a node identified with it's NodeID. 
if only one operation is invalid, we'll ban this node ? and ignore all remaining operations ?

**Comment by damip** [comment]
@aoudiamoncef that's when operations are included in blocks: their total size cannot exceed the max block size.
This issue should focus on "free" operations propagating outside of a block.

**Comment by modship** [comment]
@aoudiamoncef 
i think in your case you can do it like this : 

.any() stop iter() if one respect the condition wich is more performant than find if you doesn't wan't the result of find : 

```rust

                if operations.iter().any(|operation| {
                    operation.serialized_size() > self.config.max_serialized_operations_size_per_block
                }) {
                    warn!(
                        "Node id {} sent us an operation which exceed max block size.",
                        node
                    );
                    let _ = self.ban_node(&node).await;
                } else {
                    self.on_operations_received(node, operations, op_timer)
                        .await;
                }
```

**Comment by aoudiamoncef** [comment]
Good catch, any fit better our usecase. Thank you
