### ISSUE TITLE
SCs are not including in blocks on Sandbox Mode

### ISSUE THREAD

**Issue by nirnaeth-arnoediad** [massalabs/massa#3114]
**Bug Description**
I am trying to execute our hello world example (https://github.com/massalabs/massa-sc-template) in sandbox mode but generally not included in a block (rare but sometimes it does). Sandbox node produces blocks and wallet has balance, active rolls etc.

**Produce to Execute SC**
1) npx massa-sc-create hello-world
2) cd hello-world
3) npm install
4) npm run build
5) send_smart_contract A1Zj5bdbUSkKh6kyoffnXAZxfvY2sxb4N2kofgjdgWAYbvFueQ9 /home/mburaky/massa-sc/hello-world/build/main.wasm 1000000 1 1 1
6) get_operations mK5yFg6hRhn7mduv4rxbSQFbwxDn39uiU8shBs4hfiSTFdXZZ

**Screenshots**

![sc](https://user-images.githubusercontent.com/57898835/193944686-9aced76e-89c8-41d9-9cda-d04220a02e58.png)
![sc2](https://user-images.githubusercontent.com/57898835/193944697-ef9710c4-6386-4d13-a05b-5fa9c4437c68.png)

**Comment by AurelienFT** [comment]
Can you try again with a node and a client that is up to date with main ?

**Comment by qdrn** [comment]
What's the balance of the address `A1Zj5bdbUSkKh6kyoffnXAZxfvY2sxb4N2kofgjdgWAYbvFueQ9` ? You are using quite some gas so you need to have a lot of coins.

**Comment by AurelienFT** [comment]
> What's the balance of the address `A1Zj5bdbUSkKh6kyoffnXAZxfvY2sxb4N2kofgjdgWAYbvFueQ9` ? You are using quite some gas so you need to have a lot of coins.

The balance is on the screen he seems to have enough gas.

**Comment by AurelienFT** [comment]
@nirnaeth-arnoediad I need the source of this SC can you share it here ?

**Comment by altai0** [comment]
i faced a similar problem
It is not processed and remains in the pool.


![image](https://user-images.githubusercontent.com/36895904/194528562-2945ee26-4468-438f-a984-2d2e4988b395.png)

15 minutes later
![image](https://user-images.githubusercontent.com/36895904/194529386-b12b94f0-8a87-4f5c-bc47-c18029727792.png)

My Sc 

[my-sc.zip](https://github.com/massalabs/massa/files/9732986/my-sc.zip)

**Comment by qdrn** [comment]
> i faced a similar problem It is not processed and remains in the pool.
> 
> ![image](https://user-images.githubusercontent.com/36895904/194528562-2945ee26-4468-438f-a984-2d2e4988b395.png)
> 
> 15 minutes later ![image](https://user-images.githubusercontent.com/36895904/194529386-b12b94f0-8a87-4f5c-bc47-c18029727792.png)
> 
> My Sc
> 
> [my-sc.zip](https://github.com/massalabs/massa/files/9732986/my-sc.zip)
> 
> i tried the same smart contract on TESTNET network and it worked fine ![image](https://user-images.githubusercontent.com/36895904/194533338-409c8e83-e838-4bd2-a9b2-0c3fce2ea4cd.png)

Which version of the network did you use for the SANDBOX ?

**Comment by altai0** [comment]
@qdrn 15 https://github.com/massalabs/massa/releases/tag/TEST.15.0

**Comment by qdrn** [comment]
@altai0 your node is not creating blocks. You are missing this step: `node_add_staking_secret_keys SECRETK`

**Comment by qdrn** [comment]
@nirnaeth-arnoediad are you still having this issue with the main/testnet branch ?

**Comment by nirnaeth-arnoediad** [comment]
> @nirnaeth-arnoediad I need the source of this SC can you share it here ?

Its our massa-sc-template
main.ts
```
import { createSC, fileToBase64, call, Context, generateEvent} from "@massalabs/massa-sc-std";

export function main(_args: string): void {
    const bytes = fileToBase64('./build/smart-contract.wasm');
    let addr = createSC(bytes);
    generateEvent("Address = " + addr.toByteString());
    // Here example of how to call a smart contract
    generateEvent(call(addr, "helloworld", "World", 0));
    generateEvent(`${Context.caller().toByteString()}`);
}
```
smart.contract.ts
```
export function helloworld(name: string): string {
    return `Hello, ${name}!`;
}
```

**Comment by nirnaeth-arnoediad** [comment]
> @nirnaeth-arnoediad are you still having this issue with the main/testnet branch ? You should probably always use a testnet branch for development purposes. Those are more stable.

Ser I checkout to testnet branch and update it. Still issue remains

**Comment by qdrn** [comment]
Can you also provide the `package.json` file so I can use the exact same configuration ?

**Comment by qdrn** [comment]
Also `initial_ledger.json` and `initial_rolls.json` together with the private key you are using.

**Comment by nirnaeth-arnoediad** [comment]
> Also `initial_ledger.json` and `initial_rolls.json` together with the private key you are using.

package.json
```
{
  "name": "hello-world",
  "version": "0.1.0",
  "scripts": {
    "build": "massa-sc-scripts build-sc src/smart-contract.ts && massa-sc-scripts build-sc src/main.ts build/main.wasm",
    "clean": "massa-sc-scripts clean"
  },
  "dependencies": {
    "assemblyscript": "^0.19.20",
    "massa-sc-scripts": "4.0.7",
    "@massalabs/massa-sc-std": "^4.0.2"
  }
}
```
initial_ledger.json
```
    "A12Gno3zjFUoAy8tnGif8YikQwUTLj1ggRC5AqnJXWC9Qq9r5MNa": {
        "balance": "80000000",
        "datastore": {},
        "bytecode": []
    }
```
initial_rolls.json (last wallet is mine)
```
{
    "A1qDAxGJ387ETi9JRQzZWSPKYq4YPXrFvdiE4VoXUaiAt38JFEC": 10,
    "A12M3AQqs7JH7mSe1UZyEA5NQ7nGQHXaqqxe1TGEpkimcRhsQ4eF": 10,
    "A1nsqw9mCcYLyyMJx5f4in4NXDoe4B1LzV9pQdvX5Wrxq9ehf6h": 10,
    "A1pdnk7gME8DSA6ueNZdCHqfSt9YfTwAJSgRCcB8g3z3kkapWtU": 10,
    "A1H1Ze77ctAFi4FBc3nVe9AtWdtg7246V9pVXSeXqWaJFLPKfB1": 10,
    "A12Dvay7jT1maaKpV9CHX6yMt3cS5ZEWy6Q67HV8twVGS3ihoq5x": 10,
    "A13evhD7c9AXFc6CxWWjWWRT6bQnejYhq3MsNofJWJDe4UQStJE": 10,
    "A1UpZLobUAWqj3M9DpBZNhh4GD4ZLvixKXQu2kt7ZDUiEepD89E": 10,
    "A12p8v9V68SiehQb2Syzy6smfv9NTCJh2p6JPbsacy7PaGRw39uH": 10,
    "A12Gno3zjFUoAy8tnGif8YikQwUTLj1ggRC5AqnJXWC9Qq9r5MNa": 10
}
```
wallet_info
```
Secret key: S12QJNBeNePr4Ua3NK4oFyv9rrWxJoTgZ2fEmi7DtcJuvAGhdpQK
Public key: P118p6bkVtB4i6X2yq5AjP5BwryE13xMf4LvsYy8Jyj68JbWQGw
Address: A12Gno3zjFUoAy8tnGif8YikQwUTLj1ggRC5AqnJXWC9Qq9r5MNa (thread 20):
	Balance: final=80000000, candidate=80000000
	Rolls: active=10, final=10, candidate=10
```

**Comment by qdrn** [comment]
I believe your issue is that there are many staking addresses which you don't own. This makes it unlikely that you create the blocks in the thread where your operation should be included. This explains why sometimes it works and sometimes it doesn't. It would change `initial_rolls.json` to:
```
{
    "A12Gno3zjFUoAy8tnGif8YikQwUTLj1ggRC5AqnJXWC9Qq9r5MNa": 10
}
```
Let me know if it fixes your issue.

**Comment by nirnaeth-arnoediad** [comment]
You are right! It is fixed now ser. Thanks for all of your assistance. Also thank you to @AurelienFT
