### ISSUE TITLE
Re-add bandwidth limit

### ISSUE THREAD

**Issue by damip** [massalabs/massa#3126]
* make sure it works properly
* re-add the speed limit removed here https://github.com/massalabs/massa/pull/3125/commits/d7c6ed4cffbfde0f39106d1d49467ca59aeb8046

**Comment by damip** [comment]
Let's do this together with network refactoring

**Comment by damip** [comment]
We now have up and down bandwidth limiters on bootstrap and protocol @modship @Ben-PH  ?

**Comment by Ben-PH** [comment]
yeah: #4059

**Comment by damip** [comment]
Cool then we can close this :)
