### ISSUE TITLE
Remove `gas_price`

### ISSUE THREAD

**Issue by damip** [massalabs/massa#3140]
## Rationale

Block producers consume the following resources when adding an operation `op` to their block:
* block space: capacity = MAX_BLOCK_SIZE, consumed: `op.serialized_data.len()`
* block gas: capacity = MAX_BLOCK_GAS, consumed; `op.get_gas_usage()`

Given those constraints, block producers try to maximize their gains: the sum of all included `op.fee + op.max_gas*op.gas_price`.

As a result, we observe that the only relevant op fields for this mechanism are `op.max_gas` and `op.fee`. The `gas_price` field redundant and can be included inside `fee`.

## What needs to be done

* remove `gas_price` from everywhere it appears (operations, operation-related methods, API, client,  etc...)
* every time `op.fee + op.max_gas*op.gas_price` was used, replace if with `fee`.
* remove `gasprice` from `AsyncMessage` and surrounding mechanisms as well (for example, sorting async messages for exection...)

**Comment by gterzian** [comment]
@massalabs/core-team @damip Ok I will start work on this, sorry I cannot join the call because the vpn is not working today...

**Comment by gterzian** [comment]
Note: also need to remove `simulated_gas_price` from `ReadOnlyBytecodeExecution`.

**Comment by gterzian** [comment]
@damip should we make `max_gas` an `Amount` also while we are at it?

**Comment by damip** [comment]
> @damip should we make `max_gas` an `Amount` also while we are at it?

no, gas should never be made into an Amount (see my comments in the PR)

**Comment by AurelienFT** [comment]
Done in https://github.com/massalabs/massa/pull/3173
