### ISSUE TITLE
Invalid parameters in add_staking_secret_keys

### ISSUE THREAD

**Issue by aoudiamoncef** [massalabs/massa#3146]
**Describe the bug**
When we call `add_staking_secret_keys` with an array of strings as parameters, we got this error:

```json
{
    "jsonrpc": "2.0",
    "error": {
        "code": -32602,
        "message": "Invalid params: invalid type: string \"S1kGdz7x3zBNMCGUX6DEgstXNmsrBjZs1qwZBqFB58fD8Gqyrrb\", expected {'secret_key': 'xxx', 'public_key': 'xxx'}."
    },
    "id": 1
}
```

**Expected behavior**
It should be able to parse private keys as `Vec<KeyPair>`

**Possible solution**
In massa client we use :
https://github.com/massalabs/massa/blob/04d8869b28c4023524b6c23e2f33454c2bedaddf/massa-client/src/cmds.rs#L1099-L1101

Another solution is :
We could change `serde` Serializer/Deserializer implementations in `massa-signature` module.

**Comment by AurelienFT** [comment]
I think the best solution is to change here  : 
https://github.com/massalabs/massa/blob/main/massa-api/src/private.rs#L89

Replace `Vec<KeyPair>` by`Vec<String>`  and use the `from_str()` of `KeyPair` (that use a secret key to create a keypair) to convert from `String` to `KeyPair` for the rest of the code.

Changing the `serde_json` serialization isn't a good solution because we are using it to decode config files that save both secret key and public.

**Comment by aoudiamoncef** [comment]
What do you think about this possible solution: 

```
            fn visit_str<E>(self, v: &str) -> Result<Self::Value, E>
            where
                E: serde::de::Error,
            {
                KeyPair::from_str(v).map_err(serde::de::Error::custom)
            }
```

See https://serde.rs/string-or-struct.html

**Comment by AurelienFT** [comment]
> What do you think about this possible solution:
> 
> ```rust
> fn visit_str<E>(self, v: &str) -> Result<Self::Value, E>
>  where
>     E: serde::de::Error,
> {
>     KeyPair::from_str(v).map_err(serde::de::Error::custom)
>  }
> ```
> 
> See https://serde.rs/string-or-struct.html

I don't think it should be that complicated. Just use String as parameter and call `KeyPair::from_str` in the function of the API.

**Comment by aoudiamoncef** [comment]
<img width="1085" alt="image" src="https://user-images.githubusercontent.com/22281426/195813374-e4aca304-826a-4737-af4e-04bc7c1e687e.png">

Invalid params: JSON RPC error
bad request: API error
parsing error : caused by error

I tried to add the parameter which is responsible of error throwing.

I'm waiting for feedback @AurelienFT

**Comment by aoudiamoncef** [comment]
fixed by https://github.com/massalabs/massa/pull/3158
