### ISSUE TITLE
Add test account secret keys to genesis file for CI tests

### ISSUE THREAD

**Issue by BatiGencho** [massalabs/massa#3175]
For our web3-js we need to run in the pipeline a test suite that deploys a sc to the testnet and does manipulations on it. Since the deployer address now needs to have coins in it before deploying a sc, it might be beneficial to have a funded and fixed (address-secret key) pair added to the genesis file that the test-suite could make use of.

**Comment by AurelienFT** [comment]
The addresses with coins at start of each testnet are here : https://github.com/massalabs/massa/blob/main/massa-node/base_config/initial_ledger.json
