### ISSUE TITLE
IPv6 in massa-node/config/config.toml

### ISSUE THREAD

**Issue by JeromeSi** [massalabs/massa#3197]
**Describe the bug**
maasa-node don't run when we use an IPv6 address like 2a02:842b:8faa:2301::2 but work fine with 2a02:842b:8faa:2301:0:0:0:2

**Desktop (please complete the following information):**
- OS: Ubuntu 22.04

**Comment by aoudiamoncef** [comment]
Can you share your config file please ?

**Comment by JeromeSi** [comment]
Hi,
After your message I make a new test and that's work fine.
I don't know where I make a mistake
Sorry for the disturbance

**Comment by aoudiamoncef** [comment]
Don't worry 😅, I'm glad to see that it's fixed 🙏
