### ISSUE TITLE
Send network event failed An error occurred during channel communication: Failed to send event.

### ISSUE THREAD

**Issue by Unrender** [massalabs/massa#3198]
Hi,

- OS: MacOS 13
- Massa 16.0

My log is full of this error : "Send network event failed An error occurred during channel communication: Failed to send event."
After a while, the node crashes. It crashed 5 times today.
Have you an idea ?

Thanks a lot.

[logs.txt.zip](https://github.com/massalabs/massa/files/9913999/logs.txt.zip)

**Comment by vkomenda** [comment]
Not sure if the current reason for crashes with the same warning is the same but my testnet node did crash a few times in the past couple days. Attaching the log.
[crash-20230112.txt](https://github.com/massalabs/massa/files/10418211/crash-20230112.txt)

**Comment by aoudiamoncef** [comment]
Hi @Unrender @vkomenda,

This kind of bug is often caused by issues in the server. 

You'll find answers and help to setup your node in the dedicated Discord channel

https://discord.com/channels/828270821042159636/1052987210137342042

**Comment by vkomenda** [comment]
@aoudiamoncef The issue wasn't discussed on tech-support as far as I can see. I've added a description there. However I think it's wrong to let the node panic and not have error handling. So it's not a tech support issue. It's a development issue.

**Comment by aoudiamoncef** [comment]
It's like a race, if your node can't handle the blockchain progress and be always synced. It's time to leave the network. 

This issue was seen multiple times in poor network environments, having a good hardware spec isn't enough to hava a stable  node.

**Comment by vkomenda** [comment]
My server is a bare-metal 32-core AMD EPYC 7502P with 10 GbE DC connection. If you are suggesting that it may be slow for Massa then how about those low-spec Hetzner nodes? So let's eliminate this talk of poor network environments.

**Comment by vkomenda** [comment]
> It's like a race, if your node can't handle the blockchain progress and be always synced. It's time to leave the network.

I don't believe one follows from the other. If the software encounters a transient networking error, it should work around it, not let the node crash and leave up to systemd to restart the service.

**Comment by aoudiamoncef** [comment]
> My server is a bare-metal 32-core AMD EPYC 7502P with 10 GbE DC connection. If you are suggesting that it may be slow for Massa then how about those low-spec Hetzner nodes? So let's eliminate this talk of poor network environments.

This my old laptop spec which runs on every episodes without any issue even when we push the transaction to the top:

CPU: Intel i7-6700HQ (8)
Memory: 8GB
OS: Debian 11

A personal 2Gb down/ 1Gb upload fibered connexion.

We have many people suffering from bootstrap or/and connectivity issues. They have decent node specs too, but it's doesn't work. Sometimes they call the support and reinstantiate the VPS in another DC did the trick...etc

**Comment by aoudiamoncef** [comment]
> > It's like a race, if your node can't handle the blockchain progress and be always synced. It's time to leave the network.
> 
> 
> 
> I don't believe one follows from the other. If the software encounters a transient networking error, it should work around it, not let the node crash and leave it up to systemd to restart the service.

IMHO, this panicking is the latest solution, we tried to recover many times without success, so to protect the stability of the networks, the node should be disconnected. 

@AurelienFT could add his light about this system design.
