### ISSUE TITLE
Massa does not show correct version tag

### ISSUE THREAD

**Issue by isezen** [massalabs/massa#3204]
**Describe the bug**
Massa does not show correct version tag (see following commands). At the moment, version `TEST.16.0`.
```
$ massa-client --version
massa-client 0.1.0
$ massa-node --version
massa-node 0.1.0
```
Only way to get version tag is to run `massa-client get_status -p password` command, However, if the node did not connected to other boot sraps; the command gives the error below:

```
Error: check if your node is running: error trying to connect: tcp connect error: Connection refused (os error 111)
```

**Expected behavior**
```
$ massa-client --version
massa-client TEST.16.0
$ massa-node --version
massa-node TEST.16.0
```

**Server Info:**

- OS: Linux Ubuntu Server
- Version 22.04

**Comment by AurelienFT** [comment]
Hello,
Thanks for the report

**Comment by aoudiamoncef** [comment]
> > This could be easily done with an RPC call, so we don't have to maintain it in client side.
> 
> The `--version` is generated by cargo so your RPC call must modify the `Cargo.toml` I think it's better to have it in CD.


I'm agree with you for binaries version. I'm sorry, I was talking about getting `node` version with an RPC call.

**Comment by modship** [comment]
Hi, 
Possible solution is to script that with cargo make : https://github.com/sagiegurari/cargo-make

It provide CARGO_MAKE_PROJECT_VERSION and CARGO_MAKE_CRATE_VERSION

**Comment by modship** [comment]
Now we have a task to set package versions of massa libraries.
For the next testnet (TESTNET 23) the version number is `0.23.0`
