### ISSUE TITLE
Add ARM64 binaries for MacOS

### ISSUE THREAD

**Issue by thomas-senechal** [massalabs/massa#3212]
**Is your feature request related to a problem? Please describe.**
For now, MacOS binaries provided in [releases](https://github.com/massalabs/massa/releases) are only available for `x86_64` processors. Most new Macs come with an `arm64` processor.

**Describe the solution you'd like**
Add `arm64` binaries for MacOS in [releases](https://github.com/massalabs/massa/releases).

**Describe alternatives you've considered**
- Let `arm64` Mac users compile binaries themselves. But that's not really user friendly and requires way more time and disk space.
- ...

**Additional context**
- Seeing how the [CD workflow](https://github.com/massalabs/massa/blob/99b5d6dab5acc31eb30da11b3ee6ff4da9cee6cc/.github/workflows/cd.yml) is made, it should be as easy as removing [MacOS `arm64`](https://github.com/massalabs/massa/blob/99b5d6dab5acc31eb30da11b3ee6ff4da9cee6cc/.github/workflows/cd.yml#L38) from the matrix [`exclude`](https://github.com/massalabs/massa/blob/99b5d6dab5acc31eb30da11b3ee6ff4da9cee6cc/.github/workflows/cd.yml#L35) and add it to the [`include`](https://github.com/massalabs/massa/blob/99b5d6dab5acc31eb30da11b3ee6ff4da9cee6cc/.github/workflows/cd.yml#L18).

**Comment by qdrn** [comment]
This needs to be done for the hackathon.
