### ISSUE TITLE
Review bootstrap server concurrency

### ISSUE THREAD

**Issue by gterzian** [massalabs/massa#3227]
From the fix at https://github.com/massalabs/massa/pull/3173/commits/7fb0e858b389c7710fe196fad5e3ec99cc934414, it seems that the [`test_bootstrap_server`](https://github.com/massalabs/massa/blob/0adc60d632f0a7d0e7581b3f3b70a7ff5562637d/massa-bootstrap/src/tests/scenarios.rs#L55) test is influenced by the ordering of the operations in the test setup, since this points to a potential timing issue within the code(lack of explicit synchronization around something that needs to be "waited on"), it's worth investing exactly what the issue is.

**Comment by AurelienFT** [comment]
I think it comes from the rebase you made  on `testnet_17` because as I see your changes in your PR: https://github.com/massalabs/massa/pull/3173/files there no real changes in the bootstrap tests except a comment
