### ISSUE TITLE
Intermittent failure of `tests::scenarios::test_bootstrap_server`

### ISSUE THREAD

**Issue by gterzian** [massalabs/massa#3241]
First noticed in https://github.com/massalabs/massa/pull/3173

**Comment by gterzian** [comment]
```
thread 'tests::scenarios::test_bootstrap_server' panicked at 'assertion failed: `(left == right)`
  left: `1`,
 right: `0`: length mismatch', massa-bootstrap/src/tests/tools.rs:356:5
```

**Comment by Eitu33** [comment]
@gterzian @AurelienFT I can take care of that, I will handle it as soon as I'm finished with the final state hash

**Comment by AurelienFT** [comment]
I have made a script to launch this test 100 times and didn't had any fail. Lets wait to see if it happens in the CI. For the moment I close this.

**Comment by Eitu33** [comment]
I made an update on it after a specific update which caused the same error, I believe one was merged without the other, and everything got back together on `testnet_17`
