### ISSUE TITLE
Hard gas limit on read-only calls/executions

### ISSUE THREAD

**Issue by damip** [massalabs/massa#3242]
Currently, the caller chooses the gas limit when doing read-only calls or executions. If they put a very high value and run an infinite loop, they might kill the node.

TODO: add a hard, config-file-defined gas limit on read-only calls and executions

**Comment by Eitu33** [comment]
Okay 👍

**Comment by damip** [comment]
Basically it should return an error if the max_gas given in the api call is above a constant
