### ISSUE TITLE
Forbid coin transfers towards SC addresses

### ISSUE THREAD

**Issue by damip** [massalabs/massa#3247]
Make sure that normal transfer operations and ABI calls cannot credit SC addresses, and that the only way to send them coins is through function calls. This will allow filtering incoming funds and not allowing uncontrolled credits.

**Comment by AurelienFT** [comment]
I don't really the need for that.

**Comment by damip** [comment]
> I don't really the need for that, can you maybe explain why incoming funds from transaction is a problem ?

The SC cannot refuse them. See the discussion on discord/Dusa channel

**Comment by Ben-PH** [comment]
I'll take this one, as it's a good synergy with #3475

**Comment by Ben-PH** [comment]
> > I don't really the need for that, can you maybe explain why incoming funds from transaction is a problem ?
> 
> The SC cannot refuse them. See the discussion on discord/Dusa channel

@damip  is this the discussion you're referring to? https://discord.com/channels/761151090673844244/973847775060054026/1029769416549871708

Are there any other convos/informations that I can refer to for better context?

**Comment by Ben-PH** [comment]
agreed.

**Comment by damip** [comment]
It's the right discord convo.

* for the `Operation::Transaction` operation type: the operation fails if the `sender` or `destination` is an SC address
* for ABI coin transfers, the transfer fails if the destination is an SC address, unless the sender has write access to it

**Comment by Ben-PH** [comment]
Waiting on versioning to get started.
