### ISSUE TITLE
multi-dimensional packing operations

### ISSUE THREAD

**Issue by AurelienFT** [massalabs/massa#3248]
Related to this todo in the code : https://github.com/massalabs/massa/blob/main/massa-pool-worker/src/types.rs#L66

In more specifications

**Comment by AurelienFT** [comment]
Related to #2850

**Comment by damip** [comment]
sovled by https://github.com/massalabs/massa/issues/4009

**Comment by qdrn** [comment]
It's a bit weird the way it was done: if the operation is twice as big then the fee should be twice as big to compensate and those two operations should roughly have the same score. It's not the case in what was implemented AFAIK.

Also, I don't understand the rationale behind the choice of exponential (and decay factor).
