### ISSUE TITLE
Improve displaying time values

### ISSUE THREAD

**Issue by aoudiamoncef** [massalabs/massa#3252]
Actual:
```
command > get_status
...
Config:
    Genesis timestamp: 2022-11-25T09:54:36Z
...
Current time: 2022-11-25T10:44:11Z
Current cycle: 1
Last slot: (period: 185, thread: 30)
Next slot: (period: 185, thread: 31)

Consensus stats:
        Start stats timespan time: 2022-11-25T10:43:11Z
        End stats timespan time: 2022-11-25T10:44:11Z
...
```
Expected:
```
command > get_status
...
Config:
    Genesis timestamp: 1669370076000 // Timestamp in milliseconds
	OR
	Genesis time: 2022-11-25T09:54:36Z // Humain readable
...
Current time: 2022-11-25T10:44:11Z
...
Consensus stats:
        Start stats timespan time: 2022-11-25T10:43:11Z
        End stats timespan time: 2022-11-25T10:44:11Z
...
```

May be we could use only `TIMESTAMP` ?  or give the use the ability to switch between the different formats ? it depends on the type of the user.

**Comment by AurelienFT** [comment]
I find it more human readable to have a time then timestamp just need to specify description

**Comment by modship** [comment]
If you want i can make a PR for print both timestamp and human readable date in CompactConfig

**Comment by AurelienFT** [comment]
> If you want i can make a PR for print both timestamp and human readable date in CompactConfig

The cli is meant to be used by humans. It's better to not give multiple representation of the data in the CLI. Keep the timestamp for API

**Comment by Ben-PH** [comment]
Do we want to get rid of 
```
Current cycle: 1
Last slot: (period: 185, thread: 30)
Next slot: (period: 185, thread: 31)
```
?

**Comment by AurelienFT** [comment]
> Do we want to get rid of
> 
> ```
> Current cycle: 1
> Last slot: (period: 185, thread: 30)
> Next slot: (period: 185, thread: 31)
> ```
> 
> ?

No I don't think we want to remove informations that we already display

**Comment by Ben-PH** [comment]
#3394
