### ISSUE TITLE
Specify the result of the SC read-only execution

### ISSUE THREAD

**Issue by aoudiamoncef** [massalabs/massa#3264]
Actual: 

https://github.com/massalabs/massa/blob/0adc60d632f0a7d0e7581b3f3b70a7ff5562637d/massa-models/src/execution.rs#L6-L14
Expected:
We should add better result status rather than returning just `Ok`

**Comment by damip** [comment]
Can we make the return value optional ? so that if the called function has no return value, or an incompatible one, it yields nothing ?

**Comment by aoudiamoncef** [comment]
This issue is about the status part as you can see below: 
```json
{
    "jsonrpc": "2.0",
    "result": [
        {
            "executed_at": {
                "period": 165,
                "thread": 3
            },
            /// THIS SHOULD BE IMPROVED or renamed to `status`
            "result": "Ok",
            "output_events": [
               ...
            ],
            "gas_cost": 3166
        }
    ],
    "id": 1
}
```

To answer your question, we planned to add this field to the reponse:

```rust
    /// Returned value from the module call
    pub call_result: Vec<u8>,
 ```

**Comment by AurelienFT** [comment]
Done in https://github.com/massalabs/massa/issues/2951
