### ISSUE TITLE
Remove blockId from API call response when not found

### ISSUE THREAD

**Issue by aoudiamoncef** [massalabs/massa#3269]
**Query:**
```
curl --location --request POST 'http://localhost:33035' \
--header 'Content-Type: application/json' \
--data-raw '{
    "jsonrpc": "2.0",
    "id": 1,
    "method": "get_block",
    "params": ["D6kTS4Wh3B7FRDCw6ncqrCuY7NVPYBbGwdSg814Kd13fS7xQa"]
}'
```

**Actual:** 

```json
{
    "jsonrpc": "2.0",
    "result": {
        "id": "D6kTS4Wh3B7FRDCw6ncqrCuY7NVPYBbGwdSg814Kd13fS7xQa",
        "content": null
    },
    "id": 1
}
```

**Expected:** 
```json
{
    "jsonrpc": "2.0",
    "result": null,
    "id": 1
}
```

**Comment by modship** [comment]
Hi @aoudiamoncef , 

#3271

**Comment by AurelienFT** [comment]
We are freezing the features for this testnet we will merge it in the next testnet and so you will be able to test it.

**Comment by aoudiamoncef** [comment]
Hi @AurelienFT @modship,

We would implement `get_blocks` :

```rust
async fn get_blocks(&self, ids: Vec<BlockId>) -> RpcResult<Vec<BlockInfo>>
```

When you send 10 block ids,  we could receive only 5 results for example. Is It what is expected ?

**Comment by AurelienFT** [comment]
@aoudiamoncef I think `[block, null, block, null, block, block, null, null, block, null]` is great

**Comment by sydhds** [comment]
I would say: {block_id: BLOCK_DATA, block_id: null, ...}

**Comment by aoudiamoncef** [comment]
IMHO, an approche with returning only found result is widespread in API design. 

This is the actual behavior in `get_operations` for example

**Comment by AurelienFT** [comment]
Ah yes because we have the id in the ones found so yeah no problems
