### ISSUE TITLE
Labnet tutorial

### ISSUE THREAD

**Issue by gterzian** [massalabs/massa#3270]
Is there a tutorial somewhere on how to interact with the labnet using a local client? Something similar to what we have for the testnet at https://docs.massa.net/en/latest/testnet/.

**Comment by gterzian** [comment]
cc @massalabs/core-team

**Comment by AurelienFT** [comment]
The labnet is used internally and so the IP isn't public. You have the IP in the private repository `private-deployment` or I can send you on discord.
