### ISSUE TITLE
exit command in massa-client

### ISSUE THREAD

**Issue by JeromeSi** [massalabs/massa#3281]
**Describe the bug**
`exit` command doesn't work  in massa-client 17.0 (TEST.17.0/massa_TEST.17.0_release_linux.tar.gz)

**To Reproduce**
1. open massa-client with `./massa-client -p password`
2. type `exit`
3. See error

**Expected behavior**
I expect massa-client is closing

**Desktop (please complete the following information):**

- OS: Ubuntu 22.04 and debian 11.3
- Version : massa_TEST.17.0_release_linux.tar.gz)

**Comment by AurelienFT** [comment]
Exit has been removed as it's not compatible with the new code of the CLI. Use CTRL+D instead.
