### ISSUE TITLE
Add colors on CLI output

### ISSUE THREAD

**Issue by AurelienFT** [massalabs/massa#3294]
It will be more easily to have colors in the CLI outputs. For example this output : 

```
get_operations 21z3jS2zzuv8dZpf7YrHhJugoe3s9NDn7dWmJzdCHQQHmdoaix
Operation 21z3jS2zzuv8dZpf7YrHhJugoe3s9NDn7dWmJzdCHQQHmdoaix[ (in pool)]
In blocks:
    - 2VKNvrkorxr2Qj3LJiYsZ2Jt9H8uL61eTSvkvBRgtoFiaVWCSX
Signature: EJQQXzdoshJihGbq8px2dG4N3MBzaFstwWkiLAYLY9q5gyppeSZhbCoRMnBh1kUXhEsmSH3oR39ik8ronYERoR9Axpnqi
Creator pubkey: P1KbDkC1ajppBoY6vbGX58m9cLBc1zNQXvTde9EuTcwci7nS2rB
Creator address: A12KCLh2bca76aWug4z5pDRekMzxFexYJUecXMuMNypUQQQFd1zn
Id: 21z3jS2zzuv8dZpf7YrHhJugoe3s9NDn7dWmJzdCHQQHmdoaix
Fee: 0
Expire period: 3897
Operation type: ExecuteSC:
    - max_gas:1000000
``` 

could have all the differents informations colored to read it more easily.

Tracking PR: https://github.com/massalabs/massa/pull/3661

**Comment by qdrn** [comment]
Adding `good first issue` label. Feel free to remove it if I'm mistaken.

**Comment by aoudiamoncef** [comment]
Resources: 

- [ansi_term](https://docs.rs/ansi_term/0.12.1/ansi_term/)
- [fern](https://docs.rs/fern/latest/fern/index.html)

**Comment by litchipi** [comment]
The client seams to use https://crates.io/crates/console to work with colors, I guess I'll just re-use this directly

**Comment by litchipi** [comment]
Added a discussion topic about the choices of the colors: https://github.com/massalabs/massa/discussions/3671
