### ISSUE TITLE
Please direct users to massalabs OR educate them on how to open issues

### ISSUE THREAD

**Issue by workingjubilee** [massalabs/massa#3305]
If you have bugs to report while using the Rust compiler, we are of course interested to hear them. However, some recent users of the Massa "decentralized" "block" "chain" software are providing... not very useful reports of issues to the primary Rust monorepo. See:
- https://github.com/rust-lang/rust/issues/105326
- https://github.com/rust-lang/rust/issues/105346

I would be most appreciative if your documentation and error messages directed people to report issues to this repository and not to us. If the issue should be elevated to us, of course, then please do so, and we'll try to address it appropriately.

An alternative solution is to educate prospective users about how to report a bug to us so they are offering a useful contribution. In particular, it would be most appreciated if people checked for duplicates, first. Though, this is a lower priority than having a context-laden report at all.

Obviously, I am not expecting anyone to magically prevent people from opening bad issues against the Rust monorepo, but if these people are capable of following directions far enough to get to the point of installing rustc and running cargo, then they probably are capable of following a few more directions.

**Comment by damip** [comment]
Done.
