### ISSUE TITLE
Add endpoint to edit bootstrap white/black lists

### ISSUE THREAD

**Issue by AurelienFT** [massalabs/massa#3316]
Whitelist/Blacklists allow people give rights to an IP to connect to their node.

Currently they are only editable via a JSON file.

TODO: Add API endpoint and client command to manage those configs dynamically.

**Comment by aoudiamoncef** [comment]
@AurelienFT, we could create the methods below:

- node_bootstrap_whitelist/blacklist
- node_add_to_bootstrap_whitelist/blacklist
- node_remove_from_bootstrap_whitelist/blacklist 

If we node_add_to_bootstrap_whitelist then we should remove it from blacklist and vice versa.

**Comment by AurelienFT** [comment]
> @AurelienFT, we could create the methods below:
> 
> * node_bootstrap_whitelist/blacklist
> * node_add_to_bootstrap_whitelist/blacklist
> * node_remove_from_bootstrap_whitelist/blacklist (could be merged in a single method as it's used only for info)
> 
> If we node_add_to_bootstrap_whitelist then we should remove it from blacklist and vice versa.

maybe we could have only 2 methods in the client. `node_bootstrap_whitelist` and `node_bootstrap_blacklist` and have the second which choose the action and the third optional for the IP.
Three different possibilities for the second argument : 
- `list` no third parameter, just list the ips.
- `add` add the third parameter as an IP in the white/blacklist
- `remove` remove the third parameter as an IP in the white/blacklist

**Comment by aoudiamoncef** [comment]
It's a good design for the CLI. 

For API side, we'll make 6 new methods as said below ?

**Comment by AurelienFT** [comment]
> It's a good design for the CLI.
> 
> For API side, we'll make 6 new methods as said above ?

Yes

**Comment by aoudiamoncef** [comment]
Should I add additional checks, E.g if an IP is in blacklist, so i should remove it from whitelist ?

**Comment by AurelienFT** [comment]
> Should I add additional checks, E.g if an IP is in blacklist, so i should remove it from whitelist ?

Yes it could be better to avoid inconsistency.

**Comment by AurelienFT** [comment]
> To achieve this with low cost:
> 
> * When I try to delete an entry from black/white list and black/white list  file doesn't exit, I should create it.
> * If we don't create the empty file when it's not exist, so if the black/white list become empty, we should remove the empty file.

Be careful an empty whitelist means "I allow nobody to bootstrap" and a non-existing whitelist means "I allow everyone to bootstrap"

**Comment by aoudiamoncef** [comment]
This is a good error message to be supplied to the caller when the white list file doesn't exist. 

When the bootstrap blacklist file is empty or contains an empty array. Should I remove it ?

**Comment by AurelienFT** [comment]
> This is a good error message to be supplied to the caller when the white list file doesn't exist.
> 
> When the bootstrap blacklist file is empty or contains an empty array. Should I remove it ?

There is no error cases just two different behaviour. I just wanted to point out "empty array in file" =/= "file not exist".
For the blacklist side "empty array in file" == "file not exist".

**Comment by aoudiamoncef** [comment]
Actually, we have an uncovered case:

- I should be able to delete whitelist file if it's empty via an RPC call.

It could be added in a separate method or as a parameter.

**Comment by AurelienFT** [comment]
> Actually, we have an uncovered case:
> 
> * I should be able to delete whitelist file if it's empty via an RPC call.
> 
> It could be added in a separate method or as a parameter.

I don't think if it's empty it should be deleted because it's a different behaviour. You could have a "everybody", or smth like that, subcommand to delete the file and allow everybody.

**Comment by AurelienFT** [comment]
https://github.com/massalabs/massa/pull/3320
