### ISSUE TITLE
Error while pruning

### ISSUE THREAD

**Issue by chriscooper1983** [massalabs/massa#3319]
Error while pruning: ContainerInconsistency("inconsistency inside block statuses pruning and finding earliest kept slots in each thread'consensus worker' panicked at 'Error while pruning: ContainerInconsistency("inconsistency inside block statuses pruning and finding earliest kept slots in each thread

**Comment by AurelienFT** [comment]
> Error while pruning: ContainerInconsistency("inconsistency inside block statuses pruning and finding earliest kept slots in each thread'consensus worker' panicked at 'Error while pruning: ContainerInconsistency("inconsistency inside block statuses pruning and finding earliest kept slots in each thread

Are you using 17.2 ?

**Comment by chriscooper1983** [comment]
Nie i am using 17.2, when this Bug came along, i ised 17.1
  

  

  

  
  
  
  
  
>

**Comment by AurelienFT** [comment]
> Nie i am using 17.2, when this Bug came along, i ised 17.1

There is no bug anymore ?

**Comment by chriscooper1983** [comment]
Actually it is working, i will tell you when something will go wrong again
  

  

  

  
  
  
  
>

**Comment by AurelienFT** [comment]
ok closing this for now. Thanks for the report
