### ISSUE TITLE
Node failed to start 

### ISSUE THREAD

**Issue by aoudiamoncef** [massalabs/massa#3326]
Both binaries and compiled from sources Massa node fails to start with the error below:

```
thread '<unnamed>' panicked at 'assertion failed: `(left != right)`
  left: `XMM3`,
 right: `XMM3`', /Users/runner/.cargo/registry/src/github.com-1ecc6299db9ec823/wasmer-compiler-singlepass-2.2.1/src/emitter_x64.rs:1448:40
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
thread '<unnamed>' panicked at 'assertion failed: `(left != right)`
  left: `XMM0`,
 right: `XMM0`', /Users/runner/.cargo/registry/src/github.com-1ecc6299db9ec823/wasmer-compiler-singlepass-2.2.1/src/emitter_x64.rs:1420:40
```

VPS spec: Massa 17.2 en binary +
Netcup + 8gb ram, 6 cpu, 160go ssd with Ubuntu 20.04.0x

We have the same error as #2698

**Comment by AurelienFT** [comment]
What's the spec of the computer that produce this bug and what's the version of the binaries tested ?

**Comment by aoudiamoncef** [comment]
I added the node spec in the issue above

**Comment by AurelienFT** [comment]
What's the OS ?

**Comment by aoudiamoncef** [comment]
We have multiple people report this error, even with a decent node specs

This could happen at startup or after 10h or 10min of running.

**Comment by aoudiamoncef** [comment]
@sydhds we need your help for this time

**Comment by sydhds** [comment]
Looks like an error related to assembly code emitted by the wasmer compiler (singlepass) and AVX.

@aoudiamoncef can we have more info about the processor used?

**Comment by aoudiamoncef** [comment]
[Netcup VPS details](https://www.netcup.eu/vserver/vps.php#v-server-details)

**Comment by AurelienFT** [comment]
Will be fixed in TEST.23 with the update of wasmer : https://github.com/massalabs/massa-sc-runtime/pull/249
