### ISSUE TITLE
Support HTTP GET queries proxying

### ISSUE THREAD

**Issue by aoudiamoncef** [massalabs/massa#3376]
It could be interesting to add `GET` request proxing to RPC methods. This feature could simplify frontend queries and allow URIs sharing.

GET /addresses/{address_id} or ?ids=[address_id, address_id] => will be binded to `get_addresses` method

[JSONRPSEE HTTP PROXY](https://github.com/paritytech/jsonrpsee/blob/master/examples/examples/http_proxy_middleware.rs)

related to #2799

**Comment by modship** [comment]
i'll check that

**Comment by modship** [comment]
Draft PR is here #3411

**Comment by aoudiamoncef** [comment]
We could add support for: 

- [ ]  addresses
- [ ]  blocks
- [ ]  endorsements
- [ ]  operations

**Comment by aoudiamoncef** [comment]
We'll switch to gRPC which supports this out of the box
