### ISSUE TITLE
UnsupportedTarget("x86_64 without AVX or SSE 4.2, use -m avx to enable")

### ISSUE THREAD

**Issue by vlasinus** [massalabs/massa#3379]
Massa 18.0
Ubuntu 18.04
Server: Intel(R) Xeon(R) CPU E5-2470 v2 @ 2.40GHz, RAM: 96mb
Everything works for a few hours, then gives an error.
Massa old version 11..17 work fine. 
--------------------------------------------------------
thread 'thread '<unnamed><unnamed>' panicked at '' panicked at 'called `Result::unwrap()` on an `Err` value: UnsupportedTarget("x86_64 without AVX or SSE 4.2, use -m avx to enable")called `Result::unwrap()` on an `Err` value: UnsupportedTarget("x86_64 without AVX or SSE 4.2, use -m avx to enable")', ', /home/lacrimas/.cargo/registry/src/github.com-1ecc6299db9ec823/wasmer-compiler-singlepass-3.1.0/src/compiler.rs/home/lacrimas/.cargo/registry/src/github.com-1ecc6299db9ec823/wasmer-compiler-singlepass-3.1.0/src/compiler.rs::128128thread '::1818<unnamed>
' panicked at 'note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
called `Result::unwrap()` on an `Err` value: UnsupportedTarget("x86_64 without AVX or SSE 4.2, use -m avx to enable")', /home/lacrimas/.cargo/registry/src/github.com-1ecc6299db9ec823/wasmer-compiler-singlepass-3.1.0/src/compiler.rs:128:thread '18
<unnamed>' panicked at 'called `Result::unwrap()` on an `Err` value: UnsupportedTarget("x86_64 without AVX or SSE 4.2, use -m avx to enable")', /home/lacrimas/.cargo/registry/src/github.com-1ecc6299db9ec823/wasmer-compiler-singlepass-3.1.0/src/compiler.rs:128:18
free(): corrupted unsorted chunks
thread '<unnamed>' panicked at 'called `Result::unwrap()` on an `Err` value: UnsupportedTarget("x86_64 without AVX or SSE 4.2, use -m avx to enable")', /home/lacrimas/.cargo/registry/src/github.com-1ecc6299db9ec823/wasmer-compiler-singlepass-3.1.0/src/compiler.rs:128:18
------------------------------------------------------------

<img width="1519" alt="Снимок экрана 2023-01-06 в 15 33 05" src="https://user-images.githubusercontent.com/34749561/211013395-7bbadc80-1623-4c47-b1b6-2b8dc0d27b92.png">

**Comment by AurelienFT** [comment]
Hello,

Thanks for your bug report. @sydhds could give you a more precise answer so I invoke him.

**Comment by sydhds** [comment]
@vlasinus I'm currently investigating the issue. Can you give me more info about your cpu (log from: cat /proc/cpuinfo) ?

**Comment by vlasinus** [comment]
@sydhds 
processor	: 0
vendor_id	: GenuineIntel
cpu family	: 15
model		: 6
model name	: Common KVM processor
stepping	: 1
microcode	: 0x1
cpu MHz		: 2399.998
cache size	: 16384 KB
physical id	: 0
siblings	: 8
core id		: 0
cpu cores	: 8
apicid		: 0
initial apicid	: 0
fpu		: yes
fpu_exception	: yes
cpuid level	: 13
wp		: yes
flags		: fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush mmx fxsr sse sse2 ht syscall nx lm constant_tsc nopl xtopology cpuid tsc_known_freq pni cx16 x2apic hypervisor lahf_lm cpuid_fault pti
bugs		: cpu_meltdown spectre_v1 spectre_v2 spec_store_bypass l1tf mds swapgs itlb_multihit mmio_unknown
bogomips	: 4799.99
clflush size	: 64
cache_alignment	: 128
address sizes	: 40 bits physical, 48 bits virtual
power management:

processor	: 1
vendor_id	: GenuineIntel
cpu family	: 15
model		: 6
model name	: Common KVM processor
stepping	: 1
microcode	: 0x1
cpu MHz		: 2399.998
cache size	: 16384 KB
physical id	: 0
siblings	: 8
core id		: 1
cpu cores	: 8
apicid		: 1
initial apicid	: 1
fpu		: yes
fpu_exception	: yes
cpuid level	: 13
wp		: yes
flags		: fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush mmx fxsr sse sse2 ht syscall nx lm constant_tsc nopl xtopology cpuid tsc_known_freq pni cx16 x2apic hypervisor lahf_lm cpuid_fault pti
bugs		: cpu_meltdown spectre_v1 spectre_v2 spec_store_bypass l1tf mds swapgs itlb_multihit mmio_unknown
bogomips	: 4799.99
clflush size	: 64
cache_alignment	: 128
address sizes	: 40 bits physical, 48 bits virtual
power management:

processor	: 2
vendor_id	: GenuineIntel
cpu family	: 15
model		: 6
model name	: Common KVM processor
stepping	: 1
microcode	: 0x1
cpu MHz		: 2399.998
cache size	: 16384 KB
physical id	: 0
siblings	: 8
core id		: 2
cpu cores	: 8
apicid		: 2
initial apicid	: 2
fpu		: yes
fpu_exception	: yes
cpuid level	: 13
wp		: yes
flags		: fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush mmx fxsr sse sse2 ht syscall nx lm constant_tsc nopl xtopology cpuid tsc_known_freq pni cx16 x2apic hypervisor lahf_lm cpuid_fault pti
bugs		: cpu_meltdown spectre_v1 spectre_v2 spec_store_bypass l1tf mds swapgs itlb_multihit mmio_unknown
bogomips	: 4799.99
clflush size	: 64
cache_alignment	: 128
address sizes	: 40 bits physical, 48 bits virtual
power management:

processor	: 3
vendor_id	: GenuineIntel
cpu family	: 15
model		: 6
model name	: Common KVM processor
stepping	: 1
microcode	: 0x1
cpu MHz		: 2399.998
cache size	: 16384 KB
physical id	: 0
siblings	: 8
core id		: 3
cpu cores	: 8
apicid		: 3
initial apicid	: 3
fpu		: yes
fpu_exception	: yes
cpuid level	: 13
wp		: yes
flags		: fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush mmx fxsr sse sse2 ht syscall nx lm constant_tsc nopl xtopology cpuid tsc_known_freq pni cx16 x2apic hypervisor lahf_lm cpuid_fault pti
bugs		: cpu_meltdown spectre_v1 spectre_v2 spec_store_bypass l1tf mds swapgs itlb_multihit mmio_unknown
bogomips	: 4799.99
clflush size	: 64
cache_alignment	: 128
address sizes	: 40 bits physical, 48 bits virtual
power management:

processor	: 4
vendor_id	: GenuineIntel
cpu family	: 15
model		: 6
model name	: Common KVM processor
stepping	: 1
microcode	: 0x1
cpu MHz		: 2399.998
cache size	: 16384 KB
physical id	: 0
siblings	: 8
core id		: 4
cpu cores	: 8
apicid		: 4
initial apicid	: 4
fpu		: yes
fpu_exception	: yes
cpuid level	: 13
wp		: yes
flags		: fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush mmx fxsr sse sse2 ht syscall nx lm constant_tsc nopl xtopology cpuid tsc_known_freq pni cx16 x2apic hypervisor lahf_lm cpuid_fault pti
bugs		: cpu_meltdown spectre_v1 spectre_v2 spec_store_bypass l1tf mds swapgs itlb_multihit mmio_unknown
bogomips	: 4799.99
clflush size	: 64
cache_alignment	: 128
address sizes	: 40 bits physical, 48 bits virtual
power management:

processor	: 5
vendor_id	: GenuineIntel
cpu family	: 15
model		: 6
model name	: Common KVM processor
stepping	: 1
microcode	: 0x1
cpu MHz		: 2399.998
cache size	: 16384 KB
physical id	: 0
siblings	: 8
core id		: 5
cpu cores	: 8
apicid		: 5
initial apicid	: 5
fpu		: yes
fpu_exception	: yes
cpuid level	: 13
wp		: yes
flags		: fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush mmx fxsr sse sse2 ht syscall nx lm constant_tsc nopl xtopology cpuid tsc_known_freq pni cx16 x2apic hypervisor lahf_lm cpuid_fault pti
bugs		: cpu_meltdown spectre_v1 spectre_v2 spec_store_bypass l1tf mds swapgs itlb_multihit mmio_unknown
bogomips	: 4799.99
clflush size	: 64
cache_alignment	: 128
address sizes	: 40 bits physical, 48 bits virtual
power management:

processor	: 6
vendor_id	: GenuineIntel
cpu family	: 15
model		: 6
model name	: Common KVM processor
stepping	: 1
microcode	: 0x1
cpu MHz		: 2399.998
cache size	: 16384 KB
physical id	: 0
siblings	: 8
core id		: 6
cpu cores	: 8
apicid		: 6
initial apicid	: 6
fpu		: yes
fpu_exception	: yes
cpuid level	: 13
wp		: yes
flags		: fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush mmx fxsr sse sse2 ht syscall nx lm constant_tsc nopl xtopology cpuid tsc_known_freq pni cx16 x2apic hypervisor lahf_lm cpuid_fault pti
bugs		: cpu_meltdown spectre_v1 spectre_v2 spec_store_bypass l1tf mds swapgs itlb_multihit mmio_unknown
bogomips	: 4799.99
clflush size	: 64
cache_alignment	: 128
address sizes	: 40 bits physical, 48 bits virtual
power management:

processor	: 7
vendor_id	: GenuineIntel
cpu family	: 15
model		: 6
model name	: Common KVM processor
stepping	: 1
microcode	: 0x1
cpu MHz		: 2399.998
cache size	: 16384 KB
physical id	: 0
siblings	: 8
core id		: 7
cpu cores	: 8
apicid		: 7
initial apicid	: 7
fpu		: yes
fpu_exception	: yes
cpuid level	: 13
wp		: yes
flags		: fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush mmx fxsr sse sse2 ht syscall nx lm constant_tsc nopl xtopology cpuid tsc_known_freq pni cx16 x2apic hypervisor lahf_lm cpuid_fault pti
bugs		: cpu_meltdown spectre_v1 spectre_v2 spec_store_bypass l1tf mds swapgs itlb_multihit mmio_unknown
bogomips	: 4799.99
clflush size	: 64
cache_alignment	: 128
address sizes	: 40 bits physical, 48 bits virtual
power management:

**Comment by RootEvgeniy** [comment]
If using Proxmox then change KVM to HOST.

**Comment by vlasinus** [comment]
after update linux all work. (apt update/upgrade)

**Comment by sydhds** [comment]
@vlasinus under KVM, your CPU does not support SSE4_2 (which is required). Normally you could configure it to support this extension.
We will update our documentation for the minimum CPU spec required.

**Comment by vlasinus** [comment]
@sydhds switch cpu to host. begin test.

**Comment by ErkanDERELI** [comment]
> ## Massa 18.0
> Ubuntu 18.04
> Sunucu: Intel(R) Xeon(R) CPU E5-2470 v2 @ 2.40GHz, RAM: 96mb
> Her şey birkaç saat çalışıyor, sonra hata veriyor.
> Massa eski sürüm 11..17 iyi çalışıyor.
> ## 'thread' iş parçacığı '' 'de panikledi' `Result::unwrap()`bir `Err`değer üzerinde çağrıldı: UnsupportedTarget("AVX veya SSE 4.2 olmadan x86_64, etkinleştirmek için -m avx'i kullanın") `Result::unwrap()`bir `Err`değer üzerinde çağrıldı: UnsupportedTarget("x86_64 AVX veya SSE 4.2 olmadan, etkinleştirmek için -m avx kullanın")', ', /home/lacrimas/.cargo/registry/src/github.com-1ecc6299db9ec823/wasmer-compiler-singlepass-3.1.0/src/compiler.rs/home/lacrimas/ .cargo/registry/src/github.com-1ecc6299db9ec823/wasmer-compiler-singlepass-3.1.0/src/compiler.rs::128128thread '::1818
> ' 'not: adlı `RUST_BACKTRACE=1`bir geri izlemeyi görüntülemek için ortam değişkeniyle çalıştır' konumunda panikledi üzerinde
> `Result::unwrap()``Err`değer: UnsupportedTarget("AVX veya SSE 4.2 olmadan x86_64, etkinleştirmek için -m avx'i kullanın")', /home/lacrimas/.cargo/registry/src/github.com-1ecc6299db9ec823/wasmer-compiler-singlepass-3.1.0/ src/compiler.rs:128:thread '18
> ' şu değerde çağrıldığında panikledi: UnsupportedTarget("AVX veya SSE 4.2 olmadan x86_64, etkinleştirmek için -m avx'i kullanın")', `Result::unwrap()`/home/lacrimas/.cargo/registry/ `Err`src/github.com-1ecc6299db9ec823/wasmer-compiler-singlepass-3.1.0/src/compiler.rs:128:18
> free(): bozuk sıralanmamış parçalar
> iş parçacığı '' panikledi ' `Result::unwrap()`bir `Err`değerde çağrıldı: UnsupportedTarget("x86_64 olmadan AVX veya SSE 4.2, etkinleştirmek için -m avx'i kullanın")', /home/lacrimas/.cargo/registry/src/github.com-1ecc6299db9ec823/wasmer-compiler-singlepass-3.1.0/src/compiler.rs:128:18
> <img alt="Снимок экрана 2023-01-06 в 15 33 05" width="1519" src="https://user-images.githubusercontent.com/34749561/211013395-7bbadc80-1623-4c47-b1b6-2b8dc0d27b92.png">

Hello. I also got this error. I am using proxmox on my Dell R710 server. I made WM cpu type westmere. Seems like no problem for now.

Cpu - X5675

**Comment by sydhds** [comment]
> > ## Massa 18.0
> > Ubuntu 18.04
> > Sunucu: Intel(R) Xeon(R) CPU E5-2470 v2 @ 2.40GHz, RAM: 96mb
> > Her şey birkaç saat çalışıyor, sonra hata veriyor.
> > Massa eski sürüm 11..17 iyi çalışıyor.
> > ## 'thread' iş parçacığı '' 'de panikledi' `Result::unwrap()`bir `Err`değer üzerinde çağrıldı: UnsupportedTarget("AVX veya SSE 4.2 olmadan x86_64, etkinleştirmek için -m avx'i kullanın") `Result::unwrap()`bir `Err`değer üzerinde çağrıldı: UnsupportedTarget("x86_64 AVX veya SSE 4.2 olmadan, etkinleştirmek için -m avx kullanın")', ', /home/lacrimas/.cargo/registry/src/github.com-1ecc6299db9ec823/wasmer-compiler-singlepass-3.1.0/src/compiler.rs/home/lacrimas/ .cargo/registry/src/github.com-1ecc6299db9ec823/wasmer-compiler-singlepass-3.1.0/src/compiler.rs::128128thread '::1818
> > ' 'not: adlı `RUST_BACKTRACE=1`bir geri izlemeyi görüntülemek için ortam değişkeniyle çalıştır' konumunda panikledi üzerinde
> > `` Result::unwrap()``Err ``değer: UnsupportedTarget("AVX veya SSE 4.2 olmadan x86_64, etkinleştirmek için -m avx'i kullanın")', /home/lacrimas/.cargo/registry/src/github.com-1ecc6299db9ec823/wasmer-compiler-singlepass-3.1.0/ src/compiler.rs:128:thread '18
> > ' şu değerde çağrıldığında panikledi: UnsupportedTarget("AVX veya SSE 4.2 olmadan x86_64, etkinleştirmek için -m avx'i kullanın")', `Result::unwrap()`/home/lacrimas/.cargo/registry/ `Err`src/github.com-1ecc6299db9ec823/wasmer-compiler-singlepass-3.1.0/src/compiler.rs:128:18
> > free(): bozuk sıralanmamış parçalar
> > iş parçacığı '' panikledi ' `Result::unwrap()`bir `Err`değerde çağrıldı: UnsupportedTarget("x86_64 olmadan AVX veya SSE 4.2, etkinleştirmek için -m avx'i kullanın")', /home/lacrimas/.cargo/registry/src/github.com-1ecc6299db9ec823/wasmer-compiler-singlepass-3.1.0/src/compiler.rs:128:18
> > <img alt="Снимок экрана 2023-01-06 в 15 33 05" width="1519" src="https://user-images.githubusercontent.com/34749561/211013395-7bbadc80-1623-4c47-b1b6-2b8dc0d27b92.png">
> 
> Hello. I also got this error. I am using proxmox on my Dell R710 server. I made WM cpu type westmere. Seems like no problem for now.
> 
> Cpu - X5675

By using the Westmere model for the CPU in your VM you are only using SSE 4.2 instruction but your host CPU supports AVX. It should be faster with AVX instructions.
