### ISSUE TITLE
deserialized endorsements fail signature verification in doctest

### ISSUE THREAD

**Issue by Ben-PH** [massalabs/massa#3381]
**Describe the bug**
If one verifies the signature of the endorsements following the deserialization loop found in 

` src/export_active_block.rs - export_active_block::ExportActiveBlockDeserializer::deserialize (line 157)`

the verifications fail.

**To Reproduce**

apply this diff to commit 65fcea9a7 then run `cargo test -F testing -p massa_consensus_exports --doc`

```diff
index f0e5bae6b..b20b3c4c3 100644
--- a/massa-models/src/block.rs
+++ b/massa-models/src/block.rs
@@ -771,6 +771,9 @@ impl Deserializer<BlockHeader> for BlockHeaderDeserializer {
             ),
         )
         .parse(rest)?;
+        for end in endorsements.iter() {
+            end.verify_signature().unwrap();
+        }
 
         Ok((
             rest,
```

**Expected behavior**

passing tests

**Additional context**

Discovered as part of work being done in #3364

**Comment by Ben-PH** [comment]
This can better reveal the crux of the issue:

checkout `deser-bug-demo` branch
`git checkout HEAD~1`
cd into massa-consensus-export
`cargo test --doc`

see failure

`git checkout deser-bug-demo`
`cargo test--doc`

passes.

the commit that allows a pass is [here](https://github.com/massalabs/massa/commit/9a9d2f2c82c5cb14974143f9c1bcbec368aee907)

**Comment by AurelienFT** [comment]
Done in #3364
