### ISSUE TITLE
Gas calibration test when branch have '/'

### ISSUE THREAD

**Issue by AurelienFT** [massalabs/massa#3382]
https://github.com/massalabs/massa/actions/runs/3856607258/jobs/6573016068

**Comment by Ben-PH** [comment]
also here: https://github.com/massalabs/massa/actions/runs/3873013423/jobs/6602532549

the source of that error comes from a branch without `/`. Might be the `_`?

#3384

**Comment by AurelienFT** [comment]
On the PR your linked me it pass. The workflow you linked me has compile error on all of the jobs of it. Don't seems to be a bug on this job in your case, just a normal failed CI because of compilation error.

**Comment by AurelienFT** [comment]
Fixed in https://github.com/massalabs/massa/pull/3390
