### ISSUE TITLE
Node crash when using Thyra

### ISSUE THREAD

**Issue by Eitu33** [massalabs/massa#3407]
## Context

It has been reported that `massa-node` crashes when a [thyra](https://github.com/massalabs/thyra) instance is pointing towards it. This is the investigation issue.

**Comment by Eitu33** [comment]
I wasn't able to produce any crash when using thyra with a sandbox node.

I uploaded flappy and bbx successfully and dusa upload gets stuck on the last chunk but no crash happened.

**Comment by Eitu33** [comment]
Wasn't able to produce any unexpected behaviour using my testnet node either

**Comment by AurelienFT** [comment]
Was related to https://github.com/massalabs/massa/pull/3436
