### ISSUE TITLE
Bootstrap server dashboard.

### ISSUE THREAD

**Issue by Ben-PH** [massalabs/massa#3429]
**Is your feature request related to a problem? Please describe.**

Not a problem per-se, but could help monitor the useful network metrics.

**Describe the solution you'd like**

To be able to visit a website, where you can select from a list of bootstrap servers, or enter a node address for a specific one.

At the home-page, it can provide an overall view of known bootstrap servers (plus manually entered ones), such as total slots available, recent average slot availability, total number of nodes bootstrapped during a configured time-window, etc.

Upon selecting a server, it will take you to a dashboard where it will present useful metrics, such as average success rates, which nodes have been bootstrapped (perhaps limited to a configured duration), time-taken to bootstrap.

**Additional context**

Low priority at time of writing, particularly when considering the work required for mainnet.

**Comment by qdrn** [comment]
It would maybe make sense to handle such a thing in Thyra rather than in the massa node ? It may require works on this repo though.

It's a low priority feature anyway!

cc @gregLibert

**Comment by gregLibert** [comment]
Yep, something cool to add to the node plugin manager. 
Although I don't know where most of the data identified by @Ben-PH can be retrieved...

@SlnPons :-)

**Comment by Ben-PH** [comment]
This idea came out of putting together #3431 . the Bootstrap server has debug outputs that would allow you to derive the bootstrap time from the log outputs. That could be extended such that it caches the times for retrieval via an API call, for example.

**Comment by Ben-PH** [comment]
The way I've put it together it's on the server. Could be done client-side if it makes sense to do so.

**Comment by AurelienFT** [comment]
I think that this is nearly fully covered by the metrics dashboard and can be close. @modship what do you think ?

**Comment by modship** [comment]
> I think that this is nearly fully covered by the metrics dashboard and can be close. @modship what do you think ?

yes ! it can be closed
