### ISSUE TITLE
Fix protocol endorsement test

### ISSUE THREAD

**Issue by gterzian** [massalabs/massa#3433]
As part of https://github.com/massalabs/massa/pull/3272, I noticed that turning the protocol worker into a separate thread would make certain tests fail, because they were previously only passing because the test would deadlock on `pool_event_receiver.wait_command`--and wake-up when the timer was hit. 

For most tests this was just a matter for [fixing the faulty logic](https://github.com/massalabs/massa/pull/3272/commits/397e6300e1d9c7ef492851f69fb741288e77226c).

However for one test in particular, `test_protocol_does_not_send_invalid_endorsements_it_receives_to_pool`, it seems either there is a bug in the code--invalid endorsements are sent to pool--or the assumptions of the test are wrong. Since investigating this is outside of the scope of https://github.com/massalabs/massa/pull/3272, I am opening this issue. 

To prove that the test indeed fails when the deadlock is removed, I have opened https://github.com/massalabs/massa/pull/3432, where the test fails just because the test uses a multithreaded runtime--which also removes the deadlock. 

In the meantime, I am marking the test as `ignore` in https://github.com/massalabs/massa/pull/3272.

**Comment by AurelienFT** [comment]
I don't understand your point. The test code seems to be coherent and yes it fails when you add `(flavor = "multi_thread", worker_threads = 2)` but the other test you linked `test_protocol_propagates_operations_only_to_nodes_that_dont_know_about_it` where you said "fixing the faulty logic" was enough has the same error if we add the same code to the `tokio::test` macro.

I don't really understand what's the current issue then.

In [this change](https://github.com/massalabs/massa/pull/3272/commits/397e6300e1d9c7ef492851f69fb741288e77226c#diff-2cd69012a512299647fbe135c7ba4069294dc8eb88b72dc98830f97c45c68b24L230) you fixed a logic that were broken. But in the endorsement test the logic isn't broken. The endorsement shouldn't arrive to the pool as he is invalid.

**Comment by AurelienFT** [comment]
Doesn't happens anymore in new protocol
