### ISSUE TITLE
[META] Versioning issue

### ISSUE THREAD

**Issue by AurelienFT** [massalabs/massa#3438]
Following our discussion on https://github.com/massalabs/massa/discussions/3372

We choose to try to implement some versioning on some objects to make some tests : 

- https://github.com/massalabs/massa/pull/3417
- https://github.com/massalabs/massa/pull/3410
- https://github.com/massalabs/massa-sc-runtime/pull/208

IMPORTANT COMMENT : https://github.com/massalabs/massa/pull/3417#issuecomment-1396919842

After a meeting with the 3 PR creators @sydhds @Leo-Besancon and @AurelienFT on 18/01/23 we decided to go with this next steps : 

- @AurelienFT keep working on https://github.com/AurelienFT/transition to have all the features so that we can integrate it in our code. (Have an enum with all versioned types, serialize version, test in really case for example address)
- @Leo-Besancon keep digging on address update especially in smart contract system

To be continued...

**Comment by Leo-Besancon** [comment]
To keep track of the PRs, we are currently working on the following:
- #3563 
- #3578 
These are useful to design a transition system between different versions.

**Comment by sydhds** [comment]
https://github.com/massalabs/massa/issues/3631
