### ISSUE TITLE
Intermittent failure of protocol test -- sending blocks to consensus

### ISSUE THREAD

**Issue by gterzian** [massalabs/massa#3439]
[`test_protocol_sends_blocks_with_operations_to_consensus`](https://github.com/massalabs/massa/blob/5abd4683be2b7ff236bd5735ff4a4655487f1688/massa-protocol-worker/src/tests/in_block_operations_scenarios.rs#L126) fails intermittently.

**Comment by AurelienFT** [comment]
Doesn't appear anymore in new protcol
