### ISSUE TITLE
Testnet 19 - test suite does not compile

### ISSUE THREAD

**Issue by gterzian** [massalabs/massa#3465]

**Comment by gterzian** [comment]
Noticed while rebasing https://github.com/massalabs/massa/pull/3272 cc @massalabs/core-team

**Comment by Eitu33** [comment]
Noticed this as well, idk where it got introduced but it looks like it's yet another `testing` flag issue.

**Comment by Eitu33** [comment]
Fixed this in `testnet_19`, just now. It was a minor change.

**Comment by gterzian** [comment]
@Eitu33 Thanks!

Changed the title for the issues, it seems the `protocol_worker` test suite also does not compile.

**Comment by AurelienFT** [comment]
> Was test_exports removed from massa_consensus_exports?

No there is still a test_exports module that is exported only with `testing` feature
