### ISSUE TITLE
Remove tokio from protocol-exports and protocol-worker

### ISSUE THREAD

**Issue by gterzian** [massalabs/massa#3468]
It is currently still used in tests, and exported errors. It does not appear necessary. Follow-up to https://github.com/massalabs/massa/pull/3272

**Comment by Ben-PH** [comment]
@gterzian I've self-assigned, but feel free to reassign if appropriate.

**Comment by AurelienFT** [comment]
It's a follow-up of #3272 and as this PR isn't merged yet, it's not a good idea to make a follow up on it right now, it's possible that this PR still change a lot.

**Comment by gterzian** [comment]
This also requires removing the `async` from `MockNetworkController`, which isn't really async anyway since it will use a threaded channel after https://github.com/massalabs/massa/pull/3272. 

I also think the current mixing of async and threading creates some intermittent failures, see for example https://github.com/massalabs/massa/pull/3272#issuecomment-1413377865

**Comment by AurelienFT** [comment]
Done in https://github.com/massalabs/massa/pull/3682
