### ISSUE TITLE
Outdated links in README

### ISSUE THREAD

**Issue by qdrn** [massalabs/massa#3484]
There are some outdated links in the README. In particular in the technical documentation section. Concurrency for instance.

**Comment by aoudiamoncef** [comment]
There is some github action to auto check for dead links: 
- https://github.com/tcort/markdown-link-check
- https://github.com/maoudia/www.maoudia.com/blob/main/.github/workflows/link_check.yml

**Comment by qdrn** [comment]
I've create a followup issue. If you want to avoid maintaining a lot of link I would advice to link to the main page of the doc.

**Comment by AurelienFT** [comment]
Done in https://github.com/massalabs/massa/pull/3585
