### ISSUE TITLE
Add "sha256" ABI

### ISSUE THREAD

**Issue by damip** [massalabs/massa#3491]
Add a "sha256" ABI taking bytes as input, computing the sha256 of the bytes, and giving the hash as output bytes.

**Comment by AurelienFT** [comment]
@Ben-Rey Let's take this issue as a test for the spec format to have the best communication. Here is what I propose : 

ABI on massa-sc-runtime side : `assembly_script_sha256(bytes: &[u8]) -> &[u8]`
Behavior of the function: Computing the sha256 of the passed parameter and return the hash as a byte array.
PR on massa-sc-runtime: Not dev yet.
PR on massa-as-sdk: Node dev yet.
PR on massa-web3: Shouldn't modify anything on Massa-web3
Others repositories impacted: /


Do you see anything else important to mention on your side ?

**Comment by Ben-Rey** [comment]
I don't think so, it's pretty clear.

**Comment by aoudiamoncef** [comment]
@AurelienFT I'm interested to help in `massa-sc-runtime` side

**Comment by AurelienFT** [comment]
> I don't think so, it's pretty clear.

Ok so feel free to start implementing the `massa-as-sdk` modification it should touch only the `env.ts` file. Maybe we could use a github template for issue that is related to adding an ABI to have this format of issue pre-filled.

**Comment by aoudiamoncef** [comment]
@AurelienFT what's the gas cost of : `abi_costs.insert(String::from("assembly_script_sha256"), XX);` ?

**Comment by Ben-Rey** [comment]
> > I don't think so, it's pretty clear.
> 
> Ok so feel free to start implementing the `massa-as-sdk` modification it should touch only the `env.ts` file. Maybe we could use a github template for issue that is related to adding an ABI to have this format of issue pre-filled.

Ok I implemented it. I just need to talk to ino team to match their git workflow for massa-as-sdk. I will check github issue template.

**Comment by AurelienFT** [comment]
> @AurelienFT what's the gas cost of : `abi_costs.insert(String::from("assembly_script_sha256"), XX);` ?

It need to be calibrate using the gas-calibration project. you can try to it in the project if you want; Maybe I need to provide you some explanation as the code isn't still very clear but you can already check it a bit yourself.
For the test mock gas put whatever you want pretty low.

**Comment by AurelienFT** [comment]
> Ok I implemented it. I just need to talk to ino team to match their git workflow for massa-as-sdk. I will check github issue template.

You can edit my comment and add the PR of massa-as-sdk linked to this issue.

**Comment by Ben-Rey** [comment]
> > I don't think so, it's pretty clear.
> 
> Ok so feel free to start implementing the `massa-as-sdk` modification it should touch only the `env.ts` file. Maybe we could use a github template for issue that is related to adding an ABI to have this format of issue pre-filled.

For the template, we can do something simple like this:

**Technical specification**
Example: 
ABI on massa-sc-runtime side : `assembly_script_sha256(bytes: &[u8]) -> &[u8]`  
Behavior of the function: Computing the sha256 of the passed parameter and return the hash as a byte array.

**Related pull request**
Example:
massa-sc-runtime: Not dev yet.  
massa-as-sdk: Link to pr
massa-web3: Shouldn't modify anything on Massa-web3

**Comment by aoudiamoncef** [comment]
@Ben-Rey in core side(massa, massa-sc-runtime), all is implemented in `testnet_20` branch.

**Comment by Ben-Rey** [comment]
@AurelienFT do we close the issue ?

**Comment by AurelienFT** [comment]
Yes we can
