### ISSUE TITLE
Look into deadlock issues in boostrap tests

### ISSUE THREAD

**Issue by gterzian** [massalabs/massa#3500]
Currently some tests, for example see https://github.com/massalabs/massa/pull/3272#discussion_r1095399977, require using a multithreaded runtime to avoid a deadlock. 

We could fix this either by spawning a thread in the test or elsewhere, or by actually removing some async elements, or just leave it as it is since running the multithreaded runtime in the test does not really matter.

**Comment by AurelienFT** [comment]
Not the case anymore.
