### ISSUE TITLE
Add a structure representing an active node. 

### ISSUE THREAD

**Issue by gterzian** [massalabs/massa#3501]
After https://github.com/massalabs/massa/pull/3272  it will be a tuple of `(ConnectionId, Sender<NodeCommand>, JoinHandle<()>)`. 

See discussion at https://github.com/massalabs/massa/pull/3272#discussion_r1095849669

Follow-up on the linked to PR.

**Comment by AurelienFT** [comment]
As #3272 will not be merged I close this.
