### ISSUE TITLE
Remove async from bootstrap

### ISSUE THREAD

**Issue by AurelienFT** [massalabs/massa#3503]
The async in the bootstrap isn't justified as there is not much simultaneous tasks and they run for long term.

Here is a first design of the bootstrap architecture : 

TDB

**Comment by Ben-PH** [comment]
Going to start looking through this now.

**Comment by Ben-PH** [comment]
bootstrap server started here: https://github.com/massalabs/massa/blob/1de9a0c77dd0a53b94616d26b8a4cc59cfde3299/massa-node/src/main.rs#L499

**Comment by Ben-PH** [comment]
I'm going to use the same/similar model as some of the other workers that use `std::thread::spawn`

**Comment by Ben-PH** [comment]
Closing: #3746 is the general tracking issue for bootstrap improvements.
