### ISSUE TITLE
logs

### ISSUE THREAD

**Issue by chip2017** [massalabs/massa#3515]
**Describe the bug**

**To Reproduce**

Feb 08 17:50:46 ubuntu-16gb-ash-1 massa-node[140170]: 2023-02-08T17:50:46.464961Z  INFO massa_bootstrap::client: Bootstrap from server 198.27.74.52:31245 failed. Your node will try to bootstrap from another server in 1m.
Feb 08 17:51:46 ubuntu-16gb-ash-1 massa-node[140170]: 2023-02-08T17:51:46.465684Z  INFO massa_bootstrap::client: Start bootstrapping from 198.27.74.5:31245
Feb 08 17:51:46 ubuntu-16gb-ash-1 massa-node[140170]: 2023-02-08T17:51:46.480666Z  WARN massa_bootstrap::client: Error while connecting to bootstrap server: io error: Connection refused (os error 111)
Feb 08 17:51:46 ubuntu-16gb-ash-1 massa-node[140170]: 2023-02-08T17:51:46.480704Z  INFO massa_bootstrap::client: Bootstrap from server 198.27.74.5:31245 failed. Your node will try to bootstrap from another server in 1m.
Feb 08 17:52:46 ubuntu-16gb-ash-1 massa-node[140170]: 2023-02-08T17:52:46.481707Z  INFO massa_bootstrap::client: Start bootstrapping from 51.75.60.228:31245
Feb 08 17:52:46 ubuntu-16gb-ash-1 massa-node[140170]: 2023-02-08T17:52:46.703367Z  WARN massa_bootstrap::client: Error received from bootstrap server: Your last bootstrap on this server was 1h 2m 6s 798ms 84us 86ns ago and you have to wait 10h 57m 53s 201ms 915us 714ns before retrying.
Feb 08 17:52:46 ubuntu-16gb-ash-1 massa-node[140170]: 2023-02-08T17:52:46.703463Z  INFO massa_bootstrap::client: Bootstrap from server 51.75.60.228:31245 failed. Your node will try to bootstrap from another server in 1m.
Feb 08 17:53:46 ubuntu-16gb-ash-1 massa-node[140170]: 2023-02-08T17:53:46.704189Z  INFO massa_bootstrap::client: Start bootstrapping from [2001:41d0:1004:67::]:31245
Feb 08 17:53:46 ubuntu-16gb-ash-1 massa-node[140170]: 2023-02-08T17:53:46.873549Z  WARN massa_bootstrap::client: Error received from bootstrap server: Your last bootstrap on this server was 6h 39m 23s 179ms 998us 635ns ago and you have to wait 5h 20m 36s 820ms 1us 108ns before retrying.
Feb 08 17:53:46 ubuntu-16gb-ash-1 massa-node[140170]: 2023-02-08T17:53:46.873649Z  INFO massa_bootstrap::client: Bootstrap from server [2001:41d0:1004:67::]:31245 failed. Your node will try to bootstrap from another server in 1m.
Feb 08 17:54:46 ubuntu-16gb-ash-1 massa-node[140170]: 2023-02-08T17:54:46.875545Z  INFO massa_bootstrap::client: Start bootstrapping from 158.69.23.120:31245
Feb 08 17:54:46 ubuntu-16gb-ash-1 massa-node[140170]: 2023-02-08T17:54:46.905483Z  WARN massa_bootstrap::client: Error received from bootstrap server: Your last bootstrap on this server was 1h 1m 5s 239ms 532us 401ns ago and you have to wait 10h 58m 54s 760ms 467us 285ns before retrying.
Feb 08 17:54:46 ubuntu-16gb-ash-1 massa-node[140170]: 2023-02-08T17:54:46.905566Z  INFO massa_bootstrap::client: Bootstrap from server 158.69.23.120:31245 failed. Your node will try to bootstrap from another server in 1m.

**Comment by AurelienFT** [comment]
Hello, 
Thanks for your report
The issue to put the logs is the #3512. I'm referencing your logs there.
