### ISSUE TITLE
my_logs

### ISSUE THREAD

**Issue by Archebald-now** [massalabs/massa#3519]

**Comment by Archebald-now** [comment]
[logs.txt](https://github.com/massalabs/massa/files/10688759/logs.txt)

**Comment by Archebald-now** [comment]
after a while, the logs became like this
[logs2.txt](https://github.com/massalabs/massa/files/10688812/logs2.txt)

**Comment by AurelienFT** [comment]
Hello, 
Thanks for your report
The issue to put the logs is the #3512. I'm referencing your logs there.
