### ISSUE TITLE
logs.txt

### ISSUE THREAD

**Issue by Ivan07ArgenTerra07** [massalabs/massa#3520]
Feb 08 19:24:16 Ubuntu-2004-focal-64-minimal massa-node[3446286]: 2023-02-08T18:24:16.000835Z  WARN massa_factory_worker::endorsement_factory: endorsement factory could not get selector draws for slot (period: 33391, thread: 16): `CycleUnavailable`: PoS cycle 260 is needed but is absent from cache
Feb 08 19:24:16 Ubuntu-2004-focal-64-minimal massa-node[3446286]: 2023-02-08T18:24:16.501028Z  WARN massa_factory_worker::endorsement_factory: endorsement factory could not get selector draws for slot (period: 33391, thread: 17): `CycleUnavailable`: PoS cycle 260 is needed but is absent from cache
Feb 08 19:24:17 Ubuntu-2004-focal-64-minimal massa-node[3446286]: 2023-02-08T18:24:17.000272Z  WARN massa_factory_worker::endorsement_factory: endorsement factory could not get selector draws for slot (period: 33391, thread: 18): `CycleUnavailable`: PoS cycle 260 is needed but is absent from cache
Feb 08 19:24:17 Ubuntu-2004-focal-64-minimal massa-node[3446286]: 2023-02-08T18:24:17.500665Z  WARN massa_factory_worker::endorsement_factory: endorsement factory could not get selector draws for slot (period: 33391, thread: 19): `CycleUnavailable`: PoS cycle 260 is needed but is absent from cache
Feb 08 19:24:18 Ubuntu-2004-focal-64-minimal massa-node[3446286]: 2023-02-08T18:24:18.001082Z  WARN massa_factory_worker::endorsement_factory: endorsement factory could not get selector draws for slot (period: 33391, thread: 20): `CycleUnavailable`: PoS cycle 260 is needed but is absent from cache
Feb 08 19:24:18 Ubuntu-2004-focal-64-minimal massa-node[3446286]: 2023-02-08T18:24:18.500473Z  WARN massa_factory_worker::endorsement_factory: endorsement factory could not get selector draws for slot (period: 33391, thread: 21): `CycleUnavailable`: PoS cycle 260 is needed but is absent from cache
Feb 08 19:24:19 Ubuntu-2004-focal-64-minimal massa-node[3446286]: 2023-02-08T18:24:19.000773Z  WARN massa_factory_worker::endorsement_factory: endorsement factory could not get selector draws for slot (period: 33391, thread: 22): `CycleUnavailable`: PoS cycle 260 is needed but is absent from cache
Feb 08 19:24:19 Ubuntu-2004-focal-64-minimal massa-node[3446286]: 2023-02-08T18:24:19.501207Z  WARN massa_factory_worker::endorsement_factory: endorsement factory could not get selector draws for slot (period: 33391, thread: 23): `CycleUnavailable`: PoS cycle 260 is needed but is absent from cache
Feb 08 19:24:20 Ubuntu-2004-focal-64-minimal massa-node[3446286]: 2023-02-08T18:24:20.000599Z  WARN massa_factory_worker::endorsement_factory: endorsement factory could not get selector draws for slot (period: 33391, thread: 24): `CycleUnavailable`: PoS cycle 260 is needed but is absent from cache
Feb 08 19:24:20 Ubuntu-2004-focal-64-minimal massa-node[3446286]: 2023-02-08T18:24:20.501019Z  WARN massa_factory_worker::endorsement_factory: endorsement factory could not get selector draws for slot (period: 33391, thread: 25): `CycleUnavailable`: PoS cycle 260 is needed but is absent from cache
Feb 08 19:24:21 Ubuntu-2004-focal-64-minimal massa-node[3446286]: 2023-02-08T18:24:21.000349Z  WARN massa_factory_worker::endorsement_factory: endorsement factory could not get selector draws for slot (period: 33391, thread: 26): `CycleUnavailable`: PoS cycle 260 is needed but is absent from cache
Feb 08 19:24:21 Ubuntu-2004-focal-64-minimal massa-node[3446286]: 2023-02-08T18:24:21.500517Z  WARN massa_factory_worker::endorsement_factory: endorsement factory could not get selector draws for slot (period: 33391, thread: 27): `CycleUnavailable`: PoS cycle 260 is needed but is absent from cache
Feb 08 19:24:22 Ubuntu-2004-focal-64-minimal massa-node[3446286]: 2023-02-08T18:24:22.000839Z  WARN massa_factory_worker::endorsement_factory: endorsement factory could not get selector draws for slot (period: 33391, thread: 28): `CycleUnavailable`: PoS cycle 260 is needed but is absent from cache
Feb 08 19:24:22 Ubuntu-2004-focal-64-minimal massa-node[3446286]: 2023-02-08T18:24:22.501098Z  WARN massa_factory_worker::endorsement_factory: endorsement factory could not get selector draws for slot (period: 33391, thread: 29): `CycleUnavailable`: PoS cycle 260 is needed but is absent from cache
Feb 08 19:24:23 Ubuntu-2004-focal-64-minimal massa-node[3446286]: 2023-02-08T18:24:23.000403Z  WARN massa_factory_worker::endorsement_factory: endorsement factory could not get selector draws for slot (period: 33391, thread: 30): `CycleUnavailable`: PoS cycle 260 is needed but is absent from cache
Feb 08 19:24:23 Ubuntu-2004-focal-64-minimal massa-node[3446286]: 2023-02-08T18:24:23.500909Z  WARN massa_factory_worker::endorsement_factory: endorsement factory could not get selector draws for slot (period: 33391, thread: 31): `CycleUnavailable`: PoS cycle 260 is needed but is absent from cache
Feb 08 19:24:24 Ubuntu-2004-focal-64-minimal massa-node[3446286]: 2023-02-08T18:24:24.001279Z  WARN massa_factory_worker::endorsement_factory: endorsement factory could not get selector draws for slot (period: 33392, thread: 0): `CycleUnavailable`: PoS cycle 260 is needed but is absent from cache
Feb 08 19:24:24 Ubuntu-2004-focal-64-minimal massa-node[3446286]: 2023-02-08T18:24:24.500678Z  WARN massa_factory_worker::endorsement_factory: endorsement factory could not get selector draws for slot (period: 33392, thread: 1): `CycleUnavailable`: PoS cycle 260 is needed but is absent from cache
Feb 08 19:24:25 Ubuntu-2004-focal-64-minimal massa-node[3446286]: 2023-02-08T18:24:25.000988Z  WARN massa_factory_worker::endorsement_factory: endorsement factory could not get selector draws for slot (period: 33392, thread: 2): `CycleUnavailable`: PoS cycle 260 is needed but is absent from cache
Feb 08 19:24:25 Ubuntu-2004-focal-64-minimal massa-node[3446286]: 2023-02-08T18:24:25.500371Z  WARN massa_factory_worker::endorsement_factory: endorsement factory could not get selector draws for slot (period: 33392, thread: 3): `CycleUnavailable`: PoS cycle 260 is needed but is absent from cache
Feb 08 19:24:26 Ubuntu-2004-focal-64-minimal massa-node[3446286]: 2023-02-08T18:24:26.000779Z  WARN massa_factory_worker::endorsement_factory: endorsement factory could not get selector draws for slot (period: 33392, thread: 4): `CycleUnavailable`: PoS cycle 260 is needed but is absent from cache
Feb 08 19:24:26 Ubuntu-2004-focal-64-minimal massa-node[3446286]: 2023-02-08T18:24:26.501087Z  WARN massa_factory_worker::endorsement_factory: endorsement factory could not get selector draws for slot (period: 33392, thread: 5): `CycleUnavailable`: PoS cycle 260 is needed but is absent from cache
Feb 08 19:24:27 Ubuntu-2004-focal-64-minimal massa-node[3446286]: 2023-02-08T18:24:27.000482Z  WARN massa_factory_worker::endorsement_factory: endorsement factory could not get selector draws for slot (period: 33392, thread: 6): `CycleUnavailable`: PoS cycle 260 is needed but is absent from cache
Feb 08 19:24:27 Ubuntu-2004-focal-64-minimal massa-node[3446286]: 2023-02-08T18:24:27.500703Z  WARN massa_factory_worker::endorsement_factory: endorsement factory could not get selector draws for slot (period: 33392, thread: 7): `CycleUnavailable`: PoS cycle 260 is needed but is absent from cache
Feb 08 19:24:28 Ubuntu-2004-focal-64-minimal massa-node[3446286]: 2023-02-08T18:24:28.001050Z  WARN massa_factory_worker::endorsement_factory: endorsement factory could not get selector draws for slot (period: 33392, thread: 8): `CycleUnavailable`: PoS cycle 260 is needed but is absent from cache
Feb 08 19:24:28 Ubuntu-2004-focal-64-minimal massa-node[3446286]: 2023-02-08T18:24:28.500344Z  WARN massa_factory_worker::endorsement_factory: endorsement factory could not get selector draws for slot (period: 33392, thread: 9): `CycleUnavailable`: PoS cycle 260 is needed but is absent from cache
Feb 08 19:24:29 Ubuntu-2004-focal-64-minimal massa-node[3446286]: 2023-02-08T18:24:29.000560Z  WARN massa_factory_worker::endorsement_factory: endorsement factory could not get selector draws for slot (period: 33392, thread: 10): `CycleUnavailable`: PoS cycle 260 is needed but is absent from cache
Feb 08 19:24:29 Ubuntu-2004-focal-64-minimal massa-node[3446286]: 2023-02-08T18:24:29.500989Z  WARN massa_factory_worker::endorsement_factory: endorsement factory could not get selector draws for slot (period: 33392, thread: 11): `CycleUnavailable`: PoS cycle 260 is needed but is absent from cache
Feb 08 19:24:30 Ubuntu-2004-focal-64-minimal massa-node[3446286]: 2023-02-08T18:24:30.000203Z  WARN massa_factory_worker::endorsement_factory: endorsement factory could not get selector draws for slot (period: 33392, thread: 12): `CycleUnavailable`: PoS cycle 260 is needed but is absent from cache
Feb 08 19:24:30 Ubuntu-2004-focal-64-minimal massa-node[3446286]: 2023-02-08T18:24:30.500414Z  WARN massa_factory_worker::endorsement_factory: endorsement factory could not get selector draws for slot (period: 33392, thread: 13): `CycleUnavailable`: PoS cycle 260 is needed but is absent from cache
Feb 08 19:24:31 Ubuntu-2004-focal-64-minimal massa-node[3446286]: 2023-02-08T18:24:31.000765Z  WARN massa_factory_worker::endorsement_factory: endorsement factory could not get selector draws for slot (period: 33392, thread: 14): `CycleUnavailable`: PoS cycle 260 is needed but is absent from cache
Feb 08 19:24:31 Ubuntu-2004-focal-64-minimal massa-node[3446286]: 2023-02-08T18:24:31.501195Z  WARN massa_factory_worker::endorsement_factory: endorsement factory could not get selector draws for slot (period: 33392, thread: 15): `CycleUnavailable`: PoS cycle 260 is needed but is absent from cache
Feb 08 19:24:32 Ubuntu-2004-focal-64-minimal massa-node[3446286]: 2023-02-08T18:24:32.000469Z  WARN massa_factory_worker::endorsement_factory: endorsement factory could not get selector draws for slot (period: 33392, thread: 16): `CycleUnavailable`: PoS cycle 260 is needed but is absent from cache
Feb 08 19:24:32 Ubuntu-2004-focal-64-minimal massa-node[3446286]: 2023-02-08T18:24:32.500902Z  WARN massa_factory_worker::endorsement_factory: endorsement factory could not get selector draws for slot (period: 33392, thread: 17): `CycleUnavailable`: PoS cycle 260 is needed but is absent from cache
Feb 08 19:24:33 Ubuntu-2004-focal-64-minimal massa-node[3446286]: 2023-02-08T18:24:33.001197Z  WARN massa_factory_worker::endorsement_factory: endorsement factory could not get selector draws for slot (period: 33392, th

**Comment by AurelienFT** [comment]
Hello, 
Thanks for your report
The issue to put the logs is the #3512. I'm referencing your logs there.
