### ISSUE TITLE
logs.txt

### ISSUE THREAD

**Issue by FesenkoI** [massalabs/massa#3521]
CPU Model          : Intel(R) Core(TM) i5-2400 CPU @ 3.10GHz
 CPU Cores          : 4 @ 1742.457 MHz
 CPU Cache          : 6144 KB
 AES-NI             : Enabled
 VM-x/AMD-V         : Enabled
 Total Disk         : 99.8 GB (12.5 GB Used)
 Total Mem          : 7.7 GB (212.8 MB Used)
 Total Swap         : 4.0 GB (66.7 MB Used)
 System uptime      : 16 days, 10 hour 6 min
 Load average       : 0.01, 0.02, 0.00
 OS                 : Ubuntu 20.04.5 LTS
 Arch               : x86_64 (64 Bit)
 Kernel             : 5.4.0-137-generic
 TCP CC             : cubic
 Virtualization     : Dedicated

**Additional context**
фев 08 16:27:15 server2 massa-node[41119]: 2023-02-08T16:27:15.107774Z  INFO massa_final_state::final_state: final_state hash at slot (period: 32950, thread: 2): mYbCRjaYPUZvrcT93tcPnKPLF3Gjnd7CYue34QbYdwfqXrEE7
фев 08 16:27:15 server2 massa-node[41119]: 2023-02-08T16:27:15.974457Z  INFO massa_final_state::final_state: final_state hash at slot (period: 32950, thread: 3): 2WYLv3NLJFAiH3uEDMrVAJenumucGEvXPBp73RxxNDQViz4ZfY
фев 08 16:27:16 server2 massa-node[41119]: 2023-02-08T16:27:16.963597Z  INFO massa_final_state::final_state: final_state hash at slot (period: 32950, thread: 4): 2mctG6GQW3LgQsJiJod5UBcEYj1zwKGQKekAe3wyKPButUnmwE
фев 08 16:27:16 server2 massa-node[41119]: 2023-02-08T16:27:16.964319Z  INFO massa_final_state::final_state: final_state hash at slot (period: 32950, thread: 5): EVfAane2iJYQdmLd3M5MEwxW8PNz7q4ostJpCC6SwX2sqo5me
фев 08 16:27:17 server2 massa-node[41119]: 2023-02-08T16:27:17.584131Z  INFO massa_final_state::final_state: final_state hash at slot (period: 32950, thread: 6): MKiXq7NBGYWQNnwALj49WrP9EAWn9tKDqsBqKbHKUiYUj4JEH
фев 08 16:27:18 server2 massa-node[41119]: 2023-02-08T16:27:18.146936Z  INFO massa_final_state::final_state: final_state hash at slot (period: 32950, thread: 7): PZ7cEHDhcQdpguMcs2YGxfEbTHTmAvCHf8kufN81X44Dj9JE1
фев 08 16:27:18 server2 massa-node[41119]: 2023-02-08T16:27:18.751979Z  INFO massa_final_state::final_state: final_state hash at slot (period: 32950, thread: 8): zfuuDA2BwCw2AdBrJ99ja4vppM6vdKfcWyLH7fgTj3uyMHYGB
фев 08 16:27:18 server2 massa-node[41119]: 2023-02-08T16:27:18.752676Z  INFO massa_final_state::final_state: final_state hash at slot (period: 32950, thread: 9): 2BdKo9k9zUbbKdTCkzaACALMKZ4Qvzct9NvqXrDsxmXD9ihRJc
фев 08 16:27:19 server2 massa-node[41119]: 2023-02-08T16:27:19.098252Z  INFO massa_final_state::final_state: final_state hash at slot (period: 32950, thread: 10): Eew8yU8n9dob5XjnmhkUa6gKGdb9KZcoxMy5gp68u8qjRJe9y
фев 08 16:27:20 server2 massa-node[41119]: 2023-02-08T16:27:20.542078Z  INFO massa_final_state::final_state: final_state hash at slot (period: 32950, thread: 11): 2gkiN7SwyhLTPK4qr1Bo2zKsgvaGrh3GLc2ZssW3Sk7Z1LvKrG
фев 08 16:30:23 server2 massa-node[41119]: 2023-02-08T16:30:23.023122Z  INFO massa_protocol_worker::protocol_network: Connection closed with N12ZkojoVgM7xJ4s9ydHTTSuWkhqRcX6x699npCKABgKvcL8Ar38
фев 08 16:30:24 server2 massa-node[41119]: 2023-02-08T16:30:24.629431Z  INFO massa_protocol_worker::protocol_network: Connected to node N1FxFDKkrVscmbKRULmt7Rv3mFcs1ntZRewBZAzKPdDbbfqEco8
фев 08 16:30:42 server2 massa-node[41119]: 2023-02-08T16:30:42.131067Z  INFO massa_protocol_worker::protocol_network: Connection closed with N1eka3rV7Baq28xmLeMbtH46FeMnefvA8h676mWJ8UDcZsrnndj
фев 08 16:31:03 server2 massa-node[41119]: 2023-02-08T16:31:03.601134Z  INFO massa_protocol_worker::protocol_network: Connection closed with N1EwC64fUrvobnyFeKb5dXFRX5EGdvvjrdKNLFKupUz2ZGYkeDx
фев 08 16:31:06 server2 massa-node[41119]: 2023-02-08T16:31:06.916837Z  INFO massa_protocol_worker::protocol_network: Connected to node N1kRmUkFtLY1ffMFKd445GfGD8mHMmHRFCTRSJUWhc9MbabazDp
фев 08 16:31:07 server2 massa-node[41119]: 2023-02-08T16:31:07.138273Z  INFO massa_protocol_worker::protocol_network: Connection closed with N1kRmUkFtLY1ffMFKd445GfGD8mHMmHRFCTRSJUWhc9MbabazDp
фев 08 16:31:07 server2 massa-node[41119]: 2023-02-08T16:31:07.636762Z  INFO massa_protocol_worker::protocol_network: Connected to node N1nTXvQ9RDroQeuenjwCMPE4jCPCqa8L7Xf6WU61As1V6Zp2Sy
фев 08 16:35:30 server2 massa-node[41119]: 2023-02-08T16:35:30.864939Z  INFO massa_protocol_worker::protocol_network: Connected to node N1eka3rV7Baq28xmLeMbtH46FeMnefvA8h676mWJ8UDcZsrnndj
фев 08 16:37:23 server2 massa-node[41119]: 2023-02-08T16:37:23.239924Z  INFO massa_protocol_worker::protocol_network: Connected to node N121RSbVjP2KNTxstrFGp3WMbg8ULZubTZhDYcSPVwGr2otDyRsT
фев 08 16:37:23 server2 massa-node[41119]: 2023-02-08T16:37:23.384557Z  INFO massa_protocol_worker::protocol_network: Connection closed with N121RSbVjP2KNTxstrFGp3WMbg8ULZubTZhDYcSPVwGr2otDyRsT
фев 08 16:40:20 server2 massa-node[41119]: 2023-02-08T16:40:20.499236Z  INFO massa_protocol_worker::protocol_network: Connection closed with N12HjGVjJgzp5yAyaGLsvX5f3f5MqrifE1m4NedMbpfJsDaKBCdB
фев 08 16:43:11 server2 massa-node[41119]: 2023-02-08T16:43:11.850608Z  INFO massa_protocol_worker::protocol_network: Connected to node N1243FfmbBEzKBNfsirxerXw9VN4w3BsFFVerVBpUosu6HUE3YWu
фев 08 16:43:12 server2 massa-node[41119]: 2023-02-08T16:43:12.343920Z  INFO massa_protocol_worker::protocol_network: Connection closed with N1243FfmbBEzKBNfsirxerXw9VN4w3BsFFVerVBpUosu6HUE3YWu
фев 08 16:44:57 server2 massa-node[41119]: 2023-02-08T16:44:57.890796Z  INFO massa_protocol_worker::protocol_network: Connected to node N129cHt2faLANrwFRu3eauDLvW5LAiTUruhFtXzc3yXbkz9ZJLzu
фев 08 16:45:10 server2 massa-node[41119]: 2023-02-08T16:45:10.932756Z  INFO massa_protocol_worker::protocol_network: Connected to node N1L4seaV3E2W6AyFyUy6pNGQ2txCMqfbTR9DmEjv6RwpBMCz4T1
фев 08 16:45:11 server2 massa-node[41119]: 2023-02-08T16:45:11.549283Z  INFO massa_protocol_worker::protocol_network: Connection closed with N1L4seaV3E2W6AyFyUy6pNGQ2txCMqfbTR9DmEjv6RwpBMCz4T1
фев 08 16:46:24 server2 massa-node[41119]: 2023-02-08T16:46:24.000603Z  INFO massa_consensus_worker::worker::main_loop: Started cycle 258
фев 08 16:47:45 server2 massa-node[41119]: 2023-02-08T16:47:45.664141Z  INFO massa_protocol_worker::protocol_network: Connected to node N12JRueaTQwWbhpxw687oGbMeRX6eJNCrc58ookvpmpU38uqFadb
фев 08 16:47:46 server2 massa-node[41119]: 2023-02-08T16:47:46.007647Z  INFO massa_protocol_worker::protocol_network: Connection closed with N12JRueaTQwWbhpxw687oGbMeRX6eJNCrc58ookvpmpU38uqFadb
фев 08 16:49:46 server2 massa-node[41119]: 2023-02-08T16:49:46.897785Z  INFO massa_protocol_worker::protocol_network: Connected to node N12HjGVjJgzp5yAyaGLsvX5f3f5MqrifE1m4NedMbpfJsDaKBCdB
фев 08 17:05:52 server2 massa-node[41119]: 2023-02-08T17:05:52.559765Z  INFO massa_protocol_worker::protocol_network: Connection closed with N1mDjAt2mskqNWz1qtfJHcM4gaEKBnEpS2ns6mbZLnMp3Nq6EPC
фев 08 17:05:56 server2 massa-node[41119]: 2023-02-08T17:05:56.252807Z  INFO massa_protocol_worker::protocol_network: Connected to node N1EwC64fUrvobnyFeKb5dXFRX5EGdvvjrdKNLFKupUz2ZGYkeDx
фев 08 17:06:18 server2 massa-node[41119]: 2023-02-08T17:06:18.553209Z  INFO massa_protocol_worker::protocol_network: Connection closed with N1fEa19iM3GjEi7LX2uqqew1dpXbiUehmNUkftbptC9YG5gUMFX
фев 08 17:11:43 server2 massa-node[41119]: 2023-02-08T17:11:43.074674Z  INFO massa_protocol_worker::protocol_network: Connection closed with N12pZvXzFv4ZAMmSBScL7mPCwLD66tTkcxxGBGe3hLVWfSWwWYmr
фев 08 17:11:46 server2 massa-node[41119]: 2023-02-08T17:11:46.340252Z  INFO massa_protocol_worker::protocol_network: Connected to node N1mDjAt2mskqNWz1qtfJHcM4gaEKBnEpS2ns6mbZLnMp3Nq6EPC
фев 08 17:16:08 server2 massa-node[41119]: 2023-02-08T17:16:08.062589Z  INFO massa_protocol_worker::protocol_network: Connection closed with N1FxFDKkrVscmbKRULmt7Rv3mFcs1ntZRewBZAzKPdDbbfqEco8
фев 08 17:16:15 server2 massa-node[41119]: 2023-02-08T17:16:15.007009Z  INFO massa_protocol_worker::protocol_network: Connected to node N1FxFDKkrVscmbKRULmt7Rv3mFcs1ntZRewBZAzKPdDbbfqEco8
фев 08 17:19:43 server2 massa-node[41119]: 2023-02-08T17:19:43.919840Z  INFO massa_protocol_worker::protocol_network: Connected to node N12iKgZ4FisBbnRo5RdwhPV4awqFJhMutXGmxh9Y2qs3t83v6Cin
фев 08 17:20:24 server2 massa-node[41119]: 2023-02-08T17:20:24.000607Z  WARN massa_factory_worker::endorsement_factory: endorsement factory could not get selector draws for slot (period: 33152, thread: 0): `CycleUnavailable`: PoS cycle 259 is needed but is absent from cache
фев 08 17:20:24 server2 massa-node[41119]: 2023-02-08T17:20:24.500731Z  WARN massa_factory_worker::endorsement_factory: endorsement factory could not get selector draws for slot (period: 33152, thread: 1): `CycleUnavailable`: PoS cycle 259 is needed but is absent from cache
фев 08 17:20:25 server2 massa-node[41119]: 2023-02-08T17:20:25.000848Z  WARN massa_factory_worker::endorsement_factory: endorsement factory could not get selector draws for slot (period: 33152, thread: 2): `CycleUnavailable`: PoS cycle 259 is needed but is absent from cache
фев 08 17:20:25 server2 massa-node[41119]: 2023-02-08T17:20:25.500947Z  WARN massa_factory_worker::endorsement_factory: endorsement factory could not get selector draws for slot (period: 33152, thread: 3): `CycleUnavailable`: PoS cycle 259 is needed but is absent from cache
фев 08 17:20:26 server2 massa-node[41119]: 2023-02-08T17:20:26.001051Z  WARN massa_factory_worker::endorsement_factory: endorsement factory could not get selector draws for slot (period: 33152, thread: 4): `CycleUnavailable`: PoS cycle 259 is needed but is absent from cache
фев 08 17:20:26 server2 massa-node[41119]: 2023-02-08T17:20:26.500164Z  WARN massa_factory_worker::endorsement_factory: endorsement factory could not get selector draws for slot (period: 33152, thread: 5): `CycleUnavailable`: PoS cycle 259 is needed but is absent from cache
фев 08 17:20:27 server2 massa-node[41119]: 2023-02-08T17:20:27.000273Z  WARN massa_factory_worker::endorsement_factory: endorsement factory could not get selector draws for slot (period: 33152, thread: 6): `CycleUnavailable`: PoS cycle 259 is needed but is absent from cache
фев 08 17:20:27 server2 massa-node[41119]: 2023-02-08T17:20:27.500380Z  WARN massa_factory_worker::endorsement_factory: endorsement factory could not get selector draws for slot (period: 33152, thread: 7): `CycleUnavailable`: PoS cycle 259 is needed but is absent from cache
фев 08 17:20:28 server2 massa-node[41119]: 2023-02-08T17:20:28.000500Z  WARN massa_factory_worker::endorsement_factory: endorsement factory could not get selector draws for slot (period: 33152, thread: 8): `CycleUnavailable`: PoS cycle 259 is needed but is absent from cache
фев 08 17:20:29 server2 massa-node[41119]: 2023-02-08T17:20:29.500848Z  WARN massa_factory_worker::endorsement_factory: endorsement factory could not get selector draws for slot (period: 33152, thread: 11): `CycleUnavailable`: PoS cycle 259 is needed but is absent from cache
фев 08 17:20:30 server2 massa-node[41119]: 2023-02-08T17:20:30.000963Z  WARN massa_factory_worker::endorsement_factory: endorsement factory could not get selector draws for slot (period: 33152, thread: 12): `CycleUnavailable`: PoS cycle 259 is needed but is absent from cache
фев 08 17:20:30 server2 massa-node[41119]: 2023-02-08T17:20:30.501076Z  WARN massa_factory_worker::endorsement_factory: endorsement factory could not get selector draws for slot (period: 33152, thread: 13): `CycleUnavailable`: PoS cycle 259 is needed but is absent from cache
фев 08 17:20:31 server2 massa-node[41119]: 2023-02-08T17:20:31.000198Z  WARN massa_factory_worker::endorsement_factory: endorsement factory could not get selector draws for slot (period: 33152, thread: 14): `CycleUnavailable`: PoS cycle 259 is needed but is absent from cache
фев 08 17:20:31 server2 massa-node[41119]: 2023-02-08T17:20:31.500319Z  WARN massa_factory_worker::endorsement_factory: endorsement factory could not get selector draws for slot (period: 33152, thread: 15): `CycleUnavailable`: PoS cycle 259 is needed but is absent from cache
фев 08 17:20:32 server2 massa-node[41119]: 2023-02-08T17:20:32.000432Z  WARN massa_factory_worker::endorsement_factory: endorsement factory could not get selector draws for slot (period: 33152, thread: 16): `CycleUnavailable`: PoS cycle 259 is needed but is absent from cache
фев 08 17:20:32 server2 massa-node[41119]: 2023-02-08T17:20:32.000686Z  INFO massa_consensus_worker::worker::main_loop: Started cycle 259
фев 08 17:20:32 server2 massa-node[41119]: 2023-02-08T17:20:32.000838Z  WARN massa_factory_worker::block_factory: block factory could not get selector draws for slot (period: 33152, thread: 0): `CycleUnavailable`: PoS cycle 259 is needed but is absent from cache
фев 08 17:20:32 server2 massa-node[41119]: 2023-02-08T17:20:32.500549Z  WARN massa_factory_worker::endorsement_factory: endorsement factory could not get selector draws for slot (period: 33152, thread: 17): `CycleUnavailable`: PoS cycle 259 is needed but is absent from cache
фев 08 17:20:32 server2 massa-node[41119]: 2023-02-08T17:20:32.500934Z  WARN massa_factory_worker::block_factory: block factory could not get selector draws for slot (period: 33152, thread: 1): `CycleUnavailable`: PoS cycle 259 is needed but is absent from cache
фев 08 17:20:33 server2 massa-node[41119]: 2023-02-08T17:20:33.000662Z  WARN massa_factory_worker::endorsement_factory: endorsement factory could not get selector draws for slot (period: 33152, thread: 18): `CycleUnavailable`: PoS cycle 259 is needed but is absent from cache
фев 08 17:20:33 server2 massa-node[41119]: 2023-02-08T17:20:33.001040Z  WARN massa_factory_worker::block_factory: block factory could not get selector draws for slot (period: 33152, thread: 2): `CycleUnavailable`: PoS cycle 259 is needed but is absent from cache
фев 08 17:20:33 server2 massa-node[41119]: 2023-02-08T17:20:33.500157Z  WARN massa_factory_worker::block_factory: block factory could not get selector draws for slot (period: 33152, thread: 3): `CycleUnavailable`: PoS cycle 259 is needed but is absent from cache
фев 08 17:20:33 server2 massa-node[41119]: 2023-02-08T17:20:33.500762Z  WARN massa_factory_worker::endorsement_factory: endorsement factory could not get selector draws for slot (period: 33152, thread: 19): `CycleUnavailable`: PoS cycle 259 is needed but is absent from cache
фев 08 17:20:34 server2 massa-node[41119]: 2023-02-08T17:20:34.000283Z  WARN massa_factory_worker::block_factory: block factory could not get selector draws for slot (period: 33152, thread: 4): `CycleUnavailable`: PoS cycle 259 is needed but is absent from cache
фев 08 17:20:34 server2 massa-node[41119]: 2023-02-08T17:20:34.000859Z  WARN massa_factory_worker::endorsement_factory: endorsement factory could not get selector draws for slot (period: 33152, thread: 20): `CycleUnavailable`: PoS cycle 259 is needed but is absent from cache
фев 08 17:20:34 server2 massa-node[41119]: 2023-02-08T17:20:34.500411Z  WARN massa_factory_worker::block_factory: block factory could not get selector draws for slot (period: 33152, thread: 5): `CycleUnavailable`: PoS cycle 259 is needed but is absent from cache
фев 08 17:20:34 server2 massa-node[41119]: 2023-02-08T17:20:34.500989Z  WARN massa_factory_worker::endorsement_factory: endorsement factory could not get selector draws for slot (period: 33152, thread: 21): `CycleUnavailable`: PoS cycle 259 is needed but is absent from cache
фев 08 17:20:35 server2 massa-node[41119]: 2023-02-08T17:20:35.000100Z  WARN massa_factory_worker::endorsement_factory: endorsement factory could not get selector draws for slot (period: 33152, thread: 22): `CycleUnavailable`: PoS cycle 259 is needed but is absent from cache
фев 08 17:20:35 server2 massa-node[41119]: 2023-02-08T17:20:35.000517Z  WARN massa_factory_worker::block_factory: block factory could not get selector draws for slot (period: 33152, thread: 6): `CycleUnavailable`: PoS cycle 259 is needed but is absent from cache
фев 08 17:20:35 server2 massa-node[41119]: 2023-02-08T17:20:35.500213Z  WARN massa_factory_worker::endorsement_factory: endorsement factory could not get selector draws for slot (period: 33152, thread: 23): `CycleUnavailable`: PoS cycle 259 is needed but is absent from cache
фев 08 17:20:35 server2 massa-node[41119]: 2023-02-08T17:20:35.500603Z  WARN massa_factory_worker::block_factory: block factory could not get selector draws for slot (period: 33152, thread: 7): `CycleUnavailable`: PoS cycle 259 is needed but is absent from cache
фев 08 17:20:36 server2 massa-node[41119]: 2023-02-08T17:20:36.000329Z  WARN massa_factory_worker::endorsement_factory: endorsement factory could not get selector draws for slot (period: 33152, thread: 24): `CycleUnavailable`: PoS cycle 259 is needed but is absent from cache
фев 08 17:20:36 server2 massa-node[41119]: 2023-02-08T17:20:36.000684Z  WARN massa_factory_worker::block_factory: block factory could not get selector draws for slot (period: 33152, thread: 8): `CycleUnavailable`: PoS cycle 259 is needed but is absent from cache
фев 08 17:20:36 server2 massa-node[41119]: 2023-02-08T17:20:36.500439Z  WARN massa_factory_worker::endorsement_factory: endorsement factory could not get selector draws for slot (period: 33152, thread: 25): `CycleUnavailable`: PoS cycle 259 is needed but is absent from cache

..............................

фев 08 17:44:12 server2 massa-node[41119]: 2023-02-08T17:44:12.500632Z  WARN massa_factory_worker::block_factory: block factory could not get selector draws for slot (period: 33240, thread: 25): `CycleUnavailable`: PoS cycle 259 is needed but is absent from cache
фев 08 17:44:12 server2 massa-node[41119]: 2023-02-08T17:44:12.500657Z  WARN massa_factory_worker::endorsement_factory: endorsement factory could not get selector draws for slot (period: 33241, thread: 9): `CycleUnavailable`: PoS cycle 259 is needed but is absent from cache
фев 08 17:44:13 server2 massa-node[41119]: 2023-02-08T17:44:13.000740Z  WARN massa_factory_worker::block_factory: block factory could not get selector draws for slot (period: 33240, thread: 26): `CycleUnavailable`: PoS cycle 259 is needed but is absent from cache
фев 08 17:44:13 server2 massa-node[41119]: 2023-02-08T17:44:13.000763Z  WARN massa_factory_worker::endorsement_factory: endorsement factory could not get selector draws for slot (period: 33241, thread: 10): `CycleUnavailable`: PoS cycle 259 is needed but is absent from cache
фев 08 17:44:13 server2 massa-node[41119]: 2023-02-08T17:44:13.500848Z  WARN massa_factory_worker::block_factory: block factory could not get selector draws for slot (period: 33240, thread: 27): `CycleUnavailable`: PoS cycle 259 is needed but is absent from cache
фев 08 17:44:13 server2 massa-node[41119]: 2023-02-08T17:44:13.500867Z  WARN massa_factory_worker::endorsement_factory: endorsement factory could not get selector draws for slot (period: 33241, thread: 11): `CycleUnavailable`: PoS cycle 259 is needed but is absent from cache
фев 08 17:44:14 server2 massa-node[41119]: 2023-02-08T17:44:14.000960Z  WARN massa_factory_worker::block_factory: block factory could not get selector draws for slot (period: 33240, thread: 28): `CycleUnavailable`: PoS cycle 259 is needed but is absent from cache
фев 08 17:44:14 server2 massa-node[41119]: 2023-02-08T17:44:14.000997Z  WARN massa_factory_worker::endorsement_factory: endorsement factory could not get selector draws for slot (period: 33241, thread: 12): `CycleUnavailable`: PoS cycle 259 is needed but is absent from cache
фев 08 17:44:14 server2 systemd[1]: Stopping Massa Node...
фев 08 17:44:14 server2 systemd[1]: massad.service: Succeeded.
фев 08 17:44:14 server2 systemd[1]: Stopped Massa Node.
фев 08 17:44:14 server2 systemd[1]: Started Massa Node.
фев 08 17:44:14 server2 massa-node[56459]: 2023-02-08T17:44:14.182031Z  INFO massa_node: Node version : TEST.19.1
фев 08 17:44:14 server2 massa-node[56459]: 2023-02-08T17:44:14.680422Z  INFO massa_bootstrap::client: Start bootstrapping from 54.36.174.177:31245
фев 08 17:44:20 server2 massa-node[56459]: 2023-02-08T17:44:20.635900Z  WARN massa_bootstrap::client: Error while bootstrapping: io error: `massa_consensus` error: there was an inconsistency between containers could not find latest block for thread 0
фев 08 17:44:20 server2 massa-node[56459]: 2023-02-08T17:44:20.636101Z  INFO massa_bootstrap::client: Bootstrap from server 54.36.174.177:31245 failed. Your node will try to bootstrap from another server in 1m.
фев 08 17:45:20 server2 massa-node[56459]: 2023-02-08T17:45:20.637304Z  INFO massa_bootstrap::client: Start bootstrapping from 158.69.120.215:31245
фев 08 17:45:21 server2 massa-node[56459]: 2023-02-08T17:45:21.681929Z  WARN massa_bootstrap::client: Error while bootstrapping: io error: `massa_consensus` error: there was an inconsistency between containers could not find latest block for thread 0
фев 08 17:45:21 server2 massa-node[56459]: 2023-02-08T17:45:21.682017Z  INFO massa_bootstrap::client: Bootstrap from server 158.69.120.215:31245 failed. Your node will try to bootstrap from another server in 1m.
фев 08 17:46:21 server2 massa-node[56459]: 2023-02-08T17:46:21.683623Z  INFO massa_bootstrap::client: Start bootstrapping from 198.27.74.52:31245
фев 08 17:46:22 server2 massa-node[56459]: 2023-02-08T17:46:22.658193Z  WARN massa_bootstrap::client: Error while bootstrapping: io error: `massa_consensus` error: there was an inconsistency between containers could not find latest block for thread 0

**Comment by AurelienFT** [comment]
Hello, 
Thanks for your report
The issue to put the logs is the #3512. I'm referencing your logs there.
