### ISSUE TITLE
19.1 fail logs

### ISSUE THREAD

**Issue by RomanTsibii** [massalabs/massa#3524]
**Describe the bug**
Fail logs

**To Reproduce**

1. journalctl -o cat -f -u massa -n 100

**Expected behavior**
good work

**Screenshots**
![image](https://user-images.githubusercontent.com/43521642/217625826-735cb591-dbb0-4b96-99b0-2fb51e6dda68.png)

**Desktop (please complete the following information):**

- Contabo provider
- CPU - 6
- RAM - 15.6 Gb
- SSD - 400 GB

**Additional context**
[logs.txt](https://github.com/massalabs/massa/files/10689040/logs.txt)

**Comment by AurelienFT** [comment]
Hello, 
Thanks for your report
The issue to put the logs is the #3512. I'm referencing your logs there.
