### ISSUE TITLE
logs.txt

### ISSUE THREAD

**Issue by Kerim1979** [massalabs/massa#3530]
warning: /root/massa/massa-node/Cargo.toml: unused manifest key: build
    Finished release [optimized] target(s) in 4.39s
     Running `/root/massa/target/release/massa-node -p kerimim81`
[2m2023-02-08T16:05:45.516333Z[0m [32m INFO[0m [2mmassa_node[0m[2m:[0m Node version : TEST.19.1
[2m2023-02-08T16:05:45.583993Z[0m [32m INFO[0m [2mmassa_bootstrap::client[0m[2m:[0m Start bootstrapping from 54.36.174.177:31245
[2m2023-02-08T16:07:43.808911Z[0m [32m INFO[0m [2mmassa_bootstrap::client[0m[2m:[0m Slot is too old retry bootstrap from scratch
[2m2023-02-08T16:07:43.809339Z[0m [33m WARN[0m [2mmassa_bootstrap::client[0m[2m:[0m Error while bootstrapping: general bootstrap error: Slot too old
[2m2023-02-08T16:07:43.810994Z[0m [32m INFO[0m [2mmassa_bootstrap::client[0m[2m:[0m Bootstrap from server 54.36.174.177:31245 failed. Your node will try to bootstrap from another server in 1m.
[2m2023-02-08T16:08:43.812812Z[0m [32m INFO[0m [2mmassa_bootstrap::client[0m[2m:[0m Start bootstrapping from 198.27.74.52:31245
thread 'main' panicked at 'PoS received cycle (253) should be equal to the next expected cycle (257)', massa-pos-exports/src/pos_final_state.rs:448:17
stack backtrace:
   0:     0x5565c235a23a - std::backtrace_rs::backtrace::libunwind::trace::h3b7acaa3917681cd
                               at /rustc/e972bc8083d5228536dfd42913c8778b6bb04c8e/library/std/src/../../backtrace/src/backtrace/libunwind.rs:93:5
   1:     0x5565c235a23a - std::backtrace_rs::backtrace::trace_unsynchronized::hfa01011b323ea2f5
                               at /rustc/e972bc8083d5228536dfd42913c8778b6bb04c8e/library/std/src/../../backtrace/src/backtrace/mod.rs:66:5
   2:     0x5565c235a23a - std::sys_common::backtrace::_print_fmt::ha602fada1436baf8
                               at /rustc/e972bc8083d5228536dfd42913c8778b6bb04c8e/library/std/src/sys_common/backtrace.rs:65:5
   3:     0x5565c235a23a - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::h655541211057ac82
                               at /rustc/e972bc8083d5228536dfd42913c8778b6bb04c8e/library/std/src/sys_common/backtrace.rs:44:22
   4:     0x5565c237e0fe - core::fmt::write::h6a7eb7a2b48075cf
                               at /rustc/e972bc8083d5228536dfd42913c8778b6bb04c8e/library/core/src/fmt/mod.rs:1232:17
   5:     0x5565c2354c65 - std::io::Write::write_fmt::h2cda8d245c5515e4
                               at /rustc/e972bc8083d5228536dfd42913c8778b6bb04c8e/library/std/src/io/mod.rs:1682:15
   6:     0x5565c235a005 - std::sys_common::backtrace::_print::h6d5ba0bded266c7d
                               at /rustc/e972bc8083d5228536dfd42913c8778b6bb04c8e/library/std/src/sys_common/backtrace.rs:47:5
   7:     0x5565c235a005 - std::sys_common::backtrace::print::h3890017a5fe1cf10
                               at /rustc/e972bc8083d5228536dfd42913c8778b6bb04c8e/library/std/src/sys_common/backtrace.rs:34:9
   8:     0x5565c235bb3f - std::panicking::default_hook::{{closure}}::hd7242903a3137598
                               at /rustc/e972bc8083d5228536dfd42913c8778b6bb04c8e/library/std/src/panicking.rs:267:22
   9:     0x5565c235b87b - std::panicking::default_hook::h49bb35ce6e6e1d8d
                               at /rustc/e972bc8083d5228536dfd42913c8778b6bb04c8e/library/std/src/panicking.rs:286:9
  10:     0x5565c140515e - massa_node::run::{{closure}}::{{closure}}::h3809128c5fa9c9da
  11:     0x5565c235c26a - <alloc::boxed::Box<F,A> as core::ops::function::Fn<Args>>::call::h0aeb8804abb6fc95
                               at /rustc/e972bc8083d5228536dfd42913c8778b6bb04c8e/library/alloc/src/boxed.rs:2002:9
  12:     0x5565c235c26a - std::panicking::rust_panic_with_hook::h7ce6aaab71fab830
                               at /rustc/e972bc8083d5228536dfd42913c8778b6bb04c8e/library/std/src/panicking.rs:692:13
  13:     0x5565c235bfe9 - std::panicking::begin_panic_handler::{{closure}}::h1bf180bb16a10730
                               at /rustc/e972bc8083d5228536dfd42913c8778b6bb04c8e/library/std/src/panicking.rs:579:13
  14:     0x5565c235a6ec - std::sys_common::backtrace::__rust_end_short_backtrace::h810538e4bd7147fc
                               at /rustc/e972bc8083d5228536dfd42913c8778b6bb04c8e/library/std/src/sys_common/backtrace.rs:137:18
  15:     0x5565c235bcf2 - rust_begin_unwind
                               at /rustc/e972bc8083d5228536dfd42913c8778b6bb04c8e/library/std/src/panicking.rs:575:5
  16:     0x5565c12a12d3 - core::panicking::panic_fmt::h18415b3d88a06193
                               at /rustc/e972bc8083d5228536dfd42913c8778b6bb04c8e/library/core/src/panicking.rs:64:14
  17:     0x5565c1dab0b4 - massa_pos_exports::pos_final_state::PoSFinalState::set_cycle_history_part::he5842728659bd72e
  18:     0x5565c1431153 - massa_bootstrap::client::bootstrap_from_server::{{closure}}::h41a157faec19480c
  19:     0x5565c1436d18 - massa_bootstrap::client::get_state::{{closure}}::h84d696f10ca03617
  20:     0x5565c1458c8a - <tokio::future::poll_fn::PollFn<F> as core::future::future::Future>::poll::h3397b933d293fb39
  21:     0x5565c13f8f5a - massa_node::launch::{{closure}}::h95f81a15489ab3dd
  22:     0x5565c13e6ceb - tokio::runtime::park::CachedParkThread::block_on::h33ca8bac8f6adc68
  23:     0x5565c14cd719 - tokio::runtime::scheduler::multi_thread::MultiThread::block_on::h9b5531cdf0947cca
  24:     0x5565c12f34c4 - massa_node::main::he8be11d796addab4
  25:     0x5565c1479103 - std::sys_common::backtrace::__rust_begin_short_backtrace::ha65b973dff8ee7d6
  26:     0x5565c12d8d6d - std::rt::lang_start::{{closure}}::h7812bdb89643d909
  27:     0x5565c234e1fc - core::ops::function::impls::<impl core::ops::function::FnOnce<A> for &F>::call_once::hea48b06ca5628d65
                               at /rustc/e972bc8083d5228536dfd42913c8778b6bb04c8e/library/core/src/ops/function.rs:287:13
  28:     0x5565c234e1fc - std::panicking::try::do_call::h40c82b91c2f3ec01
                               at /rustc/e972bc8083d5228536dfd42913c8778b6bb04c8e/library/std/src/panicking.rs:483:40
  29:     0x5565c234e1fc - std::panicking::try::h294fb6a9e690234d
                               at /rustc/e972bc8083d5228536dfd42913c8778b6bb04c8e/library/std/src/panicking.rs:447:19
  30:     0x5565c234e1fc - std::panic::catch_unwind::h1628fb44d7820a35
                               at /rustc/e972bc8083d5228536dfd42913c8778b6bb04c8e/library/std/src/panic.rs:140:14
  31:     0x5565c234e1fc - std::rt::lang_start_internal::{{closure}}::hd51180ac3890c6d7
                               at /rustc/e972bc8083d5228536dfd42913c8778b6bb04c8e/library/std/src/rt.rs:148:48
  32:     0x5565c234e1fc - std::panicking::try::do_call::h365257d8d9f273c6
                               at /rustc/e972bc8083d5228536dfd42913c8778b6bb04c8e/library/std/src/panicking.rs:483:40
  33:     0x5565c234e1fc - std::panicking::try::hf00323a68991f477
                               at /rustc/e972bc8083d5228536dfd42913c8778b6bb04c8e/library/std/src/panicking.rs:447:19
  34:     0x5565c234e1fc - std::panic::catch_unwind::he7852e78401c75ed
                               at /rustc/e972bc8083d5228536dfd42913c8778b6bb04c8e/library/std/src/panic.rs:140:14
  35:     0x5565c234e1fc - std::rt::lang_start_internal::h4e48e369aae5d9d6
                               at /rustc/e972bc8083d5228536dfd42913c8778b6bb04c8e/library/std/src/rt.rs:148:20
  36:     0x5565c12f3755 - main
  37:     0x7f9d971dc083 - __libc_start_main
  38:     0x5565c12c562e - _start
  39:                0x0 - <unknown>

**Comment by AurelienFT** [comment]
Hello, 
Thanks for your report
The issue to put the logs is the #3512. I'm referencing your logs there.
