### ISSUE TITLE
logs

### ISSUE THREAD

**Issue by JekaInit** [massalabs/massa#3531]
Feb 08 18:28:47 ubuntu-8gb-hel1-2-massa massa-node[9438]: 2023-02-08T18:28:47.644143Z  INFO massa_protocol_worker::protocol_network: Connected to node N12TRuK3tD9v2LXunD2xYenQnBUGvLnoEV5Wa98Y2XjqRHLyUuDi
Feb 08 18:28:47 ubuntu-8gb-hel1-2-massa massa-node[9438]: 2023-02-08T18:28:47.674923Z  INFO massa_protocol_worker::protocol_network: Connection closed with N12TRuK3tD9v2LXunD2xYenQnBUGvLnoEV5Wa98Y2XjqRHLyUuDi
Feb 08 18:28:47 ubuntu-8gb-hel1-2-massa massa-node[9438]: 2023-02-08T18:28:47.705619Z  INFO massa_protocol_worker::protocol_network: Connected to node N12TRuK3tD9v2LXunD2xYenQnBUGvLnoEV5Wa98Y2XjqRHLyUuDi
Feb 08 18:28:47 ubuntu-8gb-hel1-2-massa massa-node[9438]: 2023-02-08T18:28:47.710435Z  INFO massa_protocol_worker::protocol_network: Connection closed with N12TRuK3tD9v2LXunD2xYenQnBUGvLnoEV5Wa98Y2XjqRHLyUuDi
Feb 08 18:28:47 ubuntu-8gb-hel1-2-massa massa-node[9438]: 2023-02-08T18:28:47.720673Z  INFO massa_protocol_worker::protocol_network: Connected to node N12TRuK3tD9v2LXunD2xYenQnBUGvLnoEV5Wa98Y2XjqRHLyUuDi
Feb 08 18:28:47 ubuntu-8gb-hel1-2-massa massa-node[9438]: 2023-02-08T18:28:47.723991Z  INFO massa_protocol_worker::protocol_network: Connection closed with N12TRuK3tD9v2LXunD2xYenQnBUGvLnoEV5Wa98Y2XjqRHLyUuDi
Feb 08 18:28:47 ubuntu-8gb-hel1-2-massa massa-node[9438]: 2023-02-08T18:28:47.735920Z  INFO massa_protocol_worker::protocol_network: Connected to node N12TRuK3tD9v2LXunD2xYenQnBUGvLnoEV5Wa98Y2XjqRHLyUuDi
Feb 08 18:28:47 ubuntu-8gb-hel1-2-massa massa-node[9438]: 2023-02-08T18:28:47.742155Z  INFO massa_protocol_worker::protocol_network: Connection closed with N12TRuK3tD9v2LXunD2xYenQnBUGvLnoEV5Wa98Y2XjqRHLyUuDi
Feb 08 18:28:47 ubuntu-8gb-hel1-2-massa massa-node[9438]: 2023-02-08T18:28:47.757940Z  INFO massa_protocol_worker::protocol_network: Connected to node N12TRuK3tD9v2LXunD2xYenQnBUGvLnoEV5Wa98Y2XjqRHLyUuDi
Feb 08 18:28:47 ubuntu-8gb-hel1-2-massa massa-node[9438]: 2023-02-08T18:28:47.762432Z  INFO massa_protocol_worker::protocol_network: Connection closed with N12TRuK3tD9v2LXunD2xYenQnBUGvLnoEV5Wa98Y2XjqRHLyUuDi
Feb 08 18:28:47 ubuntu-8gb-hel1-2-massa massa-node[9438]: 2023-02-08T18:28:47.774041Z  INFO massa_protocol_worker::protocol_network: Connected to node N12TRuK3tD9v2LXunD2xYenQnBUGvLnoEV5Wa98Y2XjqRHLyUuDi
Feb 08 18:28:47 ubuntu-8gb-hel1-2-massa massa-node[9438]: 2023-02-08T18:28:47.785066Z  INFO massa_protocol_worker::protocol_network: Connection closed with N12TRuK3tD9v2LXunD2xYenQnBUGvLnoEV5Wa98Y2XjqRHLyUuDi
Feb 08 18:28:47 ubuntu-8gb-hel1-2-massa massa-node[9438]: 2023-02-08T18:28:47.791064Z  INFO massa_protocol_worker::protocol_network: Connected to node N12TRuK3tD9v2LXunD2xYenQnBUGvLnoEV5Wa98Y2XjqRHLyUuDi
Feb 08 18:28:47 ubuntu-8gb-hel1-2-massa massa-node[9438]: 2023-02-08T18:28:47.811727Z  INFO massa_protocol_worker::protocol_network: Connection closed with N12TRuK3tD9v2LXunD2xYenQnBUGvLnoEV5Wa98Y2XjqRHLyUuDi
Feb 08 18:28:47 ubuntu-8gb-hel1-2-massa massa-node[9438]: 2023-02-08T18:28:47.828309Z  INFO massa_protocol_worker::protocol_network: Connected to node N12TRuK3tD9v2LXunD2xYenQnBUGvLnoEV5Wa98Y2XjqRHLyUuDi
Feb 08 18:28:47 ubuntu-8gb-hel1-2-massa massa-node[9438]: 2023-02-08T18:28:47.837051Z  INFO massa_protocol_worker::protocol_network: Connection closed with N12TRuK3tD9v2LXunD2xYenQnBUGvLnoEV5Wa98Y2XjqRHLyUuDi
Feb 08 18:28:47 ubuntu-8gb-hel1-2-massa massa-node[9438]: 2023-02-08T18:28:47.848055Z  INFO massa_protocol_worker::protocol_network: Connected to node N12TRuK3tD9v2LXunD2xYenQnBUGvLnoEV5Wa98Y2XjqRHLyUuDi
Feb 08 18:28:47 ubuntu-8gb-hel1-2-massa massa-node[9438]: 2023-02-08T18:28:47.853515Z  INFO massa_protocol_worker::protocol_network: Connection closed with N12TRuK3tD9v2LXunD2xYenQnBUGvLnoEV5Wa98Y2XjqRHLyUuDi
Feb 08 18:28:47 ubuntu-8gb-hel1-2-massa massa-node[9438]: 2023-02-08T18:28:47.876785Z  INFO massa_protocol_worker::protocol_network: Connected to node N12TRuK3tD9v2LXunD2xYenQnBUGvLnoEV5Wa98Y2XjqRHLyUuDi
Feb 08 18:28:47 ubuntu-8gb-hel1-2-massa massa-node[9438]: 2023-02-08T18:28:47.884141Z  INFO massa_protocol_worker::protocol_network: Connection closed with N12TRuK3tD9v2LXunD2xYenQnBUGvLnoEV5Wa98Y2XjqRHLyUuDi
Feb 08 18:28:47 ubuntu-8gb-hel1-2-massa massa-node[9438]: 2023-02-08T18:28:47.898012Z  INFO massa_protocol_worker::protocol_network: Connected to node N12TRuK3tD9v2LXunD2xYenQnBUGvLnoEV5Wa98Y2XjqRHLyUuDi
Feb 08 18:28:47 ubuntu-8gb-hel1-2-massa massa-node[9438]: 2023-02-08T18:28:47.913210Z  INFO massa_protocol_worker::protocol_network: Connection closed with N12TRuK3tD9v2LXunD2xYenQnBUGvLnoEV5Wa98Y2XjqRHLyUuDi
Feb 08 18:28:47 ubuntu-8gb-hel1-2-massa massa-node[9438]: 2023-02-08T18:28:47.922770Z  INFO massa_protocol_worker::protocol_network: Connected to node N12TRuK3tD9v2LXunD2xYenQnBUGvLnoEV5Wa98Y2XjqRHLyUuDi
Feb 08 18:28:47 ubuntu-8gb-hel1-2-massa massa-node[9438]: 2023-02-08T18:28:47.934885Z  INFO massa_protocol_worker::protocol_network: Connection closed with N12TRuK3tD9v2LXunD2xYenQnBUGvLnoEV5Wa98Y2XjqRHLyUuDi
Feb 08 18:28:47 ubuntu-8gb-hel1-2-massa massa-node[9438]: 2023-02-08T18:28:47.943314Z  INFO massa_protocol_worker::protocol_network: Connected to node N12TRuK3tD9v2LXunD2xYenQnBUGvLnoEV5Wa98Y2XjqRHLyUuDi
Feb 08 18:28:47 ubuntu-8gb-hel1-2-massa massa-node[9438]: 2023-02-08T18:28:47.964211Z  INFO massa_protocol_worker::protocol_network: Connection closed with N12TRuK3tD9v2LXunD2xYenQnBUGvLnoEV5Wa98Y2XjqRHLyUuDi
Feb 08 18:28:47 ubuntu-8gb-hel1-2-massa massa-node[9438]: 2023-02-08T18:28:47.974326Z  INFO massa_protocol_worker::protocol_network: Connected to node N12TRuK3tD9v2LXunD2xYenQnBUGvLnoEV5Wa98Y2XjqRHLyUuDi
Feb 08 18:28:47 ubuntu-8gb-hel1-2-massa massa-node[9438]: 2023-02-08T18:28:47.986207Z  INFO massa_protocol_worker::protocol_network: Connection closed with N12TRuK3tD9v2LXunD2xYenQnBUGvLnoEV5Wa98Y2XjqRHLyUuDi
Feb 08 18:28:48 ubuntu-8gb-hel1-2-massa massa-node[9438]: 2023-02-08T18:28:48.000241Z  INFO massa_consensus_worker::worker::main_loop: Started cycle 261
Feb 08 18:28:48 ubuntu-8gb-hel1-2-massa massa-node[9438]: 2023-02-08T18:28:48.000280Z  WARN massa_consensus_worker::state::stats: desynchronization detected because the recent final block history is empty or contains only blocks produced by this node
Feb 08 18:28:48 ubuntu-8gb-hel1-2-massa massa-node[9438]: 2023-02-08T18:28:48.000585Z  WARN massa_factory_worker::block_factory: block factory could not get selector draws for slot (period: 33408, thread: 0): `CycleUnavailable`: PoS cycle 261 is needed but is absent from cache
Feb 08 18:28:48 ubuntu-8gb-hel1-2-massa massa-node[9438]: 2023-02-08T18:28:48.000624Z  WARN massa_factory_worker::endorsement_factory: endorsement factory could not get selector draws for slot (period: 33408, thread: 16): `CycleUnavailable`: PoS cycle 261 is needed but is absent from cache
Feb 08 18:28:48 ubuntu-8gb-hel1-2-massa massa-node[9438]: 2023-02-08T18:28:48.007534Z  INFO massa_protocol_worker::protocol_network: Connected to node N12TRuK3tD9v2LXunD2xYenQnBUGvLnoEV5Wa98Y2XjqRHLyUuDi
Feb 08 18:28:48 ubuntu-8gb-hel1-2-massa massa-node[9438]: 2023-02-08T18:28:48.014299Z  INFO massa_protocol_worker::protocol_network: Connection closed with N12TRuK3tD9v2LXunD2xYenQnBUGvLnoEV5Wa98Y2XjqRHLyUuDi
Feb 08 18:28:48 ubuntu-8gb-hel1-2-massa massa-node[9438]: 2023-02-08T18:28:48.048498Z  WARN massa_node: in response to a desynchronization, the node is going to bootstrap again
Feb 08 18:28:48 ubuntu-8gb-hel1-2-massa massa-node[9438]: 2023-02-08T18:28:48.048714Z  INFO massa_api: API finished cleanly
Feb 08 18:28:48 ubuntu-8gb-hel1-2-massa massa-node[9438]: 2023-02-08T18:28:48.048725Z  INFO massa_api: API finished cleanly
Feb 08 18:28:48 ubuntu-8gb-hel1-2-massa massa-node[9438]: 2023-02-08T18:28:48.048729Z  INFO massa_api: API finished cleanly
Feb 08 18:28:48 ubuntu-8gb-hel1-2-massa massa-node[9438]: 2023-02-08T18:28:48.048733Z  INFO massa_factory_worker::manager: stopping factory...
Feb 08 18:28:48 ubuntu-8gb-hel1-2-massa massa-node[9438]: 2023-02-08T18:28:48.048981Z  INFO massa_factory_worker::manager: factory stopped
Feb 08 18:28:48 ubuntu-8gb-hel1-2-massa massa-node[9438]: 2023-02-08T18:28:48.048989Z  INFO massa_protocol_exports::protocol_controller: stopping protocol controller...
Feb 08 18:28:48 ubuntu-8gb-hel1-2-massa massa-node[9438]: 2023-02-08T18:28:48.088434Z  INFO massa_protocol_worker::protocol_worker: protocol worker finished cleanly
Feb 08 18:28:48 ubuntu-8gb-hel1-2-massa massa-node[9438]: 2023-02-08T18:28:48.088498Z  INFO massa_protocol_exports::protocol_controller: protocol controller stopped
Feb 08 18:28:48 ubuntu-8gb-hel1-2-massa massa-node[9438]: 2023-02-08T18:28:48.088511Z  INFO massa_consensus_worker::manager: stopping consensus worker...
Feb 08 18:28:48 ubuntu-8gb-hel1-2-massa massa-node[9438]: 2023-02-08T18:28:48.174744Z  INFO massa_consensus_worker::manager: consensus worker stopped
Feb 08 18:28:48 ubuntu-8gb-hel1-2-massa massa-node[9438]: 2023-02-08T18:28:48.174791Z  INFO massa_pool_worker::controller_impl: stopping pool workers...
Feb 08 18:28:48 ubuntu-8gb-hel1-2-massa massa-node[9438]: 2023-02-08T18:28:48.203378Z  INFO massa_pool_worker::controller_impl: pool workers stopped
Feb 08 18:28:48 ubuntu-8gb-hel1-2-massa massa-node[9438]: 2023-02-08T18:28:48.203415Z  INFO massa_execution_worker::controller: stopping Execution controller...

**Comment by AurelienFT** [comment]
Hello, 
Thanks for your report
The issue to put the logs is the #3512. I'm referencing your logs there.
