### ISSUE TITLE
Sending the logs as you asked in discord

### ISSUE THREAD

**Issue by narko2t** [massalabs/massa#3533]
-- Logs begin at Fri 2023-02-03 18:03:04 CET. --
Feb 08 19:36:31 AX41-narkosha massa-node[3502651]: 2023-02-08T18:36:31.000611Z  WARN massa_consensus_worker::state::stats: desynchronization detected because the recent final block history is empty or contains only blocks produced by this node
Feb 08 19:36:31 AX41-narkosha massa-node[3502651]: 2023-02-08T18:36:31.500724Z  WARN massa_consensus_worker::state::stats: desynchronization detected because the recent final block history is empty or contains only blocks produced by this node
Feb 08 19:36:32 AX41-narkosha massa-node[3502651]: 2023-02-08T18:36:32.000833Z  WARN massa_consensus_worker::state::stats: desynchronization detected because the recent final block history is empty or contains only blocks produced by this node
Feb 08 19:36:32 AX41-narkosha massa-node[3502651]: 2023-02-08T18:36:32.500947Z  WARN massa_consensus_worker::state::stats: desynchronization detected because the recent final block history is empty or contains only blocks produced by this node
Feb 08 19:36:33 AX41-narkosha massa-node[3502651]: 2023-02-08T18:36:33.001068Z  WARN massa_consensus_worker::state::stats: desynchronization detected because the recent final block history is empty or contains only blocks produced by this node
Feb 08 19:36:33 AX41-narkosha massa-node[3502651]: 2023-02-08T18:36:33.500194Z  WARN massa_consensus_worker::state::stats: desynchronization detected because the recent final block history is empty or contains only blocks produced by this node
Feb 08 19:36:34 AX41-narkosha massa-node[3502651]: 2023-02-08T18:36:34.000621Z  WARN massa_consensus_worker::state::stats: desynchronization detected because the recent final block history is empty or contains only blocks produced by this node
Feb 08 19:36:34 AX41-narkosha massa-node[3502651]: 2023-02-08T18:36:34.500728Z  WARN massa_consensus_worker::state::stats: desynchronization detected because the recent final block history is empty or contains only blocks produced by this node
Feb 08 19:36:35 AX41-narkosha massa-node[3502651]: 2023-02-08T18:36:35.000841Z  WARN massa_consensus_worker::state::stats: desynchronization detected because the recent final block history is empty or contains only blocks produced by this node
Feb 08 19:36:35 AX41-narkosha massa-node[3502651]: 2023-02-08T18:36:35.500951Z  WARN massa_consensus_worker::state::stats: desynchronization detected because the recent final block history is empty or contains only blocks produced by this node
Feb 08 19:36:36 AX41-narkosha massa-node[3502651]: 2023-02-08T18:36:36.001089Z  WARN massa_consensus_worker::state::stats: desynchronization detected because the recent final block history is empty or contains only blocks produced by this node
Feb 08 19:36:36 AX41-narkosha massa-node[3502651]: 2023-02-08T18:36:36.500224Z  WARN massa_consensus_worker::state::stats: desynchronization detected because the recent final block history is empty or contains only blocks produced by this node
Feb 08 19:36:37 AX41-narkosha massa-node[3502651]: 2023-02-08T18:36:37.000360Z  WARN massa_consensus_worker::state::stats: desynchronization detected because the recent final block history is empty or contains only blocks produced by this node
Feb 08 19:36:37 AX41-narkosha massa-node[3502651]: 2023-02-08T18:36:37.500474Z  WARN massa_consensus_worker::state::stats: desynchronization detected because the recent final block history is empty or contains only blocks produced by this node
Feb 08 19:36:38 AX41-narkosha massa-node[3502651]: 2023-02-08T18:36:38.000595Z  WARN massa_consensus_worker::state::stats: desynchronization detected because the recent final block history is empty or contains only blocks produced by this node
Feb 08 19:36:38 AX41-narkosha massa-node[3502651]: 2023-02-08T18:36:38.500747Z  WARN massa_consensus_worker::state::stats: desynchronization detected because the recent final block history is empty or contains only blocks produced by this node
Feb 08 19:36:39 AX41-narkosha massa-node[3502651]: 2023-02-08T18:36:39.000878Z  WARN massa_consensus_worker::state::stats: desynchronization detected because the recent final block history is empty or contains only blocks produced by this node
Feb 08 19:36:39 AX41-narkosha massa-node[3502651]: 2023-02-08T18:36:39.500433Z  WARN massa_consensus_worker::state::stats: desynchronization detected because the recent final block history is empty or contains only blocks produced by this node
Feb 08 19:36:40 AX41-narkosha massa-node[3502651]: 2023-02-08T18:36:40.000556Z  WARN massa_consensus_worker::state::stats: desynchronization detected because the recent final block history is empty or contains only blocks produced by this node
Feb 08 19:36:40 AX41-narkosha massa-node[3502651]: 2023-02-08T18:36:40.500686Z  WARN massa_consensus_worker::state::stats: desynchronization detected because the recent final block history is empty or contains only blocks produced by this node
Feb 08 19:36:41 AX41-narkosha massa-node[3502651]: 2023-02-08T18:36:41.000812Z  WARN massa_consensus_worker::state::stats: desynchronization detected because the recent final block history is empty or contains only blocks produced by this node
Feb 08 19:36:41 AX41-narkosha massa-node[3502651]: 2023-02-08T18:36:41.500929Z  WARN massa_consensus_worker::state::stats: desynchronization detected because the recent final block history is empty or contains only blocks produced by this node
Feb 08 19:36:42 AX41-narkosha massa-node[3502651]: 2023-02-08T18:36:42.001051Z  WARN massa_consensus_worker::state::stats: desynchronization detected because the recent final block history is empty or contains only blocks produced by this node
Feb 08 19:36:42 AX41-narkosha massa-node[3502651]: 2023-02-08T18:36:42.500174Z  WARN massa_consensus_worker::state::stats: desynchronization detected because the recent final block history is empty or contains only blocks produced by this node
Feb 08 19:36:43 AX41-narkosha massa-node[3502651]: 2023-02-08T18:36:43.000296Z  WARN massa_consensus_worker::state::stats: desynchronization detected because the recent final block history is empty or contains only blocks produced by this node
Feb 08 19:36:43 AX41-narkosha massa-node[3502651]: 2023-02-08T18:36:43.500421Z  WARN massa_consensus_worker::state::stats: desynchronization detected because the recent final block history is empty or contains only blocks produced by this node

**Comment by AurelienFT** [comment]
Hello, 
Thanks for your report
The issue to put the logs is the #3512. I'm referencing your logs there.
