### ISSUE TITLE
As you asked, I am sending you the logs. Before the errors started:

### ISSUE THREAD

**Issue by narko2t** [massalabs/massa#3534]
Feb 08 19:28:46 AX41-narkosha massa-node[3502651]: 2023-02-08T18:28:46.906631Z  INFO massa_protocol_worker::protocol_network: Connection closed with N12AY72Q8o2EueNbaQG7ERTHczBSEsuUBvb2f23tBZ9Fyes97HeQ
Feb 08 19:28:46 AX41-narkosha massa-node[3502651]: 2023-02-08T18:28:46.931747Z  INFO massa_protocol_worker::protocol_network: Connected to node N1fYwJHTaHTVaQtaLriqhVnGEyHkSkCaDvAMbXbp5R4LTSyq2Ya
Feb 08 19:28:47 AX41-narkosha massa-node[3502651]: 2023-02-08T18:28:47.000744Z  WARN massa_factory_worker::block_factory: block factory could not get selector draws for slot (period: 33407, thread: 30): `CycleUnavailable`: PoS cycle 260 is needed but is absent from cache
Feb 08 19:28:47 AX41-narkosha massa-node[3502651]: 2023-02-08T18:28:47.001028Z  WARN massa_factory_worker::endorsement_factory: endorsement factory could not get selector draws for slot (period: 33408, thread: 14): `CycleUnavailable`: PoS cycle 261 is needed but is absent from cache
Feb 08 19:28:47 AX41-narkosha massa-node[3502651]: 2023-02-08T18:28:47.005453Z  INFO massa_protocol_worker::protocol_network: Connected to node N12AY72Q8o2EueNbaQG7ERTHczBSEsuUBvb2f23tBZ9Fyes97HeQ
Feb 08 19:28:47 AX41-narkosha massa-node[3502651]: 2023-02-08T18:28:47.013272Z  INFO massa_protocol_worker::protocol_network: Connection closed with N1fYwJHTaHTVaQtaLriqhVnGEyHkSkCaDvAMbXbp5R4LTSyq2Ya
Feb 08 19:28:47 AX41-narkosha massa-node[3502651]: 2023-02-08T18:28:47.036668Z  INFO massa_protocol_worker::protocol_network: Connection closed with N12AY72Q8o2EueNbaQG7ERTHczBSEsuUBvb2f23tBZ9Fyes97HeQ
Feb 08 19:28:47 AX41-narkosha massa-node[3502651]: 2023-02-08T18:28:47.138741Z  INFO massa_protocol_worker::protocol_network: Connected to node N12AY72Q8o2EueNbaQG7ERTHczBSEsuUBvb2f23tBZ9Fyes97HeQ
Feb 08 19:28:47 AX41-narkosha massa-node[3502651]: 2023-02-08T18:28:47.155795Z  INFO massa_protocol_worker::protocol_network: Connection closed with N12AY72Q8o2EueNbaQG7ERTHczBSEsuUBvb2f23tBZ9Fyes97HeQ
Feb 08 19:28:47 AX41-narkosha massa-node[3502651]: 2023-02-08T18:28:47.241641Z  INFO massa_protocol_worker::protocol_network: Connected to node N1fYwJHTaHTVaQtaLriqhVnGEyHkSkCaDvAMbXbp5R4LTSyq2Ya
Feb 08 19:28:47 AX41-narkosha massa-node[3502651]: 2023-02-08T18:28:47.242094Z  INFO massa_protocol_worker::protocol_network: Connected to node N12AY72Q8o2EueNbaQG7ERTHczBSEsuUBvb2f23tBZ9Fyes97HeQ

**Comment by AurelienFT** [comment]
Hello, 
Thanks for your report
The issue to put the logs is the #3512. I'm referencing your logs there.
