### ISSUE TITLE
logs

### ISSUE THREAD

**Issue by bwoogmy** [massalabs/massa#3535]
Feb 08 18:37:18 vps-5f59a650 massa-node[344756]: 2023-02-08T18:37:18.500479Z  WARN massa_consensus_worker::state::stats: desynchronization detected because the recent final block history is empty or contains only blocks produced by this node
Feb 08 18:37:19 vps-5f59a650 massa-node[344756]: 2023-02-08T18:37:19.000670Z  WARN massa_consensus_worker::state::stats: desynchronization detected because the recent final block history is empty or contains only blocks produced by this node
Feb 08 18:37:19 vps-5f59a650 massa-node[344756]: 2023-02-08T18:37:19.500860Z  WARN massa_consensus_worker::state::stats: desynchronization detected because the recent final block history is empty or contains only blocks produced by this node
Feb 08 18:37:20 vps-5f59a650 massa-node[344756]: 2023-02-08T18:37:20.001077Z  WARN massa_consensus_worker::state::stats: desynchronization detected because the recent final block history is empty or contains only blocks produced by this node
Feb 08 18:37:20 vps-5f59a650 massa-node[344756]: 2023-02-08T18:37:20.500288Z  WARN massa_consensus_worker::state::stats: desynchronization detected because the recent final block history is empty or contains only blocks produced by this node
Feb 08 18:37:21 vps-5f59a650 massa-node[344756]: 2023-02-08T18:37:21.000500Z  WARN massa_consensus_worker::state::stats: desynchronization detected because the recent final block history is empty or contains only blocks produced by this node

**Comment by AurelienFT** [comment]
Hello, 
Thanks for your report
The issue to put the logs is the #3512. I'm referencing your logs there.
