### ISSUE TITLE
09-Feb Bug issue (Log.txt share)

### ISSUE THREAD

**Issue by olddragon78** [massalabs/massa#3537]
I share today bug issue as picture and log file 

[Uploading logs.txt…]()

![Screenshot001](https://user-images.githubusercontent.com/116439346/217689712-8d4c47ff-bd1b-4a1c-8544-b5ade2e4dba1.jpg)

**Comment by AurelienFT** [comment]
Hello, 
Thanks for your report
The issue to put the logs is the #3512. I'm referencing your logs there.
