### ISSUE TITLE
Кир#4662

### ISSUE THREAD

**Issue by Astranaar314** [massalabs/massa#3538]
Feb 08 18:35:20 ubuntu-8gb-hel1-1 massa-node[3536152]: 2023-02-08T18:35:20.000687Z  WARN massa_consensus_worker::state::stats: desynchronization detected because the recent final block history is empty or contains only blocks produced by this node
Feb 08 18:35:20 ubuntu-8gb-hel1-1 massa-node[3536152]: 2023-02-08T18:35:20.500957Z  WARN massa_consensus_worker::state::stats: desynchronization detected because the recent final block history is empty or contains only blocks produced by this node
Feb 08 18:35:21 ubuntu-8gb-hel1-1 massa-node[3536152]: 2023-02-08T18:35:21.000215Z  WARN massa_consensus_worker::state::stats: desynchronization detected because the recent final block history is empty or contains only blocks produced by this node
Feb 08 18:35:21 ubuntu-8gb-hel1-1 massa-node[3536152]: 2023-02-08T18:35:21.500468Z  WARN massa_consensus_worker::state::stats: desynchronization detected because the recent final block history is empty or contains only blocks produced by this node

**Comment by AurelienFT** [comment]
Hello, 
Thanks for your report
The issue to put the logs is the #3512. I'm referencing your logs there.
