### ISSUE TITLE
massa_factory_worker::manager: factory stopped

### ISSUE THREAD

**Issue by chriscooper1983** [massalabs/massa#3540]
root@massa:~# systemctl status massad.service 
* massad.service - Massa Node
     Loaded: loaded (/etc/systemd/system/massad.service; enabled; vendor preset>
     Active: active (running) since Wed 2023-02-08 00:50:45 UTC; 1 day 6h ago
   Main PID: 241819 (massa-node)
      Tasks: 22 (limit: 77001)
     Memory: 2.8G
        CPU: 4h 20min 5.569s
     CGroup: /system.slice/massad.service
             `-241819 /root/massa/target/release/massa-node -p 123

Feb 08 18:28:48 massa massa-node[241819]: 2023-02-08T18:28:48.050942Z  INFO mas>
Feb 08 18:28:48 massa massa-node[241819]: 2023-02-08T18:28:48.051026Z  INFO mas>
Feb 08 18:28:48 massa massa-node[241819]: 2023-02-08T18:28:48.097184Z  INFO mas>
Feb 08 18:28:48 massa massa-node[241819]: 2023-02-08T18:28:48.097242Z  INFO mas>
Feb 08 18:28:48 massa massa-node[241819]: 2023-02-08T18:28:48.097264Z  INFO mas>
Feb 08 18:28:48 massa massa-node[241819]: 2023-02-08T18:28:48.500235Z  WARN mas>
Feb 08 18:28:49 massa massa-node[241819]: 2023-02-08T18:28:49.007931Z  INFO mas>
Feb 08 18:28:49 massa massa-node[241819]: 2023-02-08T18:28:49.007960Z  INFO mas>
Feb 08 18:28:49 massa massa-node[241819]: 2023-02-08T18:28:49.090121Z  INFO mas>
Feb 08 18:28:49 massa massa-node[241819]: 2023-02-08T18:28:49.090157Z  INFO mas>
lines 1-20/20 (END)...skipping...
* massad.service - Massa Node
     Loaded: loaded (/etc/systemd/system/massad.service; enabled; vendor preset: enabled)
     Active: active (running) since Wed 2023-02-08 00:50:45 UTC; 1 day 6h ago
   Main PID: 241819 (massa-node)
      Tasks: 22 (limit: 77001)
     Memory: 2.8G
        CPU: 4h 20min 5.569s
     CGroup: /system.slice/massad.service
             `-241819 /root/massa/target/release/massa-node -p 123

Feb 08 18:28:48 massa massa-node[241819]: 2023-02-08T18:28:48.050942Z  INFO massa_factory_worker::manager: factory stopped
Feb 08 18:28:48 massa massa-node[241819]: 2023-02-08T18:28:48.051026Z  INFO massa_protocol_exports::protocol_controller: stopping protocol controller...
Feb 08 18:28:48 massa massa-node[241819]: 2023-02-08T18:28:48.097184Z  INFO massa_protocol_worker::protocol_worker: protocol worker finished cleanly
Feb 08 18:28:48 massa massa-node[241819]: 2023-02-08T18:28:48.097242Z  INFO massa_protocol_exports::protocol_controller: protocol controller stopped
Feb 08 18:28:48 massa massa-node[241819]: 2023-02-08T18:28:48.097264Z  INFO massa_consensus_worker::manager: stopping consensus worker...
Feb 08 18:28:48 massa massa-node[241819]: 2023-02-08T18:28:48.500235Z  WARN massa_consensus_worker::state::stats: desynchronization detected because the recent final block history is empty or contains only blocks produced by this node
Feb 08 18:28:49 massa massa-node[241819]: 2023-02-08T18:28:49.007931Z  INFO massa_consensus_worker::manager: consensus worker stopped
Feb 08 18:28:49 massa massa-node[241819]: 2023-02-08T18:28:49.007960Z  INFO massa_pool_worker::controller_impl: stopping pool workers...
Feb 08 18:28:49 massa massa-node[241819]: 2023-02-08T18:28:49.090121Z  INFO massa_pool_worker::controller_impl: pool workers stopped
Feb 08 18:28:49 massa massa-node[241819]: 2023-02-08T18:28:49.090157Z  INFO massa_execution_worker::controller: stopping Execution controller...

**Comment by AurelienFT** [comment]
Hello,
Thanks for your report. Sadly there is nothing on your logs that seems strange to us.
