### ISSUE TITLE
WARN massa

### ISSUE THREAD

**Issue by VladyslavD** [massalabs/massa#3541]
Feb 08 18:36:31 vlad massa-node[18794]: 2023-02-08T18:36:31.500962Z  WARN massa_consensus_worker::state::stats: desynchronization detected because the recent final block history is empty or contains only blocks produced by this node

**Comment by aoudiamoncef** [comment]
Hello, 
Thanks for your report
The issue to put the logs is the #3512. I'm referencing your logs there.

**Comment by DzmitryWaves** [comment]
Feb 08 19:37:20 vmi1096229.contaboserver.net massa-node[3391364]: 2023-02-08T18:37:20.500276Z  WARN massa_consensus_worker::state::stats: desynchronization detected because the recent final block history is empty or contains only blocks produced by this node

**Comment by DzmitryWaves** [comment]
[](https://wdfiles.ru/b373387)

**Comment by DzmitryWaves** [comment]
https://wdfiles.ru/b373387
