### ISSUE TITLE
Logs: 135.181.99.35

### ISSUE THREAD

**Issue by OlehKrepyshe** [massalabs/massa#3544]
root@Serv-4:~# massa_log
-- Logs begin at Sat 2023-02-04 00:55:50 CET. --
Feb 08 19:36:31 Serv-4 massa-node[582]: 2023-02-08T18:36:31.000742Z  WARN massa_consensus_worker::state::stats: desynchronization detected because the recent final block history is empty or contains only blocks produced by this node
Feb 08 19:36:31 Serv-4 massa-node[582]: 2023-02-08T18:36:31.500963Z  WARN massa_consensus_worker::state::stats: desynchronization detected because the recent final block history is empty or contains only blocks produced by this node
Feb 08 19:36:32 Serv-4 massa-node[582]: 2023-02-08T18:36:32.000215Z  WARN massa_consensus_worker::state::stats: desynchronization detected because the recent final block history is empty or contains only blocks produced by this node
Feb 08 19:36:32 Serv-4 massa-node[582]: 2023-02-08T18:36:32.501105Z  WARN massa_consensus_worker::state::stats: desynchronization detected because the recent final block history is empty or contains only blocks produced by this node
Feb 08 19:36:33 Serv-4 massa-node[582]: 2023-02-08T18:36:33.000346Z  WARN massa_consensus_worker::state::stats: desynchronization detected because the recent final block history is empty or contains only blocks produced by this node
Feb 08 19:36:33 Serv-4 massa-node[582]: 2023-02-08T18:36:33.500537Z  WARN massa_consensus_worker::state::stats: desynchronization detected because the recent final block history is empty or contains only blocks produced by this node
Feb 08 19:36:34 Serv-4 massa-node[582]: 2023-02-08T18:36:34.000760Z  WARN massa_consensus_worker::state::stats: desynchronization detected because the recent final block history is empty or contains only blocks produced by this node
Feb 08 19:36:34 Serv-4 massa-node[582]: 2023-02-08T18:36:34.501004Z  WARN massa_consensus_worker::state::stats: desynchronization detected because the recent final block history is empty or contains only blocks produced by this node
Feb 08 19:36:35 Serv-4 massa-node[582]: 2023-02-08T18:36:35.000210Z  WARN massa_consensus_worker::state::stats: desynchronization detected because the recent final block history is empty or contains only blocks produced by this node
Feb 08 19:36:35 Serv-4 massa-node[582]: 2023-02-08T18:36:35.500445Z  WARN massa_consensus_worker::state::stats: desynchronization detected because the recent final block history is empty or contains only blocks produced by this node
Feb 08 19:36:36 Serv-4 massa-node[582]: 2023-02-08T18:36:36.000767Z  WARN massa_consensus_worker::state::stats: desynchronization detected because the recent final block history is empty or contains only blocks produced by this node
Feb 08 19:36:36 Serv-4 massa-node[582]: 2023-02-08T18:36:36.500980Z  WARN massa_consensus_worker::state::stats: desynchronization detected because the recent final block history is empty or contains only blocks produced by this node
Feb 08 19:36:37 Serv-4 massa-node[582]: 2023-02-08T18:36:37.000165Z  WARN massa_consensus_worker::state::stats: desynchronization detected because the recent final block history is empty or contains only blocks produced by this node
Feb 08 19:36:37 Serv-4 massa-node[582]: 2023-02-08T18:36:37.500363Z  WARN massa_consensus_worker::state::stats: desynchronization detected because the recent final block history is empty or contains only blocks produced by this node
Feb 08 19:36:38 Serv-4 massa-node[582]: 2023-02-08T18:36:38.001008Z  WARN massa_consensus_worker::state::stats: desynchronization detected because the recent final block history is empty or contains only blocks produced by this node
Feb 08 19:36:38 Serv-4 massa-node[582]: 2023-02-08T18:36:38.500236Z  WARN massa_consensus_worker::state::stats: desynchronization detected because the recent final block history is empty or contains only blocks produced by this node
Feb 08 19:36:39 Serv-4 massa-node[582]: 2023-02-08T18:36:39.000488Z  WARN massa_consensus_worker::state::stats: desynchronization detected because the recent final block history is empty or contains only blocks produced by this node
Feb 08 19:36:39 Serv-4 massa-node[582]: 2023-02-08T18:36:39.500757Z  WARN massa_consensus_worker::state::stats: desynchronization detected because the recent final block history is empty or contains only blocks produced by this node
Feb 08 19:36:40 Serv-4 massa-node[582]: 2023-02-08T18:36:40.001099Z  WARN massa_consensus_worker::state::stats: desynchronization detected because the recent final block history is empty or contains only blocks produced by this node
Feb 08 19:36:40 Serv-4 massa-node[582]: 2023-02-08T18:36:40.500279Z  WARN massa_consensus_worker::state::stats: desynchronization detected because the recent final block history is empty or contains only blocks produced by this node
Feb 08 19:36:41 Serv-4 massa-node[582]: 2023-02-08T18:36:41.000523Z  WARN massa_consensus_worker::state::stats: desynchronization detected because the recent final block history is empty or contains only blocks produced by this node
Feb 08 19:36:41 Serv-4 massa-node[582]: 2023-02-08T18:36:41.500740Z  WARN massa_consensus_worker::state::stats: desynchronization detected because the recent final block history is empty or contains only blocks produced by this node
Feb 08 19:36:42 Serv-4 massa-node[582]: 2023-02-08T18:36:42.001078Z  WARN massa_consensus_worker::state::stats: desynchronization detected because the recent final block history is empty or contains only blocks produced by this node
Feb 08 19:36:42 Serv-4 massa-node[582]: 2023-02-08T18:36:42.500263Z  WARN massa_consensus_worker::state::stats: desynchronization detected because the recent final block history is empty or contains only blocks produced by this node
Feb 08 19:36:43 Serv-4 massa-node[582]: 2023-02-08T18:36:43.000946Z  WARN massa_consensus_worker::state::stats: desynchronization detected because the recent final block history is empty or contains only blocks produced by this node
Feb 08 19:36:43 Serv-4 massa-node[582]: 2023-02-08T18:36:43.500860Z  WARN massa_consensus_worker::state::stats: desynchronization detected because the recent final block history is empty or contains only blocks produced by this node
Feb 08 19:36:44 Serv-4 massa-node[582]: 2023-02-08T18:36:44.001076Z  WARN massa_consensus_worker::state::stats: desynchronization detected because the recent final block history is empty or contains only blocks produced by this node
Feb 08 19:36:44 Serv-4 massa-node[582]: 2023-02-08T18:36:44.500328Z  WARN massa_consensus_worker::state::stats: desynchronization detected because the recent final block history is empty or contains only blocks produced by this node
Feb 08 19:36:45 Serv-4 massa-node[582]: 2023-02-08T18:36:45.000670Z  WARN massa_consensus_worker::state::stats: desynchronization detected because the recent final block history is empty or contains only blocks produced by this node
Feb 08 19:36:45 Serv-4 massa-node[582]: 2023-02-08T18:36:45.501097Z  WARN massa_consensus_worker::state::stats: desynchronization detected because the recent final block history is empty or contains only blocks produced by this node
Feb 08 19:36:46 Serv-4 massa-node[582]: 2023-02-08T18:36:46.000328Z  WARN massa_consensus_worker::state::stats: desynchronization detected because the recent final block history is empty or contains only blocks produced by this node
Feb 08 19:36:46 Serv-4 massa-node[582]: 2023-02-08T18:36:46.500576Z  WARN massa_consensus_worker::state::stats: desynchronization detected because the recent final block history is empty or contains only blocks produced by this node
Feb 08 19:36:47 Serv-4 massa-node[582]: 2023-02-08T18:36:47.000819Z  WARN massa_consensus_worker::state::stats: desynchronization detected because the recent final block history is empty or contains only blocks produced by this node
Feb 08 19:36:47 Serv-4 massa-node[582]: 2023-02-08T18:36:47.501097Z  WARN massa_consensus_worker::state::stats: desynchronization detected because the recent final block history is empty or contains only blocks produced by this node
Feb 08 19:36:48 Serv-4 massa-node[582]: 2023-02-08T18:36:48.000322Z  WARN massa_consensus_worker::state::stats: desynchronization detected because the recent final block history is empty or contains only blocks produced by this node
Feb 08 19:36:48 Serv-4 massa-node[582]: 2023-02-08T18:36:48.500552Z  WARN massa_consensus_worker::state::stats: desynchronization detected because the recent final block history is empty or contains only blocks produced by this node
Feb 08 19:36:49 Serv-4 massa-node[582]: 2023-02-08T18:36:49.000498Z  WARN massa_consensus_worker::state::stats: desynchronization detected because the recent final block history is empty or contains only blocks produced by this node
Feb 08 19:36:49 Serv-4 massa-node[582]: 2023-02-08T18:36:49.500733Z  WARN massa_consensus_worker::state::stats: desynchronization detected because the recent final block history is empty or contains only blocks produced by this node
Feb 08 19:36:50 Serv-4 massa-node[582]: 2023-02-08T18:36:50.001021Z  WARN massa_consensus_worker::state::stats: desynchronization detected because the recent final block history is empty or contains only blocks produced by this node
Feb 08 19:36:50 Serv-4 massa-node[582]: 2023-02-08T18:36:50.500218Z  WARN massa_consensus_worker::state::stats: desynchronization detected because the recent final block history is empty or contains only blocks produced by this node
Feb 08 19:36:51 Serv-4 massa-node[582]: 2023-02-08T18:36:51.000439Z  WARN massa_consensus_worker::state::stats: desynchronization detected because the recent final block history is empty or contains only blocks produced by this node
Feb 08 19:36:51 Serv-4 massa-node[582]: 2023-02-08T18:36:51.500717Z  WARN massa_consensus_worker::state::stats: desynchronization detected because the recent final block history is empty or contains only blocks produced by this node
Feb 08 19:36:52 Serv-4 massa-node[582]: 2023-02-08T18:36:52.000992Z  WARN massa_consensus_worker::state::stats: desynchronization detected because the recent final block history is empty or contains only blocks produced by this node
Feb 08 19:36:52 Serv-4 massa-node[582]: 2023-02-08T18:36:52.500263Z  WARN massa_consensus_worker::state::stats: desynchronization detected because the recent final block history is empty or contains only blocks produced by this node
Feb 08 19:36:53 Serv-4 massa-node[582]: 2023-02-08T18:36:53.000500Z  WARN massa_consensus_worker::state::stats: desynchronization detected because the recent final block history is empty or contains only blocks produced by this node
Feb 08 19:36:53 Serv-4 massa-node[582]: 2023-02-08T18:36:53.500734Z  WARN massa_consensus_worker::state::stats: desynchronization detected because the recent final block history is empty or contains only blocks produced by this node
Feb 08 19:36:54 Serv-4 massa-node[582]: 2023-02-08T18:36:54.001001Z  WARN massa_consensus_worker::state::stats: desynchronization detected because the recent final block history is empty or contains only blocks produced by this node
Feb 08 19:36:54 Serv-4 massa-node[582]: 2023-02-08T18:36:54.501109Z  WARN massa_consensus_worker::state::stats: desynchronization detected because the recent final block history is empty or contains only blocks produced by this node
Feb 08 19:36:55 Serv-4 massa-node[582]: 2023-02-08T18:36:55.000325Z  WARN massa_consensus_worker::state::stats: desynchronization detected because the recent final block history is empty or contains only blocks produced by this node
Feb 08 19:36:55 Serv-4 massa-node[582]: 2023-02-08T18:36:55.500537Z  WARN massa_consensus_worker::state::stats: desynchronization detected because the recent final block history is empty or contains only blocks produced by this node
Feb 08 19:36:56 Serv-4 massa-node[582]: 2023-02-08T18:36:56.000756Z  WARN massa_consensus_worker::state::stats: desynchronization detected because the recent final block history is empty or contains only blocks produced by this node
Feb 08 19:36:56 Serv-4 massa-node[582]: 2023-02-08T18:36:56.500991Z  WARN massa_consensus_worker::state::stats: desynchronization detected because the recent final block history is empty or contains only blocks produced by this node
Feb 08 19:36:57 Serv-4 massa-node[582]: 2023-02-08T18:36:57.007991Z  WARN massa_consensus_worker::state::stats: desynchronization detected because the recent final block history is empty or contains only blocks produced by this node
Feb 08 19:36:57 Serv-4 massa-node[582]: 2023-02-08T18:36:57.500184Z  WARN massa_consensus_worker::state::stats: desynchronization detected because the recent final block history is empty or contains only blocks produced by this node
Feb 08 19:36:58 Serv-4 massa-node[582]: 2023-02-08T18:36:58.000436Z  WARN massa_consensus_worker::state::stats: desynchronization detected because the recent final block history is empty or contains only blocks produced by this node
Feb 08 19:36:58 Serv-4 massa-node[582]: 2023-02-08T18:36:58.500761Z  WARN massa_consensus_worker::state::stats: desynchronization detected because the recent final block history is empty or contains only blocks produced by this node
Feb 08 19:36:59 Serv-4 massa-node[582]: 2023-02-08T18:36:59.000960Z  WARN massa_consensus_worker::state::stats: desynchronization detected because the recent final block history is empty or contains only blocks produced by this node
Feb 08 19:36:59 Serv-4 massa-node[582]: 2023-02-08T18:36:59.500210Z  WARN massa_consensus_worker::state::stats: desynchronization detected because the recent final block history is empty or contains only blocks produced by this node
Feb 08 19:37:00 Serv-4 massa-node[582]: 2023-02-08T18:37:00.000248Z  WARN massa_consensus_worker::state::stats: desynchronization detected because the recent final block history is empty or contains only blocks produced by this node
Feb 08 19:37:00 Serv-4 massa-node[582]: 2023-02-08T18:37:00.500491Z  WARN massa_consensus_worker::state::stats: desynchronization detected because the recent final block history is empty or contains only blocks produced by this node
Feb 08 19:37:01 Serv-4 massa-node[582]: 2023-02-08T18:37:01.000662Z  WARN massa_consensus_worker::state::stats: desynchronization detected because the recent final block history is empty or contains only blocks produced by this node
Feb 08 19:37:01 Serv-4 massa-node[582]: 2023-02-08T18:37:01.500880Z  WARN massa_consensus_worker::state::stats: desynchronization detected because the recent final block history is empty or contains only blocks produced by this node
Feb 08 19:37:02 Serv-4 massa-node[582]: 2023-02-08T18:37:02.001082Z  WARN massa_consensus_worker::state::stats: desynchronization detected because the recent final block history is empty or contains only blocks produced by this node
Feb 08 19:37:02 Serv-4 massa-node[582]: 2023-02-08T18:37:02.500343Z  WARN massa_consensus_worker::state::stats: desynchronization detected because the recent final block history is empty or contains only blocks produced by this node
Feb 08 19:37:03 Serv-4 massa-node[582]: 2023-02-08T18:37:03.000578Z  WARN massa_consensus_worker::state::stats: desynchronization detected because the recent final block history is empty or contains only blocks produced by this node
Feb 08 19:37:03 Serv-4 massa-node[582]: 2023-02-08T18:37:03.500857Z  WARN massa_consensus_worker::state::stats: desynchronization detected because the recent final block history is empty or contains only blocks produced by this node
Feb 08 19:37:04 Serv-4 massa-node[582]: 2023-02-08T18:37:04.001145Z  WARN massa_consensus_worker::state::stats: desynchronization detected because the recent final block history is empty or contains only blocks produced by this node
Feb 08 19:37:04 Serv-4 massa-node[582]: 2023-02-08T18:37:04.500359Z  WARN massa_consensus_worker::state::stats: desynchronization detected because the recent final block history is empty or contains only blocks produced by this node
Feb 08 19:37:05 Serv-4 massa-node[582]: 2023-02-08T18:37:05.000581Z  WARN massa_consensus_worker::state::stats: desynchronization detected because the recent final block history is empty or contains only blocks produced by this node
Feb 08 19:37:05 Serv-4 massa-node[582]: 2023-02-08T18:37:05.500365Z  WARN massa_consensus_worker::state::stats: desynchronization detected because the recent final block history is empty or contains only blocks produced by this node
Feb 08 19:37:06 Serv-4 massa-node[582]: 2023-02-08T18:37:06.000677Z  WARN massa_consensus_worker::state::stats: desynchronization detected because the recent final block history is empty or contains only blocks produced by this node
Feb 08 19:37:06 Serv-4 massa-node[582]: 2023-02-08T18:37:06.500927Z  WARN massa_consensus_worker::state::stats: desynchronization detected because the recent final block history is empty or contains only blocks produced by this node
Feb 08 19:37:07 Serv-4 massa-node[582]: 2023-02-08T18:37:07.000217Z  WARN massa_consensus_worker::state::stats: desynchronization detected because the recent final block history is empty or contains only blocks produced by this node
Feb 08 19:37:07 Serv-4 massa-node[582]: 2023-02-08T18:37:07.500443Z  WARN massa_consensus_worker::state::stats: desynchronization detected because the recent final block history is empty or contains only blocks produced by this node
Feb 08 19:37:08 Serv-4 massa-node[582]: 2023-02-08T18:37:08.000687Z  WARN massa_consensus_worker::state::stats: desynchronization detected because the recent final block history is empty or contains only blocks produced by this node
Feb 08 19:37:08 Serv-4 massa-node[582]: 2023-02-08T18:37:08.500930Z  WARN massa_consensus_worker::state::stats: desynchronization detected because the recent final block history is empty or contains only blocks produced by this node
Feb 08 19:37:09 Serv-4 massa-node[582]: 2023-02-08T18:37:09.000166Z  WARN massa_consensus_worker::state::stats: desynchronization detected because the recent final block history is empty or contains only blocks produced by this node
Feb 08 19:37:09 Serv-4 massa-node[582]: 2023-02-08T18:37:09.500386Z  WARN massa_consensus_worker::state::stats: desynchronization detected because the recent final block history is empty or contains only blocks produced by this node
Feb 08 19:37:10 Serv-4 massa-node[582]: 2023-02-08T18:37:10.000689Z  WARN massa_consensus_worker::state::stats: desynchronization detected because the recent final block history is empty or contains only blocks produced by this node
Feb 08 19:37:10 Serv-4 massa-node[582]: 2023-02-08T18:37:10.500960Z  WARN massa_consensus_worker::state::stats: desynchronization detected because the recent final block history is empty or contains only blocks produced by this node
Feb 08 19:37:11 Serv-4 massa-node[582]: 2023-02-08T18:37:11.001106Z  WARN massa_consensus_worker::state::stats: desynchronization detected because the recent final block history is empty or contains only blocks produced by this node
Feb 08 19:37:11 Serv-4 massa-node[582]: 2023-02-08T18:37:11.500365Z  WARN massa_consensus_worker::state::stats: desynchronization detected because the recent final block history is empty or contains only blocks produced by this node
Feb 08 19:37:12 Serv-4 massa-node[582]: 2023-02-08T18:37:12.000557Z  WARN massa_consensus_worker::state::stats: desynchronization detected because the recent final block history is empty or contains only blocks produced by this node
Feb 08 19:37:12 Serv-4 massa-node[582]: 2023-02-08T18:37:12.500862Z  WARN massa_consensus_worker::state::stats: desynchronization detected because the recent final block history is empty or contains only blocks produced by this node
Feb 08 19:37:13 Serv-4 massa-node[582]: 2023-02-08T18:37:13.000255Z  WARN massa_consensus_worker::state::stats: desynchronization detected because the recent final block history is empty or contains only blocks produced by this node
Feb 08 19:37:13 Serv-4 massa-node[582]: 2023-02-08T18:37:13.500647Z  WARN massa_consensus_worker::state::stats: desynchronization detected because the recent final block history is empty or contains only blocks produced by this node
Feb 08 19:37:14 Serv-4 massa-node[582]: 2023-02-08T18:37:14.000931Z  WARN massa_consensus_worker::state::stats: desynchronization detected because the recent final block history is empty or contains only blocks produced by this node
Feb 08 19:37:14 Serv-4 massa-node[582]: 2023-02-08T18:37:14.500168Z  WARN massa_consensus_worker::state::stats: desynchronization detected because the recent final block history is empty or contains only blocks produced by this node
Feb 08 19:37:15 Serv-4 massa-node[582]: 2023-02-08T18:37:15.000425Z  WARN massa_consensus_worker::state::stats: desynchronization detected because the recent final block history is empty or contains only blocks produced by this node
Feb 08 19:37:15 Serv-4 massa-node[582]: 2023-02-08T18:37:15.500689Z  WARN massa_consensus_worker::state::stats: desynchronization detected because the recent final block history is empty or contains only blocks produced by this node
Feb 08 19:37:16 Serv-4 massa-node[582]: 2023-02-08T18:37:16.000943Z  WARN massa_consensus_worker::state::stats: desynchronization detected because the recent final block history is empty or contains only blocks produced by this node
Feb 08 19:37:16 Serv-4 massa-node[582]: 2023-02-08T18:37:16.500783Z  WARN massa_consensus_worker::state::stats: desynchronization detected because the recent final block history is empty or contains only blocks produced by this node
Feb 08 19:37:17 Serv-4 massa-node[582]: 2023-02-08T18:37:17.001025Z  WARN massa_consensus_worker::state::stats: desynchronization detected because the recent final block history is empty or contains only blocks produced by this node
Feb 08 19:37:17 Serv-4 massa-node[582]: 2023-02-08T18:37:17.500237Z  WARN massa_consensus_worker::state::stats: desynchronization detected because the recent final block history is empty or contains only blocks produced by this node
Feb 08 19:37:18 Serv-4 massa-node[582]: 2023-02-08T18:37:18.000479Z  WARN massa_consensus_worker::state::stats: desynchronization detected because the recent final block history is empty or contains only blocks produced by this node
Feb 08 19:37:18 Serv-4 massa-node[582]: 2023-02-08T18:37:18.500713Z  WARN massa_consensus_worker::state::stats: desynchronization detected because the recent final block history is empty or contains only blocks produced by this node
Feb 08 19:37:19 Serv-4 massa-node[582]: 2023-02-08T18:37:19.000924Z  WARN massa_consensus_worker::state::stats: desynchronization detected because the recent final block history is empty or contains only blocks produced by this node
Feb 08 19:37:19 Serv-4 massa-node[582]: 2023-02-08T18:37:19.501113Z  WARN massa_consensus_worker::state::stats: desynchronization detected because the recent final block history is empty or contains only blocks produced by this node
Feb 08 19:37:20 Serv-4 massa-node[582]: 2023-02-08T18:37:20.000319Z  WARN massa_consensus_worker::state::stats: desynchronization detected because the recent final block history is empty or contains only blocks produced by this node
Feb 08 19:37:20 Serv-4 massa-node[582]: 2023-02-08T18:37:20.500527Z  WARN massa_consensus_worker::state::stats: desynchronization detected because the recent final block history is empty or contains only blocks produced by this node

**Comment by aoudiamoncef** [comment]
Hello, 
Thanks for your report
The issue to put the logs is the #3512. I'm referencing your logs there.
