### ISSUE TITLE
node stop log.txt

### ISSUE THREAD

**Issue by softwarelandofficial** [massalabs/massa#3545]
node down
 
[logs.zip](https://github.com/massalabs/massa/files/10696167/logs.zip)

discord
Selcuk#8697

yesterday
Your current score for episode 19 is 8.26.

now
Your current score for episode 19 is 0.0.

**Comment by aoudiamoncef** [comment]
Hello, 
Thanks for your report
The issue to put the logs is the #3512. I'm referencing your logs there.
