### ISSUE TITLE
Massa logs: 194.146.13.18

### ISSUE THREAD

**Issue by PhilippPe3k** [massalabs/massa#3546]
root@vmi1050326:~# massa_log
-- Logs begin at Wed 2023-02-08 18:15:18 CET. --
Feb 08 19:45:03 vmi1050326.contaboserver.net massa-node[2881871]: 2023-02-08T18:45:03.501085Z  WARN massa_consensus_worker::state::stats: desynchronization detected because the recent final block history is empty or contains only blocks produced by this node
Feb 08 19:45:04 vmi1050326.contaboserver.net massa-node[2881871]: 2023-02-08T18:45:04.046325Z  WARN massa_consensus_worker::state::stats: desynchronization detected because the recent final block history is empty or contains only blocks produced by this node
Feb 08 19:45:04 vmi1050326.contaboserver.net massa-node[2881871]: 2023-02-08T18:45:04.552628Z  WARN massa_consensus_worker::state::stats: desynchronization detected because the recent final block history is empty or contains only blocks produced by this node
Feb 08 19:45:05 vmi1050326.contaboserver.net massa-node[2881871]: 2023-02-08T18:45:05.056765Z  WARN massa_consensus_worker::state::stats: desynchronization detected because the recent final block history is empty or contains only blocks produced by this node
Feb 08 19:45:05 vmi1050326.contaboserver.net massa-node[2881871]: 2023-02-08T18:45:05.501212Z  WARN massa_consensus_worker::state::stats: desynchronization detected because the recent final block history is empty or contains only blocks produced by this node
Feb 08 19:45:06 vmi1050326.contaboserver.net massa-node[2881871]: 2023-02-08T18:45:06.000517Z  WARN massa_consensus_worker::state::stats: desynchronization detected because the recent final block history is empty or contains only blocks produced by this node
Feb 08 19:45:06 vmi1050326.contaboserver.net massa-node[2881871]: 2023-02-08T18:45:06.500944Z  WARN massa_consensus_worker::state::stats: desynchronization detected because the recent final block history is empty or contains only blocks produced by this node
Feb 08 19:45:07 vmi1050326.contaboserver.net massa-node[2881871]: 2023-02-08T18:45:07.000346Z  WARN massa_consensus_worker::state::stats: desynchronization detected because the recent final block history is empty or contains only blocks produced by this node
Feb 08 19:45:07 vmi1050326.contaboserver.net massa-node[2881871]: 2023-02-08T18:45:07.500701Z  WARN massa_consensus_worker::state::stats: desynchronization detected because the recent final block history is empty or contains only blocks produced by this node
Feb 08 19:45:08 vmi1050326.contaboserver.net massa-node[2881871]: 2023-02-08T18:45:08.001072Z  WARN massa_consensus_worker::state::stats: desynchronization detected because the recent final block history is empty or contains only blocks produced by this node
Feb 08 19:45:08 vmi1050326.contaboserver.net massa-node[2881871]: 2023-02-08T18:45:08.500351Z  WARN massa_consensus_worker::state::stats: desynchronization detected because the recent final block history is empty or contains only blocks produced by this node
Feb 08 19:45:09 vmi1050326.contaboserver.net massa-node[2881871]: 2023-02-08T18:45:09.000603Z  WARN massa_consensus_worker::state::stats: desynchronization detected because the recent final block history is empty or contains only blocks produced by this node
Feb 08 19:45:09 vmi1050326.contaboserver.net massa-node[2881871]: 2023-02-08T18:45:09.500854Z  WARN massa_consensus_worker::state::stats: desynchronization detected because the recent final block history is empty or contains only blocks produced by this node
Feb 08 19:45:10 vmi1050326.contaboserver.net massa-node[2881871]: 2023-02-08T18:45:10.000141Z  WARN massa_consensus_worker::state::stats: desynchronization detected because the recent final block history is empty or contains only blocks produced by this node
Feb 08 19:45:10 vmi1050326.contaboserver.net massa-node[2881871]: 2023-02-08T18:45:10.505132Z  WARN massa_consensus_worker::state::stats: desynchronization detected because the recent final block history is empty or contains only blocks produced by this node
Feb 08 19:45:11 vmi1050326.contaboserver.net massa-node[2881871]: 2023-02-08T18:45:11.002543Z  WARN massa_consensus_worker::state::stats: desynchronization detected because the recent final block history is empty or contains only blocks produced by this node
Feb 08 19:45:11 vmi1050326.contaboserver.net massa-node[2881871]: 2023-02-08T18:45:11.506790Z  WARN massa_consensus_worker::state::stats: desynchronization detected because the recent final block history is empty or contains only blocks produced by this node
Feb 08 19:45:12 vmi1050326.contaboserver.net massa-node[2881871]: 2023-02-08T18:45:12.010855Z  WARN massa_consensus_worker::state::stats: desynchronization detected because the recent final block history is empty or contains only blocks produced by this node
Feb 08 19:45:12 vmi1050326.contaboserver.net massa-node[2881871]: 2023-02-08T18:45:12.514807Z  WARN massa_consensus_worker::state::stats: desynchronization detected because the recent final block history is empty or contains only blocks produced by this node
Feb 08 19:45:13 vmi1050326.contaboserver.net massa-node[2881871]: 2023-02-08T18:45:13.018728Z  WARN massa_consensus_worker::state::stats: desynchronization detected because the recent final block history is empty or contains only blocks produced by this node
Feb 08 19:45:13 vmi1050326.contaboserver.net massa-node[2881871]: 2023-02-08T18:45:13.522950Z  WARN massa_consensus_worker::state::stats: desynchronization detected because the recent final block history is empty or contains only blocks produced by this node
Feb 08 19:45:14 vmi1050326.contaboserver.net massa-node[2881871]: 2023-02-08T18:45:14.026664Z  WARN massa_consensus_worker::state::stats: desynchronization detected because the recent final block history is empty or contains only blocks produced by this node
Feb 08 19:45:14 vmi1050326.contaboserver.net massa-node[2881871]: 2023-02-08T18:45:14.502894Z  WARN massa_consensus_worker::state::stats: desynchronization detected because the recent final block history is empty or contains only blocks produced by this node
Feb 08 19:45:15 vmi1050326.contaboserver.net massa-node[2881871]: 2023-02-08T18:45:15.000623Z  WARN massa_consensus_worker::state::stats: desynchronization detected because the recent final block history is empty or contains only blocks produced by this node
Feb 08 19:45:15 vmi1050326.contaboserver.net massa-node[2881871]: 2023-02-08T18:45:15.538197Z  WARN massa_consensus_worker::state::stats: desynchronization detected because the recent final block history is empty or contains only blocks produced by this node
Feb 08 19:45:16 vmi1050326.contaboserver.net massa-node[2881871]: 2023-02-08T18:45:16.042222Z  WARN massa_consensus_worker::state::stats: desynchronization detected because the recent final block history is empty or contains only blocks produced by this node
Feb 08 19:45:16 vmi1050326.contaboserver.net massa-node[2881871]: 2023-02-08T18:45:16.546032Z  WARN massa_consensus_worker::state::stats: desynchronization detected because the recent final block history is empty or contains only blocks produced by this node
Feb 08 19:45:17 vmi1050326.contaboserver.net massa-node[2881871]: 2023-02-08T18:45:17.049993Z  WARN massa_consensus_worker::state::stats: desynchronization detected because the recent final block history is empty or contains only blocks produced by this node
Feb 08 19:45:17 vmi1050326.contaboserver.net massa-node[2881871]: 2023-02-08T18:45:17.554577Z  WARN massa_consensus_worker::state::stats: desynchronization detected because the recent final block history is empty or contains only blocks produced by this node
Feb 08 19:45:18 vmi1050326.contaboserver.net massa-node[2881871]: 2023-02-08T18:45:18.067166Z  WARN massa_consensus_worker::state::stats: desynchronization detected because the recent final block history is empty or contains only blocks produced by this node
Feb 08 19:45:18 vmi1050326.contaboserver.net massa-node[2881871]: 2023-02-08T18:45:18.500403Z  WARN massa_consensus_worker::state::stats: desynchronization detected because the recent final block history is empty or contains only blocks produced by this node
Feb 08 19:45:19 vmi1050326.contaboserver.net massa-node[2881871]: 2023-02-08T18:45:19.003085Z  WARN massa_consensus_worker::state::stats: desynchronization detected because the recent final block history is empty or contains only blocks produced by this node
Feb 08 19:45:19 vmi1050326.contaboserver.net massa-node[2881871]: 2023-02-08T18:45:19.500398Z  WARN massa_consensus_worker::state::stats: desynchronization detected because the recent final block history is empty or contains only blocks produced by this node
Feb 08 19:45:20 vmi1050326.contaboserver.net massa-node[2881871]: 2023-02-08T18:45:20.000660Z  WARN massa_consensus_worker::state::stats: desynchronization detected because the recent final block history is empty or contains only blocks produced by this node
Feb 08 19:45:20 vmi1050326.contaboserver.net massa-node[2881871]: 2023-02-08T18:45:20.500960Z  WARN massa_consensus_worker::state::stats: desynchronization detected because the recent final block history is empty or contains only blocks produced by this node
Feb 08 19:45:21 vmi1050326.contaboserver.net massa-node[2881871]: 2023-02-08T18:45:21.000179Z  WARN massa_consensus_worker::state::stats: desynchronization detected because the recent final block history is empty or contains only blocks produced by this node
Feb 08 19:45:21 vmi1050326.contaboserver.net massa-node[2881871]: 2023-02-08T18:45:21.500724Z  WARN massa_consensus_worker::state::stats: desynchronization detected because the recent final block history is empty or contains only blocks produced by this node
Feb 08 19:45:22 vmi1050326.contaboserver.net massa-node[2881871]: 2023-02-08T18:45:22.000582Z  WARN massa_consensus_worker::state::stats: desynchronization detected because the recent final block history is empty or contains only blocks produced by this node
Feb 08 19:45:22 vmi1050326.contaboserver.net massa-node[2881871]: 2023-02-08T18:45:22.501070Z  WARN massa_consensus_worker::state::stats: desynchronization detected because the recent final block history is empty or contains only blocks produced by this node
Feb 08 19:45:23 vmi1050326.contaboserver.net massa-node[2881871]: 2023-02-08T18:45:23.000323Z  WARN massa_consensus_worker::state::stats: desynchronization detected because the recent final block history is empty or contains only blocks produced by this node
Feb 08 19:45:23 vmi1050326.contaboserver.net massa-node[2881871]: 2023-02-08T18:45:23.509358Z  WARN massa_consensus_worker::state::stats: desynchronization detected because the recent final block history is empty or contains only blocks produced by this node
Feb 08 19:45:24 vmi1050326.contaboserver.net massa-node[2881871]: 2023-02-08T18:45:24.007719Z  WARN massa_consensus_worker::state::stats: desynchronization detected because the recent final block history is empty or contains only blocks produced by this node
Feb 08 19:45:24 vmi1050326.contaboserver.net massa-node[2881871]: 2023-02-08T18:45:24.510722Z  WARN massa_consensus_worker::state::stats: desynchronization detected because the recent final block history is empty or contains only blocks produced by this node
Feb 08 19:45:25 vmi1050326.contaboserver.net massa-node[2881871]: 2023-02-08T18:45:25.017287Z  WARN massa_consensus_worker::state::stats: desynchronization detected because the recent final block history is empty or contains only blocks produced by this node
Feb 08 19:45:25 vmi1050326.contaboserver.net massa-node[2881871]: 2023-02-08T18:45:25.520259Z  WARN massa_consensus_worker::state::stats: desynchronization detected because the recent final block history is empty or contains only blocks produced by this node
Feb 08 19:45:26 vmi1050326.contaboserver.net massa-node[2881871]: 2023-02-08T18:45:26.021739Z  WARN massa_consensus_worker::state::stats: desynchronization detected because the recent final block history is empty or contains only blocks produced by this node
Feb 08 19:45:26 vmi1050326.contaboserver.net massa-node[2881871]: 2023-02-08T18:45:26.526020Z  WARN massa_consensus_worker::state::stats: desynchronization detected because the recent final block history is empty or contains only blocks produced by this node
Feb 08 19:45:27 vmi1050326.contaboserver.net massa-node[2881871]: 2023-02-08T18:45:27.031133Z  WARN massa_consensus_worker::state::stats: desynchronization detected because the recent final block history is empty or contains only blocks produced by this node
Feb 08 19:45:27 vmi1050326.contaboserver.net massa-node[2881871]: 2023-02-08T18:45:27.503132Z  WARN massa_consensus_worker::state::stats: desynchronization detected because the recent final block history is empty or contains only blocks produced by this node
Feb 08 19:45:28 vmi1050326.contaboserver.net massa-node[2881871]: 2023-02-08T18:45:28.000599Z  WARN massa_consensus_worker::state::stats: desynchronization detected because the recent final block history is empty or contains only blocks produced by this node
Feb 08 19:45:28 vmi1050326.contaboserver.net massa-node[2881871]: 2023-02-08T18:45:28.500923Z  WARN massa_consensus_worker::state::stats: desynchronization detected because the recent final block history is empty or contains only blocks produced by this node
Feb 08 19:45:29 vmi1050326.contaboserver.net massa-node[2881871]: 2023-02-08T18:45:29.046889Z  WARN massa_consensus_worker::state::stats: desynchronization detected because the recent final block history is empty or contains only blocks produced by this node
Feb 08 19:45:29 vmi1050326.contaboserver.net massa-node[2881871]: 2023-02-08T18:45:29.554601Z  WARN massa_consensus_worker::state::stats: desynchronization detected because the recent final block history is empty or contains only blocks produced by this node
Feb 08 19:45:30 vmi1050326.contaboserver.net massa-node[2881871]: 2023-02-08T18:45:30.055236Z  WARN massa_consensus_worker::state::stats: desynchronization detected because the recent final block history is empty or contains only blocks produced by this node
Feb 08 19:45:30 vmi1050326.contaboserver.net massa-node[2881871]: 2023-02-08T18:45:30.559344Z  WARN massa_consensus_worker::state::stats: desynchronization detected because the recent final block history is empty or contains only blocks produced by this node
Feb 08 19:45:31 vmi1050326.contaboserver.net massa-node[2881871]: 2023-02-08T18:45:31.003087Z  WARN massa_consensus_worker::state::stats: desynchronization detected because the recent final block history is empty or contains only blocks produced by this node
Feb 08 19:45:31 vmi1050326.contaboserver.net massa-node[2881871]: 2023-02-08T18:45:31.500393Z  WARN massa_consensus_worker::state::stats: desynchronization detected because the recent final block history is empty or contains only blocks produced by this node
Feb 08 19:45:32 vmi1050326.contaboserver.net massa-node[2881871]: 2023-02-08T18:45:32.000641Z  WARN massa_consensus_worker::state::stats: desynchronization detected because the recent final block history is empty or contains only blocks produced by this node
Feb 08 19:45:32 vmi1050326.contaboserver.net massa-node[2881871]: 2023-02-08T18:45:32.500940Z  WARN massa_consensus_worker::state::stats: desynchronization detected because the recent final block history is empty or contains only blocks produced by this node
Feb 08 19:45:33 vmi1050326.contaboserver.net massa-node[2881871]: 2023-02-08T18:45:33.003116Z  WARN massa_consensus_worker::state::stats: desynchronization detected because the recent final block history is empty or contains only blocks produced by this node
Feb 08 19:45:33 vmi1050326.contaboserver.net massa-node[2881871]: 2023-02-08T18:45:33.500630Z  WARN massa_consensus_worker::state::stats: desynchronization detected because the recent final block history is empty or contains only blocks produced by this node
Feb 08 19:45:34 vmi1050326.contaboserver.net massa-node[2881871]: 2023-02-08T18:45:34.001204Z  WARN massa_consensus_worker::state::stats: desynchronization detected because the recent final block history is empty or contains only blocks produced by this node
Feb 08 19:45:34 vmi1050326.contaboserver.net massa-node[2881871]: 2023-02-08T18:45:34.500450Z  WARN massa_consensus_worker::state::stats: desynchronization detected because the recent final block history is empty or contains only blocks produced by this node
Feb 08 19:45:35 vmi1050326.contaboserver.net massa-node[2881871]: 2023-02-08T18:45:35.000683Z  WARN massa_consensus_worker::state::stats: desynchronization detected because the recent final block history is empty or contains only blocks produced by this node
Feb 08 19:45:35 vmi1050326.contaboserver.net massa-node[2881871]: 2023-02-08T18:45:35.501648Z  WARN massa_consensus_worker::state::stats: desynchronization detected because the recent final block history is empty or contains only blocks produced by this node
Feb 08 19:45:36 vmi1050326.contaboserver.net massa-node[2881871]: 2023-02-08T18:45:36.006107Z  WARN massa_consensus_worker::state::stats: desynchronization detected because the recent final block history is empty or contains only blocks produced by this node
Feb 08 19:45:36 vmi1050326.contaboserver.net massa-node[2881871]: 2023-02-08T18:45:36.510196Z  WARN massa_consensus_worker::state::stats: desynchronization detected because the recent final block history is empty or contains only blocks produced by this node
Feb 08 19:45:37 vmi1050326.contaboserver.net massa-node[2881871]: 2023-02-08T18:45:37.015068Z  WARN massa_consensus_worker::state::stats: desynchronization detected because the recent final block history is empty or contains only blocks produced by this node
Feb 08 19:45:37 vmi1050326.contaboserver.net massa-node[2881871]: 2023-02-08T18:45:37.518115Z  WARN massa_consensus_worker::state::stats: desynchronization detected because the recent final block history is empty or contains only blocks produced by this node
Feb 08 19:45:38 vmi1050326.contaboserver.net massa-node[2881871]: 2023-02-08T18:45:38.022181Z  WARN massa_consensus_worker::state::stats: desynchronization detected because the recent final block history is empty or contains only blocks produced by this node
Feb 08 19:45:38 vmi1050326.contaboserver.net massa-node[2881871]: 2023-02-08T18:45:38.526831Z  WARN massa_consensus_worker::state::stats: desynchronization detected because the recent final block history is empty or contains only blocks produced by this node
Feb 08 19:45:39 vmi1050326.contaboserver.net massa-node[2881871]: 2023-02-08T18:45:39.030902Z  WARN massa_consensus_worker::state::stats: desynchronization detected because the recent final block history is empty or contains only blocks produced by this node
Feb 08 19:45:39 vmi1050326.contaboserver.net massa-node[2881871]: 2023-02-08T18:45:39.515247Z  WARN massa_consensus_worker::state::stats: desynchronization detected because the recent final block history is empty or contains only blocks produced by this node
Feb 08 19:45:40 vmi1050326.contaboserver.net massa-node[2881871]: 2023-02-08T18:45:40.000988Z  WARN massa_consensus_worker::state::stats: desynchronization detected because the recent final block history is empty or contains only blocks produced by this node
Feb 08 19:45:40 vmi1050326.contaboserver.net massa-node[2881871]: 2023-02-08T18:45:40.504569Z  WARN massa_consensus_worker::state::stats: desynchronization detected because the recent final block history is empty or contains only blocks produced by this node
Feb 08 19:45:41 vmi1050326.contaboserver.net massa-node[2881871]: 2023-02-08T18:45:41.001052Z  WARN massa_consensus_worker::state::stats: desynchronization detected because the recent final block history is empty or contains only blocks produced by this node
Feb 08 19:45:41 vmi1050326.contaboserver.net massa-node[2881871]: 2023-02-08T18:45:41.500396Z  WARN massa_consensus_worker::state::stats: desynchronization detected because the recent final block history is empty or contains only blocks produced by this node
Feb 08 19:45:42 vmi1050326.contaboserver.net massa-node[2881871]: 2023-02-08T18:45:42.000708Z  WARN massa_consensus_worker::state::stats: desynchronization detected because the recent final block history is empty or contains only blocks produced by this node
Feb 08 19:45:42 vmi1050326.contaboserver.net massa-node[2881871]: 2023-02-08T18:45:42.501082Z  WARN massa_consensus_worker::state::stats: desynchronization detected because the recent final block history is empty or contains only blocks produced by this node
Feb 08 19:45:43 vmi1050326.contaboserver.net massa-node[2881871]: 2023-02-08T18:45:43.000518Z  WARN massa_consensus_worker::state::stats: desynchronization detected because the recent final block history is empty or contains only blocks produced by this node
Feb 08 19:45:43 vmi1050326.contaboserver.net massa-node[2881871]: 2023-02-08T18:45:43.500247Z  WARN massa_consensus_worker::state::stats: desynchronization detected because the recent final block history is empty or contains only blocks produced by this node
Feb 08 19:45:44 vmi1050326.contaboserver.net massa-node[2881871]: 2023-02-08T18:45:44.000525Z  WARN massa_consensus_worker::state::stats: desynchronization detected because the recent final block history is empty or contains only blocks produced by this node
Feb 08 19:45:44 vmi1050326.contaboserver.net massa-node[2881871]: 2023-02-08T18:45:44.500785Z  WARN massa_consensus_worker::state::stats: desynchronization detected because the recent final block history is empty or contains only blocks produced by this node
Feb 08 19:45:45 vmi1050326.contaboserver.net massa-node[2881871]: 2023-02-08T18:45:45.001031Z  WARN massa_consensus_worker::state::stats: desynchronization detected because the recent final block history is empty or contains only blocks produced by this node
Feb 08 19:45:45 vmi1050326.contaboserver.net massa-node[2881871]: 2023-02-08T18:45:45.500693Z  WARN massa_consensus_worker::state::stats: desynchronization detected because the recent final block history is empty or contains only blocks produced by this node
Feb 08 19:45:46 vmi1050326.contaboserver.net massa-node[2881871]: 2023-02-08T18:45:46.000199Z  WARN massa_consensus_worker::state::stats: desynchronization detected because the recent final block history is empty or contains only blocks produced by this node
Feb 08 19:45:46 vmi1050326.contaboserver.net massa-node[2881871]: 2023-02-08T18:45:46.507333Z  WARN massa_consensus_worker::state::stats: desynchronization detected because the recent final block history is empty or contains only blocks produced by this node
Feb 08 19:45:47 vmi1050326.contaboserver.net massa-node[2881871]: 2023-02-08T18:45:47.008575Z  WARN massa_consensus_worker::state::stats: desynchronization detected because the recent final block history is empty or contains only blocks produced by this node
Feb 08 19:45:47 vmi1050326.contaboserver.net massa-node[2881871]: 2023-02-08T18:45:47.512520Z  WARN massa_consensus_worker::state::stats: desynchronization detected because the recent final block history is empty or contains only blocks produced by this node
Feb 08 19:45:48 vmi1050326.contaboserver.net massa-node[2881871]: 2023-02-08T18:45:48.016389Z  WARN massa_consensus_worker::state::stats: desynchronization detected because the recent final block history is empty or contains only blocks produced by this node
Feb 08 19:45:48 vmi1050326.contaboserver.net massa-node[2881871]: 2023-02-08T18:45:48.520229Z  WARN massa_consensus_worker::state::stats: desynchronization detected because the recent final block history is empty or contains only blocks produced by this node
Feb 08 19:45:49 vmi1050326.contaboserver.net massa-node[2881871]: 2023-02-08T18:45:49.000583Z  WARN massa_consensus_worker::state::stats: desynchronization detected because the recent final block history is empty or contains only blocks produced by this node
Feb 08 19:45:49 vmi1050326.contaboserver.net massa-node[2881871]: 2023-02-08T18:45:49.528536Z  WARN massa_consensus_worker::state::stats: desynchronization detected because the recent final block history is empty or contains only blocks produced by this node
Feb 08 19:45:50 vmi1050326.contaboserver.net massa-node[2881871]: 2023-02-08T18:45:50.032724Z  WARN massa_consensus_worker::state::stats: desynchronization detected because the recent final block history is empty or contains only blocks produced by this node
Feb 08 19:45:50 vmi1050326.contaboserver.net massa-node[2881871]: 2023-02-08T18:45:50.536881Z  WARN massa_consensus_worker::state::stats: desynchronization detected because the recent final block history is empty or contains only blocks produced by this node
Feb 08 19:45:51 vmi1050326.contaboserver.net massa-node[2881871]: 2023-02-08T18:45:51.041050Z  WARN massa_consensus_worker::state::stats: desynchronization detected because the recent final block history is empty or contains only blocks produced by this node
Feb 08 19:45:51 vmi1050326.contaboserver.net massa-node[2881871]: 2023-02-08T18:45:51.500528Z  WARN massa_consensus_worker::state::stats: desynchronization detected because the recent final block history is empty or contains only blocks produced by this node
Feb 08 19:45:52 vmi1050326.contaboserver.net massa-node[2881871]: 2023-02-08T18:45:52.000766Z  WARN massa_consensus_worker::state::stats: desynchronization detected because the recent final block history is empty or contains only blocks produced by this node
Feb 08 19:45:52 vmi1050326.contaboserver.net massa-node[2881871]: 2023-02-08T18:45:52.502530Z  WARN massa_consensus_worker::state::stats: desynchronization detected because the recent final block history is empty or contains only blocks produced by this node
Feb 08 19:45:53 vmi1050326.contaboserver.net massa-node[2881871]: 2023-02-08T18:45:53.000859Z  WARN massa_consensus_worker::state::stats: desynchronization detected because the recent final block history is empty or contains only blocks produced by this node

**Comment by aoudiamoncef** [comment]
Hello, 
Thanks for your report
The issue to put the logs is the #3512. I'm referencing your logs there.
