### ISSUE TITLE
Execution deadlock

### ISSUE THREAD

**Issue by Eitu33** [massalabs/massa#3551]
## Context

Testnet 19 has crashed twice with the following symptoms:
- Nodes are still running
- API is not responding
- Execution final hash is not logged

## Problem

Only major functionality added this testnet was the module caching. If we take `CallSC` operations as an example, the corresponding bit of code for a cached module execution is:

```rust
let mut module_lock = self.module_cache.write();
let module = module_lock.get_module(&bytecode, max_gas)?;
match massa_sc_runtime::run_function(
    &*self.execution_interface,
    module.clone(),
    target_func,
    param,
    max_gas,
    self.config.gas_costs.clone(),
) {
    Ok(Response { init_cost, .. }) => {
        module_lock.save_module(&bytecode, module, init_cost);
        Ok(())
    }
    Err(err) => Err(ExecutionError::RuntimeError(format!(
        "module execution error in execute_callsc_op: {}",
        err
    ))),
}
```

Here we can see that `module_lock` is not released before the `run_function` call, at first sight it does not look like an issue given that the parent function ends right after the execution does. But `massa-sc-runtime` exposed interface now requires an implementation of `get_module` which is supposed to handle the cache for sub calls inside the VM. Here is its implementation in `massa-execution-worker`:

```rust
fn get_module(&self, bytecode: &[u8], limit: u64) -> Result<RuntimeModule> {
    let context = context_guard!(self);
    let module = context.module_cache.write().get_module(bytecode, limit)?;
    Ok(module)
}
```

It takes a lock on the caching while the execution thread still has one as well, any sub module call should create a deadlock. But the execution tests are supposed to fail in that case, and they passed on `testnet_19` merge CI and still pass on `main`.

**Comment by Eitu33** [comment]
⚠️ `ExecuteSC` does not require cache for execution, only `CallSC` operations, read-only calls, and async messages do. Execution tests make sub calls but only after `ExecuteSC` operations and in the testnet current usage the last 3 cases usually never make sub calls.

**Comment by AurelienFT** [comment]
```
Deadlock #0
Thread Id 140666461996608
   0:     0x55ffa06d6037 - backtrace::backtrace::trace::h50fc839770df81d2
   1:     0x55ffa06c773f - backtrace::capture::Backtrace::new::h70ac65363230bbc6
   2:     0x55ffa06bd3a7 - parking_lot_core::parking_lot::deadlock_impl::on_unpark::hed7c8bb86cad062e
   3:     0x55ff9f63e152 - parking_lot::raw_rwlock::RawRwLock::lock_exclusive_slow::h9bbea901f1f28bff
   4:     0x55ff9fed2e11 - <massa_execution_worker::interface_impl::InterfaceImpl as massa_sc_runtime::types::Interface>::get_module::hc2bce9cfb481c655
   5:     0x55ffa01ac29d - massa_sc_runtime::as_execution::common::call_module::h26439d7cd17f5d5c
   6:     0x55ffa01c5de7 - massa_sc_runtime::as_execution::abi::assembly_script_call::h41556e76b15ed4e4
   7:     0x55ffa01d2e57 - std::panicking::try::h61fd007fb3ab5027
   8:     0x55ffa01d4fca - corosensei::coroutine::on_stack::wrapper::hf65ba519d8d9a954
   9:     0x55ffa04902c9 - stack_call_trampoline
  10:     0x55ffa01baf3a - wasmer_vm::trap::traphandlers::on_host_stack::h0c8f51a5e3d8b442
  11:     0x55ffa01d1c57 - <Func as wasmer::sys::externals::function::inner::HostFunction<T,(A1,A2,A3,A4),Rets,wasmer::sys::externals::function::inner::WithEnv>>::function_body_ptr::func_wrapper::hd8af6b85a33c0991
  12:     0x7fefa88832ed - <unknown>
  13:     0x7fefa88843cc - <unknown>
```

**Comment by Eitu33** [comment]
Fix here: https://github.com/massalabs/massa/pull/3553
