### ISSUE TITLE
Rename white/black list to allow/block list

### ISSUE THREAD

**Issue by Ben-PH** [massalabs/massa#3561]
There are [socio-political](https://www.vice.com/en/article/v7dd3d/we-need-to-stop-saying-blacklist-and-whitelist) factors, as well as [practical](https://www.linkedin.com/pulse/allowlist-blocklist-better-terms-everyone-lets-use-them-rob-black/) reasons.

My take: As an open-source project, we should make efforts to be inclusive, even if the practical/technical argument is dismissed (though I think there is at least a non-zero benefit in that respect).

Barring any technical limitation, I think it's a valuable direction to take.

A low-quality search picked up 187 instances of "whitelist" in the project, many of them functions/types that can easily be handled with a rust-analyzer rename.

**Comment by AurelienFT** [comment]
Hello,

We already spoke about it with @aoudiamoncef and @damip. @damip and I decided that it's better to stay with words that are in the english dictionary (we take Cambridge one as reference) to avoid taking part in any socio-political movements.

Also, if someone doesn't understand whitelist he can refer to the dictionary which is not the case with allowlist.
