### ISSUE TITLE
Add bytes to ledger to prepare persistent

### ISSUE THREAD

**Issue by AurelienFT** [massalabs/massa#3598]
After merging of https://github.com/massalabs/massa/pull/3455 we want to implement the decisions taken here : https://github.com/massalabs/massa/discussions/3596#discussioncomment-5075444

Mandatory before the end of the month : 

- Add a byte at the start of each ledger key that will be used as a version in the future
- Add a byte at the start of the bytecode that will be used as a version in the future

To have in near future : 

- A byte in each value of the datastore saying if the value if read-only or not.

**Comment by Leo-Besancon** [comment]
The linked PR is only related to the first two subtasks of this issue.

**Comment by Leo-Besancon** [comment]
The first part of this issue had be completed with the merge of #3603 

Next steps for this issue are:

- Make the Bytecode Rust struct serialization consistant with the runtime. Meaning: the `Vec<u8>` we pass to the runtime should be prefixed with the version of the bytecode.
- Add a byte in each value of the datastore saying if the value if read-only or not.

**Comment by damip** [comment]
For now we won't do the readonly byte thing but we need a version number for each ledger entry. The bytecode version byte is there now.

**Comment by AurelienFT** [comment]
Last part done in : https://github.com/massalabs/massa/pull/4154
