### ISSUE TITLE
Disable Bootstrap ban protection

### ISSUE THREAD

**Issue by peterjah** [massalabs/massa#3599]
For testing purpose i am restarting my node quite often.
The probleme of doing this is the bootstrap get stuck because of the 12hours waiting restriction between 2 bootstraps
![image](https://user-images.githubusercontent.com/34547263/220679499-df14ea46-6f80-4d83-87c4-5ae7001ab17f.png)

**Describe the solution you'd like**
I would like to have the ability to setup a node with disabled ban protection. So i can use it to bootstrap a second node without hitting the ban limit

**Comment by AurelienFT** [comment]
You can change it in the config the variable is `per_ip_min_interval` in `massa/massa-node/base_config/config.toml`
