### ISSUE TITLE
Node crash with `CycleUnavailable`

### ISSUE THREAD

**Issue by JeromeSi** [massalabs/massa#3607]
**Describe the bug**
the node loose a block and cash or crash and loose a block

**Desktop :**

- OS: Ubuntu 22.04
- CPU i7-11700
- RAM 32Gb
- connection  fiber 1Gb up / 500Mb down (ping ~10ms)

In this log file, you have the beginning of error and the restart of the node

[issues-github.log](https://github.com/massalabs/massa/files/10819506/issues-github.log)

**Comment by AurelienFT** [comment]
This hasn't happened since two month. Closing it.
