### ISSUE TITLE
Refine bootstrap error enum

### ISSUE THREAD

**Issue by Ben-PH** [massalabs/massa#3608]
The bootstrap error enums has many varients wrapping a String, and because of some variant mem-sizes, clippy warnings are triggered.

I would like to have a look at this enum and see if we can have some type wrappings, Boxing of the large variants (instead of the enum itself), or other approaches that make for a more "tasteful" code-base.

**Comment by litchipi** [comment]
Is this still an issue ? I don't have any warnings when running clippy on it

**Comment by modship** [comment]
I think this issue can be closed, Large error are Boxed (UnexpectedClientMessage) in BootstrapError and clippy doesn't print any warning about error in bootstrap.
