### ISSUE TITLE
optional prefix when listing datastore elements

### ISSUE THREAD

**Issue by damip** [massalabs/massa#3625]
**Is your feature request related to a problem? Please describe.**

Right now both the API and ABI endpoints to list datastore and op datastore keys can only list all keys. 

**Describe the solution you'd like**

Since the keys are always sorted in memory, allow the following things to list only keys matching a given optional prefix:
* list account datastore keys API 
* list accoint datastore keys ABI
* list operation datastore keys ABI

**Comment by AurelienFT** [comment]
I believe the last one already exist it's `geyKeys()` ABI.

The account datastore keys are already in the answer of `get_addresses`.

We don't have ABI to list account datastore keys we can add it.

**Comment by AurelienFT** [comment]
Prefix ABI done in https://github.com/massalabs/massa/pull/3640
