### ISSUE TITLE
Double send block websocket consensus

### ISSUE THREAD

**Issue by AurelienFT** [massalabs/massa#3668]
Me neither. @aoudiamoncef can you provide some context ?

_Originally posted by @AurelienFT in https://github.com/massalabs/massa/pull/3636#discussion_r1129080861_

**Comment by aoudiamoncef** [comment]
It's the same code for sending in gRPC. We'll see the feedback from Inno team

**Comment by AurelienFT** [comment]
The comment was about the fact that there is no real difference between broadcasting a block header and a block that is not filled. We should have only block header and filled block. The block one is redundant. As GRPC is now by default activated because of the client it's important that we don't use too much resources for nothing

**Comment by aoudiamoncef** [comment]
@AurelienFT we already removed broadcasting blocks headers It in the gRPC streams. 

We could remove It and keep only blocks.

**Comment by modship** [comment]
test with new_grpc_api branch, i have 2 blocks/s with streaming

**Comment by aoudiamoncef** [comment]
With @damip we removed block headers and kept blocks/filled blocks/endorsements/operations
