### ISSUE TITLE
[TEST.20.1] problem on cycle 164

### ISSUE THREAD

**Issue by t3ier** [massalabs/massa#3681]
My node started on cycle 120 and all worked fine. But, on cycle 164, some block were missed.
My connection and my node were not stopped, I don't know what caused this problem.

**System :**
- OS : Debian GNU/Linux 11 (bullseye)
- Type of installation : systemd
- Version : TEST.20.1

I joined the full logs file on this issue.

The cycle 164 start on line 9190 :
`mars 13 11:17:52 SRV-NODE02 massa-node[2966]: 2023-03-13T10:17:52.000862Z  INFO massa_consensus_worker::worker::main_loop: Started cycle 164`

[logs_2023-03-13.txt](https://github.com/massalabs/massa/files/10957697/logs_2023-03-13.txt)

**Comment by AurelienFT** [comment]
It seems that you have been desync with the network but doesn't see precisely in your logs :/

Thanks for the report.
