### ISSUE TITLE
Determine proportion of gas for async calls

### ISSUE THREAD

**Issue by AurelienFT** [massalabs/massa#3684]
We have a maximum of u32::MAX (4 billions) of gas for a slot. We need to determine how much will be used for async calls and for operations.

**Comment by damip** [comment]
Attention points:
* we want the total slot gas to match around 300 ms on the current target specs
* if in the future computing power increases we want to allow more gas per slot without overflowing nor rescaling everything to not break compatibility => we must either use something lower than u32::max or fork the gas metering system to use u64 instead. We can determine this by looking at the.

Here is how I would proceed:
* set the instruction that is the cheapest in gas (eg. some basic addition) to cost 1000 (not 1 just in case a cheaper instruction is added in the future)
* set the max slot gas to be equivalent to 300ms of execution time on the target architecture
  * if the max slot gas overflows u32, fork the metering system to use u64 instead

**Comment by AurelienFT** [comment]
this is the only thing not covered by any issue : `set the instruction that is the cheapest in gas (eg. some basic addition) to cost 1000 (not 1 just in case a cheaper instruction is added in the future)` downgrade this issue as P2 and for test.25
