### ISSUE TITLE
Missing Unit Tests - PoS Worker

### ISSUE THREAD

**Issue by dr-chain** [massalabs/massa#3688]
It seems that the Test Suit/Unit Tests are missing for [Massa-Pos-Worker](https://github.com/massalabs/massa/tree/main/massa-pos-worker).

If they are implemented somewhere else, we can move them here so that we are coherent w.r.t. other modules.

**Comment by AurelienFT** [comment]
They don't exist. We have an issue there : https://github.com/massalabs/massa/issues/2911

**Comment by dr-chain** [comment]
Closing this issue as merged with audit issue #3687
