### ISSUE TITLE
VestingManager

### ISSUE THREAD

**Issue by modship** [massalabs/massa#3699]
Use binary search to go faster. This is potentially called more than 10000 times a second and should be well optimized

_Originally posted by @damip in https://github.com/massalabs/massa/pull/3489#discussion_r1130696161_

See also :
 https://github.com/massalabs/massa/pull/3489#discussion_r1142087199  : remove duplicate code with VestingManager
https://github.com/massalabs/massa/pull/3489#discussion_r1142087491 : iter().find() replace with binary search
https://github.com/massalabs/massa/pull/3489#discussion_r1142087702  
https://github.com/massalabs/massa/pull/3489#discussion_r1142153986 : remove Serde default Slot::min
https://github.com/massalabs/massa/pull/3489#discussion_r1142043284 : Add message for panic!
https://github.com/massalabs/massa/pull/3489#discussion_r1143481623 : Add message for user sending coins to itself

**Comment by damip** [comment]
use https://doc.rust-lang.org/std/vec/struct.Vec.html#method.binary_search_by_key

**Comment by modship** [comment]
yes, i have see that yesterday but don't know if i can use directly this, I need to examine more closely. 
This compare same type object but i my case i have `VestingRange` and `Slot` but i think i can implement mine.

**Comment by damip** [comment]
> yes, i have see that yesterday but don't know if i can use directly this, I need to examine more closely. This compare same type object but i my case i have `VestingRange` and `Slot` but i think i can implement mine.

I don't understand the concept of vestingrange, it could just be:

```rust
sruct VestingInfo {
    min_coins: Amount,
    max_rolls: u64
}

// assume the Vecs are ordered by increasing MassaTime
struct VestingManager(PreHashMap<Address, Vec<(MassaTime, VestingInfo)>);


impl VestingManaget {
    pub fn from_file(file_path) -> Self { ... TODO JUST LOAD THE HASHMAP FROM FILE  ... }

    pub fn get_vesting_info_for_addr_at_time(&self, addr: &Address, timestamp: &MassaTime) -> VestingInfo {
        self.0.get(addr).and_then(|hist| {
            hist.get(
                 hist.binary_search_by_key(timestamp, |(t, nfo)| t).unwrap_or_else(|i| i.saturating_sub(1))
            )
        }).unwrap_or_else(| | {
             VestingInfo { min_coins: Amount::MIN, max_rolls: u64::MAX }
        })
    }
}

```

**Comment by modship** [comment]
If address is not in the map it's preferable to return an Option<T> (None) instead of
 ```rust
 VestingInfo { min_balance: Amount::MIN, max_rolls: u64::MAX }
```
as it prevents the continuation of the check if the address is not vested.

**Comment by damip** [comment]
Then here is an option:

```rust
sruct VestingInfo {
    min_balance: Option<Amount>,
    max_rolls: Option<u64>
}

// assume the Vecs are ordered by increasing MassaTime
struct VestingManager(PreHashMap<Address, Vec<(MassaTime, VestingInfo)>);

impl VestingManager {
    pub fn from_file(file_path) -> Self { ... TODO JUST LOAD THE HASHMAP FROM FILE  ... }

    pub fn get_addr_vesting_at_time(&self, addr: &Address, timestamp: &MassaTime) -> VestingInfo {
        self.0.get(addr).and_then(|hist| {
            hist.get(
               hist.binary_search_by_key(timestamp, |(t, _)| *t).unwrap_or_else(|i| i.saturating_sub(1))
            ).cloned()
        }).unwrap_or_default()
    }
}
```
