### ISSUE TITLE
Wasm instructions gas cost

### ISSUE THREAD

**Issue by aoudiamoncef** [massalabs/massa#3700]
We should never be zero because someone could just make an infinite loop of just those instructions.

_Originally posted by @damip in https://github.com/massalabs/massa/pull/3489#discussion_r1142034058_

See also : 
https://github.com/massalabs/massa/pull/3489#discussion_r1142034182
https://github.com/massalabs/massa/pull/3489#discussion_r1142034269
https://github.com/massalabs/massa/pull/3489#discussion_r1142034734

Related to https://github.com/massalabs/gas-calibration/issues/4

**Comment by damip** [comment]
> @damip, as a hotfix, we put 1 ?
> 
> as said in [#3489 (comment)](https://github.com/massalabs/massa/pull/3489#discussion_r1143161728)

yes let's put 1 to all zeros
