### ISSUE TITLE
max_operations_per_block not checked when retreiving from network.

### ISSUE THREAD

**Issue by Ben-PH** [massalabs/massa#3702]
https://github.com/massalabs/massa/issues/3702#issuecomment-1477929385

For additional context, there is a fencepost error in the deserialization of the block when deserializing the vector of `OperationIds`. 

the ops_ids deserializer is constructed like so:

```rust
impl OperationIdsDeserializer {
    /// Creates a new `OperationIdsDeserializer`
    pub fn new(max_operations_per_message: u32) -> Self {
        Self {
            length_deserializer: U32VarIntDeserializer::new(
                Included(0),
                Included(max_operations_per_message),
            ),
            hash_deserializer: HashDeserializer::new(),
        }
    }
}
```

(note: the inclusive range)

**Comment by Ben-PH** [comment]
righto. I'll change the issue, keeping the fencepost issue in as context.

**Comment by damip** [comment]
@Ben-PH  I don't see any problem in the code you posted

**Comment by Ben-PH** [comment]
On first read, it appears to have the same semantics as `0..=max_operations_per_message` instead of `0..max_operations_per_message`

Perhaps it's used in a way such that it's accounted. In any case, the primary issue is as you mentioned: if the deserializer is a bug, it should by caught anyway by the check you've noted as missing.

**Comment by damip** [comment]
This was corrected here: https://github.com/massalabs/massa/commit/02714090bafd5c003e2d367b2736c7dcd93c6b2d
