### ISSUE TITLE
Block operation checks

### ISSUE THREAD

**Issue by damip** [massalabs/massa#3709]
The following points need attention:
* [x] let's set back max_operations_per_block to 5000 instead of 10000
* [x] ensure that the block size limit is respected at block creation
* [x] ensure that the block size limit is checked at block retrieval
* [x] ensure that the block operation count limit is respected at block creation
* [x] ensure that the block operation count limit is checked at block retrieval
* [x] ensure that blocks fit within the constaints of message sizes (for example MAX_MESSAGE_SIZE)
* [x] ensure that the retrieval of block operations fits within the constaints of message sizes (for example MAX_MESSAGE_SIZE or  MAX_OPERATIONS_PER_MESSAGE)
* [x] re-read block (de-)serialization and make sure it is consistent
* [x] re-read operation (de-)serialization and make sure it is consistent
* [x] re-read block retrieval messages (de-)serialization and make sure it is consistent

**Comment by sydhds** [comment]
Related PR : https://github.com/massalabs/massa/pull/3710

**Comment by sydhds** [comment]
block operation count check: done

**Comment by AurelienFT** [comment]
@sydhds Can you tick the things that has been done so that we know if we can closed or not ?

**Comment by sydhds** [comment]
> @sydhds Can you tick the things that has been done so that we know if we can closed or not ?

Done. Do you want me to check the others tasks and make a PR if needed? @AurelienFT

**Comment by sydhds** [comment]
"ensure that the block size limit is respected at block creation"

From what I see, in the block factory, the max_block_size is used when retrieving operation but we've already added some endorsements without checking the size of them. Need a fix here

**Comment by sydhds** [comment]
Need to clarify the diff and rename between:
* MAX_OPERATIONS_PER_BLOCK (set to 5000) -> used in message deser for ?
* MAX_OPERATIONS_PER_MESSAGE (set to 1024) -> used in message deser for operation_replies

**Comment by AurelienFT** [comment]
`MAX_OPERATIONS_PER_MESSAGE` should be used for naked operation propagation system

**Comment by sydhds** [comment]
> `MAX_OPERATIONS_PER_MESSAGE` should be used for naked operation propagation system

Yep but I think the naming is misleading, I'll try to propose a better and more explicit name for it :)

**Comment by sydhds** [comment]
block_header serialize does not limit the number of endorsements with a constant but with u32::max, maybe we should pass a limit to the serializer here?

**Comment by sydhds** [comment]
OperationsDeserializer has a cfg named max_operations_per_message and this is misleading ? Maybe rename this deserializer ?

**Comment by AurelienFT** [comment]
> Yep but I think the naming is misleading, I'll try to propose a better and more explicit name for it :)

Great idea

> But I am in favor of adding a unit test here

As the network refactor is taking place this month maybe not worth doing the test on old version right now, but mention it in the issue of network refactoring for the future it's a clear yes.

> block_header serialize does not limit the number of endorsements with a constant but with u32::max, maybe we should pass a limit to the serializer here

Yes we could limit to `Included(endorsement_count)`

> OperationsDeserializer has a cfg named max_operations_per_message and this is misleading ?

Yes we could rename it by `max_length` and depending on the context the parameter will either by the value of `max_operations_per_message` or `max_operations_per_block`
