### ISSUE TITLE
TODO: Stream of Ledger deltas per operation + tree of calls per operation

### ISSUE THREAD

**Issue by longgamma-massa** [massalabs/massa#3722]
**Is your feature request related to a problem? Please describe.**
In order to show all transfers, and more generally all calls that occurred per operation for Block API project (block explorer services). 

- ETA for priority on these tasks: April 6th 
- Ideal date to receive this: May 15th (in other case, we should discuss the delivery plan for the project with end-to-end testing) 

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by damip** [comment]
@longgamma-massa after studying the requirements, and the surrounding priorities, we have found that we cannot implement this before the mainnet. So let's keep things as simple as possible

**Comment by AurelienFT** [comment]
Done in execution-trace feature
