### ISSUE TITLE
Miss a block at cycle 45

### ISSUE THREAD

**Issue by JeromeSi** [massalabs/massa#3724]
**Describe the bug**
My node miss a block at cycle 45

**To Reproduce**
I don't know but I loose block only when the node produce more than 2 blocks par cycle

**Desktop (please complete the following information):**

- OS: Debian 11.4

**Hardware :**

- Device: Lenovo T440p i5-4300M
- 16Gb / SSD SATA
- Other software : CHIA / Nextcloud (4 users)

[ggcom-cycle_45.log.tar.gz](https://github.com/massalabs/massa/files/11056480/ggcom-cycle_45.log.tar.gz)
![CPU0](https://user-images.githubusercontent.com/13288010/227369804-8485463f-a8b1-47a5-b3d5-13399aa884c4.png)
![CPU1](https://user-images.githubusercontent.com/13288010/227369821-845e31d9-f6f4-49f8-82c9-39c98b77e855.png)
![CPU2](https://user-images.githubusercontent.com/13288010/227369832-7a27660f-2710-4f94-9ea1-08c20b3b888f.png)
![CPU3](https://user-images.githubusercontent.com/13288010/227369834-dcf9315d-92dd-4cef-b209-ac5d66da2d14.png)
![InterfaceTraffic](https://user-images.githubusercontent.com/13288010/227369838-947b6b4a-70b3-4372-b7a1-a6e3adc90e6a.png)
![Memory](https://user-images.githubusercontent.com/13288010/227369839-281b8242-6e95-4cb5-98f6-a4103f9aa0bf.png)

**Comment by JeromeSi** [comment]
Connexion : ethernet 1Gb/s, fiber 1Gb/s / 700Mb/s

**Comment by JeromeSi** [comment]
adresse : AU127pueMWvPb7AyAPP4QicEBv56XdwMLFuiosp6v7ceRH338LhTD
![Capture d’écran_2023-03-24_09-23-11](https://user-images.githubusercontent.com/13288010/227464639-7afac107-2f8d-4ed7-bd28-72786628565c.png)

**Comment by AurelienFT** [comment]
Closing as it hasn't been reproduced in the latest testnets
