### ISSUE TITLE
Testnet 20.2 bootstrap does not end

### ISSUE THREAD

**Issue by damip** [massalabs/massa#3731]
On my node at home, the bootstrap process lasts forever

[logs.txt](https://github.com/massalabs/massa/files/11083059/logs.txt)

Note how there is a 2-second interval between each attempt

**Comment by AurelienFT** [comment]
Bootstrap has been significatively improved and we don't reproduce this anymore. Last bug of this type to be tackle is https://github.com/massalabs/massa/issues/4101 

Closing in favor of newer reports
