### ISSUE TITLE
Internal Audit: Massa-Hash

### ISSUE THREAD

**Issue by dr-chain** [massalabs/massa#3747]
Following are the few improvements suggested for [Massa-Hash](https://github.com/massalabs/massa/tree/main/massa-hash).

In [hash.rs](https://github.com/massalabs/massa/blob/main/massa-hash/src/hash.rs):
- [x] Remove redundant function `to_bytes(&self)` / `into_bytes(self)`
- [ ] Remove redundant function `std::fmt::Debug` / `std::fmt::Display`
- [x] Remove redundant function `BitXorAssign` / `BitXor`

Following are the ideas for improving the functional documentation.
- [x] Explaining the need for bitwise XOR
- [x] Explaining the need for Hash comparison
- [x] Explaining the motivations for choosing `base58` encoding
- [x] Explaining the motivations for choosing `blake3` as the hashing algorithm

PR implementing the documentation improvements: #3748

**Comment by AurelienFT** [comment]
@damip about Remove redundant function `to_bytes(&self)` / `into_bytes(self)` do we do it and which one we keep ?

**Comment by damip** [comment]
I think we can keep both. The idea is that to_bytes creates a copy while into_bytes consumes the underlying data and returns it as bytes

**Comment by damip** [comment]
Also I don't think we need the bitwise XOR on normal (non-XOF) hashes
