### ISSUE TITLE
Tests TEST.21

### ISSUE THREAD

**Issue by AurelienFT** [massalabs/massa#3766]
Testing Test21. Here is a list to know what to test before releasing TEST.21. This is the most prioritised thing to do. 

If you can do it by wednesday morning it would be nice. Wednesday afternoon will be used to test restart scenarios.

Labnet will be launched in the morning.

If you think something is missing do not hesitate to comment

- [x] @Leo-Besancon : Ipv4/Ipv6 windows, restart between testnet (should add the timestamps before maybe the afternoon

- [x] 

- [x] @sydhds : Denonciations

- [x] @AurelienFT : New testnet, multistake

- [x] @aoudiamoncef : GRPC

- [x] @Eitu33 : Module caching

- [ ] @litchipi : Abi get_keys, get_keys_of, validate_address

- [x] @Ben-PH : bootstrap

- [x] @bilboquet : Normal launch to stake etc

**Comment by Ben-PH** [comment]
bootstrap essentially tests itself in many ways, as all activity needs to start from a bootstrap.

Am open to ideas about particular scenarios we should test.

**Comment by AurelienFT** [comment]
Yes bootstrap worked well we can tick it

**Comment by litchipi** [comment]
Just finished validation of the new ABIs, code can be seen here: https://github.com/litchipi/massa_smart_contracts/tree/test_new_abi
