### ISSUE TITLE
Mise à jour [cargo build --features massa_proto/build-tonic]

### ISSUE THREAD

**Issue by J-P1** [massalabs/massa#3797]
Bonjour,
Dans Massa-client j'ai ce warning qui ressort lancement [warning: build-tonic feature is disabled, you can update the generated code from protobuf files by running: cargo build --features massa_proto/build-tonic]
 j'ai fait cette mise à jour [cargo build --features massa_proto/build-tonic] qui s'est réalisé sans problème, par contre j'ai cette erreur qui en est ressorti, j'ai regardé et il manquerait un dossier. Simplement pour savoir si c'est normal ou pas.
![Capture2](https://user-images.githubusercontent.com/124814422/230719887-ba527064-28ab-496c-8533-70e3fc7e7d3c.PNG)

**Comment by aoudiamoncef** [comment]
Bonjour 👋 

Ce warning est destiné aux personnes qui développe sur Massa. Il concerne la partie protobuf et gRPC. Dans ton cas, il n'a strictement aucun effet.

Assure toi que tu es sur la dernière branche tesnet et `cargo clean` et relance ton node
