### ISSUE TITLE
Can not bootstrap from a custom bootstrap node

### ISSUE THREAD

**Issue by raulddan** [massalabs/massa#3799]
**Describe the bug**
Can not bootstrap from a custom bootstrap node

**To Reproduce**
We got node A and node B. 
Node A needs to bootstrap from Node B and we make the necessary mods as follows:
    - Using Node's B client: node_bootstrap_whitelist add ip_of_node_A
    - add to node's A config.toml (massa/massa-node/config): 
    
    bootstrap_list = [
       ["node_b_ip:31245", "node_b_nodeid"], ]

**Expected behavior**
Restart node A to bootstrap from node B and get the following error:

Error while bootstrapping: general bootstrap error: Parsing Error: Failed BootstrapServerMessage deserialization / Failed MIP store deserialization / Failed MipStoreRaw der / Failed mip store stats der / Failed MipStoreStats network version counters der / Count / Failed counters data der / Failed u32 deserialization / Fail / Input: []

Debug logs of both nodes: https://we.tl/t-9CgVyX528H

*** Edit: 
-node A Ubuntu 20.04
-node B Ubuntu 22.04

**Comment by JeromeSi** [comment]
Hi
I've got the same error with a custom node and an official node with binaries.
I'm trying to delete the folder massa and make a new massa installation with old config.toml and wallet.dat : same problem.
I put the debug log of the node who want to bootstrap (log_3_bootstrap_error.txt)
I put the log of the node who is running well (log_2_Running_node.txt)
[log_3_bootstrap_error.txt](https://github.com/massalabs/massa/files/11185427/log_3_bootstrap_error.txt)
[log_2_Running_node.txt](https://github.com/massalabs/massa/files/11185432/log_2_Running_node.txt)

**Comment by sydhds** [comment]
This has been investigated and a fix has been created and will be merged in testnet 22: https://github.com/massalabs/massa/pull/3802.

Thanks for the report, it really helps to debug this :)
