### ISSUE TITLE
4/8/160 maximum load and node loses roll

### ISSUE THREAD

**Issue by AntonioZolotoy** [massalabs/massa#3800]
Hetzner CX 31 server vCPU 4 AMD/ RAM 8 GB/ Disk 160 GB.
After a certain event, there is a 100% load on the server and RAM, the download and upload speed increases to 30-40Mb/s. The usual load on the processor is 8-25%, on RAM 4-7 GB, the usual download/upload speed is 8-25Mb/s.
After this event, the maximum load on the processor and memory occurs, the speed increases. And then the node loses the roll. No can find bootstrap. A full node reboot helps. I attach a screenshot, logs.

Apr 09 18:03:57 ubuntu-8gb-hil-1 massa-node[3086117]: 2023-04-09T18:03:57.011833Z  INFO massa_final_state::final_state: final_state hash at slot (period: 11937, thLK1yfBkFEgr2DTKhLiMgUotS1bQYms2DdwN5wyLh88mzQWSQ9
Apr 09 18:04:00 ubuntu-8gb-hil-1 massa-node[3086117]: 2023-04-09T18:04:00.903438Z  INFO massa_final_state::final_state: final_state hash at slot (period: 11937, th2htMVPjJjiqw3DWu2vm5WuvrQUZ3Q6Yu66Uhr6ZfnSyNhGomEB
Apr 09 18:04:02 ubuntu-8gb-hil-1 massa-node[3086117]: 2023-04-09T18:04:02.731935Z  INFO massa_final_state::final_state: final_state hash at slot (period: 11937, thSvQMAhhRCd8k4SH4u2sKo6zVoHBxu9uvWgqkRmpc3Hfu7v9Y5
Apr 09 18:04:10 ubuntu-8gb-hil-1 massa-node[3086117]: 2023-04-09T18:04:10.575061Z  INFO massa_final_state::final_state: final_state hash at slot (period: 11937, th2cXybSfQy8xWvDDkUV4wLnMswEpyG3UQVqrRS6eJUKqGGRE6p5
**Apr 09 18:04:22** ubuntu-8gb-hil-1 massa-node[3086117]: 2023-04-09T18:04:22.735371Z  INFO massa_network_worker::network_event::event_impl: Send network event failed curred during channel communication: Failed to send event.
Apr 09 18:04:22 ubuntu-8gb-hil-1 massa-node[3086117]: 2023-04-09T18:04:22.736720Z  WARN massa_protocol_worker::protocol_network: Node N12f66o99Wwzxfzab7VbL76Df1M8ga8LqzbK4WeZx sent us an operation list but we don't have block id B1ppbPpZR1krHQ8WeZ7e2NY44ryaBxcrePrvDN7whQuDDBdph6D in our wishlist.
Apr 09 18:04:22 ubuntu-8gb-hil-1 massa-node[3086117]: 2023-04-09T18:04:22.743259Z  WARN massa_protocol_worker::protocol_network: Node N12JQxX1zYLkBh2XStadVAEzZbQJVNmrVD4FNeVzc sent us an operation list but we don't have block id B1aa5CCUEG3MquoUtufXzTa3pv8ZN11eugYQeg4VQWuybUWyXkt in our wishlist.
Apr 09 18:04:22 ubuntu-8gb-hil-1 massa-node[3086117]: 2023-04-09T18:04:22.746092Z  INFO massa_network_worker::network_event::event_impl: Send network event failed curred during channel communication: Failed to send event.
Apr 09 18:04:22 ubuntu-8gb-hil-1 massa-node[3086117]: 2023-04-09T18:04:22.748078Z  INFO massa_network_worker::network_event::event_impl: Send network event failed curred during channel communication: Failed to send event.
Apr 09 18:04:22 ubuntu-8gb-hil-1 massa-node[3086117]: 2023-04-09T18:04:22.755691Z  WARN massa_protocol_worker::protocol_network: Node N1hMjBUeYRFduaYBcj8CG9w49dAVMd7HCaeX3tEz sent us an operation list for block id B121wBYwXykB18rz1qrB9es5ukimJaYF6SHxU6NUVg8rQ1XwALhp but we already received it.
Apr 09 18:04:22 ubuntu-8gb-hil-1 massa-node[3086117]: 2023-04-09T18:04:22.762344Z  INFO massa_network_worker::network_event::event_impl: Send network event failed curred during channel communication: Failed to send event.
Apr 09 18:04:22 ubuntu-8gb-hil-1 massa-node[3086117]: 2023-04-09T18:04:22.765697Z  INFO massa_network_worker::network_event::event_impl: Send network event failed curred during channel communication: Failed to send event.
Apr 09 18:04:22 ubuntu-8gb-hil-1 massa-node[3086117]: 2023-04-09T18:04:22.766809Z  INFO massa_network_worker::network_event::event_impl: Send network event failed curred during channel communication: Failed to send event.
Apr 09 18:04:26 ubuntu-8gb-hil-1 massa-node[3086117]: 2023-04-09T18:04:22.767899Z  INFO massa_network_worker::network_event::event_impl: Send network event failed curred during channel communication: Failed to send event.
Apr 09 18:04:26 ubuntu-8gb-hil-1 massa-node[3086117]: 2023-04-09T18:04:22.769022Z  INFO massa_network_worker::network_event::event_impl: Send network event failed curred during channel communication: Failed to send event.
Apr 09 18:04:26 ubuntu-8gb-hil-1 massa-node[3086117]: 2023-04-09T18:04:22.770151Z  INFO massa_network_worker::network_event::event_impl: Send network event failed curred during channel communication: Failed to send event.

![1](https://user-images.githubusercontent.com/93812394/230790763-66a1843e-bc06-418a-9b42-325433de383b.png)
![2](https://user-images.githubusercontent.com/93812394/230790768-abb9dd65-d50a-40ab-a0fb-fd6cc17f08ed.png)
[logs.txt](https://github.com/massalabs/massa/files/11186093/logs.txt)
[logs_massa.txt](https://github.com/massalabs/massa/files/11186095/logs_massa.txt)

If the capacity of this server is not enough, please report it.

**Comment by AurelienFT** [comment]
This has been fixed in newer versions.
