### ISSUE TITLE
Nodes charged with op crash with OOM.

### ISSUE THREAD

**Issue by AurelienFT** [massalabs/massa#3803]
Their RAM is growing more than the other nodes maybe a forget to delete some operations

**Comment by AurelienFT** [comment]
Can't reproduce in sandbox.

**Comment by AurelienFT** [comment]
The RAM is increasing (less fast) on other node while there is 0txps so there is also a problem on something else. Maybe a data structure without pruning.

**Comment by AurelienFT** [comment]
I reproduce in sandbox. I saw that this is in the API module himself. I launch a node without op everything is fine. I removed the whole code `send_operations` to just return `Ok(vec![])` but the memory still grow.

Need to find what in the API server/middleware could be the cause

**Comment by aoudiamoncef** [comment]
Very interesting, l'll investigate

I'm curious to see the result using ˋSendOperations` from gRPC API ? May be It's time to migrate...

**Comment by AurelienFT** [comment]
Yes I think I will change the script to grpc as a quick fix. But it would be nice to fix this as we don't plan on deprecating the JSON-RPC in short term.
