### ISSUE TITLE
Node desynchronisation in testnet 21

### ISSUE THREAD

**Issue by aoudiamoncef** [massalabs/massa#3807]
In the first bootstrap of testnet 21, we got some desyc issues in multiples nodes.

[logs_testnet_21.zip](https://github.com/massalabs/massa/files/11200466/logs_testnet_21.zip)

**Comment by AurelienFT** [comment]
We miss interpreted the logs with the print `CycleUnavailable`. When we see this print it's a mark of desyncronization in general but in this case the print is in the `denunciation_factory` this doesn't affect the health of the node and it's just a warning in this factory that do not interact with the rest of the code and could be ignored. I have place a message to tech ambassador also.
