### ISSUE TITLE
Versioning transfer & ideas

### ISSUE THREAD

**Issue by sydhds** [massalabs/massa#3808]
* Set proper values for network versions in block header (everything is set up but for now the versions are both set to 0).
  *  In the protocol module, handle block headers with incompatible active versions.  
* Test in labnet / testnet the transitioning of a dummy MipInfo (with Component::Dummy)
  * Would be nice to test some edge cases like bootstrapping near the various transistions
* Test a more real scenario with a MipInfo for Address or Block
  * This is the time to use the VersioningFactory trait and use it everywhere it is needed. In case addresses are versioned, testing the SC side looks a good idea too.

**Comment by AurelienFT** [comment]
Can we close this ? @sydhds @Eitu33

**Comment by Eitu33** [comment]
Yes
