### ISSUE TITLE
Buildnet unexpectedly stop

### ISSUE THREAD

**Issue by qdrn** [massalabs/massa#3837]
**Describe the bug**
At some point the buildnet stopped functionning. The processes were still running on both servers but the node was not responding anymore. In htop 2 threads were using 100% cpus. Unfortunately I don't have lvl 3 logs nor the name of the processes...

**Comment by AN09111976** [comment]
Hi, it may help: 

.[2m2023-04-18T13:49:43.957283Z.[0m .[33m WARN.[0m .[2mmassa_factory_worker::denunciation_factory.[0m.[2m:.[0m Cannot get producer from selector: `CycleUnavailable`: PoS cycle 455 is needed but is absent from cache
Could not deserialize as static object: Feature static load is not compiled in is not yet supported
thread 'execution' panicked at 'critical: module deserialization failed: incompatible binary: The provided bytes are not wasmer-universal', massa-module-cache/src/hd_cache.rs:153:84
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

**Comment by qdrn** [comment]
Hi @AN09111976 ! Were you using the buildernet ? Or the testnet ?

**Comment by AurelienFT** [comment]
Without further debug infos and now that your network is working. I'm closing this.
