### ISSUE TITLE
Deserialization failed: incompatible binary

### ISSUE THREAD

**Issue by abregand** [massalabs/massa#3838]
Hi,

It's the second time, the node crash :
"Could not deserialize as static object: Feature static load is not compiled in is not yet supported
thread 'execution' panicked at 'critical: module deserialization failed: incompatible binary: The provided bytes are not wasmer-universal', massa-module-cache/src/hd_cache.rs:153:84"

First time, on the first restart it's ok, but the second, 4 restart are necessary.. And after 3min, crash again..

![image](https://user-images.githubusercontent.com/67349221/232823192-406c4ca4-11d4-4139-bb73-29853bbf2eac.png)

**Comment by Eitu33** [comment]
It is unlikely that this issue is related to the processor, this is an internal problem. After a quick look at the logic it looks like an edge case, we will investigate if the errors spreads. Thanks for the report 👍

**Comment by qdrn** [comment]
I had the same one also:
```log
Could not deserialize as static object: Feature static load is not compiled in is not yet supported
thread 'execution' panicked at 'critical: module deserialization failed: incompatible binary: The provided bytes are not wasmer-universal', massa-module-cache/src/hd_cache.rs:153:84
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

**Comment by litchipi** [comment]
@AurelienFT @Eitu33 Any news on this ? I can assign myself to it if needed (might need a crash course around the code if you are comfortable inside it)
