### ISSUE TITLE
Change lru crate in network

### ISSUE THREAD

**Issue by AurelienFT** [massalabs/massa#3844]
Use this crate : schnellru = "0.2.1"

**Comment by litchipi** [comment]
I got some problems as `schenllru` doesn't provide any `iter_mut` or `promote` (make a key the newest used one) function.
It made a problem in `massa-protocol-worker/src/handlers/operation_handler/propagation.rs:L117` for example.
I don't really see how to work around that, and am wondering if that's a blocker for the choice of this framework over `lru` which was working fine before.
@AurelienFT your thoughts ?

**Comment by AurelienFT** [comment]
We are using the other crate in the rest of the massa and this crate doesn't allow to make `LRUSet` which forced me to make a `LRUMap` with `()` as value.
I don't know `schenllru` much maybe @Eitu33 you can help on that
