### ISSUE TITLE
Use millis with massa-time in massa-protocol

### ISSUE THREAD

**Issue by AurelienFT** [massalabs/massa#3854]
if we keep the u128 we should use .as_nano(), no ?

.as_millis() : https://doc.rust-lang.org/stable/std/time/struct.Duration.html#method.as_millis

.as_nanos() : https://doc.rust-lang.org/stable/std/time/struct.Duration.html#method.as_nanos

_Originally posted by @modship in https://github.com/massalabs/massa/pull/3840#discussion_r1175193145_

**Comment by damip** [comment]
Why are we handling time manually without going through MassaTime ?

**Comment by damip** [comment]
> We wanted to have a nano precision which is not possible. If we go for milis we can use MassaTime

Out of curiosity, why do you need nano ? (Btw nano is often rounded, imprecise or plain broken on many architectures)

**Comment by AurelienFT** [comment]
It was because we use it as an index to have less numbers of collision but maybe millis can make the job

**Comment by damip** [comment]
> It was because we use it as an index to have less numbers of collision but maybe millis can make the job

It is used as a connection ID ? A simple always-incrementing u64 can also do the trick in a cleaner way

**Comment by AurelienFT** [comment]
No not used as a connection id it's just an index to sort lasted tested peers

**Comment by AurelienFT** [comment]
Done in #3976
