### ISSUE TITLE
Benchmark Sparse Merkle Tree crates

### ISSUE THREAD

**Issue by damip** [massalabs/massa#3859]
Discussion: https://github.com/massalabs/massa/discussions/3852#discussioncomment-5708901

Task: Benchmark the following crates to see how easily/efficiently they keep track of a state hash:

* https://docs.rs/monotree/latest/monotree/
* https://docs.rs/sparse-merkle-tree/latest/sparse_merkle_tree/
* https://diem.github.io/diem/diem_jellyfish_merkle/index.html
* https://github.com/y-pakorn/cw-merkle-tree
* https://docs.rs/lsmtree/latest/lsmtree/

Benchmark parameters: speed of hash update on insertion/deletion in a BTreeMap of 1M key-value elements

**Comment by damip** [comment]
@litchipi  so this can be considered as done / closed ?

Followups for implementing it in the state should be opened @Leo-Besancon

**Comment by litchipi** [comment]
Yes I think so. I'll follow up the discussion once I have the time to discuss with @Leo-Besancon about it next week
