### ISSUE TITLE
Add support for Merkle trees 

### ISSUE THREAD

**Issue by leoloco** [massalabs/massa#3889]
**Context**
Many decentralized applications rely on some implementation of merkle tree to generate and verify proofs. At its core, merkle tree is just a concept that can be declined in various implementations; different hashing algorithm, binary or not, left or right priority, etc... Rather than each application developing its own implementation, the EVM ecosystem seems to have chosen a library maintained by OpenZeppelin as a standard. We could opt in for this option but it would improve standardization if support for merkle tree was directly added to the ABI based on the same implementation as [OpenZepplin](https://github.com/OpenZeppelin/openzeppelin-contracts/blob/master/contracts/utils/cryptography/MerkleProof.sol). Then we could easily verify proofs of trees generated with [OpenZepplin merkle tree javascript library](https://github.com/OpenZeppelin/merkle-tree) 

**Technical specification**
- `verify(proof: &[ [u8; 32] ], root: [u8; 32], leaf: [u8; 32]) -> bool`
Returns true if a `leaf` can be proved to be a part of a Merkle tree defined by `root`. For this, a `proof` must be provided, containing sibling hashes on the branch from the leaf to the root of the tree. Each pair of leaves and each pair of pre-images are assumed to be sorted.
- `processProof(proof: &[ [u8; 32] ], leaf: [u8; 32]) -> [u8; 32]`
Returns the rebuilt hash obtained by traversing a Merkle tree up from `leaf` using `proof`. A `proof` is valid if and only if the rebuilt hash matches the root of the tree. When processing the proof, the pairs of leafs & pre-images are assumed to be sorted.
- `multiProofVerify(proof: &[ [u8; 32] ], proofFlags: &[bool], root: [u8; 32], leaves: &[ [u8; 32] ]) -> bool`
Returns true if the `leaves` can be simultaneously proven to be a part of a merkle tree defined by `root`, according to `proof` and `proofFlags` as described in {processMultiProof}.
- `processMultiProof(proof: &[ [u8; 32] ], proofFlags: &[bool], leaves: &[ [u8; 32] ]) -> [u8; 32]`
Returns the root of a tree reconstructed from `leaves` and sibling nodes in `proof`. The reconstruction proceeds by incrementally reconstructing all inner nodes by combining a leaf/inner node with either another leaf/inner node or a proof sibling node, depending on whether each `proofFlags` item is true or false respectively.
CAUTION: Not all merkle trees admit multiproofs. To use multiproofs, it is sufficient to ensure that: 1) the tree is complete (but not necessarily perfect), 2) the leaves to be proven are in the opposite order they are in the tree (i.e., as seen from right to left starting at the deepest layer and continuing at the next layer).
- `_hashPair(a: [u8; 32], b: [u8; 32]) -> [u8; 32]`
Returns the keccak256 hash of the concatenation of a and b, with a and b in ascending order, e.g, ```if a<b return keccak256(concat(a,b)) else return keccak256(concat(b,a))  ```

**Comment by AurelienFT** [comment]
Hello,
Can you edit the default template to provide us more informations about your ABI request please :)

**Comment by leoloco** [comment]
I've updated the technical spec and context.

**Comment by damip** [comment]
I think that we shouldn't hardcode it in the node, but make a smart contract lib that does the merkle tree stuff.
What should be added to the node tho is: https://github.com/massalabs/massa/issues/3897

**Comment by damip** [comment]
keccas256 support was absorbed here: https://github.com/massalabs/massa-sc-runtime/issues/246

The merkle tree verification should be done in SC
