### ISSUE TITLE
Bootstrap when a lot of block missing

### ISSUE THREAD

**Issue by AurelienFT** [massalabs/massa#3893]
In this case this kind of print appears : 
```
[2m2023-04-29T07:09:06.432449Z[0m [34mDEBUG[0m [2mmassa_bootstrap::server[0m[2m:[0m bootstrap serving error for peer 149.202.84.7:41596: `massa_consensus` error: there was an inconsistency between containers block B12ADqdNjJh1i2dJarEW12xCAAt1bTTQKcMxCSbF2nYEXs5eyG62 is missing
```

Bootstrap should work and no errors should be posted.

We can test by launching a labnet and disconnect one of the node then half of the block will be missing and we will reproduce

**Comment by Ben-PH** [comment]
The log appears to come from `massa-consensus-worker/src/state/mod.rs` use of `ConsensusState` method `try_get_full_active_block`, which itself, appears to only be used in that same file.

it's used by 
- `list_latest_final_blocks_at`
- `list_earliest_blocks_of`
- `list_required_active_blocks`

**Comment by AurelienFT** [comment]
You can reproduce this bug by launching a labnet kill one node (so that half of the blocks are missing) wait a bit and try to bootstrap.

**Comment by AurelienFT** [comment]
Done in https://github.com/massalabs/massa/pull/4007
