### ISSUE TITLE
get_status network stats counter bug

### ISSUE THREAD

**Issue by modship** [massalabs/massa#3894]
When node disconnect, the counter doesn't decrease (maybe some other case). 

** `In connections` stay at : 1 on the screen but node has left.
![Capture d’écran 2023-05-03 à 11 53 44](https://user-images.githubusercontent.com/9607217/235886322-580b1b7a-799d-47d4-b84d-becb01e0e55f.png)

**Comment by AurelienFT** [comment]
It has been fixed now @modship  ?

**Comment by modship** [comment]
> It has been fixed now @modship  ? We fixed this together last week no ?

Yes i think
