### ISSUE TITLE
Add support for keccak256

### ISSUE THREAD

**Issue by leoloco** [massalabs/massa#3897]
**Technical specification**
Related to [this issue](https://github.com/massalabs/massa/issues/3889)

-   ABI on massa-sc-runtime side :  `keccak256(bytes: &[u8]) -> &[u8]`
-   Behavior of the function: Computing the keccak256 of the passed parameter and return the hash as a byte array.

**Related pull request links**
-   massa-sc-runtime:
-   massa-as-sdk:
-   massa-web3:

**Comment by damip** [comment]
Could we group this with the work on refactoring the ABIs in wasmv1 runtime @bilboquet and aim for the next testnet ?

**Comment by damip** [comment]
Absorbed here: https://github.com/massalabs/massa-sc-runtime/issues/246
