### ISSUE TITLE
No routable IP set > V TEST .22.0

### ISSUE THREAD

**Issue by Azazel020** [massalabs/massa#3913]
**Describe the bug**

The command wallet_info shows below the NodeID > No routable IP is set  but all variables are there, see screenshot.

Ports are open en checked

**To Reproduce**
- Open client  >> wallet_info

**Screenshots**
See attachment

**Desktop (please complete the following information):**

- Ubuntu  (VPS/Contabo)

**Comment by Azazel020** [comment]
![Massa_no_routable_ip](https://user-images.githubusercontent.com/44430967/236552798-680d807c-1932-42b2-95d7-d107f9e52e57.png)

**Comment by AurelienFT** [comment]
Your file should change the file config.toml to use [protocol] instead of [network] it has been updated in the doc : https://docs.massa.net/en/latest/testnet/routability.html

**Comment by Azazel020** [comment]
Changed the config to [protocol] and rebooted the service. Problem solved!

**Comment by Azazel020** [comment]
Changed the config to [protocol] and rebooted the service. Problem solved!
