### ISSUE TITLE
Error messages of BootstrapError are not informative

### ISSUE THREAD

**Issue by damip** [massalabs/massa#3927]
The DisplayDoc crate is in use, but many doc comments look like "    /// all io errors except for Timedout, and would-block (unix error when timed out)". So it ends up displaying random code comments instead of errors, it also forgets displaying the underlying error.

Use the format "IO Error: {0}" instead

**Comment by Ben-PH** [comment]
#3746

**Comment by Ben-PH** [comment]
https://github.com/massalabs/massa/pull/3931/files#diff-5b38096b65a4c50b6d1e84b4fd10b58ee3d1d380b40eb15e2c40ea7abf18b09d
