### ISSUE TITLE
thread 'consensus worker' panicked at 'missing object in storage on storage object reference drop',

### ISSUE THREAD

**Issue by yatsvic** [massalabs/massa#3952]
**Describe the bug**
I see my node crashed.
The message from log is:
```
may 15 23:15:10 chuck run-validator.sh[1386306]: thread 'consensus worker' panicked at 'missing object in storage on storage object reference drop', massa-storage/src/lib.rs:352:21
```

**To Reproduce**
Just to run node.

**Expected behavior**
Node expected to work fine.

**Desktop (please complete the following information):**
- Ubuntu 20.04, Linux 5.9.16-050916-generic x86_64

**Comment by modship** [comment]
panic when consensus_state.prune_active() call  `storage.drop_operation_refs(&storage.get_op_refs().clone())`

What to do @AurelienFT  ?

**Comment by AurelienFT** [comment]
That should never happens that's why there is a except. But as it's in consensus maybe it's complicated to dive in. If you want you can or take something else as you want just don't feel stuck :)

**Comment by yatsvic** [comment]
I recently detected RAM problem. It was floating issue with timings, hard to detect even via memtest. 
So I had to increase RAM timings for stability. 
I think this issue is definitely due to RAM problem. Should be closed.
