### ISSUE TITLE
Port 31244 temporaly closed

### ISSUE THREAD

**Issue by abregand** [massalabs/massa#3958]
Port **31244** is opened _or sometimes closed_ at startup, if port is open, after several hours port is closed.

Why port is closed sometimes ?

![image](https://github.com/massalabs/massa/assets/67349221/1afa6a68-72bf-421f-8f2f-300b77e04fb0)

Version 22.2

**Comment by Ben-PH** [comment]
31244 is used to bootstrap, and is the listener for incoming peers.


Some questions to help clarify:


- Is your system configured for bootstrapping? 
- What OS are you running on?
- If configured for bootstrapping, are you noticing any unexpected behavior with respect to providing the bootstrapping service?

**Comment by abregand** [comment]
**Is your system configured for bootstrapping?**

- Yes, node is routable with IPv6 address, and works.
Actually, 6IN & 10OUT.


**What OS are you running on?**

- Linux debian-8gb-fsn1-1 5.10.0-22-arm64 on Hetzner Cloud Server

**If configured for bootstrapping, are you noticing any unexpected behavior with respect to providing the bootstrapping service?**

- Only **INFO** in logs. Works normaly.

**Comment by Ben-PH** [comment]
Thank you for that information. Having a look into it now. Will keep you updated on anything learned. If you notice any behavior that could relate, even if it's highly unlikely, that would be helpful.

Also, thanks heaps for bringing this up.

**Comment by Ben-PH** [comment]
thanks for the broken-pipe logs. That's typically due to the connection being closed on the other side. This could be a bug in the system, or it could be external to the code base causing the closure.

Two questions, the first one is important, the second one, feel free to ignore.

- Following these error-logs, does your system stop bootstrapping clients successfully? I'd like to check my hypothesis that it's strictly per-connection, as opposed to the listening system.
- Do you have any "gut-feeling" about whether or not these pipes are broken due to situations outside/inside the codebase?

**Comment by Ben-PH** [comment]
I think I might have found a fix for you. Are you comfortable with compiling from source? If you build from commit 570ce4678788f012ad47ad6ce1106f0de649b732, that might sort you out. If you use discord, you can reach out to me: Hawkey#5212 and I can help walk you through the process.

**Comment by Ben-PH** [comment]
There will be a 22.3 release coming out shortly, which will include the fixes in that commit.

**Comment by abregand** [comment]
> thanks for the broken-pipe logs. That's typically due to the connection being closed on the other side. This could be a bug in the system, or it could be external to the code base causing the closure.
> 
> Two questions, the first one is important, the second one, feel free to ignore.
> 
> * Following these error-logs, does your system stop bootstrapping clients successfully? I'd like to check my hypothesis that it's strictly per-connection, as opposed to the listening system.
> * Do you have any "gut-feeling" about whether or not these pipes are broken due to situations outside/inside the codebase?

Following these error-logs, `massa_protocol_worker::handlers::peer_handler: Peer connected` does not appeared again.
Only testing info like `INFO massa_protocol_worker::handlers::peer_handler::tester: testing peer P1gEdBVEbRFbBxBtrjcTDDK9JPbJFDay27uiJRE3vmbFAFDKNh7 listener addr: 54.36.174.177:31244`

My logs : https://gist.github.com/abregand/9e66abf421f05c6d19d01541142241f2

**Comment by abregand** [comment]
> I think I might have found a fix for you. Are you comfortable with compiling from source? If you build from commit [570ce46](https://github.com/massalabs/massa/commit/570ce4678788f012ad47ad6ce1106f0de649b732), that might sort you out. If you use discord, you can reach out to me: Hawkey#5212 and I can help walk you through the process.

I'll try when I have some time, thanks.

**Comment by abregand** [comment]
> I think I might have found a fix for you. Are you comfortable with compiling from source? If you build from commit [570ce46](https://github.com/massalabs/massa/commit/570ce4678788f012ad47ad6ce1106f0de649b732), that might sort you out. If you use discord, you can reach out to me: Hawkey#5212 and I can help walk you through the process.

With commit [570ce46] it's ok, the port is open.
If port close again, I tell you back.

**Comment by Ben-PH** [comment]
Awesome.

Thanks for the report, I'll keep this issue open for the time being, just in case you have any more issues, but if I haven't heard from you in some time, I'll close it then.

**Comment by AurelienFT** [comment]
Just to clarify a bit, 31244 is only used for network it'd 31245 that is use for bootstrap

**Comment by abregand** [comment]
Port closed again (~06:31) but no error just warn in logs.

`May 17 06:30:10 debian-8gb-fsn1-1 sh[1216593]: 2023-05-17T04:30:10.985195Z  WARN massa_protocol_worker::handlers::peer_handler: Failed to send message: Location: send data write `

**Comment by AurelienFT** [comment]
We are missing logs on the left and above please can you include the fist lin fully and some lines above please

**Comment by abregand** [comment]
Logs : https://gist.github.com/abregand/0014bfacf2d8019b7db2c13e9c7169b6

**Comment by AurelienFT** [comment]
Really strange it seems to you are stuck with two peers. It's complicated to debug with only those logs. We will try to reproduce. In the meantime, does it affect the health of your node ?

**Comment by abregand** [comment]
I restarted.
No, node works.

**Comment by AurelienFT** [comment]
Ok nice let it run then we will try to reproduce in the following weeks.

**Comment by abregand** [comment]
OK, currently, port 31244 does not close and node works perfectly.

Good job!
