### ISSUE TITLE
Use array in grpc

### ISSUE THREAD

**Issue by AurelienFT** [massalabs/massa#3965]
Using an array is a cheap way to get the flexibility and avoid breaking changes. In production, any detail counts:
```
data.status == "FINAL" (enum approach)
data.status.contains("FINAL")
data.status.containsOneOf("FAILED", "SCHEDULED")
```

As you can see, our approach doesn't introduce any additional complexity, but It adds more features.

_Originally posted by @aoudiamoncef in https://github.com/massalabs/massa/pull/3934#discussion_r1196491857_
            

I understand what you mean. I'm saying that this thinking could be applied to any other field in the API and in state changes. Multiple fee, multiple recipient,... But we will not do that because maybe we will never need multiple value in this field. So why applying this rule of array to status field ? @aoudiamoncef

**Comment by AurelienFT** [comment]
poke @aoudiamoncef

**Comment by aoudiamoncef** [comment]
**This design is opinionated** 

The operation status should be flexible, attaching multiple tags to an operation is fluent
