### ISSUE TITLE
testnet 23 objects format changes

### ISSUE THREAD

**Issue by Eitu33** [massalabs/massa#3988]
## Context

Testnet 23 introduces the first versioned objects, therefore involving some format changes in the bytes representations.

Feel free to ask questions in the discussion following this issue.

### Address

String (same): `A` + `U / S` + base58Check(`version_bytes` + `addr_hash_bytes`) 
Bytes (diff): `version_bytes` + `addr_hash_bytes` previously `addr_hash_bytes`

### Public Key

String (same): `P` +  base58Check(`version_bytes` + `key_hash_bytes`)
Bytes (diff): `version_bytes` + `key_hash_bytes` previously `key_hash_bytes`

### Secret Key

String (same): `S` +  base58Check(`version_bytes` + `key_hash_bytes`)
Bytes (diff): `version_bytes` + `key_hash_bytes` previously `key_hash_bytes`

### Signature

String (diff):  base58Check(`version_bytes` + `sig_hash_bytes`) previously base58Check(`sig_hash_bytes`) 
Bytes (diff): `version_bytes` + `sig_hash_bytes` previously `sig_hash_bytes`

### Notes

The objects that were of length 32 before the update are now of len 33 **BUT** that is not fixed as the version bytes are serialized as VarInt and will take more space as we go up in versions.

Because Public Keys bytes representation has changed, they do not result in the same addresses after a derive, please update your addresses.

**Comment by AurelienFT** [comment]
@massalabs/run Can you propagate this changes to modules like massa-web3 ?

**Comment by AurelienFT** [comment]
Closing but can still be used as a temporary doc
