### ISSUE TITLE
Create internal monitoring infrastructure

### ISSUE THREAD

**Issue by AurelienFT** [massalabs/massa#4006]
## Context

We want to have some statistics on the internal structures of massa. We can use prometheus exporters to save the content of the internal data and follow their evolution across the time

## TODO

Here is two first things that we can monitor :

- [ ] Create a `massa-channel` module that wrap the crossbeam channel but also export the size of the channel often (when receiving for example or at a certain interval)
- [ ] Monitor the `massa-storage` module to have his number of blocks, ops and endorsements stored displayed often (when reading or at a certain interval)

It would be nice to setup a grafana architecture to view those stats. Maybe we can take example from https://github.com/massalabs/sre-scripts/pull/2

**Comment by AurelienFT** [comment]
@modship We must add a monitoring on more system things like connection : https://github.com/massalabs/massa/issues/2404#issuecomment-1576447075

We must also add infos about the slot of the active execution cursor and the final one in execution and consensus

**Comment by damip** [comment]
Here are some important things to monitor:
* network bandwidth p/down (alert if too low or too high)
* number of active connections (alert if 0 for more than 1 min)
* avg time between when we added a block to the graph vs the timestamp of the block's slot
* execution final cursor
* execution speculative cursor

**Comment by AurelienFT** [comment]
@damip I think there is some kind of mix that is done there. We add monitoring on channels all across the code, storage etc.. That is done only if we compile a node with a certain feature and then we can use this metrics within a prometheus or whatever.

We can of course make a little thread on the node that will parse these metrics and display logs of error in kind of specific conditions the thing is that I don't think we want to everyone run the metrics on the channels storage etc..

So maybe we need to make two levels of metrics the user ones that will be always there and the advanced ones that is only for internal tests/debug/opti ?
