### ISSUE TITLE
Consensus - Encapsulate the state machine into a separate structure

### ISSUE THREAD

**Issue by AurelienFT** [massalabs/massa#4018]
Maybe in the future we should encapsulate the state machine into a separate structure that only allows certain transitions and automatically manages the indexes, in order to robustify things because it's very brittle right now

_Originally posted by @damip in https://github.com/massalabs/massa/pull/4015#pullrequestreview-1455490724_

**Comment by damip** [comment]
Upgrading to P1 because of external audit timings dependency

**Comment by AurelienFT** [comment]
Done in https://github.com/massalabs/massa/pull/4162
