### ISSUE TITLE
Add `serialized_size` field to `SecureShares` in APIs 

### ISSUE THREAD

**Issue by aoudiamoncef** [massalabs/massa#4019]
This will help us to know the size in bytes of Operations, Endorsements and Blocks. 

Currently, we have a method which calculates size on fly:
```rust
    /// get full serialized size
    pub fn serialized_size(&self) -> usize {
        self.serialized_data
            .len()
            .saturating_add(self.signature.get_ser_len())
            .saturating_add(self.content_creator_pub_key.get_ser_len())
    }
```

cc @longgamma-massa

**Comment by aoudiamoncef** [comment]
@damip what do you think about it ?

**Comment by damip** [comment]
Where do we need it ?

Intuitively, we need to use it *very* often to justify adding it as a field in RAM VS just recomputing when needed

**Comment by damip** [comment]
@aoudiamoncef  Can it be computed on the fly to be added to the returned GRPC/API objects instead of being kept in the native object in RAM ?
