### ISSUE TITLE
Time to exectution feature for Explorer

### ISSUE THREAD

**Issue by longgamma-massa** [massalabs/massa#4023]
**Is your feature request related to a problem? Please describe.**
Massa blockchain is super fast and because of it can be used for various high-tx-throughput usecases. For the Explorer's scope for the Mainnet, we want to add a feature on the Main Dashboard of the explorer's website: Time to execution. 

**Describe the solution you'd like**
This feature should show how it's very fast to execute operation on Massa. 

For this we would like to measure the period (in seconds or milliseconds) between:
a) Operation propagation time (standard name across chains is Operation timestamp) - the time Op was first seen in the pool.
b) time when Op was first included in a block (executed) - this timestamp should NOT include time to finality.

**Describe alternatives you've considered**
Time to finality  - not very informative because Massa finalizes blocks super fast and does not show the execution power (speed and capacity to process operations) that we want to show.

**Additional context**

Operation timestamp feature issue #3207

**Comment by AurelienFT** [comment]
Hello,

You can register to the websocket for new operations in the node and subscribe to the one for full block and so you can have the time between this two events which correspond to you "a" and "b"

**Comment by longgamma-massa** [comment]
we can close this issue @AurelienFT
