### ISSUE TITLE
Get Address API endpoint enhancements

### ISSUE THREAD

**Issue by longgamma-massa** [massalabs/massa#4024]
**Is your feature request related to a problem? Please describe.**
To show interesting and useful features for Address object in the Explorer, we'd like the following indicators added to the API:

- instead of current cycle property, add Creation Cycle (cycle in which an Address was created)
- For SC address types:
a) add the address hash that deployed (created) this contract - Creator address
b) add the op hash that deployed this contract - Creation operation

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by AurelienFT** [comment]
@damip this is not possible regarding the low amount of informations we keep when we delete the blocks ?
