### ISSUE TITLE
Token transfers (deltas) per SC-operation type

### ISSUE THREAD

**Issue by longgamma-massa** [massalabs/massa#4025]
**Is your feature request related to a problem? Please describe.**
CallSC and ExecuteSC operations are currently limited in the scope to show only transfers of value in MAS (value transferred property).

For a user of a DEX or any other protocol application on Massa blockchain, it is important to verify that indeed he accomplished a swap, or a transfer of FTs or NFTs, using the explorer interface as a go-to website for verifying info on Massa blockchain. 

**Main usecase:**
Alice performed a swap between 50 MAS coin to 100 USDT (FT token on Massa). 
How it works:
1. Alice to DEXs proxy contract -> 50 MAS
2. DEXs proxy contract issues wrapped MAS token which is sent to the other SC proxy contract of a DEX: SC1 to SC2 -> 50 wrapped MAS
3. DEX SC2 to Alice -> 100 USDT

In case of Token:Token swap it works similarly but without wrapping.

The Need:
List all transfers that occurred per operation (MAS coin, FT, or NFT) so we can show it to user in the needed format:
- token name and symbol
- From
- To
- Value transferred a)for MAS coin and NFT will be in MAS coin, b) for  Fungible Token transfers will be in FT value

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by longgamma-massa** [comment]
Ping me for UI design if you need it

**Comment by damip** [comment]
Technical translation: Save the call trees and state changes caused by every operation and provide them in the execution stream

**Comment by damip** [comment]
@longgamma-massa after studying the requirements, and the surrounding priorities, we have found that we cannot implement saving per-op changes/call trees before the mainnet. So let's keep things as simple as possible

**Comment by AurelienFT** [comment]
Done in execution-trace/transfers for CEXs
