### ISSUE TITLE
Calls tree per SC-operation type (internal transactions)

### ISSUE THREAD

**Issue by longgamma-massa** [massalabs/massa#4026]
**Is your feature request related to a problem? Please describe.**
Explorer's interface should show all read and write Calls made per operation (Call SC and Execute SC), in order for SC-developers to validate the functionality of their SCs on a deeper level (notion of cascade calls), and discover issues in functionality.

**Describe the solution you'd like**
Example on Blockchair - click on 'Calls included' tab: https://blockchair.com/ethereum/transaction/0x4a1a06d1a1e20dc1b936b8d898d71b47224312cb623fc4098af1cda2c0e17915

Data needed:
- call fn name
- invoked addresses 
- invoked calls of other contracts and invoked functions (this is a nice-to-have feature)
- Notion of stopped execution of an Operation, at a specific call (if applicable)

As a start I suggest listing all first-level calls and function names, without cascade option (calls of SC1 making calls on other SC)

Scope:
Both read and write calls

**Describe alternatives you've considered**

**Additional context**

**Comment by AurelienFT** [comment]
Don in exeuction-trace
