### ISSUE TITLE
Add acceptance of local addresses in categories

### ISSUE THREAD

**Issue by AurelienFT** [massalabs/massa#4035]
In categories we can remove the pre and post handshake nb_connections as it's not used anymore. We also need to add a boolean on the peer category setup to accept local addresses to connect to us.

**Comment by litchipi** [comment]
The `max_in_connections_post_handshake` value seams still used inside PeerNet, so we can't remove it without a refactor in PeerNet.
Inside `check_addr_accepted_pre_handshake` the value `max_in_connections_post_handshake` is used, is it intended ?

Right now I don't see any check about if an IP is local or not, so I guess we accept them by default. So the local address allowance is more a `add config flag to refuse local addr` ?

**Comment by AurelienFT** [comment]
> The max_in_connections_post_handshake value seams still used inside PeerNet, so we can't remove it without a refactor in PeerNet.
Inside check_addr_accepted_pre_handshake the value max_in_connections_post_handshake is used, is it intended ?

In fact that just old code that has been kept to more easily deploy a code that is working during a weekend. As there is no more real usage  of `max_in_connections_pre_handshake` `max_in_connections_post_handshake` should be renamed to `max_in_connections`

We don't accept them by default because we have a bunch of `is_global()` in massa. You can check the commit in massa in the branch `flag_private_addresses` that contains an updated version with a feature flag that I made for Arshavee and her simulator.

**Comment by AurelienFT** [comment]
Done in https://github.com/massalabs/massa/pull/4116
