### ISSUE TITLE
Address string parsing incorrect

### ISSUE THREAD

**Issue by damip** [massalabs/massa#4043]
In string deserialization

```rust
        let err = Err(ModelsError::AddressParseError(s.to_string()));

        // Handle the prefix ("A{U|S}")
        let mut chars = s.chars();
        let Some(ADDRESS_PREFIX) = chars.next() else {
            return err;
        };
        let Some(pref) = chars.next() else {
            return err;
        };

        let res = match pref {
            'U' => Address::User(UserAddress::from_str_without_prefixed_type(&s[2..])?),
            'S' => Address::SC(SCAddress::from_str_without_prefixed_type(&s[2..])?),
            _ => return err,
        };
```

This is dangerous and could be used by an attacker to crash the node.

Explanation:
```rust
// the following code panics
fn main() {
 let s: &str = "🫱💣";
 println!("s[1..] = {}", &s[1..]);
}
```
the code panics because there is a fundamental difference between characters and bytes: utf-8 characters are composed of a variable number of bytes. You can get the indices of characters using https://doc.rust-lang.org/std/primitive.str.html#method.char_indices 
The crash happens because `&str` always needs to be a valid string. And by doing `s[1..]` we are cutting the first character 🫱 (4 bytes) in the middle and it results in an invalid string.

To remember: you should basically never use the `s[i]`notation for strings unless you know exactly what you are doing !

So we can do the following instead:
```rust
        let err = Err(ModelsError::AddressParseError(s.to_string()));

        // Handle the prefix ("A{U|S}")
        let mut chars = s.chars();
        let Some(ADDRESS_PREFIX) = chars.next() else {
            return err;
        };
        let Some(pref) = chars.next() else {
            return err;
        };

        let res = match pref {
            'U' => Address::User(UserAddress::from_str_without_prefixed_type(chars.as_str())?),
            'S' => Address::SC(SCAddress::from_str_without_prefixed_type(chars.as_str())?),
            _ => return err,
        };
```

TODO: similar problems for other strucutres like public key etc... and maybe other parts using strings

**Comment by Ben-PH** [comment]
this ripgrep ~~will~~ should find all instances of array-indexing in our codebase, excluding the ones in test-files (exclusion done by the glob)

`rg '\[\d+\]' -g '*.rs' --glob '!*test*'`

From a quick, casual search, i couldn't find a lint that warns of array-indexing.

This might be something worth putting into the style-guide. @damip Do you want to lead/open the discussion? happy to open a discussion myself and link back to here otherwise.

**Comment by AurelienFT** [comment]
Fixed by https://github.com/massalabs/massa/pull/4076

**Comment by damip** [comment]
Can we double check if the problem is present elsewhere ? (eg. public key, private key etc..)

**Comment by AurelienFT** [comment]
Regarding [this comment](https://github.com/massalabs/massa/issues/4043#issuecomment-1578758649) and [this one](https://github.com/massalabs/massa/pull/4076#issue-1754430879) it has been checked by 2 dev I think we can close this.
