### ISSUE TITLE
Node crashed with message: Corruption: File Too Small (Node version 23)

### ISSUE THREAD

**Issue by ciasis** [massalabs/massa#4047]
**Describe the bug**
Please refer to the screenshot below, I can't describe the bug. It only says: Corruption: file too small

**To Reproduce**
My node randomly crashed after some time after I compiled the new node version 23.

**Expected behavior**
It runs smoothly.

**Screenshots**
![image_2023-06-06_09-38-07](https://github.com/massalabs/massa/assets/50784424/6450a72f-a055-45c9-9fce-4be3ca22f3fc)

**Desktop (please complete the following information):**

- VPS with Ubuntu 20.04

**Additional context**

**Comment by AurelienFT** [comment]
Closing as it hasn't been reproduced in the latest testnets
