### ISSUE TITLE
Obtain ledger statistics

### ISSUE THREAD

**Issue by damip** [massalabs/massa#4048]
Have an API endpoint allowing to get:
* total number of addresses
* total supply of MASSA

This might require adding those counters as state entries as well to avoid having to scan the whole ledger for them

**Comment by AurelienFT** [comment]
Ping @mod

**Comment by aoudiamoncef** [comment]
Cc @modship

**Comment by AurelienFT** [comment]
This is not related to monitoring. And I think should be discuss. To we want to save this information of supply of massa always ? it could add a lot of complexity to the node.

**Comment by aoudiamoncef** [comment]
This infos should be persisted. Why not save this informations in the ledger directly. But It'll lead to additional complexity

**Comment by damip** [comment]
Yes it will add complexity because it needs to be maintained, recomputed at bootstrap, and saved in the ledger... blocking for now

**Comment by AurelienFT** [comment]
This can be done using separate projects to read the ledger. @Leo-Besancon made a script externally, closing this.
