### ISSUE TITLE
Disable block and endorsement production when we have 0 connections 

### ISSUE THREAD

**Issue by damip** [massalabs/massa#4052]
Disable block and endorsement production when our node is not connected to any other nodes. This prevents our node from finalizing its own blocks when it loses connection. Also emit warnings to say that a block/endorsement production was skipped for lack of connectivity

This should be a config parameter.
It should be disabled for nodes that run as initial bootstrap (they can be initially alone in the network) as well as sandbox

**Comment by AurelienFT** [comment]
Fix in #4151
