### ISSUE TITLE
Accept messages instead in addition of `SecureShares` in gRPC API

### ISSUE THREAD

**Issue by aoudiamoncef** [massalabs/massa#4063]
Currently, for `SendOperations` we accept only `SecureShares` as parameter, this imply that the client should know how to serialise `Operations` which could be avoided only by accepting a `protobuf` message as parameter: 

Actual:
```proto
// SendOperationsRequest holds parameters to SendOperations
message SendOperationsRequest {
  // Request id
  string id = 1;
  // Secured shared operations
  repeated massa.model.v1.SecureShare operations = 2;
}
```
Expected:
```proto
// SendOperationsRequest holds parameters to SendOperations
message SendOperationsRequest {
  // Request id
  string id = 1;
  oneof message {
  // Operations
  repeated massa.model.v1.Operations operations = 1;
  // Secured shared operations
  repeated massa.model.v1.SecureShare secure_shares_ops = 2;
  }
}
```

Or accept both:
```proto
// SendOperationsRequest holds parameters to SendOperations
message SendOperationsRequest {
  // Request id
  string id = 1;
  // Operations
  repeated massa.model.v1.Operations operations = 1;
  // Secured shared operations
  repeated massa.model.v1.SecureShare secure_shares_ops = 2;
}
```

**Comment by aoudiamoncef** [comment]
@damip we need your help for this one

**Comment by damip** [comment]
The client needs to be able to sign the operation they created. To do that they need to hash the protocol binary representation of the op. For now those two representations are not unified (we can discuss doing it later by switching all serializations to protobuf). But for now we just take a pure "bytes" representation of the operation

**Comment by aoudiamoncef** [comment]
We could invert this issue. what about making it possible to return `SecureShares` ? the user could choose the output format.

**Comment by aoudiamoncef** [comment]
This issue was solved by using binary format instead of `SecureShare`
