### ISSUE TITLE
node_ start/stop _staking does not check args

### ISSUE THREAD

**Issue by thibault-ketterer** [massalabs/massa#4069]
**Describe the bug**
there is no arg check on
- node_start_staking
- node_stop_staking
are not giving a warning when call with no arguments, which can lead to misleading information

(I lost 5 days of rewards + 5 reinstall and reboot because of this)

**To Reproduce**

1. call `node_start_staking` with no argument
2. it gives "Keys successfully added1"

**Expected behavior**
like send_ transaction
![image](https://github.com/massalabs/massa/assets/4283686/27d6fc04-dac2-40f5-9618-66c7d5b351de)

**Screenshots**
![image](https://github.com/massalabs/massa/assets/4283686/e3b998b3-6fad-4a93-9e3f-48a386e672db)

**Desktop (please complete the following information):**
- OS: [ubuntu LTS 22]
- Browser [/]
- Version [TEST.23.1]

**Smartphone (please complete the following information):**
- Device: [Linux]
- OS: [ubuntu LTS 22]
- Browser [/]
- Version [TEST.23.1]

**Additional context**

**Comment by thibault-ketterer** [comment]
same thing for (no args number check)
- wallet_get_public_key
- wallet_get_secret_key
- wallet_add_secret_keys
- wallet_remove_addresses

**Comment by thibault-ketterer** [comment]
I've submitted this PR to fix all this
https://github.com/massalabs/massa/pull/4070

**Comment by AurelienFT** [comment]
Hello, 

Thanks a lot for your great contribution. Very appreciate !
