### ISSUE TITLE
Error in read only call deserialize module fail

### ISSUE THREAD

**Issue by AurelienFT** [massalabs/massa#4081]
```
RequestWithResponseSender { request: ReadOnlyExecutionRequest { max_gas: 1000000, call_stack: [ExecutionStackElement { address: AU1avoFNgYmRUvnPFJcWgYf1ZRmtb4YMbpyVWtQHYoVX32grCKtC, coins: 0, owned_addresses: [AU1avoFNgYmRUvnPFJcWgYf1ZRmtb4YMbpyVWtQHYoVX32grCKtC], operation_datastore: None }, ExecutionStackElement { address: AS12NXR6BMGUeizRPDDZQRKH7E5gPZk9BtRKa9TbD8omNzDhER5cM, coins: 0, owned_addresses: [AS12NXR6BMGUeizRPDDZQRKH7E5gPZk9BtRKa9TbD8omNzDhER5cM], operation_datastore: None }], target: FunctionCall { target_addr: AS12NXR6BMGUeizRPDDZQRKH7E5gPZk9BtRKa9TbD8omNzDhER5cM, target_func: "allowance", parameter: [53, 0, 0, 0, 65, 85, 49, 50, 65, 97, 55, 78, 119, 87, 105, 68, 115, 84, 66, 83, 115, 90, 66, 116, 100, 74, 65, 53, 66, 87, 66, 54, 97, 117, 120, 83, 51, 72, 81, 78, 98, 122, 82, 86, 106, 67, 122, 115, 99, 116, 86, 65, 114, 86, 98, 56, 52, 53, 0, 0, 0, 65, 83, 49, 50, 78, 70, 87, 75, 81, 68, 116, 78, 112, 122, 71, 76, 84, 65, 53, 49, 119, 54, 90, 68, 90, 117, 74, 116, 83, 82, 98, 82, 100, 97, 70, 80, 78, 72, 120, 56, 85, 80, 57, 89, 72, 80, 99, 117, 78, 121, 52, 65, 97] }, is_final: false }, response_tx: Sender { .. } }]
Could not deserialize as static object: Feature static load is not compiled in is not yet supported
thread 'execution' panicked at 'critical: module deserialization failed: incompatible binary: The provided bytes are not wasmer-universal', massa-module-cache/src/hd_cache.rs:153:84
```

This error come when wasmer try to deserialize : https://github.com/wasmerio/wasmer/blob/2904171d1d4c1fc56ed859732c5fafdc49cdb5d7/lib/compiler/src/engine/artifact.rs#L154
They call [`ArtifactBuild::is_deserializable`](https://github.com/wasmerio/wasmer/blob/4bf34da06f8f98f2f3b0b41c620bc375e99e8ee1/lib/compiler/src/artifact_builders/artifact_builder.rs#L35) which check for the magic number that should be here if we serialized the module using their function.
If it don't find it it tries a serializing that is available only if we use a feature that we use.

The problem is why we don't have the magic number as we are serializing it using this [`serialize`](https://github.com/wasmerio/wasmer/blob/4bf34da06f8f98f2f3b0b41c620bc375e99e8ee1/lib/compiler/src/artifact_builders/artifact_builder.rs#L35) (that is wrapped to `module.serialize()`) and that should serialize with the magic number. We need to see what is inside the cache

**Comment by damip** [comment]
* we need to make sure we clear the HD cache at launch

**Comment by damip** [comment]
```rust
    /// Serialize a RuntimeModule, prepending its byte id
    pub fn serialize(&self) -> Result<Vec<u8>> {
        let (mut ser, id) = match self {
            RuntimeModule::ASModule(module) => (module.serialize()?, RuntimeModuleId::ASModuleId),
            RuntimeModule::WasmV1Module(module) => {
                (module.serialize(), RuntimeModuleId::WasmV1ModuleId)
            }
        };

        // CHECK: as we know the size before hand, maybe we can put the id at the end of the
        // vector, this would prevent a memmove
        ser.insert(0, id as u8);

        Ok(ser)
    }
```

why is the prefix hardcoded to 0 ? shouldn't it depend on the version (AsModule vs WasmV1) ?

**Comment by damip** [comment]
> No 0 is the position in the vector not the value. The value is the second parameter

oops

**Comment by AurelienFT** [comment]
Don't forget that this bug comes from the code of testnet 21.

**Comment by damip** [comment]
> Don't forget that this bug comes from the code of testnet 21.

yes, we should also try with 23

**Comment by AurelienFT** [comment]
In this testnet 21 we didn't had the clear of the HD at launch it has been added in 22.

**Comment by AurelienFT** [comment]
After some checks it seems that it's the right version of massa-sc-runtime that has been used. I'm creating a project to test the cache and what's inside.

**Comment by AurelienFT** [comment]
There is an empty module marked as invalid in the cache

**Comment by AurelienFT** [comment]
Conclusion: After diving in the cache, I found an empty module it shouldn't be there and even if it there we should be robust. 

## Why it's there ?
