### ISSUE TITLE
Secure xor hashes

### ISSUE THREAD

**Issue by AurelienFT** [massalabs/massa#4092]
After further study with Seb, there is a way to make the XOR secure against the algorithm we mentioned.
The paper states an attack complexity of `O(2^'2sqrt(n))` where n is the number of bits of the hash.

So if we want a 128 bit security (the same as the one of 256bit hash collisions) we need to increase the hash size to `n=4096bits` which is **512 bytes**. (that's a big hash !). This can be done with the blake3 crate using XOF extensions, see the "extended output" example in https://docs.rs/blake3/latest/blake3/#examples

_Originally posted by @damip in https://github.com/massalabs/massa/discussions/3852#discussioncomment-6188158_

**Comment by damip** [comment]
We should remove the XOR operator we added to MassaHash

**Comment by Leo-Besancon** [comment]
Adapting the code to use extended hash for the db xor seems relatively straightforward, but I was thinking about what we print in the node. Printing 512 bytes of hash every slot on finalize() seems too much, but I assume everything else (such as printing the first and last bytes, but cutting out the middle) would decrease the security?

**Comment by damip** [comment]
> Adapting the code to use extended hash for the db xor seems relatively straightforward, but I was thinking about what we print in the node. Printing 512 bytes of hash every slot on finalize() seems too much, but I assume everything else (such as printing the first and last bytes, but cutting out the middle) would decrease the security?

This is what printing the whole thing would look like:
```
268fLe9QDjspF4qK49vappFjSNn41QCMEAGvbiMqgoYdYFY9N7djSXcdKqAkFHepKRZyYcaGdTqqeRtmRsB8ZLTsxceT3rW7MvRhpAroRfqfREqvHeNbxKrDNDbCSk36DP8iohqC14CkW7uHQio7t7d4ESRGupytpqBgGgNuLXqnhfNGC6UP1TTgf4762iJm43MhznjnVz7LgcBp2iRwhXrnci9XFEiEy21KSzkCnyGKJJgL4MVoFVu3KK7AriqV4KBw7GcszmzKb1U8qsRApiwMzrei3XquWb3zWsGBHDWDa4aY26xKoCtUMeJTt1uaRhQnVKw1NToeWa5y5MhCoNNXpqSgFqtE4aV7tYzb75bpVJxgW2BDBThvZPZZw7HYCBj1hb7GNa9FeyT9cassSczYQXTMvNcXBJ3YVvQw5rBomqBA1NaxzYH1NVFJxDZ6rZnLUjfDyumgzBNRG31bFKHLCLTtqptETnPXuVT6mrReyuq1RkVXqigkEZB44AiXDqbnTADiCCBaoU9Lo39CcK5rFJjnQntJJWVztqhHJUUufaK3BPAyYVqso3EcmLUWv2cRLn6h4amFKUHdLuS2XdUMBNL8LGX8aShHiZfbCfhviKHH9pR5QD76AXo27JvU73W5mQVbcp1eiMenEPT5reh68bzbYUv2skDpeS4NfnJVtbof17dHCdG8NNgJ
```

so what I recommend is to print the normal hash of the big hash :)

**Comment by AurelienFT** [comment]
Done in #4137 and #4155
