### ISSUE TITLE
Check constants

### ISSUE THREAD

**Issue by damip** [massalabs/massa#4106]
In constants.rs:
* [x] remove `pub const ADDRESS_SIZE_BYTES: usize = 32;` 
* [x] set BLOCK_REWARD = 1.02  (mantissa = 102, scale = 2)
* [x] choose MAX_ASYNC_GAS wisely
* [x] at this line `pub const MAX_GAS_PER_BLOCK: u64 = u32::MAX as u64;`
  * [x] make sure we support u64 bit gas everywhere (also in runtime)
  * [x] make sure that in the future when computer perf increases, we can increase `MAX_GAS_PER_BLOCK` without hitting a limit
 * [x] TODO : adjust LRU sizes cf  https://github.com/massalabs/massa/issues/4129  in on_operations_announcements_received , insert_checked_operation
 * [x] Storage costs

**Comment by AurelienFT** [comment]
Could be nice to group with : https://github.com/massalabs/massa/issues/3739 and https://github.com/massalabs/massa/issues/2863

**Comment by AurelienFT** [comment]
Done in #4133
