### ISSUE TITLE
Protocol keep sending even if a peer is disconnected

### ISSUE THREAD

**Issue by AurelienFT** [massalabs/massa#4109]
Need investigations : 
![jp2](https://github.com/massalabs/massa/assets/32803821/20e5c400-1f87-4139-817a-20cd542fda61)
![jp1](https://github.com/massalabs/massa/assets/32803821/12f3ca3f-0375-4d82-a62e-e78fe75d7bff)

**Comment by damip** [comment]
After having 11 active out connections, I tried disconnecting my ethernet cable for 30 seconds and reconnecting it => all 11 connections were kept (still listed in client) and after that, since a few mintues, there are many "failed to send XX " to all of the connected nodes
