### ISSUE TITLE
Protocol bypass limit of connexion

### ISSUE THREAD

**Issue by AurelienFT** [massalabs/massa#4110]
Bunch of users on discord claimed to have more than 10/15 (not only 1/2 more but even 5/6 so don't seems to be a concurrent problem) active connections. Need to verify if this is indeed connections running or just the counters that are not updated and which case this can happens.

**Comment by modship** [comment]
@AurelienFT you fixed that ?

**Comment by AurelienFT** [comment]
It seems that nobody encours this on 24.1 so I guess it's fixed we will open a new one if needed
