### ISSUE TITLE
Testnet desync versioning

### ISSUE THREAD

**Issue by AurelienFT** [massalabs/massa#4120]
Please post your logs below.

**Comment by raulddan** [comment]
[https://we.tl/t-dSdCGTA2WY](url)

**Comment by caku91** [comment]
https://we.tl/t-dd7Xo8AkPl

**Comment by bartouse01** [comment]
[20230619-logs.zip](https://github.com/massalabs/massa/files/11792946/20230619-logs.zip)

**Comment by h4ckm1n-dev** [comment]
https://we.tl/t-CA6Y9HdJgR

**Comment by JeromeSi** [comment]
[40 min of logs in debug mode](https://nextcloud.ggcom.men/index.php/s/KtoJBkYCYP7dwN7)

**Comment by AurelienFT** [comment]
> This looks like a bootstrap bug.

This is not it's because we reduced the number of periods kept to 32 because of memory problem and so with a blockchain with 15% of the block finality was so long that it took more than 32

**Comment by AurelienFT** [comment]
Thanks for all the report we have fixed some problems.
