### ISSUE TITLE
denunciation-pool thread uses 100% CPU

### ISSUE THREAD

**Issue by damip** [massalabs/massa#4128]
When analyzing CPU usage, I found that the denunciation-pool thread used the most CPU of all threads (100% of one core for testnet 23.2 under 2ktxps). This shouldn't be the case.

![image](https://github.com/massalabs/massa/assets/10211103/cf3e7764-69e0-417c-a3e5-b43361c76e8d)

I also get a lot of : 
```
Could not add endorsements to pool: worker channel is full.
Could not add denunciation precursor to pool: worker channel is full.
Could not notify endorsement pool of new final slots: worker channel is full.
```

so it also looks like the endorsement pool is struggling

**Comment by AurelienFT** [comment]
If the denunciation pool is using a lot of CPU + channels are full is certainly a infinite loop or something like that on the denunciation pool because the channel to send data is shared across all of the 3 pools

**Comment by AurelienFT** [comment]
@sydhds can you check on that for this month ?

**Comment by damip** [comment]
> If the denunciation pool is using a lot of CPU + channels are full is certainly a infinite loop or something like that on the denunciation pool because the channel to send data is shared across all of the 3 pools

We are not sharing channels, they are 3 separate chans

**Comment by damip** [comment]
Possible deadlock source corrected in https://github.com/massalabs/massa/pull/4134

**Comment by AurelienFT** [comment]
> 3

Indeed my bad.
