### ISSUE TITLE
Storage ownership optimization

### ISSUE THREAD

**Issue by damip** [massalabs/massa#4143]
```
2023-06-23T11:54:59.558264Z ERROR massa_storage: blocks: {0: "api", 268096: "protocol", 270009: "execution", 271869: "consensus"}
2023-06-23T11:54:59.558282Z ERROR massa_storage: endos: {0: "api", 2: "protocol", 1703: "execution", 14654: "consensus"}
2023-06-23T11:54:59.558291Z ERROR massa_storage: ops: {0: "factory", 18426: "pool", 289420: "execution", 942403: "protocol", 990060: "consensus"}
```

Question: the others behave like expected but why does Protocol keep ~1M references to ops ?

**Comment by AurelienFT** [comment]
It's not related to the storage of the retrieval thread can keeps the ops for a certain amount of time [here](https://github.com/massalabs/massa/blob/b640980d15ce46b6dd25a29656e1c01158c04a8e/massa-protocol-worker/src/handlers/operation_handler/retrieval.rs#L292) ? [It's clear each 100 seconds](https://github.com/massalabs/massa/blob/a48f8b214d2cc0dee129b5a67fbed8bf894b7cdd/massa-node/base_config/config.toml#L195) at a 10k txps rate it's 1M. Can you precise the conditions of your observation ?

**Comment by damip** [comment]
> It's not related to the storage of the retrieval thread can keeps the ops for a certain amount of time [here](https://github.com/massalabs/massa/blob/b640980d15ce46b6dd25a29656e1c01158c04a8e/massa-protocol-worker/src/handlers/operation_handler/retrieval.rs#L292) ? [It's clear each 100 seconds](https://github.com/massalabs/massa/blob/a48f8b214d2cc0dee129b5a67fbed8bf894b7cdd/massa-node/base_config/config.toml#L195) at a 10k txps rate it's 1M. Can you precise the conditions of your observation ?

Yes, that was it :)
