### ISSUE TITLE
Long term memory leak on versioning statistics

### ISSUE THREAD

**Issue by damip** [massalabs/massa#4149]
![image](https://github.com/massalabs/massa/assets/10211103/f8e6fb36-16f6-463d-8a56-20217fd26252)

![image](https://github.com/massalabs/massa/assets/10211103/7b4678ce-65aa-458a-94bc-6a4a87f3e583)

And some other problems:
* [ ] block misses seem mismanaged
* [ ] update_versioning_stats takes a long lock on storage.read_blocks() while writing in the state db. This has an important performance impact
* [ ] unwrap should never be used => use expect with a proper error message
* [ ] db updates should happen in apply_final_execution_output => self.final_state.write().finalize() because otherwise we would take 2 separate locks/batches on the db (one for updating the state and one for updating only the mip counters) which causes atomicity problems

My recommendations:
* look into finding the source of the bug. Maybe something badly pruned in update_network_version_stats ?
* in `ExecutionOutput`, replace `block_id: Option<BlockId>` by `block_info: Option<BlockInfo>` where `BlockInfo { block_id: BlockId, current_version: u32, announced_version: u32 }` and make sure that `execute_slot` fills this field the same way it filled `block_id`. This also removes the need to find/lock the block again in Storage just to read its version info as the lock already taken when executing the block can be used.
* Properly take into account that info in apply_final_execution_output to generate a StateChange that reflects the stats update. Then pass that change to `self.final_state.write().finalize(...)` to write it using the same write batch as the one we would use for the rest of the state

**Comment by sydhds** [comment]
WIP PR: #4169
