### ISSUE TITLE
No Versioning info send in Bootstrap when state is Defined

### ISSUE THREAD

**Issue by sydhds** [massalabs/massa#4159]
* Bug exposed by test: test_version_non_compatible_mip in massa-functional-tests

**Comment by AurelienFT** [comment]
Do you think we can fix this for testnet 24 release to perform a new versionning test on testnet ?

**Comment by sydhds** [comment]
> Do you think we can fix this for testnet 24 release to perform a new versionning test on testnet ? or we keep it for next month ?

WIP PR here: https://github.com/massalabs/massa/pull/4164
