### ISSUE TITLE
Implement internal event ids generation

### ISSUE THREAD

**Issue by aoudiamoncef** [massalabs/massa#4167]
Currently, we don't provide an identifier for execution event. 

We should implement a mechanism to create UUID for every generated events. 

cc @damip

**Comment by damip** [comment]
This is a more general requirement: track the execution history using an incremental hash that can then be used to generate any kind of ID (events, autonomous SCs...) and for the RNG as well

**Comment by AurelienFT** [comment]
Close in favor of https://github.com/massalabs/massa/issues/4186
