### ISSUE TITLE
Add execution history incremental hash

### ISSUE THREAD

**Issue by damip** [massalabs/massa#4186]
In the execution module, add a `history_hash` that evolves like this:
* `history_hash = 00000000000000000000000` at genesis
* at every executed slot:
  * `history_hash = hash_tuple[ history_hash | S.to_bytes_key() | 0u8  ]`  if S is a miss
  * `history_hash = hash_tuple[ history_hash | S.to_bytes_key() | 1u8 | B.id ]`  if S contains a block B

Note that this supports restarts as the next slot to be executed retrieves the history_hash from the last executed slot before restart.

That way, `history_hash` then represents the whole history of all slots that have been executed since genesis and until now, and can be used to generate unique IDs for autonomous SC messages and events like this:

`event_id = blake3[ history_hash | (index_of_created_event_at_this_slot as u64).to_be_bytes() ]`

That way, if blockcliques change (new blocks before), event IDs also change even if they are emitted at the same block/index.

`history_hash` also needs to be added to the final state (updated at slot finalization), bootstrapped and taken into account in the state hash. This allows ensuring the integrity of the execution history together with the state history because the state hash then takes into account the hash of the whole history of executed slots.

**Comment by AurelienFT** [comment]
Done in https://github.com/massalabs/massa/pull/4197
