### ISSUE TITLE
Implement `to_mantissa_scale` in `Amount`

### ISSUE THREAD

**Issue by aoudiamoncef** [massalabs/massa#4191]
To bind Massa Amount to gRPC `NativeAmount` we need to implement a function to make the conversion:

Add the following constants  to `constants.rs`
```rust
pub const AMOUNT_DECIMAL_SCALE: u32 = 9;
pub const AMOUNT_DECIMAL_FACTOR: u64 = 10u64.pow(AMOUNT_DECIMAL_SCALE);
```

Add to `amount.rs`:
```rust
    /// Returns the value in the (mantissa, scale) format where
    /// amount = mantissa * 10^(-scale)
    pub fn to_mantissa_scale(&self) -> (u64, u32) {
        (self.0, AMOUNT_DECIMAL_SCALE)
    }
```

Add some tests.

**Comment by bilboquet** [comment]
You're right that we are probably missing this kind of function.
last week we had some discussion with @damip and it's fine to use "proto" types in the massa project as we are already using them in many place. so you may want to directly return NativeAmount
hence
```rust
pub fn to_mantissa_scale(&self) -> NativeAmount
```

**Comment by damip** [comment]
> You're right that we are probably missing this kind of function. last week we had some discussion with @damip and it's fine to use "proto" types in the massa project as we are already using them in many place. so you may want to directly return NativeAmount hence
> 
> ```rust
> pub fn to_mantissa_scale(&self) -> NativeAmount
> ```

That discussion was about ways to transfer data in the Interface with execution. I recommend that we still keep this one as described in the issue to reduce dependencies of low-level objects (eg. Amount) as much as possible.

**Comment by aoudiamoncef** [comment]
> You're right that we are probably missing this kind of function. last week we had some discussion with @damip and it's fine to use "proto" types in the massa project as we are already using them in many place. so you may want to directly return NativeAmount hence
> 
> ```rust
> pub fn to_mantissa_scale(&self) -> NativeAmount
> ```

I have to write a mapping for grpp_model::NativeAmount, so a tuple is fine
