### ISSUE TITLE
Versioni info in Address, BlockId, OperationId & co

### ISSUE THREAD

**Issue by sydhds** [massalabs/massa#4196]
- [x]  BlockId (and all XXId struct) should be versioned. Ensure that the binary ser/deser & text ser/deser are homogeneous regarding to this.

- [x] Check again Address & Keypair, it seems they are some issue with binary ser/deser (regarding the Version) but looks ok on the text side:

- [x]  Check "impl Serializer<UserAddress> for AddressSerializer" versus "to_prefixed_bytes(self)"

- [x]  Check that the trait Preshashed is ok with those modification: the prehash might only use the part without version?

- [x]  Check the consequence for OperationIdPrefix in the protocol 

- [x] For Address, ensure that the thread computation is done without taking into account the version number (maybe add a unit test for that)?

**Comment by AurelienFT** [comment]
> Check again Address & Keypair, it seems they are some issue with binary ser/deser (regarding the Version) 

Can you be more precise ?
