### ISSUE TITLE
Reinstate stream limiter

### ISSUE THREAD

**Issue by AurelienFT** [massalabs/massa#4222]
- Re-add stream limiter in bootstrap and protocol
- Uncomment check in test bootstrap_bandwidth

**Comment by Abhijrathod** [comment]
Locate the bootstrap file: Find the file that contains the bootstrap logic in your project. It might be named something like bootstrap.js or bootstrap.py. Open that file in an editor.

Add the stream limiter: Look for a section of code that handles the stream or bandwidth settings. This could be related to network configurations or streaming protocols. Add the necessary code to limit the stream. The specific implementation depends on your project and requirements. Here's an example of what it might look like in JavaScript:

`// Add code to limit the stream
stream.limiter.enable();`


Save the file.

Locate the protocol file: Find the file that handles the protocol logic. This could be named protocol.js or protocol.py. Open that file in an editor.

Add the stream limiter: Look for the section of code where the protocol is defined or configured. Add the necessary code to enable the stream limiter. Again, the exact implementation will depend on your project. Here's an example in JavaScript:


`javascript
Copy code
// Add code to enable the stream limiter
protocol.enableStreamLimiter();`


Save the file.

Locate the test file: Find the file that contains the test logic, specifically the bootstrap_bandwidth test. Open that file in an editor.

Uncomment the check: Look for the section of code that includes the bootstrap_bandwidth test and remove any comment markers (e.g., // or #) to uncomment the check. It should look something like this:

`// Uncomment the check in test bootstrap_bandwidth
if (bootstrap_bandwidth) {
  // Perform the test
}`

**Comment by damip** [comment]
@Abhijrathod 💩
