### ISSUE TITLE
Diagnostic peer algorithm faults on protocol

### ISSUE THREAD

**Issue by AurelienFT** [massalabs/massa#4225]
Looking at the testnet statistics and topology we have two strange observations:

- ~~It seems that the OUT connections limit is often 1 higher than expected~~ (no one have this in 24.1 anymore)
- The bootstrap servers don't have all their IN slots filled with a network with more than one thousand node that all want 1 bootstrap server to be connected to them. Their slots should be full very fast. Maybe the algorithm isn't well implemented

**Comment by modship** [comment]
@AurelienFT  we can close this ?! related to https://github.com/massalabs/massa/pull/4243

**Comment by AurelienFT** [comment]
When https://github.com/massalabs/massa/pull/4261 is merged no ?
