### ISSUE TITLE
Crash on execution

### ISSUE THREAD

**Issue by AurelienFT** [massalabs/massa#4229]
```
thread 'execution' panicked at 'critical: rocksdb crud operation failed: RocksDBError("Error { message: \"Corruption: block checksum mismatch: stored = 2846754421, computed = 978386348, type = 4  in storage/ledger/rocks_db/001986.sst offset 12656798 size 4078\" }")', massa-executed-ops/src/executed_ops.rs:180:14
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

**Comment by Leo-Besancon** [comment]
From what I gathered, the most likely explanation would be a hardware issue (either RAM or disk corruption), especially if it only happened once for just one node (see https://github.com/facebook/rocksdb/issues/7033 and for example the linked issues here: https://github.com/FISCO-BCOS/FISCO-BCOS/issues/1895#issuecomment-814634439)

However, if this repeats, it could be something else, such as:
- A software bug on RocksDB's side
- A software bug on our side (the way we write / flush data, but I don't really see where)
- OS disk interference on flushes? I son't think it could lead to data corruption, but if we delete the files or reload a ledger at a bad time, etc.)

With more instance of the crash, we could analyze: 
- If the loaded .sst was recently written to or not
- If the ledger was bootstraped, does the read failure happen just after bootstrap or on a long-running node?

Some thoughts:
- RocksDB seems to provide a .repair() method to try and repair a corrupted DB, but IMO we need to bootstrap again if this happens, so crashing is fine for now.
- I don't really see something directly related to this in the changelog, but we could update to 21.0: https://github.com/rust-rocksdb/rust-rocksdb/releases/tag/v0.21.0
