### ISSUE TITLE
Memory leak

### ISSUE THREAD

**Issue by UnNicky** [massalabs/massa#4236]
**Describe the bug**
I made an update of my node from 23 to 24.1 yesterday and since update it started eating memory (I monitored simply looking at htop how it grows unlimited), upon eating almost all 10Gb of RAM the system stops massad process, while the service restarts it. And it keeps rolling up.
List of crashes:
![image](https://github.com/massalabs/massa/assets/113925134/3a4b1149-ad4b-410e-8b7d-f03cb9f5444d)

Before the crashes I found WARNs about peers connection drops:
![image](https://github.com/massalabs/massa/assets/113925134/9bd80979-2d5d-4dc4-8c04-7609448bf15c)

And it leads to kind of kills:
![image](https://github.com/massalabs/massa/assets/113925134/a5dd0fc7-227b-4068-9436-76849f27e868)

I also supposed it may be caused by issues on the provider network (the server itself is VPS 6/10/100 on PQ with IPv6 tunnel), there was once last month. Upon reaching support they moved VPS to another node. Keep monitoring.

In either case massad should not eat all the memory even (though it was not confirmed by the provider) if there are network connectivity issues on the server.

**To Reproduce**

Just running 24.1 node version leads to memory leak.

**Expected behavior**
Massa should have memory leak management mechanism which prevents node crashes.

**Screenshots**
As above

**VPS (please complete the following information):**

Processor  : Intel(R) Xeon(R) CPU E5-2680 v2 @ 2.80GHz
CPU cores  : 6 @ 2793.268 MHz
AES-NI     : ✔ Enabled
VM-x/AMD-V : ❌ Disabled
RAM        : 9.7 GiB
Swap       : 228.4 MiB
Disk       : 88.5 GiB
Distro     : Ubuntu 20.04.6 LTS
Kernel     : 5.4.0-150-generic
VM Type    : KVM
IPv4/IPv6  : ✔ Online / ✔ Online

**Additional context**
Ready to provide historical logs/greps for better tracking of what's happen.

https://discord.com/channels/828270821042159636/1127258018640306278/1127258018640306278

**Comment by UnNicky** [comment]
Just adding, so there are no more issues on the network and memory-leak process now works faster:
![image](https://github.com/massalabs/massa/assets/113925134/03fe0f60-87f2-4fea-bc89-60eeee9b2137)

**Comment by UnNicky** [comment]
So it just crashed again:
![image](https://github.com/massalabs/massa/assets/113925134/f9129ac3-b938-4d0f-8d41-4e47cb276102)

**Comment by damip** [comment]
Thank you @UnNicky for the report. We are investigating it !

**Comment by damip** [comment]
More discussion in https://discord.com/channels/828270821042159636/1127258018640306278

**Comment by JeromeSi** [comment]
Same problem with my node
The number of active nodes decrease (25 to 5) and the RAM memory usage increase (~5Gb to ~12Gb)
logs but only in level 2, sorry 1 hour before and 1 hour after
[logs-ep.24.1-crash-2023-07-11_00-10.txt](https://github.com/massalabs/massa/files/12021918/logs-ep.24.1-crash-2023-07-11_00-10.txt)

**Comment by UnNicky** [comment]
Updated discord thread - https://discord.com/channels/828270821042159636/1127258018640306278
Will try tomorrow ggcom suggestions.
Meanwhile adding logs before crash. 
[massa_logs_tail_to_crash.log](https://github.com/massalabs/massa/files/12253346/massa_logs_tail_to_crash.log)

**Comment by AurelienFT** [comment]
Closing as it hasn't been reproduced in the latest testnets
