### ISSUE TITLE
Memory leak in API calls

### ISSUE THREAD

**Issue by damip** [massalabs/massa#4246]
Ran a testnet 24.1 node locally in release mode. No staking, no tx spamming.

Used this to spam the API:

```bash
#!/bin/bash
while true
do
	curl http://127.0.0.1:5000/api/v2/latest_blocks
	curl http://127.0.0.1:5000/api/v2/info
	sleep 0.1
done
```

Result showing the leak after 2 days:

![image](https://github.com/massalabs/massa/assets/10211103/d4f60e55-041b-4554-88ec-fb2bdfbed089)

![image](https://github.com/massalabs/massa/assets/10211103/846ffa6f-f268-4d69-b7e7-4118d306a2d8)

The leak is located in tokio tasks which is consistent with a leak in the API.

Cross-confirmation: RAM usage on TESTNET0 (linked to the explorer APIs) grows much faster than TESTNET4 (no API calls)

**Comment by aoudiamoncef** [comment]
Great job 👏 

If we could relaunch the same with a gRPC calls. 

@AurelienFT observations said that It's the same thing even with gRPC. 

We should look at the design of massa-node and APIs integration on it.

**Comment by aoudiamoncef** [comment]
It seems similar to  https://github.com/paritytech/jsonrpsee/issues/1150

**Comment by AurelienFT** [comment]
Closing in favor of https://github.com/massalabs/massa/issues/4246
