### ISSUE TITLE
Add abi to extract a public key from an Eth signature

### ISSUE THREAD

**Issue by sydhds** [massalabs/massa#4262]
**Technical specification**

-   ABI on massa-sc-runtime side : e.g. `get_public_key_from_evm_sig(bytes: &[u8]) -> &[u8]`
-   Behavior of the function: e.g. Extract the public key from an eth signature. This will help to implement [ecrecover](https://docs.soliditylang.org/en/latest/units-and-global-variables.html).

**Related pull request links**

-   massa-sc-runtime:
-   massa-as-sdk:
-   massa-web3:

**Comment by Eitu33** [comment]
done in https://github.com/massalabs/massa/issues/4270
