### ISSUE TITLE
Peers IN / OUT connections unstable when genesis is not reached yet

### ISSUE THREAD

**Issue by litchipi** [massalabs/massa#4273]
## Description
Before genesis, the peers attempt to connect to each other simultaneously as IN and OUT connections. That triggers an instability shown below

![image](https://github.com/massalabs/massa/assets/61109829/2b164cb1-e8d1-4a16-a5fe-4d250aeb2dea)

On this image, the genesis was `17:39:15`

## To reproduce
Start a labnet, observer the grafana graphs before genesis

# Expected behavior
Stable connection

**Comment by modship** [comment]
Labnet0 log 

Instability : 
![labnet_flou_1](https://github.com/massalabs/massa/assets/9607217/f267085b-b860-478e-95e8-621edfd89cb5)



Stable when "Massa network has started ! " : 
![labnet_flou_2](https://github.com/massalabs/massa/assets/9607217/83f7c661-2ac3-48e6-993f-6845dcca2870)

**Comment by AurelienFT** [comment]
Fixed in Peernet : https://github.com/massalabs/PeerNet/pull/65
