### ISSUE TITLE
Add a maximum length to the events

### ISSUE THREAD

**Issue by AurelienFT** [massalabs/massa#4280]
Events generated from smart contract should have a maximum length otherwise we could have security issues.

@damip do you have a maximum length in mind?

**Comment by damip** [comment]
Yes it should be limited. Probably to something like 100kB

**Comment by AurelienFT** [comment]
@massalabs/core-team If anyone is free can he self assign this today please.

**Comment by bilboquet** [comment]
Shouldn't it be the case for other abis that use bytes, string, or even repeated fields too?

**Comment by Leo-Besancon** [comment]
I read all the current interface methods, for me we could add checks on the size / value for the arguments listed below.
All other cases have data parsed from arguments (for example check_address(addr: str), etc.), and the check should be performed on the parser directly if it's not currently done.

Bytecode:
- get_module(bytecode: &[u8]) 
- create_module(bytecode: &[u8]) 
- set_bytecode(bytecode: &[u8])

Hashes:
- hash_keccak256(bytes: &[u8])
- hash_sha256(bytes: &[u8])
- hash_blake3(bytes: &[u8])

Key-value getter and setters:
- get_ds_keys(prefix_opt: Option<&[u8]>)
- get_ds_value(key: &[u8])
- set_ds_value(key: &[u8], value: &[u8])
- append_ds_value(key: &[u8], value: &[u8])
- delete_ds_entry(key: &[u8])
- has_data(key: &[u8])
- ds_entry_exists(key: &[u8])
- op_entry_exists(key: &[u8])
- get_op_data(key: &[u8])

B58 to and from:
- base58_check_to_bytes_wasmv1(s: &str)
- bytes_to_base58_check_wasmv1(data: &[u8])

Signatures:
- signature_verify(data: &[u8], signature: &str, public_key: &str)
- evm_signature_verify(signature_: &[u8], message_: &[u8], public_key_: &[u8])

Others:
- unsafe_random(size: u64)
- send_message(data: &[u8], filter: Option<(&str, Option<&[u8]>)>)





What are your thoughts on this?

**Comment by bilboquet** [comment]
> I read all the current interface methods, for me we could add checks on the size / value for the arguments listed below. All other cases have data parsed from arguments (for example check_address(addr: str), etc.), and the check should be performed on the parser directly if it's not currently done.
> 
...
> What are your thoughts on this?

I personally need to think twice about all this.
So I suggest you move your last comment to a follow up issue so you can merge and close this one.

**Comment by damip** [comment]
All the byte arrays passed to the runtime from an ABI call coming from inside the VM are already checked: https://github.com/massalabs/massa-sc-runtime/blob/main/src/wasmv1_execution/ffi.rs#L52-L91 so no worries for the general case.

Some things have a particular size limit:
* bytecode size: MAX_BYTECODE_LENGTH (no need to check in get_bytecode if we check in set_bytecode and account creation)
* max size for event emission: TO BE DEFINED
* max size for autonomous message function name length: MAX_FUNCTION_NAME_LENGTH
* max size for autonomous message function parameter length: MAX_PARAMETERS_SIZE
* max datastore key length when writing: MAX_DATASTORE_KEY_LENGTH
* max datastore entry count when adding elements: MAX_DATASTORE_ENTRY_COUNT
* max datasotre value length when writing **and appending**: MAX_DATASTORE_VALUE_LENGTH
* unsafe_random should also be limited to a constant to be defined

**Comment by damip** [comment]
See https://github.com/massalabs/massa/issues/4288
