### ISSUE TITLE
Add coins and fee argument for the "execute_read_only_call" endpoint

### ISSUE THREAD

**Issue by Elli610** [massalabs/massa#4286]
**Is your feature request related to a problem? Please describe.**
When we call execute_read_only_call, it can be to check that a Smart Contract call will pass or revert. However, the result can not be reliable if I do not send the amount of coins and the fees that I want during the test

**Describe the solution you'd like**
in my opinion it would be good to add (in optional arguments or not) coin and fee parameters in order to solve this problem

**Additional context**
It would be useful for the wallet-provider

TODO: also add optional OperationID parameter (for the getOperationId ABI)

**Comment by modship** [comment]
If I understand correctly, fees are managed in `prepare_operation_for_execution`, which is currently not called in the context of a read-only execution. 
Does it cause any problems to call it during a read-only execution? (I don't think so.)

Regarding the 'coins' parameter, should it be passed to the VM in the 'parameter' field as Vec<u8> ?

**Comment by qdrn** [comment]
@modship FYI @Elli610 is not working anymore in the company.

**Comment by Eitu33** [comment]
> Does it cause any problems to call it during a read-only execution? (I don't think so.)

@modship You can call anything in the read-only execution as long as you make sure any changes are rolled back afterwards when we reset the execution context
