### ISSUE TITLE
Port key listing with prefix to the old runtime 

### ISSUE THREAD

**Issue by damip** [massalabs/massa#4295]
The new runtime has prefix support for listing the keys of the account datastore and the operation datastore but not the old one.

TODO:
* add a `assembly_script_get_op_keys_with_prefix` variant of `assembly_script_get_op_keys`: call it `assembly_script_get_op_keys_prefix`
* add a `assembly_script_get_keys_with_prefix` variant of `assembly_script_get_keys`: call it `assembly_script_get_keys_prefix`

**Comment by sydhds** [comment]
Added a prefix for getOpKeys as an argument:

* https://github.com/massalabs/massa/pull/4361
* https://github.com/massalabs/massa-sc-runtime/pull/302
* https://github.com/massalabs/massa-unit-tests-src/pull/36
* https://github.com/massalabs/massa-as-sdk/pull/292

@damip is that ok to provide prefix as an argument (can be empty) or you prefer separate functions.

**Comment by damip** [comment]
@sydhds we need a separate function to not break retro-compatibility with SCs that are already deployed
