### ISSUE TITLE
OOM Killer / Memory usage

### ISSUE THREAD

**Issue by Tropmathise** [massalabs/massa#4325]
Hello,

Since episode 25, I have a memory usage that is gradually increasing until reaching the maximum capacity and having an OOM Killer (cf image). 
![image](https://github.com/massalabs/massa/assets/66423224/6fa70ae0-004c-486c-acef-08ceb76bf047)

When I start the node, RAM is around 3 / 16Go and after couple hours, it reaches 12-16 / 16Go and then crashes. 

![image](https://github.com/massalabs/massa/assets/66423224/444c3bea-95d6-41db-88aa-814e408ff3ce)

One error that I get also : 
![image](https://github.com/massalabs/massa/assets/66423224/6c50a0a6-9561-4f68-ae33-727dcee50698)

I had no issue during episode 23 and 24. 

Ping test of the connected ip : ![image](https://github.com/massalabs/massa/assets/66423224/6c89f335-6af1-443e-bd51-f313919155a6)

Can you help me track something ? 
Thanks

**Comment by Tropmathise** [comment]
I have reinstalled my VPS and downloaded only Massa binaries. Same error.

**Comment by aoudiamoncef** [comment]
Hi @Tropmathise 
Could you share the link to technical specs or commercial offert in the official website of the provider ?

**Comment by Tropmathise** [comment]
Hello @aoudiamoncef 
Scaleway Dedibox Start-2-M-SATA
It's a 16Go RAM, Intel C750 Averton, 250Mbits/s

**Comment by aoudiamoncef** [comment]
In a VPS environment, It's hard to debug. It seems to be a desync issue. If we found something, I'll update this issue

**Comment by damip** [comment]
Could have been resolved by https://github.com/massalabs/massa/pull/4342 let's see in the next testnet
