### ISSUE TITLE
Regression on Bootstrap event polling

### ISSUE THREAD

**Issue by Leo-Besancon** [massalabs/massa#4333]
It seems that https://github.com/massalabs/massa/pull/4319, and more specifically https://github.com/massalabs/massa/pull/4319/commits/ad7ddc5b8c5063cec0183f19af7ed5ad6af2bb99, introduced a regression on a fix introduced in https://github.com/massalabs/massa/pull/4084. The result is a lack of routability on windows (which seems to be the only platform affected).

We should re-introduce looping on `mio_server` accept (and not only on the main listener), in order to be sure to correctly poll Mio's events.
More info here: https://users.rust-lang.org/t/why-mio-poll-only-receives-the-very-first-event/87501
> Mio is edge triggered. You only get a notification when readiness changes from NOT READY to READY, and it only changes from READY to NOT READY when you get a WouldBlock error. Therefore, you must keep calling accept until it fails with a WouldBlock error.

Side note: we should also make sure if the same fix is needed in Peernet!

Reported in: https://discord.com/channels/828270821042159636/1137667605751136327

**Comment by damip** [comment]
@Leo-Besancon I think this is done ?

**Comment by Leo-Besancon** [comment]
This is done, but not merged yet. We have to target testnet26 and make sure the dependencies are lined up!

**Comment by Leo-Besancon** [comment]
Closed by https://github.com/massalabs/massa/pull/4343
