### ISSUE TITLE
 Test SC deployment 

### ISSUE THREAD

**Issue by modship** [massalabs/massa#4359]
test SC deployment and call with massa-web3 and massa-station

At the end of #4352

**Comment by modship** [comment]
The method [deploySmartContract()](https://github.com/massalabs/massa-web3/blob/d9e2252e0cea5b8051ec0a10c06c251429de2fcf/src/web3/SmartContractsClient.ts#L92) of massa-web3/web3/SmartContractsClient should be rename to `executeSmartContract()`

**Comment by modship** [comment]
For osx we also need this fix for wasmer : https://github.com/wasmerio/wasmer/issues/4072

**Comment by bilboquet** [comment]
Wasmer 4.2 has been released. It should fix the crash we had some times on m2 cpu

**Comment by AurelienFT** [comment]
Closing the update of wasmer will be done in #4401
