### ISSUE TITLE
jsonRPC connection error

### ISSUE THREAD

**Issue by caku91** [massalabs/massa#4370]
I use an Android app with jsonRPC Api for monitoring my node since episode 18 without problem.
In episode 25.2 since cycle 819, I am encountering a problem from jsonrpsee server. Server response :
`ResponseError. Reason: Too Many Requests, Response: Too many connections. Please try again later.`
The error occurs only with the public API (33035), private API have no connection problem (33034).

Massa cli does not work anymore and wallet_info return only my public address.
Others functions return :
`Error: check if your node is running: ErrorObject { code: ServerError(-32080), message: "Networking or low-level protocol error: Server returned an error status code: 429", data: None }`

My node run, create blocks and i have the maximum point in the leaderboard for this episode.

I have removed the port forwarding in my box for 33035 and stopped my App since 2 days but the problem is still here.

what can i do to solve this problem ? 

Thanks

**Comment by aoudiamoncef** [comment]
@caku91 Are you using a reverse proxy like Nginx ?

**Comment by caku91** [comment]
no i don't use reverse proxy.
do you use a new filtering system since version 25 ?

**Comment by aoudiamoncef** [comment]
We just upgrade `jsonrpsee` crate to the latest version which fixes a memory leak. 

Have you a way to monitor the load on your node ? 

IMHO, we should open an issue in `jsonrpsee` Github

**Comment by caku91** [comment]
with netstat i see many etablished connections on port 33035. 83.202.34.89 is my wan ip
With tcptrack no connection on port 33035

[tcptrack.log](https://github.com/massalabs/massa/files/12427897/tcptrack.log)
[netstat.log](https://github.com/massalabs/massa/files/12427898/netstat.log)

**Comment by caku91** [comment]
I have restarted the node.
In my android code I add this header in okHttp connection `setHeader("Connection", "close")`

**Comment by caku91** [comment]
it seems to be better.
I see the connections then they are closed.
![Capture d’écran 2023-08-24 130206](https://github.com/massalabs/massa/assets/96083404/847e2346-f19b-4143-bda9-fd034fc71988)

**Comment by aoudiamoncef** [comment]
We'll make a small test without any Massa related code. 

Just use this simple server [example](https://github.com/aoudiamoncef/massa-api-loadtest/blob/main/src/jsonrpsee.rs)

**Comment by caku91** [comment]
Connection is never close on the server when I use the okHttp default parameters (keep-alive)
when I force close the connection, server close the connection.

In the screenshot, the first 2 connections are with keep-alive. Others connection are with header connection close.
The 2 first connections are never closed other are closed after a few seconds
![Capture d’écran 2023-08-24 151544](https://github.com/massalabs/massa/assets/96083404/f8039e87-f98e-412c-a190-c0d1f4eae41b)

**Comment by aoudiamoncef** [comment]
I used OkHttp in the past and I added the header like you didi to fix some connection issue. But the 429 status code is weird on the jsonrpsee server

**Comment by caku91** [comment]
It seems that the timeout is very long or does not trigger on the server side and the connections accumulate up to the authorized limit
