### ISSUE TITLE
Divide storage costs by 10

### ISSUE THREAD

**Issue by damip** [massalabs/massa#4371]
* [x] `LEDGER_COST_PER_BYTE = 1e-4`
* [x] `LEDGER_ENTRY_BASE_COST = 1e-3`
* [x] update massa-web3 estimator
* [x] update documentation

**Comment by qdrn** [comment]
Can't this wait mainnet ?

**Comment by damip** [comment]
> Can't this wait mainnet ?

Given that it's only 2 constants to change at 3 places, better to use the last testnet to make sure everything is consistent, and have it in the updated buildnet to avoid negative reactions from builders, as well as in the doc to avoid negative feelings on due diligence

**Comment by litchipi** [comment]
@damip I don't find the estimator in `massa-web3`, could you tell me where it's located so I can create a PR for it now ?

**Comment by AurelienFT** [comment]
> @damip I don't find the estimator in `massa-web3`, could you tell me where it's located so I can create a PR for it now ?

You can ask run team on discord

**Comment by damip** [comment]
note that this is low priority on the web3 side. We can simply change the constants in the node, things will remain retro-compatible (just slightly overestimate storage costs on web3 without consequences)

**Comment by damip** [comment]
The current documentation was incorrect. We will use the opportunity to fix it

**Comment by litchipi** [comment]
That explains a lot indeed, let's fix it

**Comment by litchipi** [comment]
Should be merged and closed at buildnet update (https://github.com/massalabs/massa-sc-toolkit/pull/355#issuecomment-1695610074), de-assigning myself from it now
