### ISSUE TITLE
Doc duplicated in massa_sdk ClientConfig struct

### ISSUE THREAD

**Issue by sydhds** [massalabs/massa#4410]
/// maximum size in bytes of a request.
    pub max_request_body_size: u32,
    /// maximum size in bytes of a response.
    pub request_timeout: MassaTime,
    /// maximum size in bytes of a response.
    pub max_concurrent_requests: usize,

**Comment by aoudiamoncef** [comment]
It's just the wrong comment ?

**Comment by sydhds** [comment]
> It's just the wrong comment ?

Yes the doc comments looks duplicated no?
