### ISSUE TITLE
API unit tests

### ISSUE THREAD

**Issue by modship** [massalabs/massa#4426]
## GRPC Public - Api #4423 

- [x] execute_read_only_call
- [x] get_blocks
- [x] get_datastore_entries
- [x] get_endorsements
- [x] get_stakers
- [x] get_next_block_best_parents
- [x] get_operations
- [x] get_sc_execution_events
- [x] get_selector_draws #4429 
- [x] get_status
- [x] get_transactions_throughput
- [x] query_state
- [x] search_blocks
- [x] search_endorsements
- [x] search_operations

### stream

- [x] new_blocks
- [x] new_endorsements
- [x] new_filled_blocks
- [x] new_operations
- [ ] new_slot_execution_outputs  ⚠️  Partially done, filters must being implemented #4443
- [x] send_blocks :no_entry_sign: was disabled
- [x] send_endorsements
- [x] send_operations
- [x] transactions_throughput

![image](https://github.com/massalabs/massa/assets/9607217/ba24e4f0-2b56-45df-b3a3-ec99d6e1f520)

## JSONRpc Public - Api #4465 
- [x] execute_read_only_bytecode
- [x] execute_read_only_call
- [x] get_status
- [x] get_cliques
- [x] get_stakers
- [x] get_operations
- [x] get_endorsements
- [x] get_blocks
- [x] get_blockclique_block_by_slot
- [x] get_graph_interval
- [x] get_datastore_entries
- [x] get_addresses
- [x] send_operations
- [x] get_filteres_sc_outpout_event
- [x] get_openrpc_spec
#### wrong api check 
- [x] stop_node
- [x] node_sign_message
- [x] remove_staking_addresses
- [x] get_staking_addresses
- [x] node_ban_by_ip
- [x] node_ban_by_id
- [x] node_unban_by_ip
- [x] node_unban_by_id
- [x] node_peers_whitelist
- [x] node_add_to_peers_whitelist
- [x] node_bootstrap_whitelist
- [x] node_bootstrap_whitelist_allow_all
- [x] node_add_to_bootstrap_whitelist
- [x] node_remove_from_bootstrap_whitelist
- [x] node_boostrap_blacklist
- [x] node_add_to_bootstrap_blacklist
- [x] node_remove_from_bootstrap_blacklist
- [x] add_staking_secret_keys

## Api V2

- [x] get_largest_stakers
- [x] get_next_block_best_parents
- [x] get_version
- [x] subscribe_new_blocks
- [x] subscribe_new_blocks_headers
- [x] subscribe_new_filled_blocks
- [x] subscribe_new_operations

## Server

- [X] max_connections
- [X] max_request_size
- [X] ws disabled / enabled
- [X] http disabled / enabled
- [X] allowed hosts 
- [X] server stop

![image](https://github.com/massalabs/massa/assets/9607217/aca8a070-1ab0-41b8-bca1-05f5d2c771dd)

**Comment by Leo-Besancon** [comment]
Well done!
