### ISSUE TITLE
Internal Audit + Unit testing of massa-final-state and related modules

### ISSUE THREAD

**Issue by Leo-Besancon** [massalabs/massa#4435]

**Comment by sydhds** [comment]
Final state unit tests PR: https://github.com/massalabs/massa/pull/4447

**Comment by sydhds** [comment]
Massa db unit tests: https://github.com/massalabs/massa/pull/4452

**Comment by sydhds** [comment]
Massa async pool: https://github.com/massalabs/massa/pull/4459

**Comment by sydhds** [comment]
Exec ops/de: https://github.com/massalabs/massa/pull/4472

**Comment by sydhds** [comment]
POS exports: https://github.com/massalabs/massa/pull/4476
