### ISSUE TITLE
Node API thread crash - Testnet 26

### ISSUE THREAD

**Issue by ASAPSegfault** [massalabs/massa#4438]
**Describe the bug**
When I run the indexer updated to version 26 I make the node crash.
The only new feature I am using is the QueryState request in gRPC. Here is the query inside the request in question, with the Operation ID field replaced by a dummy value:

ExecutionQueryRequestItem{
			RequestItem: ExecutionQueryRequestItem_OpExecutionStatusFinal{
				OpExecutionStatusFinal: OpExecutionStatusFinal{OperationId: "An Operation ID"},
			},
})

I am sending a lot of these queries in one request. I don't have the exact number right now but I can log it if required.

**To Reproduce**
DM me

**Expected behavior**
The node shouldn't crash when I send requests to it

**Comment by aoudiamoncef** [comment]
Cc @damip 

It seems to be lock issue here. It's never released and we have the JsonRPC API out of service too. So it's not related to gRPC.

**Comment by damip** [comment]
@ASAPSegfault  How does it crash exactly ? Freeze ? error message ?

**Comment by damip** [comment]
@aoudiamoncef did you manage to reproduce it ?

**Comment by aoudiamoncef** [comment]
> @ASAPSegfault How does it crash exactly ? Freeze ? error message ?

I tested the node after the incident, It's a lock issue, all is up but nothing respond. Even the JsonRPC API is in the same state.

**Comment by damip** [comment]
@aoudiamoncef can you launch with deadlock detection and reproduce it ? it should pinpoint which locks are problematic

**Comment by aoudiamoncef** [comment]
After some tests with @ASAPSegfault, the logs didn't show anything except: 
```shell
[2m2023-10-02T16:04:23.935305Z[0m [32m INFO[0m [2mmassa_final_state::final_state[0m[2m:[0m final_state hash at slot (period: 42, thread: 2): 2Yx9GnLZkNGyx4JLNWuj9TKm1CNZh3szKYNbeJ1UBEatzZNxeS
[2m2023-10-02T16:04:24.361828Z[0m [31mERROR[0m [2mmassa_grpc::stream::new_slot_execution_outputs[0m[2m:[0m status: Unknown, message: "h2 protocol error: error reading a body from connection: connection reset", details: [], metadata: MetadataMap { headers: {} }    
[2m2023-10-02T16:04:24.361861Z[0m [31mERROR[0m [2mmassa_grpc::stream::new_slot_execution_outputs[0m[2m:[0m failed to send back new_slot_execution_outputs error response: channel closed    
```

We reduced the number of operations, we got the same result. 

We removed the calls to `QueryState` all was fine, no issue even on high throughput

 The bug seems to come from inside `QueryState`.
