### ISSUE TITLE
Add `get_address_bytecode` ABI to the JsonRPC API

### ISSUE THREAD

**Issue by damip** [massalabs/massa#4474]
Add get_address_bytecode ABI to the JSONRPSEE API:

```
get_address_bytecode:
    
    Arguments:
       * address: the address to get the bytecode for
       * final: optional boolean (default: false)
   
    Return value:
       * error if the address does not exist
       * the bytecode of the address in its candidate state if final=false or its final state if final=true (the execution controller's query_state function can be used to get the info). The binary bytecode should be encoded the same way as the other binary data we return elsewhere through JSONRPSEE 
```

**Comment by aoudiamoncef** [comment]
@damip should we do like `get_addresses` ?

```rust
    /// get addresses bytecode
    async fn get_addresses_bytecode(&self, criteria: Vec<(Address, bool)>) -> RpcResult<Vec<Vec<u8>>> 
 ```

**Comment by Leo-Besancon** [comment]
> Current version which I choosed to be easily binded to` QueryState`: (vec of 5 addresses filters == 5 results):
> 
> ```
> /// filter used when retrieving address informations
> #[derive(Debug, Deserialize, Clone, Serialize)]
> pub struct AddressFilter {
>     /// Address
>     pub address: Address,
> 
>     /// true means final
>     /// false means candidate
>     pub is_final: bool,
> }
> ```

IMO this is sufficient yes. Having a vec of inputs / outputs is not mandatory but indeed nicer.
`is_final` could be an Option, but I kinda dislike bool Options and I don't think it's needed.
