### ISSUE TITLE
Calibrate and adjust APIs arguments limits

### ISSUE THREAD

**Issue by aoudiamoncef** [massalabs/massa#4475]
Currently, we have set a lot of limitations which aren't accurate sometimes. We have to update this to ensure the security and improve the usability of the APIs(JsonRPC/gRPC)

See [node configuration](https://docs.massa.net/docs/node/all-configs#node-configuration)
See [client configuration](https://docs.massa.net/docs/node/all-configs#client-configuration)

**Comment by Leo-Besancon** [comment]
Yes this is an important issue, we need to clarify what limits have been calibrated and how to calibrate the rest!
@modship and @aoudiamoncef, can you sync on this and document what is done and what is to be done?
