### ISSUE TITLE
Allow launching the blockchain with predefined SCs

### ISSUE THREAD

**Issue by damip** [massalabs/massa#4482]
* Allow launching the blockchain genesis with predefined bytecodes at hardcoded addresses: TODO test
* make sure it is compatible with the vesting system: TODO test

This is needed for the multisig system managing funds

**Comment by damip** [comment]
There might be a risk that the crediting fails because the target is an SC (and not EOA) address. We should make sure that it does not make the vesting fail silently when targeting an SC address

**Comment by Leo-Besancon** [comment]
Reading the code, everything seems to be ok (crediting of the initial_deferred_credits will call `transfer_coins()` with `check_right` set to false so we don't fail on an SC), but I have to see the best way to check every case (probably will either make a specific execution TU or a functional test).

**Comment by damip** [comment]
Cool ! can we make sure by trying it ?

**Comment by Leo-Besancon** [comment]
> Cool ! can we make sure by trying it ?

Yes, I'm trying to setup the test framework to do that :)

**Comment by Leo-Besancon** [comment]
Everything checked with https://github.com/massalabs/massa-functional-tests/pull/6
