### ISSUE TITLE
Simulate the growth rate of the ledger size

### ISSUE THREAD

**Issue by litchipi** [massalabs/massa#4516]
Following #4420

As the ledger bootstrap takes way too much time once it'll grow big (partly because of #4371), a refactor of the bootstrap system has to be done.
However, as the mainnet approach, there's no time now, and the good idea would be to **simulate how fast the ledger could grow**, on a normal situation, but also if an attacker knows this is an issue and wants to bring the bootstrap duration upward.

For more informations on this issue, how and why, @damip is your man here

**Comment by AurelienFT** [comment]
Duplicate with ledger size tests issue
