### ISSUE TITLE
Read only call fail with insuffisient found

### ISSUE THREAD

**Issue by Thykof** [massalabs/massa#4542]
**Describe the bug**

On buildnet v24.1

I think there is a bug in `execute_read_only_call` because the call fail with error `readonly call failed: VM Error in ReadOnlyExecutionTarget::FunctionCall context: VM execution error: RuntimeError: Runtime error: Runtime error: failed to transfer 260.01 from spending address AS12aPb1146jBpsRmcKgr1UV13kk1WRCeyShfs3L2ai4T8fV4zxM6 due to insufficient balance 0 | Init cost is 221444` but the actual `send_operations` is executed with success.

**To Reproduce**

I have the problem when using web on chain feature of Massa Station: the master account of the buildnet (big balance, enough) is doing a call sc to `appendBytesToWebsite` at `AS12aPb1146jBpsRmcKgr1UV13kk1WRCeyShfs3L2ai4T8fV4zxM6` with coins 260024000000 nanoMAS and I have the error on the read only: `failed to transfer 260.01 from spending address AS12aPb1146jBpsRmcKgr1UV13kk1WRCeyShfs3L2ai4T8fV4zxM6 due to insufficient balance 0`. The balance of AS12aPb1146jBpsRmcKgr1UV13kk1WRCeyShfs3L2ai4T8fV4zxM6 is in fact 0, this is the smart contract web site storer just deployed, but I do the callSC with coins 260024000000 nanoMAS, and the caller address is the master account (AU1wN8rn4SkwYSTDF3dHFY4U28KtsqKL1NnEjDZhHnHEy6cEQm53). 

Then, I do the actual CallSC, and the operation is execute, is a success and final.

**Expected behavior**

Have the same execution result on read only and call sc.

**Comment by damip** [comment]
@Thykof thanks for the report. Can you give us the exact JSONRPC request you have sent for the read only call with all parameters inside ?

**Comment by Leo-Besancon** [comment]
Hi! Just catching up a bit about this issue. Saw nothing out of the ordinary in the code, so I'd have to test with debug logs to better understand what's going out. Just to check though, @damip If this is on buildnet, the ReadOnly call does not take the coins data currently, no? It's only in v27?

**Comment by modship** [comment]
> Hi! Just catching up a bit about this issue. Saw nothing out of the ordinary in the code, so I'd have to test with debug logs to better understand what's going out. Just to check though, @damip If this is on buildnet, the ReadOnly call does not take the coins data currently, no? It's only in v27?

yes https://github.com/massalabs/massa/pull/4455

**Comment by Thykof** [comment]
I'm using buildnet v24.1

Curl request:
[curl-request-massa-4542-1.txt](https://github.com/massalabs/massa/files/13392241/curl-request-massa-4542-1.txt)

Response:
[curl-response-massa-4542-1.txt](https://github.com/massalabs/massa/files/13392248/curl-response-massa-4542-1.txt)

**Comment by Leo-Besancon** [comment]
> I'm using buildnet v24.1
> 
> Curl request: [curl-request-massa-4542-1.txt](https://github.com/massalabs/massa/files/13392241/curl-request-massa-4542-1.txt)
> 
> Response: [curl-response-massa-4542-1.txt](https://github.com/massalabs/massa/files/13392248/curl-response-massa-4542-1.txt)

Buildnet v24.1 does not have the coins argument implemented for Read Only Calls. Once we transition to v27, you will be able to do this!

**Comment by Thykof** [comment]
okay thanks!
