### ISSUE TITLE
improve error message

### ISSUE THREAD

**Issue by damip** [massalabs/massa#4551]
On buildnetv27, when I do a call SC on a no-existent target address:

```
Runtime error: runtime error when executing operation O1EmJVtjgzR5RzNodm7m8V8chxxmFkFBHsBcm9pd4sCr7oHFYzF: Runtime error: failed to transfer 0 operation coins from AU1wN8rn4SkwYSTDF3dHFY4U28KtsqKL1NnEjDZhHnHEy6cEQm53 to AS12HwmDTbTp6JTzfAjqTfVvYqYEAPUsP42v3ivgtWJtmVb6F4g8d: Runtime error: insufficient amount 0 to create credited address AS12HwmDTbTp6JTzfAjqTfVvYqYEAPUsP42v3ivgtWJtmVb6F4g8d\
```

AU1wN8rn4SkwYSTDF3dHFY4U28KtsqKL1NnEjDZhHnHEy6cEQm53: is the master buildnet account 
AS12HwmDTbTp6JTzfAjqTfVvYqYEAPUsP42v3ivgtWJtmVb6F4g8d: does not exist

_Originally posted by @Thykof in https://github.com/massalabs/massa/issues/4541#issuecomment-1820982231_

**Comment by modship** [comment]
in case of :
- exec async_msg
- exec op CallSC
- exec call SC to SC
- exec read only call

we should first check the target address : 
- if is not SC address but user address => The called address XXXXXXXXXX is not a smart contract address.
- if target address doesn't exist => The called smart contract address XXXXXXXXXX does not exist
