### ISSUE TITLE
endure that direct bracket accesses are always safe (eg. `buffer[i+3:]` will panic if i is too big)

### ISSUE THREAD

**Issue by Leo-Besancon** [massalabs/massa#4556]

**Comment by sydhds** [comment]
## Massa models

### slot.rs

* L.114 & 119: Ok
* L.153 &155: Ok
* L.211 & 242,243: Ok
* L.259,260: Ok

### datastore.rs

* line 158: get_prefix_bounds TODO TODO
* line 187 & 188 & 210: TU

### denunciation.rs

L.964: FIXED - no more indexing

### block.rs

L.155,258,274,284: N/A (doctest)
L.389,390: commented code (impl Signable<BlockId> for BlockHeader)
L.644,706,813,872,948,1003,1102: N/A (unit tests)

## block_header.rs

L.178,338,351,361: N/A (doctest)
L.400: N/A (tag(&[0]))
L.402: N/A (tag(&[1]))
L.462: TODO recheck
L.636,642,645,664: N/A (unit tests)

## clique.rs

L.163,164: Not array indexing

## block_id.rs

L.70: Array indexing with index 0 for &[u8; 32]

## version.rs

L.221,222,223,232,235: Array indexing but length previously checked

## operation.rs

L.261,270: Ok (Slicing &[u8; 32] with slice(0, 17))
L.1188: Ok (Len previously checks, should return empty &[u8])
L.1190: Ok (Len previously checks)
L.1446: N/A (Array type)
L.1565: N/A (vec! declaration)

## serialization.rs

L.38,48: TODO recheck
L.76, 95: TODO recheck
L.115: Ok (length checked)
L.127: Ok (length checked)
L.203,211: N/A (tag[XX])
L.656,665: Ok (length checked)
L.724,747,750: N/A (unit tests)

## ledger.rs

L.265: Not array indexing

## address.rs

L.343: Array indexing with index 0 for &[u8; 32]

**Comment by sydhds** [comment]
## Massa async pool

### pool.rs

L.375: Ok (length checked)
L.439: Ok (length checked)

**Comment by sydhds** [comment]
## Massa bootstrap

### lib.rs

L.93: Ok (length checked)

### bindings/client.rs

L.210: Ok (type length in function argument type)

### bindings/server.rs

L.301, 312: TODO (Should we check for leader_buf size?, expect ?)

### bindings.rs

L.35: Ok (length checked)
L.92: Ok (length checked)

**Comment by sydhds** [comment]
## Massa consensus worker

### controller.rs

L.87: Ok (function argument type)

### state/prune.rs

L.130: Ok (closure for_each index)

### state/graph.rs

L.111: Ok (assume max_cliques len always >= 1)
L.118, 122, 123, 125, 206, 224, 225, 238: Ok (sort closure with previous length)

### state/blocks_state.rs

L.131: Ok (vec definition)

### state/clique_computation.rs

Not checked

## state/process.rs

L.513: Ok (as long as self.compute_fitness_find_blockclique returns an ok index)
L.535: Ok (position_blockclique already used L.513)

**Comment by sydhds** [comment]
## Massa db worker

### massa_db.rs

L.653, 654, 657: Ok (length checked)
L.1094, 1096, 1098, ...: N/A (unit tests)

**Comment by sydhds** [comment]
## Massa execution exports

### event_sore.rs

L.126, ...: N/A (unit tests)

### controller_traits.rs

L56, 66, 105: Ok (function argument type)

**Comment by sydhds** [comment]
## Massa hash

### hash_xof.rs

L.154, 155: Ok (length checked)

### hash.rs

L.251, 252: Ok (length checked)

**Comment by sydhds** [comment]
## Massa ledger exports

### types.rs

L.75, 77, 81, 84: FIXED (with nom take)
L.218, 220, 223: FIXED (with nom take)
L.302, 304, 307: FIXED (with nom take)

**Comment by sydhds** [comment]
## Massa ledger worker

### ledger_db.rs

L.548: N/A (docstring)

**Comment by sydhds** [comment]
## Massa node

### operation_injector.rs

N/A (testing tool)

**Comment by sydhds** [comment]
## Massa protocol worker

### ./handlers/operation_handler/retrieval.rs

L.173, 174, 176, 177: N/A (Code commented)

### ./handlers/peer_handler/messages.rs

L.241: Ok (length checked)

### handlers/peer_handler/mod.rs

L.445: Ok (length defined as const on L.444)

**Comment by sydhds** [comment]
## Massa serialization

L.505, ...: N/A (unit tests)

**Comment by sydhds** [comment]
## Massa signature

### signature_impl.rs

L.302, 711, 1055: Ok (length checked)
L.1241: Ok (length checked)

**Comment by sydhds** [comment]
## Nothing to check

* massa-api: N/A
* massa-api-exports: N/A
* massa-channel: N/A 
* massa-cipher: N/A
* massa-db-exports: N/A
* massa-factory-exports: N/A
* massa-factory-worker: N/A
* massa-final-state: N/A
* massa-grpc: N/A
* massa-logging: N/A
* massa-metrics: N/A
* massa-pool-exports: N/A
* massa-pool-worker: N/A
* massa-protocol-exports: N/A
* massa-sdk: N/A
* massa-storage: N/A
* massa-time: N/A
* massa-wallet: N/A
* 

## NOT CHECKED

* massa-client
* massa-xtasks

**Comment by sydhds** [comment]
## Massa versioning

* https://github.com/massalabs/massa/pull/4623
