### ISSUE TITLE
Provide an error message when too much gas is provided to an operation.

### ISSUE THREAD

**Issue by bilboquet** [massalabs/massa#4558]
Having various maximum authorized value for `max_gas` seems very misleading for users.
As an example, users often provide `u32::MAX` gas for CreateSC operations while the maximum authorized value is 3_980_167_295. In this case the node fails silently (operation simply expires) while we could detect the error and give the user feedback when the operation is added.
The same mechanism, with different maximum value, applies to CallSC operations.

**Comment by Leo-Besancon** [comment]
@bilboquet Dupplicate of https://github.com/massalabs/massa/issues/4524?

**Comment by peterjah** [comment]
Hey, thanks for the issue, this is highly needed for this and every potential errors than can occurs when deploying/ or calling smart contracts. The best implementation would to have not only a clear error message, but also an error code to avoid string parsing with ugly regexs...

**Comment by bilboquet** [comment]
> @bilboquet Dupplicate of #4524?

Ho yes sorry, closing it
