### ISSUE TITLE
[Meta] ChainId

### ISSUE THREAD

**Issue by sydhds** [massalabs/massa#4583]
## Intro

ChainId implementation for [Massa](https://www.notion.so/massa-innoteam/ChainID-cc390e005f5c4cb886c608581e7a7be9)

## Documentation

ChainId idea comes from Etherum (and was required to separate the network between Ethereum & Ethereum Classic)

### Ethereum ChainId

* https://github.com/ethereum/EIPs/blob/master/EIPS/eip-155.md
* List of chainId:
  * https://chainid.network/ - https://github.com/ethereum-lists/chains
* Ethereum SC (Solidity) documentation:
  * https://eips.ethereum.org/EIPS/eip-1344
  * https://docs.soliditylang.org/en/latest/units-and-global-variables.html#block-and-transaction-properties 

Example code from [Umbrella](https://github.com/umbrella-network/phoenix/blob/develop/contracts/onChainFeeds/UmbrellaFeeds.sol):

```solidity
function update(
    bytes32[] calldata _priceKeys,
    PriceData[] calldata _priceDatas,
    Signature[] calldata _signatures
) external {
    if (_priceKeys.length != _priceDatas.length) revert ArraysDataDoNotMatch();

    bytes32 priceDataHash = keccak256(abi.encode(getChainId(), address(this), _priceKeys, _priceDatas));
    verifySignatures(priceDataHash, _signatures);

    ...
}

function getChainId() public view returns (uint256 id) {
    // solhint-disable-next-line no-inline-assembly
    assembly {
        id := chainid()
    }
}
```

## Implementation

* Massa node
  * [massa-proto]
    * https://github.com/massalabs/massa-proto/pull/57 
  * [massa-proto-rs]
    *  https://github.com/massalabs/massa-proto-rs/pull/32
  * [massa-sc-runtime]:
    * implement new abi:
      * [old abi] chainid() -> u64
      * [grpc] chainid_v1() -> u64
      * Gas calibration
    * https://github.com/massalabs/massa-sc-runtime/pull/320
  * [massa]:
    * Modify SecureShare impl
    * implement abi calls
      * Add a new entry in config.toml
    * Add to API:
      * [jsonrpc] add to get_status() (public api)
      * [grpc] add to https://github.com/massalabs/massa-proto/blob/main/proto/commons/massa/model/v1/node.proto
        * Add to PublicStatus (privé) & NodeStatus (privé)
          * Warning -> Add to the end of the struct to be backward compat
    * labnet deploy
      * https://github.com/massalabs/private-deployment/pull/31 
    * https://github.com/massalabs/massa/pull/4588
* Massa node test tooling
  * [massa-test-framework]:
    * Modify op serialization code in Python https://github.com/massalabs/massa-test-framework/pull/24
  * [massa-functional-tests]:
    * implement a test showcasing invalid transaction replay https://github.com/massalabs/massa-functional-tests/pull/15
  * [massa-unit-tests-src]:
    * https://github.com/massalabs/massa-unit-tests-src/pull/38 
* Massa tooling
  * [massa-as-sdk]:
    * implement abi function
    * update doc
    * https://github.com/massalabs/massa-as-sdk/pull/316
  * [as_abi_proto]:
    * OUTDATED - will not be updated    
* Massa projects
  * [massa station & massa wallet]
    * Massa Wallet: https://github.com/massalabs/station-massa-wallet/pull/856
    * Massa Station: https://github.com/massalabs/station/pull/1297
  * [massa-web3]:
    * Secure share impl modification (Typescript)
      * eval: 0.5 days
    * Risk: Ben is in holidays next week (until Thursday)
    * Next version: 2.3.0?
    * https://github.com/massalabs/massa-web3/pull/510
  * [umbrella]:
    * Use chainId abi in SC in update function
    * Update Certik (Damir)
    * eval: 0.5 days
      * https://github.com/massalabs/umbrella/pull/22 
  * [massa-explorer]
    * https://github.com/massalabs/massa-explorer => test.massa.net/v1
    * https://github.com/massalabs/massa.net => test.massa.net
  * Other:
    * [bearby]:
      * Contact Discord channel: #bearby
      * Github issue / PR
      * https://github.com/bearby-wallet/bearby-extension/pull/56 (bearby extension)
      * eval: 1.5 days

### Remaining questions

* Should we implement a NetworkId as well? 
  * https://besu.hyperledger.org/stable/public-networks/concepts/network-and-chain-id

**Comment by damip** [comment]
Update doc https://docs.massa.net/docs/learn/operation-format-execution#signature

**Comment by sydhds** [comment]
* massa client: check that op can be emitted
* test.massa.net - https://test.massa.net/v1/ -> wallet in js code

**Comment by sydhds** [comment]
* PR to chain id list site
