### ISSUE TITLE
Error in Rewards

### ISSUE THREAD

**Issue by ivan-strelka** [massalabs/massa#4602]
Hi. I have a 350 Testnet Score. Node points 260 points. Passed KYC. Am I not included in the reward list? Why?
My wallet Mainnet AU12fBVEMyX56cxAKp49QGWvtbEmbJAdpzL3tEtBNRp97nLhd7Ccm

**Comment by damip** [comment]
Hello, in your case you have those points in total but you haven't reached 200 points by the end of testnet 24 so your account is not eligible.

See our announcements from this summer, as well https://massalabs.medium.com/from-testing-to-reality-mainnet-is-coming-to-light-as-testnet-wraps-up-e9908b32a9f3

**Comment by ivan-strelka** [comment]
Thanks so much. It's sad.
