### ISSUE TITLE
DEVN.28.2 - Bootstraps servers in config.toml on release is inconsitent with the one in sources (on base_config)

### ISSUE THREAD

**Issue by Floyz** [massalabs/massa#4613]
**Describe the bug**

When trying to run node from release ( https://github.com/massalabs/massa/releases/download/DEVN.28.2/massa_DEVN.28.2_release_linux.tar.gz )  , bootstrap not working on provided server list inside base_config.toml.
![image](https://github.com/massalabs/massa/assets/40758026/d217d006-d094-449f-8911-e1087f7f2a61)

It's working when we get the build from source base_config.toml instead
Here is bootstrap servers differences between release and source :

![image](https://github.com/massalabs/massa/assets/40758026/0bb59844-bef9-49bc-9921-382ff0d3c5e0)

**To Reproduce**

try to run a node from release DEVN.28.2 at https://github.com/massalabs/massa/releases/download/DEVN.28.2/massa_DEVN.28.2_release_linux.tar.gz

Node is unable to bootstrap in this situation

**Expected behavior**
Node bootstrap to correct server list

- OS: Ubuntu 22.04

**Comment by rykcod** [comment]
Same issue captains

**Comment by damip** [comment]
Hello !
This is expected, in the last buildnet, the bootstrap lists were shuffled.
We will release an update to fix this

**Comment by Leo-Besancon** [comment]
Hi! Sorry for the mixup, using the bootstrap list in the [buildnet branch](https://github.com/massalabs/massa/blob/buildnet/massa-node/base_config/config.toml#L102) will work.

You can just update your config.toml file with the following:
```
[bootstrap]
bootstrap_list = [ [ "149.202.84.7:31245", "N1kKfgrCveVnosUkxTzaBw5cf9f2cbTvK3R5Ssb2Pf76au8xwmH",], [ "149.202.84.39:31245", "N12sNdL7YwSawpnJrk9XCWDjKbgfNamAobp62AX5qfkgpBkGh2wC",], [ "37.187.156.118:31245", "N1NnuSW48GKGaYZamAVKXfXbbnt3StxWoHpYtBZSJvY9e8U1BTC",],]

```
