### ISSUE TITLE
100% core usage by protocol-block thread

### ISSUE THREAD

**Issue by damip** [massalabs/massa#4616]
Reports of 100% single core usage by a thread whose name starts with "protocol-block". 

TODO:
* [x] identify whether it's `protocol-block-handler-propagation` or `protocol-block-handler-retrieval`
* [x] find the source of the issue and check if it has consequences on the launch
* [x] fix the issue in a PR
* [ ] if it is critical, deploy a 1.1 version, otherwise just merge it in main as there is no impact post-genesis

**Comment by bilboquet** [comment]
Faulty thread is: `protocol-block-handler-retrieval`
