### ISSUE TITLE
get_address endpoint performance on the mainnet JSON RPC API

### ISSUE THREAD

**Issue by noesusset** [massalabs/massa#4618]
**Describe the bug**
When fetching some address on the endpoint https://mainnet.massa.net/api/v2/get_addresses it is much slower than on the buildnet.
On average for 1 address on the buildnet it is 60ms, for the mainnet it is around 700ms.

**To Reproduce**
To reproduce here a request with one address (the top staker on the mainnet)

  curl --location 'https://mainnet.massa.net/api/v2' \
  --header 'Content-Type: application/json' \
  --data '{
      "jsonrpc": "2.0",
      "id": 1,
      "method": "get_addresses",
      "params": [["AU128Rexxftc1jYhyouTesxjPqeezEHh5LUAzNaAfqDo1dWRgPH8m" ]]
  }'

And here is the same but with the top stakers on the buildnet

curl --location 'https://buildnet.massa.net/api/v2' \
--header 'Content-Type: application/json' \
--data '{
    "jsonrpc": "2.0",
    "id": 1,
    "method": "get_addresses",
    "params": [["AU1wN8rn4SkwYSTDF3dHFY4U28KtsqKL1NnEjDZhHnHEy6cEQm53" ]]
}'

To be able to really see the difference here is a request with the top 8 stakers on the mainnet and the top 4 on the buildnet
curl --location 'https://mainnet.massa.net/api/v2' \
--header 'Content-Type: application/json' \
--data '{
    "jsonrpc": "2.0",
    "id": 1,
    "method": "get_addresses",
    "params": [["AU128Rexxftc1jYhyouTesxjPqeezEHh5LUAzNaAfqDo1dWRgPH8m","AU12L4gaQ8j8j5yBt2jSmcsmu51yZW2gLjnZr5rAWnjKJDNacR3jp","AU12Lb7GafJueFnoCc4GRSXreCHWtYynLkzSS5iWTCsMVi6zue4rA","AU1NNfMpS4fpfgwpaHWJD8H7AkJ3TpmvR2cAVbgbsbspGFFgBT3a","AU12kg1cBcYVQFKyJ2HwHa4Wz9d8Z98BvaqynzmpRsE1xiqyHcAhd","AU1ouP66v1VKaZjX4TDp9kHMbktEesNSLyEhpSbPSSHb9uTLMtXa","AU1B2CNhMQqeWMNcQj7seQbsdfUTw1M5cUoUZ4e6i9KhPnMhP1wK","AU1BuNG4JHpZgLcPQuAqk2BmKzTgUjHbfBAcfwzPGFvJWeZja5CK" ]]
}'

curl --location 'https://buildnet.massa.net/api/v2' \
--header 'Content-Type: application/json' \
--data '{
    "jsonrpc": "2.0",
    "id": 1,
    "method": "get_addresses",
    "params": [["AU1wN8rn4SkwYSTDF3dHFY4U28KtsqKL1NnEjDZhHnHEy6cEQm53","AU17Prntejq6G4Rwj5tpn6nnuniNAvV5atP1Um6Ujg3tGebsG1jR","AU12Kqf1GkNGqByGLXrzBCAN6uZUdgtwyAE5MGq5brSeL1hdaxTZx","AU12w3XtFaRCSeda3dwR4mnV7buET97KZ4TXnGCE8gY9F9aNzY1Yh" ]]
}'

**Expected behavior**
a huge difference for the time of the request

**Screenshots**
![image](https://github.com/massalabs/massa/assets/96011618/25c9cc77-03a8-46ba-b653-d82c25c9ef13)
![image](https://github.com/massalabs/massa/assets/96011618/8ef6a405-6995-42f6-96ae-e66a33b389ce)

**Comment by damip** [comment]
@sydhds @bilboquet can you take a look to understand what is going on and fix if necessary ?

**Comment by bilboquet** [comment]
Solved in MAIN.2.0
