### ISSUE TITLE
Massa-Client Could not open wallet: YAML error: control characters are not allowed

### ISSUE THREAD

**Issue by qdrn** [massalabs/massa#4626]

**Comment by bilboquet** [comment]
Can you provide the wallet?
What's the wallet history (created with…), has it been open/modified by any other application?
At least, can you open the wallet with a text editor and tell us where control characters appear? (it should be pure ASCII)

**Comment by qdrn** [comment]
> Was the wallet generated on Windows then moved to a Unix-like OS (or the other way)? (It should be harmless but…)

No

**Comment by tuzara82** [comment]
Which converter should I use.Thanks

**Comment by AurelienFT** [comment]
Massa Station v0.5 wasn't mainnet compatible that's why wallets isn't supported here. Now in the latests versions of massa-station (v0.6.2) wallet are compatible, closing this.
