### ISSUE TITLE
Problem with Massa Station wallet

### ISSUE THREAD

**Issue by VSDKK** [massalabs/massa#4678]
Hello! I lost my wallet password. I have a .yaml file, but it does not allow me to withdraw funds. KYC was done in person. Tokens are on massawallet. Is it possible to recover the access code? Is it possible to change my wallet address to receive frozen tokens that I haven't received yet? Maybe massawallet is blocked for a certain period after entering the wrong password? I'm sure one of my options should unlock the wallet, but I can't. Tokens were earned as rewards for holding a node.

**Comment by AurelienFT** [comment]
Hello,
Sadly if you lost your password and your secret key we can't do anything for you :/
