### ISSUE TITLE
Compiling the node, crash at   Compiling librocksdb-sys v0.11.0+8.1.1    Compiling quiche v0.20.0

### ISSUE THREAD

**Issue by Migtey** [massalabs/massa#4682]
**Describe the bug**
Compiling the node, crash at different stages

PS C:\massa\massa-node> cargo run --release -- -p PASSWORD
   Compiling librocksdb-sys v0.11.0+8.1.1
   Compiling quiche v0.20.0
   Compiling massa_sdk v2.1.0 (C:\massa\massa-sdk)
error: failed to run custom build command for `librocksdb-sys v0.11.0+8.1.1`

Caused by:
  process didn't exit successfully: `C:\massa\target\release\build\librocksdb-sys-bfa49dd2ed04f393\build-script-build` (exit code: 101)
  --- stderr
  thread 'main' panicked at C:\Users\migte\.cargo\registry\src\index.crates.io-6f17d22bba15001f\bindgen-0.65.1\lib.rs:603:31:
  Unable to find libclang: "couldn't find any valid shared libraries matching: ['clang.dll', 'libclang.dll'], set the `LIBCLANG_PATH` environment variable to a path where one of these files can be found (invalid: [])"
  note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
warning: build failed, waiting for other jobs to finish...
error: failed to run custom build command for `quiche v0.20.0`

Caused by:
  process didn't exit successfully: `C:\massa\target\release\build\quiche-ed37c6852f33dc45\build-script-build` (exit code: 101)
  --- stdout
  CMAKE_TOOLCHAIN_FILE_x86_64-pc-windows-msvc = None
  CMAKE_TOOLCHAIN_FILE_x86_64_pc_windows_msvc = None
  HOST_CMAKE_TOOLCHAIN_FILE = None
  CMAKE_TOOLCHAIN_FILE = None
  CMAKE_GENERATOR_x86_64-pc-windows-msvc = None
  CMAKE_GENERATOR_x86_64_pc_windows_msvc = None
  HOST_CMAKE_GENERATOR = None
  CMAKE_GENERATOR = None
  CMAKE_PREFIX_PATH_x86_64-pc-windows-msvc = None
  CMAKE_PREFIX_PATH_x86_64_pc_windows_msvc = None
  HOST_CMAKE_PREFIX_PATH = None
  CMAKE_PREFIX_PATH = None
  CMAKE_x86_64-pc-windows-msvc = None
  CMAKE_x86_64_pc_windows_msvc = None
  HOST_CMAKE = None
  CMAKE = None
  running: "cmake" "C:\\Users\\migte\\.cargo\\registry\\src\\index.crates.io-6f17d22bba15001f\\quiche-0.20.0\\deps/boringssl" "-G" "Visual Studio 17 2022" "-Thost=x64" "-Ax64" "-DCMAKE_INSTALL_PREFIX=C:\\massa\\target\\release\\build\\quiche-06c5c30e71a56fc9\\out" "-DCMAKE_C_FLAGS= -nologo -MD -Brepro" "-DCMAKE_C_FLAGS_RELEASE= -nologo -MD -Brepro" "-DCMAKE_CXX_FLAGS= -nologo -MD -Brepro" "-DCMAKE_CXX_FLAGS_RELEASE= -nologo -MD -Brepro" "-DCMAKE_ASM_FLAGS= -nologo -MD -Brepro" "-DCMAKE_ASM_FLAGS_RELEASE= -nologo -MD -Brepro" "-DCMAKE_BUILD_TYPE=Release"

  --- stderr
  thread 'main' panicked at C:\Users\migte\.cargo\registry\src\index.crates.io-6f17d22bba15001f\cmake-0.1.50\src\lib.rs:1098:5:

  failed to execute command: program not found
  is `cmake` not installed?

  build script failed, must exit now
  note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
PS C:\massa\massa-node>

Windows 11
Reinstalled Visual Studio 2022 with proper add-ons to be sure.

**Comment by AurelienFT** [comment]
Hello
It seems that you are missing one of our dependency which is `cmake`
You should have miss a step documented here : https://docs.massa.net/docs/node/install#on-windows

**Comment by Migtey** [comment]
You can close the ticket. It was more complex issue. After reading through
the instructions, few missing parts.

If I may, it will be super crucial to get a packaged installation for
broader node deployment to more general public (if it's the intention)

Thank you very much for your reply.
