### ISSUE TITLE
Cannot merge external contributor PRs

### ISSUE THREAD

**Issue by AurelienFT** [massalabs/massa#4694]
External contributor PR such as https://github.com/massalabs/massa/pull/4686 can't be merged because auto-merge requires the whole CI pipeline to pass but the `doc` job never success on the PR depending on branches from fork. @Leo-Besancon can you take a look as you were the one that setup this (if it's not you can you redirect the issue) please ?

**Comment by Leo-Besancon** [comment]
I think @damip was the one to have access to the repo maintenance settings. Could you make the "docs" CI job not required for merging? (for example gas-costs-check is not required).
It's probably the easiest, no?

**Comment by AurelienFT** [comment]
It seems to be ok, the auto merge works. Closing
